### ISSUE TITLE
panic in GetSessions

### ISSUE THREAD

**Issue by kinghrothgar** [gravitational/teleport#1002]
```
May 18 16:52:13: level=error msg="failed to retrieve user authority key, err: client: etcd cluster is unavailable or misconfigured" file="auth/tun.go:224" func="auth.(*AuthTunnel).isHostAuthority"
May 18 16:52:13: level=warning msg="conn(10.142.0.27:45100->10.142.0.28:3025, user=2f7eb86e-c281-41f8-b65e-9547df5d332d.admiral) ERROR: failed auth user 2f7eb86e-c281-41f8-b65e-9547df5d332d.admiral, err: ssh: certificate signed by unrecognized authority" file="auth/tun.go:406" func="auth.(*AuthTunnel).keyAuth"
May 18 16:52:13: level=error msg="client: etcd cluster is unavailable or misconfigured" file="session/session.go:274" func="session.(*server).GetSessions"
May 18 16:52:14: level=error msg="failed to retrieve user authority key, err: client: etcd cluster is unavailable or misconfigured" file="auth/tun.go:224" func="auth.(*AuthTunnel).isHostAuthority"
May 18 16:52:14: level=warning msg="conn(10.142.0.26:31798->10.142.0.28:3025, user=71c6d006-951e-4fe0-85b2-005d04879e5b.admiral) ERROR: failed auth user 71c6d006-951e-4fe0-85b2-005d04879e5b.admiral, err: ssh: certificate signed by unrecognized authority" file="auth/tun.go:406" func="auth.(*AuthTunnel).keyAuth"
May 18 16:52:14: 2017/05/18 16:52:14 http: panic serving 10.142.0.26:31786: runtime error: invalid memory address or nil pointer dereference
May 18 16:52:14: goroutine 2466947 [running]:
May 18 16:52:14: net/http.(*conn).serve.func1(0xc423c41800)
May 18 16:52:14: /opt/go/src/net/http/server.go:1491 +0x12a
May 18 16:52:14: panic(0xd86a20, 0xc420010090)
May 18 16:52:14: /opt/go/src/runtime/panic.go:458 +0x243
May 18 16:52:14: github.com/gravitational/teleport/lib/session.(*server).GetSessions(0xc42043ad60, 0xc420249d6f, 0x7, 0xeb5d23, 0x7, 0xeb27c7, 0x4, 0x0)
May 18 16:52:14: /gopath/src/github.com/gravitational/teleport/lib/session/session.go:284 +0x231
May 18 16:52:14: github.com/gravitational/teleport/lib/auth.(*AuthWithRoles).GetSessions(0xc4202d8960, 0xc420249d6f, 0x7, 0xeb792f, 0x9, 0xc420249d6f, 0x7, 0xc4255a9930)
May 18 16:52:14: /gopath/src/github.com/gravitational/teleport/lib/auth/auth_with_roles.go:63 +0xa7
May 18 16:52:14: github.com/gravitational/teleport/lib/auth.(*APIServer).getSessions(0xc424adb800, 0x15c6740, 0xc4202d8960, 0x15b8fe0, 0xc4200fd930, 0xc421b23c20, 0xc4209172c0, 0x2, 0x3, 0xc420249d61, ...)
May 18 16:52:14: /gopath/src/github.com/gravitational/teleport/lib/auth/apiserver.go:904 +0xcf
May 18 16:52:14: github.com/gravitational/teleport/lib/auth.(*APIServer).(github.com/gravitational/teleport/lib/auth.getSessions)-fm(0x15c6740, 0xc4202d8960, 0x15b8fe0, 0xc4200fd930, 0xc421b23c20, 0xc4209172c0, 0x2, 0x3, 0xc420249d61, 0x2, ...)
May 18 16:52:14: /gopath/src/github.com/gravitational/teleport/lib/auth/apiserver.go:122 +0xb3
May 18 16:52:14: github.com/gravitational/teleport/lib/auth.(*APIServer).withAuth.func1(0x15b8fe0, 0xc4200fd930, 0xc421b23c20, 0xc4209172c0, 0x2, 0x3, 0x0, 0xc4209172c0, 0x1f, 0xc423ba3930)
May 18 16:52:14: /gopath/src/github.com/gravitational/teleport/lib/auth/apiserver.go:200 +0x3e1
May 18 16:52:14: github.com/gravitational/teleport/lib/httplib.MakeHandler.func1(0x15b8fe0, 0xc4200fd930, 0xc421b23c20, 0xc4209172c0, 0x2, 0x3)
May 18 16:52:14: /gopath/src/github.com/gravitational/teleport/lib/httplib/httplib.go:43 +0x6b
May 18 16:52:14: github.com/gravitational/teleport/vendor/github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc424adb838, 0x15b8fe0, 0xc4200fd930, 0xc421b23c20)
May 18 16:52:14: /gopath/src/github.com/gravitational/teleport/vendor/github.com/julienschmidt/httprouter/router.go:298 +0x7d8
May 18 16:52:14: github.com/gravitational/teleport/lib/httplib.RewritePaths.func1(0x15b8fe0, 0xc4200fd930, 0xc421b23c20)
May 18 16:52:14: /gopath/src/github.com/gravitational/teleport/lib/httplib/httplib.go:141 +0x122
May 18 16:52:14: net/http.HandlerFunc.ServeHTTP(0xc4242fbe60, 0x15b8fe0, 0xc4200fd930, 0xc421b23c20)
May 18 16:52:14: /opt/go/src/net/http/server.go:1726 +0x44
May 18 16:52:14: github.com/gravitational/teleport/lib/auth.(*AuthTunnel).onAPIConnection.func2(0x15b8fe0, 0xc4200fd930, 0xc421b23b30)
May 18 16:52:14: /gopath/src/github.com/gravitational/teleport/lib/auth/tun.go:388 +0x12b
May 18 16:52:14: net/http.HandlerFunc.ServeHTTP(0xc4242fbe90, 0x15b8fe0, 0xc4200fd930, 0xc421b23b30)
May 18 16:52:14: /opt/go/src/net/http/server.go:1726 +0x44
May 18 16:52:14: net/http.serverHandler.ServeHTTP(0xc423c41780, 0x15b8fe0, 0xc4200fd930, 0xc421b23b30)
May 18 16:52:14: /opt/go/src/net/http/server.go:2202 +0x7d
May 18 16:52:14: net/http.(*conn).serve(0xc423c41800, 0x15ba3a0, 0xc424de1a40)
May 18 16:52:14: /opt/go/src/net/http/server.go:1579 +0x4b7
May 18 16:52:14: created by net/http.(*Server).Serve
May 18 16:52:14: /opt/go/src/net/http/server.go:2293 +0x44d
May 18 16:52:14: level=error msg="failed to retrieve user authority key, err: client: etcd cluster is unavailable or misconfigured" file="auth/tun.go:224" func="auth.(*AuthTunnel).isHostAuthority"
May 18 16:52:14: level=warning msg="conn(10.142.0.26:31802->10.142.0.28:3025, user=71c6d006-951e-4fe0-85b2-005d04879e5b.admiral) ERROR: Failed to authorize user 71c6d006-951e-4fe0-85b2-005d04879e5b.admiral, err: ssh: certificate signed by unrecognized authority" file="auth/tun.go:411" func="auth.(*AuthTunnel).keyAuth"
```

Using the web UI I believe causes this.  It is causing teleport to be unsuable.  I have an HA setup with an etcd backend and 3 auth nodes.

**Comment by kontsevoy** [comment]
@kinghrothgar looks like your `etcd` connection is mis-configured. Meanwhile we'll work on better handling this error. Thanks.
