### ISSUE TITLE
Unable to upgrade go-mysql to v1.4

### ISSUE THREAD

**Issue by jimbishopp** [gravitational/teleport#10067]
Multiple issues were encountered while attempting to upgrade `go-mysql` to version `v1.4` in Teleport.

Tests in the `lib/srv/db` package returned an error after upgrading `go-mysql`. The new client now returns an empty `mysql.Resultset` in the `mysql.Result` object rather than `nil` for `select 1` queries. Tests were updated to expect a non-nil `Resultset`, but testing resulted in a panic (see below for error output).

References:
- The [go-mysql commit](https://github.com/gravitational/go-mysql/commit/569627f58e688bce205cbac8202acda20c8dfbed) that applies Teleport-specific code to the `go-mysql` `v1.4` fork.
- The [Teleport commit](https://github.com/gravitational/teleport/commit/13d3af31fa4e258eccf369f463e64f68aeb56656) that upgrades Teleport to use the `go-mysql` `v1.4`. This commit also includes an attempted fix for the `Resetset` issue.

Test Output:
After upgrade but before applying a fix for `Resultset`.
```go
$ go test github.com/gravitational/teleport/lib/srv/db
--- FAIL: TestAccessMySQL (4.15s)
    --- FAIL: TestAccessMySQL/has_access_to_all_database_users (1.04s)
        access_test.go:242: 
            	Error Trace:	access_test.go:242
            	Error:      	Not equal: 
            	            	expected: &mysql.Result{Status:0x0, Warnings:0x0, InsertId:0x1, AffectedRows:0x0, Resultset:(*mysql.Resultset)(nil)}
            	            	actual  : &mysql.Result{Status:0x0, Warnings:0x0, InsertId:0x1, AffectedRows:0x0, Resultset:(*mysql.Resultset)(0xc0002c00e0)}
            	            	
            	            	Diff:
            	            	--- Expected
            	            	+++ Actual
            	            	@@ -5,3 +5,11 @@
            	            	  AffectedRows: (uint64) 0,
            	            	- Resultset: (*mysql.Resultset)(<nil>)
            	            	+ Resultset: (*mysql.Resultset)({
            	            	+  Fields: ([]*mysql.Field) <nil>,
            	            	+  FieldNames: (map[string]int) <nil>,
            	            	+  Values: ([][]mysql.FieldValue) <nil>,
            	            	+  RawPkg: ([]uint8) <nil>,
            	            	+  RowDatas: ([]mysql.RowData) <nil>,
            	            	+  Streaming: (bool) false,
            	            	+  StreamingDone: (bool) false
            	            	+ })
            	            	 })
            	Test:       	TestAccessMySQL/has_access_to_all_database_users
    --- FAIL: TestAccessMySQL/access_allowed_to_specific_user (0.44s)
        access_test.go:242: 
            	Error Trace:	access_test.go:242
            	Error:      	Not equal: 
            	            	expected: &mysql.Result{Status:0x0, Warnings:0x0, InsertId:0x1, AffectedRows:0x0, Resultset:(*mysql.Resultset)(nil)}
            	            	actual  : &mysql.Result{Status:0x0, Warnings:0x0, InsertId:0x1, AffectedRows:0x0, Resultset:(*mysql.Resultset)(0xc000314000)}
            	            	
            	            	Diff:
            	            	--- Expected
            	            	+++ Actual
            	            	@@ -5,3 +5,11 @@
            	            	  AffectedRows: (uint64) 0,
            	            	- Resultset: (*mysql.Resultset)(<nil>)
            	            	+ Resultset: (*mysql.Resultset)({
            	            	+  Fields: ([]*mysql.Field) <nil>,
            	            	+  FieldNames: (map[string]int) <nil>,
            	            	+  Values: ([][]mysql.FieldValue) <nil>,
            	            	+  RawPkg: ([]uint8) <nil>,
            	            	+  RowDatas: ([]mysql.RowData) <nil>,
            	            	+  Streaming: (bool) false,
            	            	+  StreamingDone: (bool) false
            	            	+ })
            	            	 })
            	Test:       	TestAccessMySQL/access_allowed_to_specific_user
--- FAIL: TestGCPRequireSSL (1.99s)
    access_test.go:419: 
        	Error Trace:	access_test.go:419
        	Error:      	Not equal: 
        	            	expected: &mysql.Result{Status:0x0, Warnings:0x0, InsertId:0x1, AffectedRows:0x0, Resultset:(*mysql.Resultset)(nil)}
        	            	actual  : &mysql.Result{Status:0x0, Warnings:0x0, InsertId:0x1, AffectedRows:0x0, Resultset:(*mysql.Resultset)(0xc00035ab60)}
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -5,3 +5,11 @@
        	            	  AffectedRows: (uint64) 0,
        	            	- Resultset: (*mysql.Resultset)(<nil>)
        	            	+ Resultset: (*mysql.Resultset)({
        	            	+  Fields: ([]*mysql.Field) <nil>,
        	            	+  FieldNames: (map[string]int) <nil>,
        	            	+  Values: ([][]mysql.FieldValue) <nil>,
        	            	+  RawPkg: ([]uint8) <nil>,
        	            	+  RowDatas: ([]mysql.RowData) <nil>,
        	            	+  Streaming: (bool) false,
        	            	+  StreamingDone: (bool) false
        	            	+ })
        	            	 })
        	Test:       	TestGCPRequireSSL
FAIL
exit status 1
FAIL	github.com/gravitational/teleport/lib/srv/db	202.539s
```

After applying a fix for `Resultset`.
```go
$ go test github.com/gravitational/teleport/lib/srv/db
--- FAIL: TestAccessMySQL (1.20s)
    --- FAIL: TestAccessMySQL/has_access_to_all_database_users (0.47s)
panic: runtime error: index out of range [1] with length 0 [recovered]
	panic: runtime error: index out of range [1] with length 0

goroutine 535 [running]:
testing.tRunner.func1.2({0x6c475a0, 0xc0000552a8})
	/usr/local/Cellar/go/1.17.3/libexec/src/testing/testing.go:1209 +0x24e
testing.tRunner.func1()
	/usr/local/Cellar/go/1.17.3/libexec/src/testing/testing.go:1212 +0x218
panic({0x6c475a0, 0xc0000552a8})
	/usr/local/Cellar/go/1.17.3/libexec/src/runtime/panic.go:1038 +0x215
encoding/binary.littleEndian.Uint16(...)
	/usr/local/Cellar/go/1.17.3/libexec/src/encoding/binary/binary.go:53
github.com/go-mysql-org/go-mysql/client.(*Conn).handleOKPacket(0xc000f6a960, {0xc0012f4040, 0x1, 0x10})
	/Users/jim/go/pkg/mod/github.com/gravitational/go-mysql@v1.4.1-0.20220131222804-569627f58e68/client/resp.go:51 +0x23a
github.com/go-mysql-org/go-mysql/client.(*Conn).readResult(0xc000f6a960, 0x3)
	/Users/jim/go/pkg/mod/github.com/gravitational/go-mysql@v1.4.1-0.20220131222804-569627f58e68/client/resp.go:232 +0x258
github.com/go-mysql-org/go-mysql/client.(*Conn).exec(0xc0012abe90, {0x6e2a6a9, 0x742e780})
	/Users/jim/go/pkg/mod/github.com/gravitational/go-mysql@v1.4.1-0.20220131222804-569627f58e68/client/conn.go:329 +0x6d
github.com/go-mysql-org/go-mysql/client.(*Conn).Execute(0x74595d8, {0x6e2a6a9, 0x0}, {0x0, 0x0, 0x0})
	/Users/jim/go/pkg/mod/github.com/gravitational/go-mysql@v1.4.1-0.20220131222804-569627f58e68/client/conn.go:188 +0xbc
github.com/gravitational/teleport/lib/srv/db.TestAccessMySQL.func1(0x74ef2e0)
	/Users/jim/dev/teleport/teleport/lib/srv/db/access_test.go:240 +0x21f
testing.tRunner(0xc00173c000, 0xc000eee210)
	/usr/local/Cellar/go/1.17.3/libexec/src/testing/testing.go:1259 +0x102
created by testing.(*T).Run
	/usr/local/Cellar/go/1.17.3/libexec/src/testing/testing.go:1306 +0x35a
exit status 2
FAIL	github.com/gravitational/teleport/lib/srv/db	7.275s
```

**Comment by smallinsky** [comment]
Not longer valid. We are already using go-mysql to v1.5 https://github.com/gravitational/teleport/blob/master/go.mod#L55
