### ISSUE TITLE
Teleport panics with unaligned 64-bit atomic operation on 32bit ARM

### ISSUE THREAD

**Issue by LongHairedHacker** [gravitational/teleport#11106]
### Description

**What happened**:
I tried adding a 32bit ARM node (raspberry pi running a customized OpenWRT) to a teleport cluster,
following the instructions for [Adding a Node located behind NAT](https://goteleport.com/docs/setup/admin/adding-nodes/#adding-a-node-located-behind-nat)
The teleport binary crashes reliably as soon as I try to connect to it via the webinterface or tsh.

The session in the webinterface ends with:
```
disconnected
wait: remote command exited without exit status or exit signal
```

On the ARM node teleport crashes with:
```
DEBU [NODE]      Successfully authenticated fingerprint:ssh-rsa-cert-v01@openssh.com SHA256:8342ZwDCXygxbXC3am1BFZe2JGPW3rH5FxeLBmxX+eg local:192.168.42.27:44350 remote:192.168.42.54:39892 user:root srv/authhandlers.go:293
DEBU [NODE]      Checking permissions for (testuser,root) to login to node with RBAC checks. srv/authhandlers.go:422
DEBU [RBAC]      Access to node "acd7cdeb-2046-4508-a768-50baf4e98878" granted, allow rule in role "access" matched. services/role.go:1853
DEBU [SSH:NODE]  Incoming connection 192.168.42.54:39892 -> 192.168.42.27:44350 version: SSH-2.0-Go, certtype: "user" sshutils/server.go:466
DEBU [SSH:NODE]  Received out-of-band request: &{Type:x-teleport-version WantReply:true Payload:[] ch:<nil> mux:0x71b9d80}. sshutils/server.go:521
DEBU [NODE]      Handling request env, want reply true. id:1 local:192.168.42.27:44350 login:root remote:192.168.42.54:39892 teleportUser:testuser regular/sshserver.go:1398
DEBU [KEEPALIVE] Starting keep-alive loop with with interval 5m0s and max count 3. srv/keepalive.go:65
DEBU [NODE]      Handling request env, want reply true. id:1 local:192.168.42.27:44350 login:root remote:192.168.42.54:39892 teleportUser:testuser regular/sshserver.go:1398
DEBU [NODE]      Handling request env, want reply true. id:1 local:192.168.42.27:44350 login:root remote:192.168.42.54:39892 teleportUser:testuser regular/sshserver.go:1398
DEBU [NODE]      Handling request env, want reply true. id:1 local:192.168.42.27:44350 login:root remote:192.168.42.54:39892 teleportUser:testuser regular/sshserver.go:1398
DEBU [NODE]      Handling request env, want reply true. id:1 local:192.168.42.27:44350 login:root remote:192.168.42.54:39892 teleportUser:testuser regular/sshserver.go:1398
DEBU [NODE]      Handling request env, want reply true. id:1 local:192.168.42.27:44350 login:root remote:192.168.42.54:39892 teleportUser:testuser regular/sshserver.go:1398
DEBU             Will create new session for SSH connection 192.168.42.54:39892. srv/ctx.go:512
DEBU [NODE]      Handling request auth-agent-req@openssh.com, want reply true. id:1 local:192.168.42.27:44350 login:root remote:192.168.42.54:39892 teleportUser:testuser regular/sshserver.go:1398
DEBU [NODE]      Starting agent server for Teleport user testuser and socket /tmp/teleport-2905853319/teleport-12593.socket. id:1 local:192.168.42.27:44350 login:root remote:192.168.42.54:39892 teleportUser:testuser regular/sshserver.go:889
DEBU             Will create new session for SSH connection 192.168.42.54:39892. srv/ctx.go:512
DEBU [NODE]      Handling request pty-req, want reply true. id:1 local:192.168.42.27:44350 login:root remote:192.168.42.54:39892 teleportUser:testuser regular/sshserver.go:1398
DEBU [NODE]      Requested terminal "xterm-256color" of size {80 25} id:1 local:192.168.42.27:44350 login:root remote:192.168.42.54:39892 teleportUser:testuser srv/termhandlers.go:73
DEBU             Set permissions on /dev/pts/1 to 0:0 with mode -rw--w----. srv/term.go:407
DEBU [SESSION:N] Unable to update window size, no session found in context. srv/sess.go:445
DEBU             Will create new session for SSH connection 192.168.42.54:39892. srv/ctx.go:512
DEBU [NODE]      Handling request shell, want reply true. id:1 local:192.168.42.27:44350 login:root remote:192.168.42.54:39892 teleportUser:testuser regular/sshserver.go:1398
DEBU [SESSION:N] Creating tracker srv/sess.go:1709
INFO [NODE]      Creating (interactive) session 1b91eb19-3efe-40f0-92c1-c556ce6ffe09. id:1 local:192.168.42.27:44350 login:root remote:192.168.42.54:39892 teleportUser:testuser srv/sess.go:223
DEBU [SESSION:N] Using async streamer for session 1b91eb19-3efe-40f0-92c1-c556ce6ffe09. srv/sess.go:1255
DEBU [SESSION:N] Tracking participant: testuser srv/sess.go:1751
INFO [AUDIT]     session.start addr.remote:192.168.42.54:39892 cluster_name:PL911 code:T2000I ei:0 event:session.start login:root namespace:default server_addr:192.168.42.27:44350 server_hostname:testberry server_id:acd7cdeb-2046-4508-a768-50baf4e98878 session_recording:node sid:1b91eb19-3efe-40f0-92c1-c556ce6ffe09 size:80:25 time:2022-03-14T12:03:47.144Z uid:315481ea-e10a-4f13-814a-7878e3e5db7e user:testuser events/emitter.go:325
INFO [SESSION:N] New party ServerContext(192.168.42.54:39892->192.168.42.27:44350, user=root, id=1) party(id=d995772a-1da4-4c6a-b935-d5b68efaea5b) joined session: 1b91eb19-3efe-40f0-92c1-c556ce6ffe09 srv/sess.go:1516
DEBU             Will join session 1b91eb19-3efe-40f0-92c1-c556ce6ffe09 for SSH connection 192.168.42.54:39892. srv/ctx.go:514
DEBU [SESSION:N] Launching session 1b91eb19-3efe-40f0-92c1-c556ce6ffe09. srv/sess.go:823
panic: unaligned 64-bit atomic operation

goroutine 241 [running]:
runtime/internal/atomic.panicUnaligned()
	/opt/go/src/runtime/internal/atomic/unaligned.go:8 +0x24
runtime/internal/atomic.Xadd64(0x78cecd4, 0x0)
	/opt/go/src/runtime/internal/atomic/atomic_arm.s:256 +0x14
github.com/gravitational/teleport/lib/srv.(*TermManager).writeToClients(0x78cecc0, {0x0, 0x0, 0x0})
	/go/src/github.com/gravitational/teleport/lib/srv/termmanager.go:83 +0x140
github.com/gravitational/teleport/lib/srv.(*TermManager).writeUnconditional(...)
	/go/src/github.com/gravitational/teleport/lib/srv/termmanager.go:169
github.com/gravitational/teleport/lib/srv.(*TermManager).On(0x78cecc0)
	/go/src/github.com/gravitational/teleport/lib/srv/termmanager.go:192 +0x94
github.com/gravitational/teleport/lib/srv.(*session).launch(0x78f0270, 0x756d080)
	/go/src/github.com/gravitational/teleport/lib/srv/sess.go:827 +0x1b8
github.com/gravitational/teleport/lib/srv.(*session).addParty.func2(0x78f0270)
	/go/src/github.com/gravitational/teleport/lib/srv/sess.go:1548 +0x24
created by github.com/gravitational/teleport/lib/srv.(*session).addParty
	/go/src/github.com/gravitational/teleport/lib/srv/sess.go:1547 +0x680
```

**What you expected to happen**:
A successful connection to the node with shell access.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Download the `Linux ARMv7 (32-bit)` release from https://goteleport.com/teleport/download/
2. Unpack it and copy it onto a 32bit ARM system e.g. a RaspberryPi running a 32bit Raspbian
3. Generate an access token for your cluster e.g. `tctl nodes add --roles=node`
4. Run teleport on the 32bit ARM node e.g. `./teleport start  --roles=node --token=<token> --ca-pin=<capin> --auth-server=<authserver>:3080 --insecure -d`
5. Try to connect to the node you've just added. 

### Node Details
- Node OS: Customized OpenWRT
- Teleport version: `v9.0.0 git:v9.0.0-0-g1fa8857aa go1.17.7`
- Hardware: Raspberry Pi

### Server Details
- Server OS: Ubuntu 20.04
- Teleport version: `v9.0.0 git:v9.0.0-0-g1fa8857aa go1.17.7`
- Where are you running Teleport? Dedicated Hardware (Proxy and Authserver running on my desktop machine for testing)

### Client Details
- Tsh version: Teleport v9.0.0 git:v9.0.0-0-g1fa8857aa go1.17.7
- Computer OS:  Ubuntu 20.04
- Installed via website download (extracted from tarball)

### Additional Information
As far as I can tell this bug is causes by an incorrect usage of `atomic.AddUint64` in [lib/srv/termmanager.go#L83](https://github.com/gravitational/teleport/blob/v9.0.0/lib/srv/termmanager.go#L83).

The [documentation]() for `sync/atomic` states:
```
On ARM, 386, and 32-bit MIPS, it is the caller's responsibility to arrange for 64-bit alignment of 64-bit words accessed atomically. 
The first word in a variable or in an allocated struct, array, or slice can be relied upon to be 64-bit aligned.
```

Looking at [TermManager](https://github.com/gravitational/teleport/blob/v9.0.0/lib/srv/termmanager.go#L33) struct,
`countWritten` is not within the first word of the struct.
So to fix this issue it should be sufficient to move `countWritten` and `countRead` to the beginning of the struct,
to keep them 64bit aligned.

**Comment by gclawes** [comment]
Seeing a similar issue on `v9.0.4`:
```
Apr 07 22:27:09 teleport.home.arpa teleport[961]: panic: unaligned 64-bit atomic operation
Apr 07 22:27:09 teleport.home.arpa teleport[961]: goroutine 255 [running]:
Apr 07 22:27:09 teleport.home.arpa teleport[961]: runtime/internal/atomic.panicUnaligned()
Apr 07 22:27:09 teleport.home.arpa teleport[961]:         /opt/go/src/runtime/internal/atomic/unaligned.go:8 +0x24
Apr 07 22:27:09 teleport.home.arpa teleport[961]: runtime/internal/atomic.Store64(0x88c4034, 0x16e3cac37ee5504c)
Apr 07 22:27:09 teleport.home.arpa teleport[961]:         /opt/go/src/runtime/internal/atomic/atomic_arm.s:301 +0x14
Apr 07 22:27:09 teleport.home.arpa teleport[961]: github.com/gravitational/teleport/lib/reversetunnel.(*remoteConn).setLastHeartbeat(0x88c4000, {0x206eae4c, 0xed9e1947d, 0x0})
Apr 07 22:27:09 teleport.home.arpa teleport[961]:         /go/src/github.com/gravitational/teleport/lib/reversetunnel/conn.go:170 +0xac
Apr 07 22:27:09 teleport.home.arpa teleport[961]: github.com/gravitational/teleport/lib/reversetunnel.(*localSite).handleHeartbeat(0x7d87ea0, 0x88c4000, {0x4a0f24c, 0x7c27800}, 0x8493e80)
Apr 07 22:27:09 teleport.home.arpa teleport[961]:         /go/src/github.com/gravitational/teleport/lib/reversetunnel/localsite.go:447 +0x6f4
Apr 07 22:27:09 teleport.home.arpa teleport[961]: created by github.com/gravitational/teleport/lib/reversetunnel.(*server).handleNewService
Apr 07 22:27:09 teleport.home.arpa teleport[961]:         /go/src/github.com/gravitational/teleport/lib/reversetunnel/srv.go:688 +0x200
```
```
root@teleport:~# teleport version
Teleport v9.0.4 git:v9.0.4-0-gf577413d3 go1.17.7
root@teleport:~# uname -a
Linux teleport.home.arpa 4.14.274 #0 SMP Wed Mar 30 06:09:22 2022 armv7l GNU/Linux
```
