### ISSUE TITLE
"SLOW TRANSACTION" sqlite warnings render cluster unusable after upgrade

### ISSUE THREAD

**Issue by codingllama** [gravitational/teleport#12743]
**Expected behavior:**

Upgrade goes smoothly, everything works, magic.

**Current behavior:**

Customer reported issues after an attempted upgrade from `v7.3.8` to `v8.3.9`(OSS). Logs are swamped with "SLOW TRANSACTION" warnings and the Web UI becomes unusable.

Downgrading back to `v7.3.8` is a viable mitigation.

Log excerpts from v8:

```
2022-05-18T15:58:09Z WARN [REVERSE:T] Cache "remote-proxy" first init failed, continuing re-init attempts in background. error:[
ERROR REPORT:
Original Error: *trace.ConnectionProblemError connection error: desc = &#34;transport: Error while dialing failed to dial: cluster XXXX is offline&#34;
Stack Trace:
	/go/src/github.com/gravitational/teleport/vendor/github.com/gravitational/teleport/api/client/streamwatcher.go:40 github.com/gravitational/teleport/api/client.(*Client).NewWatcher
	/go/src/github.com/gravitational/teleport/lib/cache/cache.go:803 github.com/gravitational/teleport/lib/cache.(*Cache).fetchAndWatch
	/go/src/github.com/gravitational/teleport/lib/cache/cache.go:726 github.com/gravitational/teleport/lib/cache.(*Cache).update
	/opt/go/src/runtime/asm_amd64.s:1581 runtime.goexit
User Message: connection error: desc = &#34;transport: Error while dialing failed to dial: cluster XXXX is offline&#34;] cache/cache.go:689
```

The vast majority of SLOW TRANSACTION are like the ones below:

```
2022-05-18T16:03:10Z WARN [SQLITE]    "SLOW TRANSACTION: 1.024480269s,

goroutine 127509 [running]:
  runtime/debug.Stack()
    /opt/go/src/runtime/debug/stack.go:24 +0x65
  github.com/gravitational/teleport/lib/backend/lite.(*Backend).inTransaction.func1()
    /go/src/github.com/gravitational/teleport/lib/backend/lite/lite.go:876 +0x5b
  github.com/gravitational/teleport/lib/backend/lite.(*Backend).inTransaction(0xc000920340, {0x52e50b0, 0xc000130008}, 0xc014bc9058)
    /go/src/github.com/gravitational/teleport/lib/backend/lite/lite.go:927 +0x22c
  github.com/gravitational/teleport/lib/backend/lite.(*Backend).Put(0x2d6ed034311910, {0x52e50b0, 0xc000130008}, {{0xc006a08420, 0x5d, 0x60}, {0xc01465f980, 0x161, 0x161}, {0x13802725, ...}, ...})
    /go/src/github.com/gravitational/teleport/lib/backend/lite/lite.go:439 +0xda
  github.com/gravitational/teleport/lib/backend.(*Sanitizer).Put(0xc0000dfa80, {0x52e50b0, 0xc000130008}, {{0xc006a08420, 0x5d, 0x60}, {0xc01465f980, 0x161, 0x161}, {0x13802725, ...}, ...})
    /go/src/github.com/gravitational/teleport/lib/backend/sanitize.go:81 +0xc5
  github.com/gravitational/teleport/lib/backend.(*Reporter).Put(0xc0008c7350, {0x52e50b0, 0xc000130008}, {{0xc006a08420, 0x5d, 0x60}, {0xc01465f980, 0x161, 0x161}, {0x13802725, ...}, ...})
    /go/src/github.com/gravitational/teleport/lib/backend/report.go:139 +0xca
  github.com/gravitational/teleport/lib/services/local.(*PresenceService).UpsertTunnelConnection(0xc00013b680, {0x53751e8, 0xc008694a20})
    /go/src/github.com/gravitational/teleport/lib/services/local/presence.go:581 +0x364
  github.com/gravitational/teleport/lib/auth.(*ServerWithRoles).UpsertTunnelConnection(0xc00878fc70, {0x53751e8, 0xc008694a20})
    /go/src/github.com/gravitational/teleport/lib/auth/auth_with_roles.go:2596 +0xe5
  github.com/gravitational/teleport/lib/auth.(*APIServer).upsertTunnelConnection(0xc000090c00, {0x53a4730, 0xc00878fc70}, {0x14af506, 0xc014bc94e0}, 0x532507, {0x68, 0x0, 0x0}, {0xc01468bce1, ...})
    /go/src/github.com/gravitational/teleport/lib/auth/apiserver.go:2420 +0xa5
  github.com/gravitational/teleport/lib/auth.(*APIServer).withAuth.func1({0x52a19f8, 0xc007d495e0}, 0xc013fccb00, {0xc014883c80, 0x1, 0x3})
    /go/src/github.com/gravitational/teleport/lib/auth/apiserver.go:306 +0x3c4
  github.com/gravitational/teleport/lib/httplib.MakeHandlerWithErrorWriter.func1({0x52a19f8, 0xc007d495e0}, 0xc0070584e0, {0xc014883c80, 0x1, 0x3})
    /go/src/github.com/gravitational/teleport/lib/httplib/httplib.go:67 +0x89
  github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc000294528, {0x52a19f8, 0xc007d495e0}, 0xc013fccb00)
    /go/src/github.com/gravitational/teleport/vendor/github.com/julienschmidt/httprouter/router.go:399 +0x86b
  github.com/gravitational/teleport/lib/httplib.RewritePaths.func1({0x52a19f8, 0xc007d495e0}, 0xc013fccb00)
    /go/src/github.com/gravitational/teleport/lib/httplib/httplib.go:184 +0x6b
  net/http.HandlerFunc.ServeHTTP(0x52e5078, {0x52a19f8, 0xc007d495e0}, 0x51dd300)
    /opt/go/src/net/http/server.go:2047 +0x2f
  github.com/gravitational/teleport/lib/auth.(*Middleware).ServeHTTP(0xc000071680, {0x52a19f8, 0xc007d495e0}, 0xc013fbaa00)
    /go/src/github.com/gravitational/teleport/lib/auth/middleware.go:593 +0x35d
  github.com/gravitational/oxy/ratelimit.(*TokenLimiter).ServeHTTP(0xc001817c80, {0x52a19f8, 0xc007d495e0}, 0xc013fbaa00)
    /go/src/github.com/gravitational/teleport/vendor/github.com/gravitational/oxy/ratelimit/tokenlimiter.go:118 +0x1ce
  github.com/gravitational/oxy/connlimit.(*ConnLimiter).ServeHTTP(0xc0018c22a0, {0x52a19f8, 0xc007d495e0}, 0xc008ebea50)
    /go/src/github.com/gravitational/teleport/vendor/github.com/gravitational/oxy/connlimit/connlimit.go:75 +0x326
  net/http.serverHandler.ServeHTTP({0x528a760}, {0x52a19f8, 0xc007d495e0}, 0xc013fbaa00)
    /opt/go/src/net/http/server.go:2879 +0x43b
  net/http.(*conn).serve(0xc0048530e0, {0x52e5120, 0xc0019cda10})
    /opt/go/src/net/http/server.go:1930 +0xb08
  created by net/http.(*Server).Serve
    /opt/go/src/net/http/server.go:3034 +0x4e8
  ." lite/lite.go:876
```

Also observed, but in a much smaller frequency:

```
2022-05-18T16:03:20Z WARN [SQLITE]    "SLOW TRANSACTION: 11.153682906s,

goroutine 121144 [running]:
  runtime/debug.Stack()
    /opt/go/src/runtime/debug/stack.go:24 +0x65
  github.com/gravitational/teleport/lib/backend/lite.(*Backend).inTransaction.func1()
    /go/src/github.com/gravitational/teleport/lib/backend/lite/lite.go:876 +0x5b
  github.com/gravitational/teleport/lib/backend/lite.(*Backend).inTransaction(0xc000920340, {0x52e50b0, 0xc000130008}, 0xc015866d30)
    /go/src/github.com/gravitational/teleport/lib/backend/lite/lite.go:927 +0x22c
  github.com/gravitational/teleport/lib/backend/lite.(*Backend).Get(0xc000920340, {0x52e50b0, 0xc000130008}, {0xc006bba2d0, 0x1, 0x30})
    /go/src/github.com/gravitational/teleport/lib/backend/lite/lite.go:630 +0x105
  github.com/gravitational/teleport/lib/backend.(*Sanitizer).Get(0xc0000dfa80, {0x52e50b0, 0xc000130008}, {0xc006bba2d0, 0x25, 0x30})
    /go/src/github.com/gravitational/teleport/lib/backend/sanitize.go:98 +0x74
  github.com/gravitational/teleport/lib/backend.(*Reporter).Get(0xc0008c7350, {0x52e50b0, 0xc000130008}, {0xc006bba2d0, 0x25, 0x30})
    /go/src/github.com/gravitational/teleport/lib/backend/report.go:167 +0x1e3
  github.com/gravitational/teleport/lib/services/local.(*PresenceService).getRemoteCluster(0xc00013b680, {0xc0080624e0, 0x52949a8})
    /go/src/github.com/gravitational/teleport/lib/services/local/presence.go:763 +0x167
  github.com/gravitational/teleport/lib/services/local.(*PresenceService).UpdateRemoteCluster(0xc00013b680, {0x52e50b0, 0xc000130008}, {0x536e610, 0xc00492a600})
    /go/src/github.com/gravitational/teleport/lib/services/local/presence.go:708 +0x92
  github.com/gravitational/teleport/lib/auth.(*Server).updateRemoteClusterStatus(0xc0004461e0, {0x536e610, 0xc00492a600})
    /go/src/github.com/gravitational/teleport/lib/auth/trustedcluster.go:424 +0x4aa
  github.com/gravitational/teleport/lib/auth.(*Server).GetRemoteClusters(0xc0004461e0, {0x0, 0x7, 0x4225ca8})
    /go/src/github.com/gravitational/teleport/lib/auth/trustedcluster.go:448 +0xcc
  github.com/gravitational/teleport/lib/auth.(*ServerWithRoles).GetRemoteClusters(0xc00b5bd960, {0x0, 0x0, 0x0})
    /go/src/github.com/gravitational/teleport/lib/auth/auth_with_roles.go:2666 +0x93
  github.com/gravitational/teleport/lib/auth.(*APIServer).getRemoteClusters(0xc000090800, {0x53a4730, 0xc00b5bd960}, {0x14af506, 0xc011b974e0}, 0x532507, {0x68, 0x0, 0x0}, {0xc006f44c79, ...})
    /go/src/github.com/gravitational/teleport/lib/auth/apiserver.go:2510 +0x3b
  github.com/gravitational/teleport/lib/auth.(*APIServer).withAuth.func1({0x52a19f8, 0xc0089f1dc0}, 0xc004855d00, {0xc00fb07680, 0x1, 0x3})
    /go/src/github.com/gravitational/teleport/lib/auth/apiserver.go:306 +0x3c4
  github.com/gravitational/teleport/lib/httplib.MakeHandlerWithErrorWriter.func1({0x52a19f8, 0xc0089f1dc0}, 0xc002b9c240, {0xc00fb07680, 0x1, 0x3})
    /go/src/github.com/gravitational/teleport/lib/httplib/httplib.go:67 +0x89
  github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc000294528, {0x52a19f8, 0xc0089f1dc0}, 0xc004855d00)
    /go/src/github.com/gravitational/teleport/vendor/github.com/julienschmidt/httprouter/router.go:399 +0x86b
  github.com/gravitational/teleport/lib/httplib.RewritePaths.func1({0x52a19f8, 0xc0089f1dc0}, 0xc004855d00)
    /go/src/github.com/gravitational/teleport/lib/httplib/httplib.go:184 +0x6b
  net/http.HandlerFunc.ServeHTTP(0x52e5078, {0x52a19f8, 0xc0089f1dc0}, 0x51dd300)
    /opt/go/src/net/http/server.go:2047 +0x2f
  github.com/gravitational/teleport/lib/auth.(*Middleware).ServeHTTP(0xc000071680, {0x52a19f8, 0xc0089f1dc0}, 0xc005171000)
    /go/src/github.com/gravitational/teleport/lib/auth/middleware.go:593 +0x35d
  github.com/gravitational/oxy/ratelimit.(*TokenLimiter).ServeHTTP(0xc001817c80, {0x52a19f8, 0xc0089f1dc0}, 0xc005171000)
    /go/src/github.com/gravitational/teleport/vendor/github.com/gravitational/oxy/ratelimit/tokenlimiter.go:118 +0x1ce
  github.com/gravitational/oxy/connlimit.(*ConnLimiter).ServeHTTP(0xc0018c22a0, {0x52a19f8, 0xc0089f1dc0}, 0x10000c00258f9e0)
    /go/src/github.com/gravitational/teleport/vendor/github.com/gravitational/oxy/connlimit/connlimit.go:75 +0x326
  net/http.serverHandler.ServeHTTP({0xc006cbff50}, {0x52a19f8, 0xc0089f1dc0}, 0xc005171000)
    /opt/go/src/net/http/server.go:2879 +0x43b
  net/http.(*conn).serve(0xc003f40fa0, {0x52e5120, 0xc0019cda10})
    /opt/go/src/net/http/server.go:1930 +0xb08
  created by net/http.(*Server).Serve
    /opt/go/src/net/http/server.go:3034 +0x4e8
  ." lite/lite.go:876
```

Note that "failed to dial" are also seen in v7, but slow transaction or other degradation symptoms aren't.

Bug details:
- Teleport version: v8.3.9
- Recreation steps: unclear
- Debug logs: see excerpts above, ask me for more details.

**Comment by codingllama** [comment]
Other details that we've noticed, but don't seem necessarily tied to the main issue:

The customer has a few enterprise clusters that underwent the same version upgrade, but didn't present any issues. One of the Enterprise servers shows a large number of ["Discovery channel overflow" warnings](https://github.com/gravitational/teleport/blob/ee02465d14dd2b7fa12521ac957ca41f0006d274/lib/reversetunnel/conn.go#L208). It might be worth a look.

The enterprise clusters are happily running `v8.3.9` at the moment.

**Comment by ruiztulio** [comment]
@espadolini I applied that config the same day you posted it, seems to be working good so far:

![image](https://user-images.githubusercontent.com/2739530/170723026-b3ec36f8-a7aa-425f-a6c1-5e4d0cfa3dd1.png)

The ```sync``` option didn't work, actually showed me an error, but the storage type worked fine like this:

```yaml
teleport:
    storage:
        type: sqlite
```

The log isn't spammed with the sqlite messages and the CPU usage is very low:

![image](https://user-images.githubusercontent.com/2739530/170723606-5ee29566-b37c-4da9-95a6-5005357fb092.png)

Thanks for the tip

**Comment by espadolini** [comment]
@ruiztulio what version are you running? Specifying the backend type as `sqlite` was only necessary because of a quirk in how we process the configuration file - the default was already `sqlite`. I guess restarting fixed your auth for now, but the issue might still be there?

**Comment by ruiztulio** [comment]
@espadolini The version is:

Teleport Version: v9.0.4 git:v9.0.4-0-gf577413d3 go1.17.7 OSS

I read the doc and the sqlite was the default, tried you advice because I thought something wasn't updated (either the default or the doc).

I had to restarted previous to the change a few times because it became unusable at times. Perhaps is flacky thing?

**Comment by espadolini** [comment]
There could be some other issue that's causing a lot of backend writes, but your version already runs sqlite with the behavior that's specified in my config file snippet, so the performance wouldn't improve; you should consider upgrading to the latest (v9.3.0), however.

**Comment by aleedom** [comment]
Got back into the office today, and was in the process of testing the change above, 
```
teleport:
  storage:
    type: sqlite
    sync: OFF
```
but it looks like its not necessary.  

Prior to testing that change, I upgraded the cluster from version 7.3.8 (downgraded to that version after first failed upgrade) to 8.3.12 (problem initially happend after upgrading to 8.3.9). The server seems to be stable on 8.3.12 without needing the config change.

**Comment by aleedom** [comment]
WIth sync off, I don't seem to be seeing the slow transactions any more.  Going to hold off on changing the journal mode for now to see if things stay stable.   Once things stabalize on 8.x our first priority is to migrate to a better storage solution, almost certainly dynamo db.

**Comment by espadolini** [comment]
Let's wait for a few more days to see if the problem resurfaces again.

We're not currently using SQLite to its fullest extent because typically when a cluster becomes big enough for performance to be an issue, it also becomes important enough to require a HA-capable backend - which sqlite is very much not, barring weird - and unsupported - setups with NFS. If you're planning on moving to etcd or dynamodb in the near future it's not really a priority to make your current setup more resilient; please take regular backups of your backend, however. 😅

**Comment by espadolini** [comment]
@aleedom Has the cluster been stable after the changes to the sync mode? Any further issues?
