### ISSUE TITLE
TestLimiter is flaky

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#13526]
From the CI:

```
FAIL: github.com/gravitational/teleport/lib/srv/regular
FAIL: github.com/gravitational/teleport/lib/srv/regular.TestLimiter
...
    sshserver_test.go:1491: 
        	Error Trace:	sshserver_test.go:1491
        	Error:      	Expected value not to be nil.
        	Test:       	TestLimiter
```
CI Logs:
- https://console.cloud.google.com/cloud-build/builds/a9a86131-7a3f-4485-9e63-8e880039d3ac;step=0?project=ci-account
- https://console.cloud.google.com/cloud-build/builds;region=us-west1/e301f826-2435-4419-adf5-8d6c1c6470eb?project=ci-account
- https://console.cloud.google.com/cloud-build/builds;region=us-west1/d5048ba4-c06a-411d-9718-599a543e393c?project=ci-account

Investigate how to remove the test's reliance on time and make it non-flaky.

**Comment by zmb3** [comment]
I've also seen it panic, not just fail.

```
➜ go test -run TestLimiter -race -count=100 ./lib/srv/regular
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x103839518]

goroutine 20317 [running]:
github.com/gravitational/teleport/lib/srv.(*terminal).closeTTY(0x0)
	/Users/zmb/teleport/lib/srv/term.go:273 +0x38
github.com/gravitational/teleport/lib/srv.(*terminal).Close(0x0)
	/Users/zmb/teleport/lib/srv/term.go:265 +0x30
github.com/gravitational/teleport/lib/srv.(*session).Stop(0xc001dcf760)
	/Users/zmb/teleport/lib/srv/sess.go:661 +0x1a4
github.com/gravitational/teleport/lib/srv.(*session).Close(0xc001dcf760)
	/Users/zmb/teleport/lib/srv/sess.go:680 +0x38
github.com/gravitational/teleport/lib/srv.(*SessionRegistry).OpenSession(0xc004620f00?, {0x105234990, 0xc000b50480}, 0xc004620f00)
	/Users/zmb/teleport/lib/srv/sess.go:266 +0x398
github.com/gravitational/teleport/lib/srv.(*TermHandlers).HandleShell(0xc0053d18a8, {0x105234990, 0xc000b50480}, 0xc004bb2980, 0xc004620f00)
	/Users/zmb/teleport/lib/srv/termhandlers.go:115 +0x108
github.com/gravitational/teleport/lib/srv/regular.(*Server).dispatch(0xc001a13b80, {0x1052300c8, 0xc004f533c0}, {0x105234990, 0xc000b50480}, 0xc004bb2980, 0xc004620f00)
	/Users/zmb/teleport/lib/srv/regular/sshserver.go:1575 +0x604
github.com/gravitational/teleport/lib/srv/regular.(*Server).handleSessionRequests(0xc001a13b80, {0x1052300c8, 0xc004f533c0}, _, {{0xc004b3c07d, 0x3}, {0x0, 0x0}, {0xc004989abd, 0x3}, ...}, ...)
	/Users/zmb/teleport/lib/srv/regular/sshserver.go:1485 +0xb14
github.com/gravitational/teleport/lib/srv/regular.(*Server).HandleNewChan.func1()
	/Users/zmb/teleport/lib/srv/regular/sshserver.go:1217 +0xd8
created by github.com/gravitational/teleport/lib/srv/regular.(*Server).HandleNewChan
	/Users/zmb/teleport/lib/srv/regular/sshserver.go:1216 +0xeb0
FAIL	github.com/gravitational/teleport/lib/srv/regular	94.129s
FAIL
```

**Comment by nklaassen** [comment]
hit this a couple times today, added logs to the description

**Comment by zmb3** [comment]
Reopening this one as it's back among the top failing tests.

**Comment by GavinFrazar** [comment]
Saw this fail today for failing to cleanup a temp dir. We must have some goroutine that we don't wait to finish in the test:

log: https://console.cloud.google.com/cloud-build/builds/7749e62a-191d-43dc-a608-9e86e083d030?project=ci-account

relevant snippet:

```
OUTPUT github.com/gravitational/teleport/lib/srv/regular.TestLimiter
===================================================
=== RUN   TestLimiter
=== PAUSE TestLimiter
=== CONT  TestLimiter
=== CONT  TestLimiter
    testing.go:1090: TempDir RemoveAll cleanup: unlinkat /tmp/TestLimiter672771855/003/log/upload/streaming/default: directory not empty
--- FAIL: TestLimiter (16.40s)
```

While trying to repro locally I also noticed that this test case is creating zombie shell processes: 3 new shell processes per run. I now have 177 tty zombies.

**Comment by zmb3** [comment]
@GavinFrazar I've noticed the same when trying to reproduce `TestAgentForward`. Something in lib/srv is not cleaning up shell processes correctly.

**Comment by GavinFrazar** [comment]
I think this test caused this failure on branch/v11: https://console.cloud.google.com/cloud-build/builds/cd51f11c-8f22-4099-8e7e-01a8b013f145?project=ci-account

either that or TestInactivityTimeout, it's hard to tell what caused the test suite timeout

**Comment by zmb3** [comment]
There seems to still be a few issues with this one:

1. It suffers from #13335, so reproducing flakes locally is a pain.
2. It suffers from the "tempdir cleanup problem" which can be fixed by using `newFixtureWithoutDiskBasedLogging(t)`
3. It's still flaky. `go test -run TestLimiter -race -count=200 -failfast ./lib/srv/regular` failed after about 10 minutes for me locally, but the goroutine dump that it prints is so massive you can't tell what actually went wrong.

**Comment by ibeckermayer** [comment]
I believe this is what flaked here (timeout flake)

https://console.cloud.google.com/cloud-build/builds/e4aa2c54-3c37-470e-966f-a01501ff3f48?project=ci-account

**Comment by zmb3** [comment]
This hasn't shown up recently, The 2 most recent occurrences were the test timeout issue that was recently fixed. I'm calling this one solved.

**Comment by zmb3** [comment]
The timeout is back on v13: https://github.com/gravitational/teleport/actions/runs/5467675358/jobs/9954293445

**Comment by ravicious** [comment]
Timeout on v13, does it warrant reopening?

https://github.com/gravitational/teleport/actions/runs/8141493060/job/22248971636#step:6:4446

```
panic: test timed out after 10m0s
running tests:
	TestLimiter (9m46s)
```
