### ISSUE TITLE
Panic in SSH users creation 

### ISSUE THREAD

**Issue by jakule** [gravitational/teleport#13634]
While testing user creation Teleport process was killed by a panic.

My config and logs below:

Role:
```yaml
kind: role
version: v5
metadata:
  name: auto-users
spec:
  options:
    # Allow automatic creation of users.
    create_host_user: true
  allow:
    logins: [ "ubuntu1" ]
    host_groups: ["ubuntu"]
    node_labels:
      'hostname': 'teleport1'
```

Teleport log:

```
2022-06-17T15:14:49-04:00 INFO [SESSION:N] New party ServerContext(127.0.0.1:45576->127.0.0.1:3022, user=ubuntu1, id=8) party(id=3f857a81-5605-477d-8bfb-3dc883be848c) joined session: 4c8bb22a-a8f4-489c-bc8e-32ecd3730608 srv/sess.go:1608
2022-06-17T15:14:49-04:00 DEBU [SESSION:N] Launching session 4c8bb22a-a8f4-489c-bc8e-32ecd3730608. srv/sess.go:937
2022-06-17T15:14:49-04:00 DEBU [SESSION:N] Tracking participant: 3f857a81-5605-477d-8bfb-3dc883be848c srv/sess.go:1586
2022-06-17T15:14:49-04:00 INFO [SESSION:N] New party ServerContext(127.0.0.1:45576->127.0.0.1:3022, user=ubuntu1, id=8) party(id=3f857a81-5605-477d-8bfb-3dc883be848c) joined session: 4c8bb22a-a8f4-489c-bc8e-32ecd3730608 srv/sess.go:1608
2022-06-17T15:14:49-04:00 DEBU [NODE]      Waiting for continue signal id:8 local:127.0.0.1:3022 login:ubuntu1 remote:127.0.0.1:45576 teleportUser:bob srv/sess.go:1088
2022-06-17T15:14:49-04:00 DEBU [NODE]      Got continue signal id:8 local:127.0.0.1:3022 login:ubuntu1 remote:127.0.0.1:45576 teleportUser:bob srv/sess.go:1104
2022-06-17T15:14:49-04:00 DEBU             Will join session 4c8bb22a-a8f4-489c-bc8e-32ecd3730608 for SSH connection 127.0.0.1:45576. srv/ctx.go:531
2022-06-17T15:14:49-04:00 DEBU [SESSION:N] Starting poll and sync of terminal size to all parties. srv/sess.go:1478
2022-06-17T15:14:51-04:00 DEBU [PROC:1]    Broadcasting event. event:TeleportDegraded pid:17146.1 service/supervisor.go:376
2022-06-17T15:15:51-04:00 DEBU [PROC:1]    Broadcasting event. event:TeleportDegraded pid:17146.1 service/supervisor.go:376
2022-06-17T15:16:51-04:00 DEBU [PROC:1]    Broadcasting event. event:TeleportDegraded pid:17146.1 service/supervisor.go:376
2022-06-17T15:17:51-04:00 DEBU [PROC:1]    Broadcasting event. event:TeleportDegraded pid:17146.1 service/supervisor.go:376
2022-06-17T15:18:51-04:00 DEBU [PROC:1]    Broadcasting event. event:TeleportDegraded pid:17146.1 service/supervisor.go:376
2022-06-17T15:18:51-04:00 DEBU             Failed to find user "root" login time: key /hostuser_interaction_time/root is not found srv/usermgmt.go:282
2022-06-17T15:18:51-04:00 DEBU             Failed to find user "daemon" login time: key /hostuser_interaction_time/daemon is not found srv/usermgmt.go:282
2022-06-17T15:18:51-04:00 DEBU             Failed to find user "bin" login time: key /hostuser_interaction_time/bin is not found srv/usermgmt.go:282
2022-06-17T15:18:51-04:00 DEBU             Failed to find user "sys" login time: key /hostuser_interaction_time/sys is not found srv/usermgmt.go:282
2022-06-17T15:18:51-04:00 DEBU             Failed to find user "sync" login time: key /hostuser_interaction_time/sync is not found srv/usermgmt.go:282
2022-06-17T15:18:51-04:00 DEBU             Failed to find user "games" login time: key /hostuser_interaction_time/games is not found srv/usermgmt.go:282
2022-06-17T15:18:51-04:00 DEBU             Failed to find user "man" login time: key /hostuser_interaction_time/man is not found srv/usermgmt.go:282
2022-06-17T15:18:51-04:00 DEBU             Failed to find user "lp" login time: key /hostuser_interaction_time/lp is not found srv/usermgmt.go:282
2022-06-17T15:18:51-04:00 DEBU             Failed to find user "mail" login time: key /hostuser_interaction_time/mail is not found srv/usermgmt.go:282
2022-06-17T15:18:51-04:00 DEBU             Failed to find user "news" login time: key /hostuser_interaction_time/news is not found srv/usermgmt.go:282
2022-06-17T15:18:51-04:00 DEBU             Failed to find user "uucp" login time: key /hostuser_interaction_time/uucp is not found srv/usermgmt.go:282
2022-06-17T15:18:51-04:00 DEBU             Failed to find user "proxy" login time: key /hostuser_interaction_time/proxy is not found srv/usermgmt.go:282
2022-06-17T15:18:51-04:00 DEBU             Failed to find user "www-data" login time: key /hostuser_interaction_time/www-data is not found srv/usermgmt.go:282
2022-06-17T15:18:51-04:00 DEBU             Failed to find user "backup" login time: key /hostuser_interaction_time/backup is not found srv/usermgmt.go:282
2022-06-17T15:18:51-04:00 DEBU             Failed to find user "list" login time: key /hostuser_interaction_time/list is not found srv/usermgmt.go:282
2022-06-17T15:18:51-04:00 DEBU             Failed to find user "irc" login time: key /hostuser_interaction_time/irc is not found srv/usermgmt.go:282
2022-06-17T15:18:51-04:00 DEBU             Failed to find user "gnats" login time: key /hostuser_interaction_time/gnats is not found srv/usermgmt.go:282
2022-06-17T15:18:51-04:00 DEBU             Failed to find user "nobody" login time: key /hostuser_interaction_time/nobody is not found srv/usermgmt.go:282
2022-06-17T15:18:51-04:00 DEBU             Failed to find user "systemd-network" login time: key /hostuser_interaction_time/systemd-network is not found srv/usermgmt.go:282
2022-06-17T15:18:51-04:00 DEBU             Failed to find user "systemd-resolve" login time: key /hostuser_interaction_time/systemd-resolve is not found srv/usermgmt.go:282
2022-06-17T15:18:51-04:00 DEBU             Failed to find user "messagebus" login time: key /hostuser_interaction_time/messagebus is not found srv/usermgmt.go:282
2022-06-17T15:18:51-04:00 DEBU             Failed to find user "systemd-timesync" login time: key /hostuser_interaction_time/systemd-timesync is not found srv/usermgmt.go:282
2022-06-17T15:18:51-04:00 DEBU             Failed to find user "syslog" login time: key /hostuser_interaction_time/syslog is not found srv/usermgmt.go:282
2022-06-17T15:18:51-04:00 DEBU             Failed to find user "_apt" login time: key /hostuser_interaction_time/_apt is not found srv/usermgmt.go:282
2022-06-17T15:18:51-04:00 DEBU             Failed to find user "tss" login time: key /hostuser_interaction_time/tss is not found srv/usermgmt.go:282
2022-06-17T15:18:51-04:00 DEBU             Failed to find user "uuidd" login time: key /hostuser_interaction_time/uuidd is not found srv/usermgmt.go:282
2022-06-17T15:18:51-04:00 DEBU             Failed to find user "tcpdump" login time: key /hostuser_interaction_time/tcpdump is not found srv/usermgmt.go:282
2022-06-17T15:18:51-04:00 DEBU             Failed to find user "sshd" login time: key /hostuser_interaction_time/sshd is not found srv/usermgmt.go:282
2022-06-17T15:18:51-04:00 DEBU             Failed to find user "pollinate" login time: key /hostuser_interaction_time/pollinate is not found srv/usermgmt.go:282
2022-06-17T15:18:51-04:00 DEBU             Failed to find user "landscape" login time: key /hostuser_interaction_time/landscape is not found srv/usermgmt.go:282
2022-06-17T15:18:51-04:00 DEBU             Failed to find user "ubuntu" login time: key /hostuser_interaction_time/ubuntu is not found srv/usermgmt.go:282
2022-06-17T15:18:51-04:00 DEBU             Failed to find user "lxd" login time: key /hostuser_interaction_time/lxd is not found srv/usermgmt.go:282
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x23918c6]

goroutine 759 [running]:
github.com/gravitational/teleport/lib/services/local.(*PresenceService).GetHostUserInteractionTime(0x0, {0x61b4ac8, 0xc001be6980}, {0xc0006e0fa0?, 0x0?})
	/go/src/github.com/gravitational/teleport/lib/services/local/presence.go:1461 +0x106
github.com/gravitational/teleport/lib/srv.(*HostUserManagement).DeleteAllUsers(0xc001be69c0)
	/go/src/github.com/gravitational/teleport/lib/srv/usermgmt.go:280 +0x1a7
github.com/gravitational/teleport/lib/srv.(*HostUserManagement).UserCleanup(0xc001be69c0)
	/go/src/github.com/gravitational/teleport/lib/srv/usermgmt.go:340 +0x8c
created by github.com/gravitational/teleport/lib/srv/regular.(*Server).Serve
	/go/src/github.com/gravitational/teleport/lib/srv/regular/sshserver.go:381 +0xea
```

tsh log:

```
$ tsh ssh ubuntu1@localhost
$ ls
$ pwd
/home/ubuntu1
$ whoami
ubuntu1
$ ERROR: wait: remote command exited without exit status or exit signal
```

Bug details:
- Teleport version: v10-alpha1
- Recreation steps:
1. Start teleport
2. Start SSH session using user provision
- OS: Ubuntu 22.04 LTS (Jammy Jellyfish)

**Comment by jakule** [comment]
I was able to trace down the issue. It was caused by one code change that I made trying to debug a different issue. I'm closing the issue.
