### ISSUE TITLE
Current v2.3.1 binary crash at startup

### ISSUE THREAD

**Issue by halfa** [gravitational/teleport#1395]
Occurs in `Teleport v2.3.1 git:v2.3.1-0-g35dc536`, the current and latest binary distribution.

```go
$ ./teleport start -d --config=/etc/teleport.yml
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x8778a8]

goroutine 1 [running]:
github.com/gravitational/teleport/lib/utils.VerifyCertificateChain(0xc420185980, 0x16e0, 0x18e0, 0x16e0, 0x18e0)
	/gopath/src/github.com/gravitational/teleport/lib/utils/certs.go:171 +0xa8
github.com/gravitational/teleport/lib/config.ApplyFileConfig(0xc420191b00, 0xc420221680, 0xc420191b00, 0x0)
	/gopath/src/github.com/gravitational/teleport/lib/config/configuration.go:303 +0x1cda
github.com/gravitational/teleport/lib/config.Configure(0xc4201040f0, 0xc420221680, 0x10d85aa, 0x5)
	/gopath/src/github.com/gravitational/teleport/lib/config/configuration.go:614 +0xab
github.com/gravitational/teleport/tool/teleport/common.Run(0xc42008a110, 0x3, 0x3, 0x0, 0x0, 0xc42017bf00, 0xe279d2, 0xc420000340, 0xc420000340)
	/gopath/src/github.com/gravitational/teleport/tool/teleport/common/teleport.go:148 +0x31ca
main.main()
	/gopath/src/github.com/gravitational/teleport/tool/teleport/main.go:30 +0x7c
```

I suspect commit 1f63b8d is the culprit. It doesn't appear in the `Teleport v2.3.1 git:v2.3.0-48-g9936ae20` that I just build from sources.

**Comment by halfa** [comment]
To sum up, the issue seems to be already fixed.
I'm only reporting it because the affected binary is featured on the _release_ page.

**Comment by kontsevoy** [comment]
@halfa correct, this was (most likely) caused by the certificate parsing bug, we'll update the releases page once the official point-release is ready. [day or two]. Thanks!
