### ISSUE TITLE
Teleport Desktop Access 10 SIGSEGV

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#14248]
Current behavior:

While testing Teleport 10, I found that the Teleport service kept crashing on first connection. I'm able to connect after Teleport restarts itself.  The stacktrace is huge, https://gist.github.com/benarent/bb4a28e32d2b749b218dfb23c7f615c2 below is the first part. 

```
Jul 08 17:28:49 ip-10-0-130-83 teleport[28145]: GLOBAL: Unknown Fast Path order RdpError(RdpError { kind: NotImplemented, message: "GLOBAL: Fast Path parsing not implemented Fast>
Jul 08 17:28:55 ip-10-0-130-83 teleport[28145]: 2022-07-08T17:28:55Z [WINDOWS_D] INFO TDP input streaming finished client-ip:35.89.11.66 desktop-addr:10.0.143.123:3389 desktop-na>
Jul 08 17:28:55 ip-10-0-130-83 teleport[28145]: 2022-07-08T17:28:55Z [WINDOWS_D] WARN error closing the TDP connection: EOF client-ip:35.89.11.66 desktop-addr:10.0.143.123:3389 d>
Jul 08 17:28:55 ip-10-0-130-83 teleport[28145]: fatal error: unexpected signal during runtime execution
Jul 08 17:28:55 ip-10-0-130-83 teleport[28145]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x7fa1f468bfc4]
Jul 08 17:28:55 ip-10-0-130-83 teleport[28145]: runtime stack:
Jul 08 17:28:55 ip-10-0-130-83 teleport[28145]: runtime.throw({0x506731b?, 0x4010003?})
Jul 08 17:28:55 ip-10-0-130-83 teleport[28145]:         /opt/go/src/runtime/panic.go:992 +0x71
Jul 08 17:28:55 ip-10-0-130-83 teleport[28145]: runtime.sigpanic()
Jul 08 17:28:55 ip-10-0-130-83 teleport[28145]:         /opt/go/src/runtime/signal_unix.go:802 +0x3a9
Jul 08 17:28:55 ip-10-0-130-83 teleport[28145]: goroutine 550 [syscall]:
Jul 08 17:28:55 ip-10-0-130-83 teleport[28145]: runtime.cgocall(0x3f39e20, 0xc0014e3ed8)
Jul 08 17:28:55 ip-10-0-130-83 teleport[28145]:         /opt/go/src/runtime/cgocall.go:157 +0x5c fp=0xc0014e3eb0 sp=0xc0014e3e78 pc=0x4ff2bc
Jul 08 17:28:55 ip-10-0-130-83 teleport[28145]: github.com/gravitational/teleport/lib/srv/desktop/rdp/rdpclient._Cfunc_read_rdp_output(0x7fa1ac000e50)
Jul 08 17:28:55 ip-10-0-130-83 teleport[28145]:         _cgo_gotypes.go:311 +0x4c fp=0xc0014e3ed8 sp=0xc0014e3eb0 pc=0x387226c
Jul 08 17:28:55 ip-10-0-130-83 teleport[28145]: github.com/gravitational/teleport/lib/srv/desktop/rdp/rdpclient.(*Client).start.func1.1(0x0?)
Jul 08 17:28:55 ip-10-0-130-83 teleport[28145]:         /go/src/github.com/gravitational/teleport/lib/srv/desktop/rdp/rdpclient/client.go:264 +0x46 fp=0xc0014e3f10 sp=0xc0014e3ed>
Jul 08 17:28:55 ip-10-0-130-83 teleport[28145]: github.com/gravitational/teleport/lib/srv/desktop/rdp/rdpclient.(*Client).start.func1()
Jul 08 17:28:55 ip-10-0-130-83 teleport[28145]:         /go/src/github.com/gravitational/teleport/lib/srv/desktop/rdp/rdpclient/client.go:264 +0x11d fp=0xc0014e3fe0 sp=0xc0014e3f>
Jul 08 17:28:55 ip-10-0-130-83 teleport[28145]: runtime.goexit()
```

Bug details:
- Teleport version: `Teleport 10.0.0-rc-1`
- Recreation steps: Create new Teleport Desktop Access cluster with Teleport 10.0.0-rc-1.
- Debug logs: https://gist.github.com/benarent/bb4a28e32d2b749b218dfb23c7f615c2

**Comment by ibeckermayer** [comment]
I think there are two separate issues here, one of them being that the Teleport service is crashing on the first connection, which I don't have a hypothesis for, and the other being the panic.

The panic is similar to the one in https://github.com/gravitational/teleport/issues/13407 (which I still believe has been fixed), and which begins like

```
runtime/cgo.Handle.Value(...)
	/opt/homebrew/Cellar/go/1.18.3/libexec/src/runtime/cgo/handle.go:124
github.com/gravitational/teleport/lib/srv/desktop/rdp/rdpclient.handle_bitmap(0x108baeb20?, 0x140019ce4e0?)
	/Users/zmb/teleport/lib/srv/desktop/rdp/rdpclient/client.go:386 +0x8c
github.com/gravitational/teleport/lib/srv/desktop/rdp/rdpclient._Cfunc_read_rdp_output(0x600003cb0000)
	_cgo_gotypes.go:251 +0x3c
```

vs this one, which begins like

```
runtime.cgocall(0x3f39e20, 0xc0014e3ed8)
        /opt/go/src/runtime/cgocall.go:157 +0x5c fp=0xc0014e3eb0 sp=0xc0014e3e78 pc=0x4ff2bc
github.com/gravitational/teleport/lib/srv/desktop/rdp/rdpclient._Cfunc_read_rdp_output(0x7fa1ac000e50)
        cgo_gotypes.go:311 +0x4c fp=0xc0014e3ed8 sp=0xc0014e3eb0 pc=0x387226c
```

We can see that in this case, the call stack doesn't get all the way down to `handle_bitmap`, but rather we panic somewhere before then in `read_rdp_output`.

The two logs before the crash show the TDP input streaming goroutine finished "cleanly", and then called our cleanup function `c.close()`:
```
2022-07-08T17:28:55Z [WINDOWS_D] INFO TDP input streaming finished client-ip:35.89.11.66 desktop-addr:10.0.143.123:3389 desktop-na>
2022-07-08T17:28:55Z [WINDOWS_D] WARN error closing the TDP connection: EOF client-ip:35.89.11.66 desktop-addr:10.0.143.123:3389 d>
```
"clean" finish:
https://github.com/gravitational/teleport/blob/0896236422cc20c17116eea5c69863b698cefff6/lib/srv/desktop/rdp/rdpclient/client.go#L277-L287

and `c.close()`:
https://github.com/gravitational/teleport/blob/0896236422cc20c17116eea5c69863b698cefff6/lib/srv/desktop/rdp/rdpclient/client.go#L525-L543

I think what's happening is that both of those are taking place _before_ the corresponding RDP output streaming goroutine has even started:
https://github.com/gravitational/teleport/blob/0896236422cc20c17116eea5c69863b698cefff6/lib/srv/desktop/rdp/rdpclient/client.go#L257-L273

Ergo when `C.read_rdp_output(c.rustClient)` is first called in that RDP output streaming goroutine, `C.free_rdp(c.rustClient) ` has already been called in the cleanup function `c.close()`, which causes us to access freed memory here in `read_rdp_output`:
https://github.com/gravitational/teleport/blob/0896236422cc20c17116eea5c69863b698cefff6/lib/srv/desktop/rdp/rdpclient/src/lib.rs#L595
