### ISSUE TITLE
Resource watcher leak resources

### ISSUE THREAD

**Issue by jakule** [gravitational/teleport#14634]
Expected behavior:

Resource watcher should stop all resources when `Close()` is called.

Current behavior:

Goleak reports multiple goroutine leaks when added to our tests. Example from 

```
    leaks.go:78: found unexpected goroutines:
        [Goroutine 12 in state select, with github.com/gravitational/teleport/lib/services.(*resourceWatcher).watch on top of the stack:
        goroutine 12 [select]:
        github.com/gravitational/teleport/lib/services.(*resourceWatcher).watch(0x140001a0480)
        	/Users/jnyckowski/projects/teleport/lib/services/watcher.go:264 +0x544
        github.com/gravitational/teleport/lib/services.(*resourceWatcher).runWatchLoop(0x140001a0480)
        	/Users/jnyckowski/projects/teleport/lib/services/watcher.go:179 +0x74
        created by github.com/gravitational/teleport/lib/services.newResourceWatcher
        	/Users/jnyckowski/projects/teleport/lib/services/watcher.go:117 +0x310
        
         Goroutine 25 in state select, with github.com/gravitational/teleport/lib/services/local.(*watcher).forwardEvents on top of the stack:
        goroutine 25 [select]:
        github.com/gravitational/teleport/lib/services/local.(*watcher).forwardEvents(0x1400079ef80)
        	/Users/jnyckowski/projects/teleport/lib/services/local/events.go:202 +0xac
        created by github.com/gravitational/teleport/lib/services/local.newWatcher
        	/Users/jnyckowski/projects/teleport/lib/services/local/events.go:162 +0x138
        ]
```

Bug details:
- Teleport version __master__
- Recreation steps
  * Enable https://github.com/uber-go/goleak in any "watcher" test
  * Disable parallel execution - for some reason goleak reports fewer bugs when `t.Parallel()` is enabled.
- Debug logs

**Comment by zmb3** [comment]
`(*resourceWatcher).runWatchLoop` looks super complicated - @rosstimothy can your team take a look and see if we can clean this up?
