### ISSUE TITLE
panic: lib/srv.(*Server).handleDirectTCPIPRequest:  invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by pierrre** [gravitational/teleport#1479]
Error:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x4640df]

goroutine 220300 [running]:
io.copyBuffer(0x1842620, 0xc42040a4d0, 0x0, 0x0, 0xc420136000, 0x8000, 0x8000, 0xc4203545c8, 0xc42040a4d0, 0xf486a0)
        /opt/go/src/io/io.go:390 +0xdf
io.Copy(0x1842620, 0xc42040a4d0, 0x0, 0x0, 0x0, 0x0, 0xc4202e5620)
        /opt/go/src/io/io.go:360 +0x68
net.genericReadFrom(0x183fbe0, 0xc420478b18, 0x0, 0x0, 0x0, 0x0, 0x0)
        /opt/go/src/net/net.go:608 +0x8d
net.(*TCPConn).readFrom(0xc420478b18, 0x0, 0x0, 0xc, 0xc4203b5ae0, 0xc420354688)
        /opt/go/src/net/tcpsock_posix.go:51 +0xa5
net.(*TCPConn).ReadFrom(0xc420478b18, 0x0, 0x0, 0x7fe3a40b8a40, 0xc420478b18, 0x2a61de92101)
        /opt/go/src/net/tcpsock.go:88 +0x5f
io.copyBuffer(0x183fbe0, 0xc420478b18, 0x0, 0x0, 0x0, 0x0, 0x0, 0x103a800, 0xc420354700, 0x183fbe0)
        /opt/go/src/io/io.go:384 +0x2cb
io.Copy(0x183fbe0, 0xc420478b18, 0x0, 0x0, 0x0, 0xc4203547c0, 0x72d015)
        /opt/go/src/io/io.go:360 +0x68
github.com/gravitational/teleport/lib/srv.(*Server).handleDirectTCPIPRequest.func2(0xc42040a4c0, 0x184fe00, 0xc420478b18, 0x0, 0x0)
        /gopath/src/github.com/gravitational/teleport/lib/srv/sshserver.go:791 +0xd3
created by github.com/gravitational/teleport/lib/srv.(*Server).handleDirectTCPIPRequest
        /gopath/src/github.com/gravitational/teleport/lib/srv/sshserver.go:793 +0x928
```

Version: `Teleport v2.2.7 git:v2.2.7-1-ge354e02b`
(Yes I know it's an old version)

**Comment by klizhentas** [comment]
interesting problem. I can't spot the root cause just looking at the code path:

https://github.com/gravitational/teleport/blob/v2.2.7/lib/srv/sshserver.go

can you reliably reproduce?

**Comment by pierrre** [comment]
Hello,
No sorry I can't reproduce it.
It happened once on 1 server.

It looks like the code has changed a lot since v2.2.7. (the file doesn't exist anymore)
You can close the issue if you want (I think you will not support this old version).

I will ask my team to update to the latest version.
