### ISSUE TITLE
`TestSemaphoreLock` flakiness

### ISSUE THREAD

**Issue by zmb3** [gravitational/teleport#14842]
## Failure

Note: this was on `branch/v10`, so it's possible that a fix on master hasn't been backported yet.

#### Link(s) to logs

- https://console.cloud.google.com/cloud-build/builds;region=us-west1/017f5ba0-fc70-498f-ad6a-70cbd8578352;step=0?project=ci-account

#### Relevant snippet

```
----------------------------------------------------------------------
FAIL: services_test.go:151: ServicesSuite.TestSemaphoreLock

services_test.go:152:
    s.suite.SemaphoreLock(c)
/workspace/lib/fixtures/fixtures.go:29:
    c.Assert(trace.IsNotFound(err), check.Equals, true, check.Commentf("expected NotFound, got %T %v at %v", trace.Unwrap(err), err, string(debug.Stack())))
... obtained bool = false
... expected bool = true
... expected NotFound, got context.deadlineExceededError context deadline exceeded at goroutine 13438 [running]:
runtime/debug.Stack()
	/opt/go/src/runtime/debug/stack.go:24 +0x72
github.com/gravitational/teleport/lib/fixtures.ExpectNotFound(0xc000c48000?, {0x2a8b540, 0xc000e4a960})
	/workspace/lib/fixtures/fixtures.go:29 +0xb4
github.com/gravitational/teleport/lib/services/suite.(*ServicesTestSuite).SemaphoreLock(0xc000260e70, 0x520d65?)
	/workspace/lib/services/suite/suite.go:1327 +0x89a
github.com/gravitational/teleport/lib/services/local.(*ServicesSuite).TestSemaphoreLock(0xc00000eea0, 0x16?)
	/workspace/lib/services/local/services_test.go:152 +0x4b
reflect.Value.call({0x1dbed40?, 0xc00000eea0?, 0xc0000c3cf8?}, {0x1e08ef5, 0x4}, {0xc000617ee0, 0x1, 0xc0000c3d18?})
	/opt/go/src/reflect/value.go:556 +0xd9d
reflect.Value.Call({0x1dbed40?, 0xc00000eea0?, 0xc000780020?}, {0xc0000c3ee0, 0x1, 0x1})
	/opt/go/src/reflect/value.go:339 +0xd8
gopkg.in/check%2ev1.(*suiteRunner).forkTest.func1(0xc0004ac960)
	/go/pkg/mod/gopkg.in/check.v1@v1.0.0-20201130134442-10cb98267c6c/check.go:775 +0xa72
gopkg.in/check%2ev1.(*suiteRunner).forkCall.func1()
	/go/pkg/mod/gopkg.in/check.v1@v1.0.0-20201130134442-10cb98267c6c/check.go:669 +0xe6
created by gopkg.in/check%2ev1.(*suiteRunner).forkCall
	/go/pkg/mod/gopkg.in/check.v1@v1.0.0-20201130134442-10cb98267c6c/check.go:666 +0x585
```

**Comment by fspmarshall** [comment]
Aught to be fixed now that https://github.com/gravitational/teleport/pull/14475 is merged.  Feel free to re-open if that doesn't pan out.
