### ISSUE TITLE
Can't set user logins on existent account

### ISSUE THREAD

**Issue by lfdominguez** [gravitational/teleport#15083]
Expected behavior:
Add the missing login to existent user with the command `tctl users update --set-logins=login user`

Current behavior:
Crash:
```
panic: assignment to entry in nil map

goroutine 1 [running, locked to thread]:
github.com/gravitational/teleport/tool/tctl/common.(*UserCommand).Update(0xc000c96140, {0x37f2a60, 0xc000c7b080}, {0x381f2e8, 0xc000c834c0})
	/go/src/github.com/gravitational/teleport/tool/tctl/common/user_command.go:309 +0x333
github.com/gravitational/teleport/tool/tctl/common.(*UserCommand).TryRun(0xc000c96140, {0x37f2a60, 0xc000c7b080}, {0xc00097ab60, 0xc}, {0x381f2e8, 0xc000c834c0})
	/go/src/github.com/gravitational/teleport/tool/tctl/common/user_command.go:123 +0x1b7
github.com/gravitational/teleport/tool/tctl/common.Run({0xc000d1fe60, 0x11, 0x41f525?})
	/go/src/github.com/gravitational/teleport/tool/tctl/common/tctl.go:186 +0x113d
main.main()
	/go/src/github.com/gravitational/teleport/tool/tctl/main.go:46 +0x36a
```

Bug details:
- Teleport version: `Teleport v10.0.2 git:v10.1.0-dev.ryan.1-0-g9c2b63781 go1.18.3`

- Recreation steps:
  1. Create a user without principals (logins)
  2. Try to add login to the created account with command `tctl users update --set-logins=login user` 
 
- Debug logs
```
panic: assignment to entry in nil map

goroutine 1 [running, locked to thread]:
github.com/gravitational/teleport/tool/tctl/common.(*UserCommand).Update(0xc000c96140, {0x37f2a60, 0xc000c7b080}, {0x381f2e8, 0xc000c834c0})
	/go/src/github.com/gravitational/teleport/tool/tctl/common/user_command.go:309 +0x333
github.com/gravitational/teleport/tool/tctl/common.(*UserCommand).TryRun(0xc000c96140, {0x37f2a60, 0xc000c7b080}, {0xc00097ab60, 0xc}, {0x381f2e8, 0xc000c834c0})
	/go/src/github.com/gravitational/teleport/tool/tctl/common/user_command.go:123 +0x1b7
github.com/gravitational/teleport/tool/tctl/common.Run({0xc000d1fe60, 0x11, 0x41f525?})
	/go/src/github.com/gravitational/teleport/tool/tctl/common/tctl.go:186 +0x113d
main.main()
	/go/src/github.com/gravitational/teleport/tool/tctl/main.go:46 +0x36a
```

**Comment by strideynet** [comment]
It appears https://github.com/gravitational/teleport/pull/14552/files makes use of the new `SetRoles` method on the User type, which accounts for situations where there are no existing traits. So when that's merged down, this bug will be fixed.
