### ISSUE TITLE
`TestEC2IsInstanceMetadataAvailable` flakiness

### ISSUE THREAD

**Issue by zmb3** [gravitational/teleport#15304]
#### Link(s) to logs

- https://console.cloud.google.com/cloud-build/builds/52d61a26-7ba6-4982-a10d-4ca10841ff2a;step=0?project=ci-account

#### Relevant snippet

```
=== CONT  TestEC2IsInstanceMetadataAvailable/response_with_new_id_format
    ec2_test.go:156: 
        	Error Trace:	ec2_test.go:156
        	Error:      	Should be true
        	Test:       	TestEC2IsInstanceMetadataAvailable/response_with_new_id_format
    --- FAIL: TestEC2IsInstanceMetadataAvailable/response_with_new_id_format (0.35s)
```

**Comment by zmb3** [comment]
Running on 716c2bdbf93944eecc49a43f582b5af5d0602378, I'm not able to reproduce the error here, but I do see the test occasionally time out after 10 minutes.

Reproduce locally with:

```
go test -run TestEC2IsInstanceMetadataAvailable ./lib/cloud/aws -count=200 -failfast
```

It looks like the code is stuck in a sleep in the AWS SDK when the timeout occurs:

```
goroutine 2279 [select]:
github.com/aws/aws-sdk-go-v2/internal/sdk.sleepWithContext({0x10172cd40, 0x14000447cb0}, 0x101718ee0?)
	/Users/zmb/go/pkg/mod/github.com/aws/aws-sdk-go-v2@v1.16.16/internal/sdk/time.go:36 +0xa4
github.com/aws/aws-sdk-go-v2/aws/retry.(*Attempt).handleAttempt(0x1400020e500, {0x10172cd40, 0x14000447cb0}, {{0x1016ecc20?, 0x14000447bf0?}}, 0x101713338, {0x10171b960, 0x1400020e6c0})
	/Users/zmb/go/pkg/mod/github.com/aws/aws-sdk-go-v2@v1.16.16/aws/retry/middleware.go:232 +0x830
github.com/aws/aws-sdk-go-v2/aws/retry.(*Attempt).HandleFinalize(0x1400020e500, {0x10172cd08, 0x140006a2ae0}, {{0x1016ecc20?, 0x14000447b60?}}, {0x10171b960, 0x1400020e6c0})
	/Users/zmb/go/pkg/mod/github.com/aws/aws-sdk-go-v2@v1.16.16/aws/retry/middleware.go:90 +0x1e4
github.com/aws/smithy-go/middleware.decoratedFinalizeHandler.HandleFinalize(...)
	/Users/zmb/go/pkg/mod/github.com/aws/smithy-go@v1.13.3/middleware/step_finalize.go:200
github.com/aws/smithy-go/middleware.(*FinalizeStep).HandleMiddleware(0x0?, {0x10172cd08, 0x140006a2ae0}, {0x1016ecc20, 0x14000447b60}, {0x10171b980, 0x1400020e560})
	/Users/zmb/go/pkg/mod/github.com/aws/smithy-go@v1.13.3/middleware/step_finalize.go:114 +0x1c8
github.com/aws/smithy-go/middleware.decoratedHandler.Handle(...)
	/Users/zmb/go/pkg/mod/github.com/aws/smithy-go@v1.13.3/middleware/middleware.go:57
github.com/aws/smithy-go/middleware.buildWrapHandler.HandleBuild(...)
	/Users/zmb/go/pkg/mod/github.com/aws/smithy-go@v1.13.3/middleware/step_build.go:184
github.com/aws/aws-sdk-go-v2/aws/middleware.(*requestUserAgent).HandleBuild(0x14000969328?, {0x10172cd08, 0x140006a2ae0}, {{0x1016ecc20?, 0x14000447b60?}}, {0x10171b900, 0x1400052f8a0})
	/Users/zmb/go/pkg/mod/github.com/aws/aws-sdk-go-v2@v1.16.16/aws/middleware/user_agent.go:219 +0x224
github.com/aws/smithy-go/middleware.decoratedBuildHandler.HandleBuild(...)
	/Users/zmb/go/pkg/mod/github.com/aws/smithy-go@v1.13.3/middleware/step_build.go:200
github.com/aws/smithy-go/middleware.(*BuildStep).HandleMiddleware(0x140003a7e3f?, {0x10172cd08, 0x140006a2ae0}, {0x1016ecc20, 0x14000447b60}, {0x10171b980, 0x1400020e580})
	/Users/zmb/go/pkg/mod/github.com/aws/smithy-go@v1.13.3/middleware/step_build.go:114 +0x1c8
github.com/aws/smithy-go/middleware.decoratedHandler.Handle(...)
	/Users/zmb/go/pkg/mod/github.com/aws/smithy-go@v1.13.3/middleware/middleware.go:57
github.com/aws/smithy-go/middleware.serializeWrapHandler.HandleSerialize(...)
	/Users/zmb/go/pkg/mod/github.com/aws/smithy-go@v1.13.3/middleware/step_serialize.go:192
github.com/aws/aws-sdk-go-v2/feature/ec2/imds.(*serializeRequest).HandleSerialize(0x1400000f3b0, {0x10172cd08, 0x140006a2ae0}, {{0x1014b2c60?, 0x1400052f7b0?}, {0x1016ecc20?, 0x14000447b60?}}, {0x10171ba40, 0x1400052f880})
	/Users/zmb/go/pkg/mod/github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.12.17/request_middleware.go:123 +0x170
github.com/aws/smithy-go/middleware.decoratedSerializeHandler.HandleSerialize(...)
	/Users/zmb/go/pkg/mod/github.com/aws/smithy-go@v1.13.3/middleware/step_serialize.go:208
github.com/aws/aws-sdk-go-v2/feature/ec2/imds.(*resolveEndpoint).HandleSerialize(0x1?, {0x10172cd08, 0x140006a2ae0}, {{0x1014b2c60?, 0x1400052f7b0?}, {0x1016ecc20?, 0x14000447b60?}}, {0x10171b9c0, 0x1400020e640})
	/Users/zmb/go/pkg/mod/github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.12.17/request_middleware.go:219 +0x184
github.com/aws/smithy-go/middleware.decoratedSerializeHandler.HandleSerialize(...)
	/Users/zmb/go/pkg/mod/github.com/aws/smithy-go@v1.13.3/middleware/step_serialize.go:208
github.com/aws/smithy-go/middleware.(*SerializeStep).HandleMiddleware(0x1400052f7e0, {0x10172cd08, 0x140006a2ae0}, {0x1014b2c60, 0x1400052f7b0}, {0x10171b980, 0x1400020e5a0})
	/Users/zmb/go/pkg/mod/github.com/aws/smithy-go@v1.13.3/middleware/step_serialize.go:122 +0x1f0
github.com/aws/smithy-go/middleware.decoratedHandler.Handle(...)
	/Users/zmb/go/pkg/mod/github.com/aws/smithy-go@v1.13.3/middleware/middleware.go:57
github.com/aws/smithy-go/middleware.initializeWrapHandler.HandleInitialize(...)
	/Users/zmb/go/pkg/mod/github.com/aws/smithy-go@v1.13.3/middleware/step_initialize.go:184
github.com/aws/aws-sdk-go-v2/feature/ec2/imds.(*operationTimeout).HandleInitialize(0x1400038aa70, {0x10172ccd0, 0x140000460c8}, {{0x1014b2c60?, 0x1400052f7b0?}}, {0x10171ba20, 0x1400052f850})
	/Users/zmb/go/pkg/mod/github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.12.17/request_middleware.go:254 +0xb8
github.com/aws/smithy-go/middleware.decoratedInitializeHandler.HandleInitialize(...)
	/Users/zmb/go/pkg/mod/github.com/aws/smithy-go@v1.13.3/middleware/step_initialize.go:200
github.com/aws/smithy-go/middleware.(*InitializeStep).HandleMiddleware(0x14000969978?, {0x10172ccd0, 0x140000460c8}, {0x1014b2c60, 0x1400052f7b0}, {0x10171b980, 0x1400020e5c0})
	/Users/zmb/go/pkg/mod/github.com/aws/smithy-go@v1.13.3/middleware/step_initialize.go:114 +0x1c8
github.com/aws/smithy-go/middleware.decoratedHandler.Handle(...)
	/Users/zmb/go/pkg/mod/github.com/aws/smithy-go@v1.13.3/middleware/middleware.go:57
github.com/aws/smithy-go/middleware.(*Stack).HandleMiddleware(0x14000969a78?, {0x10172ccd0, 0x140000460c8}, {0x1014b2c60, 0x1400052f7b0}, {0x10171ba60?, 0x1400052f830?})
	/Users/zmb/go/pkg/mod/github.com/aws/smithy-go@v1.13.3/middleware/stack.go:109 +0x12c
github.com/aws/smithy-go/middleware.decoratedHandler.Handle(...)
	/Users/zmb/go/pkg/mod/github.com/aws/smithy-go@v1.13.3/middleware/middleware.go:57
github.com/aws/aws-sdk-go-v2/feature/ec2/imds.(*Client).invokeOperation(0x14000593800, {0x10172ccd0, 0x140000460c8}, {0x1010f50c8, 0xb}, {0x1014b2c60, 0x1400052f7b0}, {0x0, 0x0, 0x0?}, ...)
	/Users/zmb/go/pkg/mod/github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.12.17/api_client.go:240 +0x460
github.com/aws/aws-sdk-go-v2/feature/ec2/imds.(*Client).GetMetadata(0x0?, {0x10172ccd0?, 0x140000460c8?}, 0x0?, {0x0?, 0x0?, 0x0?})
	/Users/zmb/go/pkg/mod/github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.12.17/api_op_GetMetadata.go:22 +0xb4
github.com/gravitational/teleport/lib/cloud/aws.(*InstanceMetadataClient).getMetadata(0x1400011e688, {0x10172ccd0, 0x140000460c8}, {0x1010f588f, 0xb})
	/Users/zmb/teleport/lib/cloud/aws/imds.go:85 +0xa4
github.com/gravitational/teleport/lib/cloud/aws.(*InstanceMetadataClient).IsAvailable(0x140003971e0?, {0x10172ccd0?, 0x140000460c8?})
	/Users/zmb/teleport/lib/cloud/aws/imds.go:79 +0x30
github.com/gravitational/teleport/lib/cloud/aws.TestEC2IsInstanceMetadataAvailable.func3(0x140003971e0)
	/Users/zmb/teleport/lib/cloud/aws/imds_test.go:112 +0xe0
```

**Comment by zmb3** [comment]
No recent occurrences - closing.
