### ISSUE TITLE
Kubernetes exec fails when called with Python client

### ISSUE THREAD

**Issue by tigrato** [gravitational/teleport#15463]
Exec into a pod using python kubernetes client fails.

```
% python3 pod_exec.py
Traceback (most recent call last):
  File "/Users/arunnadda/lab_learning/python_library_k8s/python/kubernetes/stream/ws_client.py", line 519, in websocket_call
    client = WSClient(configuration, url, headers, capture_all)
  File "/Users/arunnadda/lab_learning/python_library_k8s/python/kubernetes/stream/ws_client.py", line 65, in __init__
    self.sock = create_websocket(configuration, url, headers)
  File "/Users/arunnadda/lab_learning/python_library_k8s/python/kubernetes/stream/ws_client.py", line 485, in create_websocket
    websocket.connect(url, **connect_opt)
  File "/opt/homebrew/lib/python3.9/site-packages/websocket_client-1.3.3-py3.9.egg/websocket/_core.py", line 248, in connect
    self.handshake_response = handshake(self.sock, url, *addrs, **options)
  File "/opt/homebrew/lib/python3.9/site-packages/websocket_client-1.3.3-py3.9.egg/websocket/_handshake.py", line 57, in handshake
    status, resp = _get_resp_headers(sock)
  File "/opt/homebrew/lib/python3.9/site-packages/websocket_client-1.3.3-py3.9.egg/websocket/_handshake.py", line 148, in _get_resp_headers
    raise WebSocketBadStatusException("Handshake status %d %s", status, status_message, resp_headers)
websocket._exceptions.WebSocketBadStatusException: Handshake status 500 Internal Server Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/arunnadda/lab_learning/python_library_k8s/python/pod_exec.py", line 132, in <module>
    main()
  File "/Users/arunnadda/lab_learning/python_library_k8s/python/pod_exec.py", line 128, in main
    exec_commands(core_v1)
  File "/Users/arunnadda/lab_learning/python_library_k8s/python/pod_exec.py", line 74, in exec_commands
    resp = stream(api_instance.connect_get_namespaced_pod_exec,
  File "/Users/arunnadda/lab_learning/python_library_k8s/python/kubernetes/stream/stream.py", line 35, in _websocket_request
    return api_method(*args, **kwargs)
  File "/Users/arunnadda/lab_learning/python_library_k8s/python/kubernetes/client/api/core_v1_api.py", line 994, in connect_get_namespaced_pod_exec
    return self.connect_get_namespaced_pod_exec_with_http_info(name, namespace, **kwargs)  # noqa: E501
  File "/Users/arunnadda/lab_learning/python_library_k8s/python/kubernetes/client/api/core_v1_api.py", line 1101, in connect_get_namespaced_pod_exec_with_http_info
    return self.api_client.call_api(
  File "/Users/arunnadda/lab_learning/python_library_k8s/python/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
  File "/Users/arunnadda/lab_learning/python_library_k8s/python/kubernetes/client/api_client.py", line 180, in __call_api
    response_data = self.request(
  File "/Users/arunnadda/lab_learning/python_library_k8s/python/kubernetes/stream/ws_client.py", line 525, in websocket_call
    raise ApiException(status=0, reason=str(e))
kubernetes.client.exceptions.ApiException: (0)
Reason: Handshake status 500 Internal Server Error
```

This happens because Teleport expects a SPDY client while Python kubernetes client uses Websockets.

- Recreation steps
run [pod_exec.py](https://github.com/kubernetes-client/python/blob/master/examples/pod_exec.py)

**Comment by alex-astronomer** [comment]
Have the same problem which is blocking development.  Keeping an eye on the PR linked!
