### ISSUE TITLE
Web UI login causes panic

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#1558]
This is occurring on master (2.5.0) whenever you login to the Web UI.

```
2018/01/08 15:21:29 http: panic serving [::1]:60947: interface conversion: auth.ClientI is *auth.Client, not *auth.TunClient
goroutine 121 [running]:
net/http.(*conn).serve.func1(0xc420320140)
	/usr/local/Cellar/go/1.9/libexec/src/net/http/server.go:1697 +0xd0
panic(0x4c68b60, 0xc42005cfc0)
	/usr/local/Cellar/go/1.9/libexec/src/runtime/panic.go:491 +0x283
github.com/gravitational/teleport/e/lib/web.(*Plugin).getLicenseCheckStatusHandle(0xc4203063c0, 0x553b720, 0xc4204722a0, 0xc420294500, 0x0, 0x0, 0x0, 0x4df4dee, 0x7, 0x4df180f, ...)
	/Users/rjones/Development/go/src/github.com/gravitational/teleport/e/lib/web/handler.go:120 +0x2a8
github.com/gravitational/teleport/e/lib/web.(*Plugin).(github.com/gravitational/teleport/e/lib/web.getLicenseCheckStatusHandle)-fm(0x553b720, 0xc4204722a0, 0xc420294500, 0x0, 0x0, 0x0, 0xc42043f820, 0x0, 0x0, 0xc4203f6340)
	/Users/rjones/Development/go/src/github.com/gravitational/teleport/e/lib/web/handler.go:39 +0x73
github.com/gravitational/teleport/lib/httplib.MakeHandler.func1(0x553b720, 0xc4204722a0, 0xc420294500, 0x0, 0x0, 0x0)
	/Users/rjones/Development/go/src/github.com/gravitational/teleport/lib/httplib/httplib.go:50 +0x9a
github.com/gravitational/teleport/vendor/github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc4205d8fc8, 0x553b720, 0xc4204722a0, 0xc420294500)
	/Users/rjones/Development/go/src/github.com/gravitational/teleport/vendor/github.com/julienschmidt/httprouter/router.go:299 +0x6f1
net/http.StripPrefix.func1(0x553b720, 0xc4204722a0, 0xc420294000)
	/usr/local/Cellar/go/1.9/libexec/src/net/http/server.go:1957 +0x1a5
net/http.HandlerFunc.ServeHTTP(0xc420528930, 0x553b720, 0xc4204722a0, 0xc420294000)
	/usr/local/Cellar/go/1.9/libexec/src/net/http/server.go:1918 +0x44
github.com/gravitational/teleport/lib/web.NewHandler.func1(0x553b720, 0xc4204722a0, 0xc420294000)
	/Users/rjones/Development/go/src/github.com/gravitational/teleport/lib/web/apiserver.go:251 +0x6be
github.com/gravitational/teleport/vendor/github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc4205d8fc8, 0x553b720, 0xc4204722a0, 0xc420294000)
	/Users/rjones/Development/go/src/github.com/gravitational/teleport/vendor/github.com/julienschmidt/httprouter/router.go:359 +0x2a2
github.com/gravitational/teleport/lib/httplib.RewritePaths.func1(0x553b720, 0xc4204722a0, 0xc420294000)
	/Users/rjones/Development/go/src/github.com/gravitational/teleport/lib/httplib/httplib.go:153 +0x12b
net/http.HandlerFunc.ServeHTTP(0xc42054bb00, 0x553b720, 0xc4204722a0, 0xc420294000)
	/usr/local/Cellar/go/1.9/libexec/src/net/http/server.go:1918 +0x44
github.com/gravitational/teleport/lib/web.(*RewritingHandler).ServeHTTP(0xc4203ae7a0, 0x553b720, 0xc4204722a0, 0xc420294000)
	<autogenerated>:1 +0x5a
github.com/gravitational/teleport/vendor/github.com/vulcand/oxy/ratelimit.(*TokenLimiter).ServeHTTP(0xc4200f5280, 0x553b720, 0xc4204722a0, 0xc420294000)
	/Users/rjones/Development/go/src/github.com/gravitational/teleport/vendor/github.com/vulcand/oxy/ratelimit/tokenlimiter.go:118 +0x27f
github.com/gravitational/teleport/vendor/github.com/vulcand/oxy/connlimit.(*ConnLimiter).ServeHTTP(0xc42031c5a0, 0x553b720, 0xc4204722a0, 0xc420294000)
	/Users/rjones/Development/go/src/github.com/gravitational/teleport/vendor/github.com/vulcand/oxy/connlimit/connlimit.go:71 +0x420
net/http.serverHandler.ServeHTTP(0xc4203800d0, 0x553b720, 0xc4204722a0, 0xc420294000)
	/usr/local/Cellar/go/1.9/libexec/src/net/http/server.go:2619 +0xb4
net/http.(*conn).serve(0xc420320140, 0x553cda0, 0xc420300640)
	/usr/local/Cellar/go/1.9/libexec/src/net/http/server.go:1801 +0x71d
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.9/libexec/src/net/http/server.go:2720 +0x288
2018/01/08 15:21:29 http: panic serving [::1]:60942: interface conversion: auth.ClientI is *auth.Client, not *auth.TunClient
goroutine 117 [running]:
net/http.(*conn).serve.func1(0xc420084a00)
	/usr/local/Cellar/go/1.9/libexec/src/net/http/server.go:1697 +0xd0
panic(0x4c68b60, 0xc42005d080)
	/usr/local/Cellar/go/1.9/libexec/src/runtime/panic.go:491 +0x283
github.com/gravitational/teleport/e/lib/web.(*Plugin).getLicenseCheckStatusHandle(0xc4203063c0, 0x553b720, 0xc420472460, 0xc420294900, 0x0, 0x0, 0x0, 0x4df4dee, 0x7, 0x4df180f, ...)
	/Users/rjones/Development/go/src/github.com/gravitational/teleport/e/lib/web/handler.go:120 +0x2a8
github.com/gravitational/teleport/e/lib/web.(*Plugin).(github.com/gravitational/teleport/e/lib/web.getLicenseCheckStatusHandle)-fm(0x553b720, 0xc420472460, 0xc420294900, 0x0, 0x0, 0x0, 0xc420022000, 0x0, 0x0, 0xc4203f6340)
	/Users/rjones/Development/go/src/github.com/gravitational/teleport/e/lib/web/handler.go:39 +0x73
github.com/gravitational/teleport/lib/httplib.MakeHandler.func1(0x553b720, 0xc420472460, 0xc420294900, 0x0, 0x0, 0x0)
	/Users/rjones/Development/go/src/github.com/gravitational/teleport/lib/httplib/httplib.go:50 +0x9a
github.com/gravitational/teleport/vendor/github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc4205d8fc8, 0x553b720, 0xc420472460, 0xc420294900)
	/Users/rjones/Development/go/src/github.com/gravitational/teleport/vendor/github.com/julienschmidt/httprouter/router.go:299 +0x6f1
net/http.StripPrefix.func1(0x553b720, 0xc420472460, 0xc4205aa700)
	/usr/local/Cellar/go/1.9/libexec/src/net/http/server.go:1957 +0x1a5
net/http.HandlerFunc.ServeHTTP(0xc4205289c0, 0x553b720, 0xc420472460, 0xc4205aa700)
	/usr/local/Cellar/go/1.9/libexec/src/net/http/server.go:1918 +0x44
github.com/gravitational/teleport/lib/web.NewHandler.func1(0x553b720, 0xc420472460, 0xc4205aa700)
	/Users/rjones/Development/go/src/github.com/gravitational/teleport/lib/web/apiserver.go:251 +0x6be
github.com/gravitational/teleport/vendor/github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc4205d8fc8, 0x553b720, 0xc420472460, 0xc4205aa700)
	/Users/rjones/Development/go/src/github.com/gravitational/teleport/vendor/github.com/julienschmidt/httprouter/router.go:359 +0x2a2
github.com/gravitational/teleport/lib/httplib.RewritePaths.func1(0x553b720, 0xc420472460, 0xc4205aa700)
	/Users/rjones/Development/go/src/github.com/gravitational/teleport/lib/httplib/httplib.go:153 +0x12b
net/http.HandlerFunc.ServeHTTP(0xc42054bb00, 0x553b720, 0xc420472460, 0xc4205aa700)
	/usr/local/Cellar/go/1.9/libexec/src/net/http/server.go:1918 +0x44
github.com/gravitational/teleport/lib/web.(*RewritingHandler).ServeHTTP(0xc4203ae7a0, 0x553b720, 0xc420472460, 0xc4205aa700)
	<autogenerated>:1 +0x5a
github.com/gravitational/teleport/vendor/github.com/vulcand/oxy/ratelimit.(*TokenLimiter).ServeHTTP(0xc4200f5280, 0x553b720, 0xc420472460, 0xc4205aa700)
	/Users/rjones/Development/go/src/github.com/gravitational/teleport/vendor/github.com/vulcand/oxy/ratelimit/tokenlimiter.go:118 +0x27f
github.com/gravitational/teleport/vendor/github.com/vulcand/oxy/connlimit.(*ConnLimiter).ServeHTTP(0xc42031c5a0, 0x553b720, 0xc420472460, 0xc4205aa700)
	/Users/rjones/Development/go/src/github.com/gravitational/teleport/vendor/github.com/vulcand/oxy/connlimit/connlimit.go:71 +0x420
net/http.serverHandler.ServeHTTP(0xc4203800d0, 0x553b720, 0xc420472460, 0xc4205aa700)
	/usr/local/Cellar/go/1.9/libexec/src/net/http/server.go:2619 +0xb4
net/http.(*conn).serve(0xc420084a00, 0x553cda0, 0xc420346300)
	/usr/local/Cellar/go/1.9/libexec/src/net/http/server.go:1801 +0x71d
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.9/libexec/src/net/http/server.go:2720 +0x288
2018/01/08 15:21:29 http: panic serving [::1]:60949: interface conversion: auth.ClientI is *auth.Client, not *auth.TunClient
goroutine 125 [running]:
net/http.(*conn).serve.func1(0xc42022b0e0)
	/usr/local/Cellar/go/1.9/libexec/src/net/http/server.go:1697 +0xd0
panic(0x4c68b60, 0xc42005d340)
	/usr/local/Cellar/go/1.9/libexec/src/runtime/panic.go:491 +0x283
github.com/gravitational/teleport/e/lib/web.(*Plugin).getLicenseCheckStatusHandle(0xc4203063c0, 0x553b720, 0xc420472540, 0xc420294a00, 0x0, 0x0, 0x0, 0x4df4dee, 0x7, 0x4df180f, ...)
	/Users/rjones/Development/go/src/github.com/gravitational/teleport/e/lib/web/handler.go:120 +0x2a8
github.com/gravitational/teleport/e/lib/web.(*Plugin).(github.com/gravitational/teleport/e/lib/web.getLicenseCheckStatusHandle)-fm(0x553b720, 0xc420472540, 0xc420294a00, 0x0, 0x0, 0x0, 0xc42077b7d0, 0x0, 0x0, 0xc4203f6340)
	/Users/rjones/Development/go/src/github.com/gravitational/teleport/e/lib/web/handler.go:39 +0x73
github.com/gravitational/teleport/lib/httplib.MakeHandler.func1(0x553b720, 0xc420472540, 0xc420294a00, 0x0, 0x0, 0x0)
	/Users/rjones/Development/go/src/github.com/gravitational/teleport/lib/httplib/httplib.go:50 +0x9a
github.com/gravitational/teleport/vendor/github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc4205d8fc8, 0x553b720, 0xc420472540, 0xc420294a00)
	/Users/rjones/Development/go/src/github.com/gravitational/teleport/vendor/github.com/julienschmidt/httprouter/router.go:299 +0x6f1
net/http.StripPrefix.func1(0x553b720, 0xc420472540, 0xc420666600)
	/usr/local/Cellar/go/1.9/libexec/src/net/http/server.go:1957 +0x1a5
net/http.HandlerFunc.ServeHTTP(0xc420528ae0, 0x553b720, 0xc420472540, 0xc420666600)
	/usr/local/Cellar/go/1.9/libexec/src/net/http/server.go:1918 +0x44
github.com/gravitational/teleport/lib/web.NewHandler.func1(0x553b720, 0xc420472540, 0xc420666600)
	/Users/rjones/Development/go/src/github.com/gravitational/teleport/lib/web/apiserver.go:251 +0x6be
github.com/gravitational/teleport/vendor/github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc4205d8fc8, 0x553b720, 0xc420472540, 0xc420666600)
	/Users/rjones/Development/go/src/github.com/gravitational/teleport/vendor/github.com/julienschmidt/httprouter/router.go:359 +0x2a2
github.com/gravitational/teleport/lib/httplib.RewritePaths.func1(0x553b720, 0xc420472540, 0xc420666600)
	/Users/rjones/Development/go/src/github.com/gravitational/teleport/lib/httplib/httplib.go:153 +0x12b
net/http.HandlerFunc.ServeHTTP(0xc42054bb00, 0x553b720, 0xc420472540, 0xc420666600)
	/usr/local/Cellar/go/1.9/libexec/src/net/http/server.go:1918 +0x44
github.com/gravitational/teleport/lib/web.(*RewritingHandler).ServeHTTP(0xc4203ae7a0, 0x553b720, 0xc420472540, 0xc420666600)
	<autogenerated>:1 +0x5a
github.com/gravitational/teleport/vendor/github.com/vulcand/oxy/ratelimit.(*TokenLimiter).ServeHTTP(0xc4200f5280, 0x553b720, 0xc420472540, 0xc420666600)
	/Users/rjones/Development/go/src/github.com/gravitational/teleport/vendor/github.com/vulcand/oxy/ratelimit/tokenlimiter.go:118 +0x27f
github.com/gravitational/teleport/vendor/github.com/vulcand/oxy/connlimit.(*ConnLimiter).ServeHTTP(0xc42031c5a0, 0x553b720, 0xc420472540, 0xc420666600)
	/Users/rjones/Development/go/src/github.com/gravitational/teleport/vendor/github.com/vulcand/oxy/connlimit/connlimit.go:71 +0x420
net/http.serverHandler.ServeHTTP(0xc4203800d0, 0x553b720, 0xc420472540, 0xc420666600)
	/usr/local/Cellar/go/1.9/libexec/src/net/http/server.go:2619 +0xb4
net/http.(*conn).serve(0xc42022b0e0, 0x553cda0, 0xc4203478c0)
	/usr/local/Cellar/go/1.9/libexec/src/net/http/server.go:1801 +0x71d
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.9/libexec/src/net/http/server.go:2720 +0x288
```

**Comment by klizhentas** [comment]
fixed via #1565
