### ISSUE TITLE
panic in integration tests

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#1577]
Teleport 2.4.
Linux

make integration

```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x46454f]

goroutine 21452 [running]:
io.copyBuffer(0x7fe19cb6eac0, 0xc420cf43c0, 0x0, 0x0, 0xc420e0c000, 0x8000, 0x8000, 0x11fb9e0, 0xc4203d9f00, 0x7fe19cb6eac0)
	/opt/go/src/io/io.go:390 +0xdf
io.Copy(0x7fe19cb6eac0, 0xc420cf43c0, 0x0, 0x0, 0x0, 0x180001, 0x0)
	/opt/go/src/io/io.go:360 +0x68
github.com/gravitational/teleport/lib/reversetunnel.(*Agent).proxyTransport.func2(0xc4201acd10, 0x1b2b5e0, 0xc420cf43c0, 0x0, 0x0)
	/home/sasha/go/src/github.com/gravitational/teleport/lib/reversetunnel/agent.go:439 +0xd3
created by github.com/gravitational/teleport/lib/reversetunnel.(*Agent).proxyTransport
	/home/sasha/go/src/github.com/gravitational/teleport/lib/reversetunnel/agent.go:440 +0x908
exit status 2
FAIL	github.com/gravitational/teleport/integration	37.471s
Makefile:128: recipe for target 'integration' failed
make: *** [integration] Error 1

```

**Comment by russjones** [comment]
I suspect that #1612 will fix this problem, but if not we have logging now that will help narrow down the problem.

I'm going to move this out of the [2.4.1 milestone](https://github.com/gravitational/teleport/milestone/18) and into the [2.5.0 milestone](https://github.com/gravitational/teleport/milestone/20) so we have some time to monitor if it occurs again.

**Comment by klizhentas** [comment]
ok, I don't see this problem any more, so going to close it, will reopen if it happens again.
