### ISSUE TITLE
`TestPingConnection` panic

### ISSUE THREAD

**Issue by zmb3** [gravitational/teleport#15867]
#### Link(s) to logs

- https://console.cloud.google.com/cloud-build/builds/800e3022-7448-4998-a9c9-ab56333703ed;step=0?project=ci-account

#### Relevant snippet

```
=== RUN   TestPingConnection/ConcurrentReads
time="2022-08-26T17:12:35Z" level=info msg="Generating TLS certificate {0x794f568 0xc001074660 CN=test-user,POSTALCODE=null,STREET= 2022-08-26 17:13:35.918079471 +0000 UTC [localhost *.localhost] [] 5 []}." common_name=test-user dns_names="[localhost *.localhost]" locality="[]" not_after="2022-08-26 17:13:35.918079471 +0000 UTC" org="[]" org_unit="[]" trace.component=ca
    --- FAIL: TestPingConnection/ConcurrentReads (5.00s)
panic: interface conversion: interface {} is []uint8, not string [recovered]
	panic: interface conversion: interface {} is []uint8, not string

goroutine 311 [running]:
testing.tRunner.func1.2({0x41df200, 0xc000b04180})
	/opt/go/src/testing/testing.go:1389 +0x366
testing.tRunner.func1()
	/opt/go/src/testing/testing.go:1392 +0x5d2
panic({0x41df200, 0xc000b04180})
	/opt/go/src/runtime/panic.go:844 +0x258
github.com/stretchr/testify/assert.messageFromMsgAndArgs({0xc000adbe78, 0x2, 0x2})
	/go/pkg/mod/github.com/stretchr/testify@v1.7.1/assert/assertions.go:191 +0x1aa
github.com/stretchr/testify/assert.Fail({0x7fcf3a728ab8, 0xc000e88680}, {0x45f7b53, 0x37}, {0xc000adbe78, 0x2, 0x2})
	/go/pkg/mod/github.com/stretchr/testify@v1.7.1/assert/assertions.go:257 +0x271
github.com/stretchr/testify/require.Fail({0x5694ea0, 0xc000e88680}, {0x45f7b53, 0x37}, {0xc000adbe78, 0x2, 0x2})
	/go/pkg/mod/github.com/stretchr/testify@v1.7.1/require/require.go:412 +0xa5
github.com/gravitational/teleport/lib/srv/alpnproxy.TestPingConnection.func2(0x0?)
	/workspace/lib/srv/alpnproxy/conn_test.go:163 +0x734
testing.tRunner(0xc000e88680, 0x46ae430)
	/opt/go/src/testing/testing.go:1439 +0x214
created by testing.(*T).Run
	/opt/go/src/testing/testing.go:1486 +0x725
===================================================
Makefile:520: recipe for target 'test-go' failed
make: *** [test-go] Error 1
```

**Comment by zmb3** [comment]
@gabrielcorado looks like this was just introduced in #14887
