### ISSUE TITLE
`TestPingConnection` flakiness

### ISSUE THREAD

**Issue by espadolini** [gravitational/teleport#15896]
#### Link(s) to logs

- https://console.cloud.google.com/cloud-build/builds/48a321d0-cd7c-47e1-a250-fc8a8347dc0e?project=ci-account

#### Relevant snippet

```
=== RUN   TestPingConnection/ConcurrentReads
time="2022-08-29T10:09:14Z" level=info msg="Generating TLS certificate {0x7950668 0xc0005a87e0 CN=test-user,POSTALCODE=null,STREET= 2022-08-29 10:10:14.395311361 +0000 UTC [localhost *.localhost] [] 5 []}." common_name=test-user dns_names="[localhost *.localhost]" locality="[]" not_after="2022-08-29 10:10:14.395311361 +0000 UTC" org="[]" org_unit="[]" trace.component=ca
    conn_test.go:177: 
        	Error Trace:	conn_test.go:177
        	Error:      	"messagme" should have 7 item(s), but has 8
        	Test:       	TestPingConnection/ConcurrentReads
        	Messages:   	Wrong message read from connection
=== RUN   TestPingConnection/ConcurrentWrites
panic: Fail in goroutine after TestPingConnection/ConcurrentReads has completed

goroutine 402 [running]:
testing.(*common).Fail(0xc000c40680)
	/opt/go/src/testing/testing.go:817 +0x19b
testing.(*common).Errorf(0xc000c40680, {0x4545f4a, 0x3}, {0xc00022a520, 0x1, 0x1})
	/opt/go/src/testing/testing.go:934 +0xa7
github.com/stretchr/testify/assert.Fail({0x7fae8b04cef0, 0xc000c40680}, {0x45a87ed, 0x22}, {0xc000b41fa8, 0x1, 0x1})
	/go/pkg/mod/github.com/stretchr/testify@v1.7.1/assert/assertions.go:262 +0x429
github.com/stretchr/testify/require.Fail({0x5695a60, 0xc000c40680}, {0x45a87ed, 0x22}, {0xc000b41fa8, 0x1, 0x1})
	/go/pkg/mod/github.com/stretchr/testify@v1.7.1/require/require.go:412 +0xa5
github.com/gravitational/teleport/lib/srv/alpnproxy.TestPingConnection.func2.2()
	/workspace/lib/srv/alpnproxy/conn_test.go:156 +0x1f2
created by github.com/gravitational/teleport/lib/srv/alpnproxy.TestPingConnection.func2
	/workspace/lib/srv/alpnproxy/conn_test.go:151 +0x346
FAIL	github.com/gravitational/teleport/lib/srv/alpnproxy	13.412s
===================================================
```

**Comment by nklaassen** [comment]
another hit https://console.cloud.google.com/cloud-build/builds/41dd36bd-8004-487b-8542-013e87b6e3a9?project=ci-account

**Comment by zmb3** [comment]
See also https://github.com/gravitational/teleport/issues/15867 which appears to have been fixed.

**Comment by smallinsky** [comment]
Should be fixed by https://github.com/gravitational/teleport/pull/15969
