### ISSUE TITLE
`TestRootScript` flakiness

### ISSUE THREAD

**Issue by nklaassen** [gravitational/teleport#16908]
#### Link(s) to logs

- https://console.cloud.google.com/cloud-build/builds/5dd6c892-d79f-4d5f-ba78-ae7f471bb75b?project=ci-account

#### Relevant snippet

```
PASS
panic: Log in goroutine after TestRootScript has completed: Failed to run script: <nil>.

goroutine 246 [running]:
testing.(*common).logDepth(0xc0002a7520, {0xc000844560, 0x1c}, 0x3)
	/opt/go/src/testing/testing.go:894 +0x6d9
testing.(*common).log(...)
	/opt/go/src/testing/testing.go:876
testing.(*common).Logf(0xc0002a7520, {0x43a80a2, 0x19}, {0xc000e86fa0, 0x1, 0x1})
	/opt/go/src/testing/testing.go:927 +0xa5
github.com/gravitational/teleport/lib/bpf.TestRootScript.func1()
	/workspace/lib/bpf/bpf_test.go:246 +0x1da
created by github.com/gravitational/teleport/lib/bpf.TestRootScript
	/workspace/lib/bpf/bpf_test.go:237 +0x2f6
FAIL	github.com/gravitational/teleport/lib/bpf	6.409s
```

**Comment by zmb3** [comment]
I'm not sure what the actual failure is about, but the panic above is due to calling `require.NoError` in a background goroutine, which is not allowed.

**Comment by zmb3** [comment]
There's also a data race due to overwriting `err` from inside a goroutine, and a goroutine that runs an infinite loop that never terminates.

**Comment by nklaassen** [comment]
Got a new failure here, it seems we are failing the test outside of the main goroutine again https://github.com/gravitational/teleport/actions/runs/4493152265/jobs/7903987200?pr=23416

**Comment by zmb3** [comment]
Likely still flaky, but disabled in #23428

**Comment by capnspacehook** [comment]
The issue in the test has been addressed and still doesn't run in CI so I think this can be closed.
