### ISSUE TITLE
tsh login panics on 7.3.25

### ISSUE THREAD

**Issue by brackendawson** [gravitational/teleport#17577]
Expected behavior: tsh login logs in

Current behavior: tsh login panics

Bug details:
- Teleport version 7.3.25
- Recreation steps `tsh login --proxy your_proxy --request-reason your_ticket --kube-cluster your_cluster your_cluster`
- Debug logs
```
If browser window does not open automatically, open it by clicking on the link:
 http://127.0.0.1:63133/e15b04ef-c04a-4e8c-b7f4-2ff3de47bbd4
unexpected fault address 0x360808085a175a75
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x360808085a175a75 pc=0x4069fff]

goroutine 1 [running]:
runtime.throw({0x55fbb87?, 0x30?})
	/usr/local/go/src/runtime/panic.go:992 +0x71 fp=0xc0003cb7c8 sp=0xc0003cb798 pc=0x4039611
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:825 +0x305 fp=0xc0003cb818 sp=0xc0003cb7c8 pc=0x404fae5
aeshashbody()
	/usr/local/go/src/runtime/asm_amd64.s:1343 +0x39f fp=0xc0003cb820 sp=0xc0003cb818 pc=0x4069fff
runtime.mapiternext(0xc0002942c0)
	/usr/local/go/src/runtime/map.go:934 +0x2cb fp=0xc0003cb890 sp=0xc0003cb820 pc=0x401402b
runtime.mapiterinit(0x1?, 0x7?, 0x1?)
	/usr/local/go/src/runtime/map.go:861 +0x228 fp=0xc0003cb8b0 sp=0xc0003cb890 pc=0x4013d08
reflect.mapiterinit(0x4018a86?, 0x30106800?, 0x40e6d27?)
	/usr/local/go/src/runtime/map.go:1373 +0x19 fp=0xc0003cb8d8 sp=0xc0003cb8b0 pc=0x4066279
github.com/modern-go/reflect2.(*UnsafeMapType).UnsafeIterate(...)
	/tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/vendor/github.com/modern-go/reflect2/unsafe_map.go:112
github.com/json-iterator/go.(*sortKeysMapEncoder).Encode(0xc000599470, 0xc00000f420, 0xc000212cc0)
	/tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/vendor/github.com/json-iterator/go/reflect_map.go:291 +0x225 fp=0xc0003cba48 sp=0xc0003cb8d8 pc=0x476f3e5
github.com/json-iterator/go.(*placeholderEncoder).Encode(0x5407080?, 0x30768801?, 0xc000212cd8?)
	/tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/vendor/github.com/json-iterator/go/reflect.go:332 +0x22 fp=0xc0003cba70 sp=0xc0003cba48 pc=0x4768202
github.com/json-iterator/go.(*structFieldEncoder).Encode(0xc0005997a0, 0x52ee51f?, 0xc000212cc0)
	/tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/vendor/github.com/json-iterator/go/reflect_struct_encoder.go:110 +0x56 fp=0xc0003cbae8 sp=0xc0003cba70 pc=0x477cb36
github.com/json-iterator/go.(*structEncoder).Encode(0xc000599860, 0x20000?, 0xc000212cc0)
	/tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/vendor/github.com/json-iterator/go/reflect_struct_encoder.go:158 +0x765 fp=0xc0003cbbd0 sp=0xc0003cbae8 pc=0x477d545
github.com/json-iterator/go.(*OptionalEncoder).Encode(0xc000212cc0?, 0xc0004ecaf0?, 0xc0003cbc60?)
	/tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/vendor/github.com/json-iterator/go/reflect_optional.go:70 +0xa4 fp=0xc0003cbc20 sp=0xc0003cbbd0 pc=0x4774744
github.com/json-iterator/go.(*placeholderEncoder).Encode(0x5407080?, 0xc000406c01?, 0xc000212cd8?)
	/tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/vendor/github.com/json-iterator/go/reflect.go:332 +0x22 fp=0xc0003cbc48 sp=0xc0003cbc20 pc=0x4768202
github.com/json-iterator/go.(*structFieldEncoder).Encode(0xc000315350, 0x5324adf?, 0xc000212cc0)
	/tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/vendor/github.com/json-iterator/go/reflect_struct_encoder.go:110 +0x56 fp=0xc0003cbcc0 sp=0xc0003cbc48 pc=0x477cb36
github.com/json-iterator/go.(*structEncoder).Encode(0xc000315410, 0xc0004ecd70?, 0xc000212cc0)
	/tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/vendor/github.com/json-iterator/go/reflect_struct_encoder.go:158 +0x765 fp=0xc0003cbda8 sp=0xc0003cbcc0 pc=0x477d545
github.com/json-iterator/go.(*placeholderEncoder).Encode(0x5407080?, 0x477c301?, 0xc000212cd8?)
	/tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/vendor/github.com/json-iterator/go/reflect.go:332 +0x22 fp=0xc0003cbdd0 sp=0xc0003cbda8 pc=0x4768202
github.com/json-iterator/go.(*structFieldEncoder).Encode(0xc000315680, 0x52ee4df?, 0xc000212cc0)
	/tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/vendor/github.com/json-iterator/go/reflect_struct_encoder.go:110 +0x56 fp=0xc0003cbe48 sp=0xc0003cbdd0 pc=0x477cb36
github.com/json-iterator/go.(*structEncoder).Encode(0xc0003156e0, 0x53ab7c0?, 0xc000212cc0)
	/tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/vendor/github.com/json-iterator/go/reflect_struct_encoder.go:158 +0x765 fp=0xc0003cbf30 sp=0xc0003cbe48 pc=0x477d545
github.com/json-iterator/go.(*sliceEncoder).Encode(0xc00000f470, 0xc000160f78, 0xc000212cc0)
	/tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/vendor/github.com/json-iterator/go/reflect_slice.go:38 +0x2bd fp=0xc0003cbfe8 sp=0xc0003cbf30 pc=0x477519d
github.com/json-iterator/go.(*structFieldEncoder).Encode(0xc0004cc5a0, 0x52f55af?, 0xc000212cc0)
	/tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/vendor/github.com/json-iterator/go/reflect_struct_encoder.go:110 +0x56 fp=0xc0003cc060 sp=0xc0003cbfe8 pc=0x477cb36
github.com/json-iterator/go.(*structEncoder).Encode(0xc0004cc870, 0x0?, 0xc000212cc0)
	/tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/vendor/github.com/json-iterator/go/reflect_struct_encoder.go:158 +0x765 fp=0xc0003cc148 sp=0xc0003cc060 pc=0x477d545
github.com/json-iterator/go.(*OptionalEncoder).Encode(0xc000377860?, 0x0?, 0x0?)
	/tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/vendor/github.com/json-iterator/go/reflect_optional.go:70 +0xa4 fp=0xc0003cc198 sp=0xc0003cc148 pc=0x4774744
github.com/json-iterator/go.(*onePtrEncoder).Encode(0xc0003b4160, 0xc000160f20, 0xc0004cd7a0?)
	/tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/vendor/github.com/json-iterator/go/reflect.go:219 +0x82 fp=0xc0003cc1d0 sp=0xc0003cc198 pc=0x47677c2
github.com/json-iterator/go.(*Stream).WriteVal(0xc000212cc0, {0x5489340, 0xc000160f20})
	/tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/vendor/github.com/json-iterator/go/reflect.go:98 +0x158 fp=0xc0003cc240 sp=0xc0003cc1d0 pc=0x4766ad8
github.com/json-iterator/go.(*frozenConfig).Marshal(0xc000377860, {0x5489340, 0xc000160f20})
	/tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/vendor/github.com/json-iterator/go/config.go:299 +0xc9 fp=0xc0003cc2d8 sp=0xc0003cc240 pc=0x475dd89
k8s.io/apimachinery/pkg/runtime/serializer/json.(*Serializer).doEncode(0x52ce001?, {0x5873680?, 0xc000160f20?}, {0x586b100, 0xc0005bef30})
	/tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/vendor/k8s.io/apimachinery/pkg/runtime/serializer/json/json.go:306 +0x6d fp=0xc0003cc370 sp=0xc0003cc2d8 pc=0x4b1bb4d
k8s.io/apimachinery/pkg/runtime/serializer/json.(*Serializer).Encode(0xc0000502d0, {0x5873680, 0xc000160f20}, {0x586b100, 0xc0005bef30})
	/tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/vendor/k8s.io/apimachinery/pkg/runtime/serializer/json/json.go:301 +0xfc fp=0xc0003cc3d0 sp=0xc0003cc370 pc=0x4b1ba7c
k8s.io/apimachinery/pkg/runtime/serializer/versioning.(*codec).doEncode(0xc0002b1c20, {0x5873630?, 0xc000212ba0}, {0x586b100, 0xc0005bef30})
	/tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/vendor/k8s.io/apimachinery/pkg/runtime/serializer/versioning/versioning.go:244 +0x8fa fp=0xc0003cc728 sp=0xc0003cc3d0 pc=0x4b20bda
k8s.io/apimachinery/pkg/runtime/serializer/versioning.(*codec).Encode(0xc0002b1c20, {0x5873630, 0xc000212ba0}, {0x586b100, 0xc0005bef30})
	/tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/vendor/k8s.io/apimachinery/pkg/runtime/serializer/versioning/versioning.go:184 +0x106 fp=0xc0003cc788 sp=0xc0003cc728 pc=0x4b20286
k8s.io/apimachinery/pkg/runtime.Encode({0x3194e630, 0xc0002b1c20}, {0x5873630, 0xc000212ba0})
	/tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/vendor/k8s.io/apimachinery/pkg/runtime/codec.go:50 +0x64 fp=0xc0003cc7c8 sp=0xc0003cc788 pc=0x4aa26a4
k8s.io/client-go/tools/clientcmd.Write(...)
	/tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/vendor/k8s.io/client-go/tools/clientcmd/loader.go:469
k8s.io/client-go/tools/clientcmd.WriteToFile({{0x0, 0x0}, {0x0, 0x0}, {0x0, 0xc0003a1fb0}, 0xc0005be060, 0xc0005be0c0, 0xc0005be0f0, {0xc0003b8c00, ...}, ...}, ...)
	/tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/vendor/k8s.io/client-go/tools/clientcmd/loader.go:422 +0xa8 fp=0xc0003cc840 sp=0xc0003cc7c8 pc=0x509ae68
github.com/gravitational/teleport/lib/kube/kubeconfig.Save({0x0?, 0x415db58?}, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0xc0003a1fb0}, 0xc0005be060, 0xc0005be0c0, ...})
	/tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/lib/kube/kubeconfig/kubeconfig.go:215 +0x58 fp=0xc0003cc8c8 sp=0xc0003cc840 pc=0x51552b8
github.com/gravitational/teleport/lib/kube/kubeconfig.Update({0x0, 0x0}, {{0xc00089e380, 0x1f}, {0xc0001240a0, 0x4d}, 0xc000318c00, 0xc000050eb0})
	/tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/lib/kube/kubeconfig/kubeconfig.go:143 +0x8eb fp=0xc0003ccc20 sp=0xc0003cc8c8 pc=0x51540ab
main.updateKubeConfig(0xc000331880, 0xc0001e78c0, {0x0, 0x0})
	/tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/tool/tsh/kube.go:398 +0x20d fp=0xc0003cccc0 sp=0xc0003ccc20 pc=0x5177bcd
main.onLogin(0xc000331880)
	/tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/tool/tsh/tsh.go:918 +0xf7f fp=0xc0003cd120 sp=0xc0003cccc0 pc=0x518caff
main.Run({0xc0001ae010, 0x8, 0x8}, {0x0, 0x0, 0xc0000021a0?})
	/tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/tool/tsh/tsh.go:617 +0xbd7a fp=0xc0003cdf00 sp=0xc0003cd120 pc=0x518ae3a
main.main()
	/tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/tool/tsh/tsh.go:286 +0x218 fp=0xc0003cdf80 sp=0xc0003cdf00 pc=0x517ef38
runtime.main()
	/usr/local/go/src/runtime/proc.go:250 +0x212 fp=0xc0003cdfe0 sp=0xc0003cdf80 pc=0x403bcf2
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc0003cdfe8 sp=0xc0003cdfe0 pc=0x406cc21

goroutine 20 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x0?)
	/tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/vendor/k8s.io/klog/v2/klog.go:1169 +0x6a
created by k8s.io/klog/v2.init.0
	/tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/vendor/k8s.io/klog/v2/klog.go:417 +0xf6

goroutine 38 [syscall]:
os/signal.signal_recv()
	/usr/local/go/src/runtime/sigqueue.go:148 +0x28
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x19
created by os/signal.Notify.func1.1
	/usr/local/go/src/os/signal/signal.go:151 +0x2a

goroutine 24 [chan receive]:
main.Run.func2()
	/tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/tool/tsh/tsh.go:574 +0xa9
created by main.Run
	/tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/tool/tsh/tsh.go:570 +0xaf45

goroutine 88 [select]:
google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc000294500)
	/tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:69 +0x8f
created by google.golang.org/grpc.newCCBalancerWrapper
	/tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:60 +0x1ca

goroutine 89 [select]:
google.golang.org/grpc.(*addrConn).resetTransport(0xc000156b00)
	/tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/vendor/google.golang.org/grpc/clientconn.go:1126 +0x5f7
created by google.golang.org/grpc.(*addrConn).connect
	/tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/vendor/google.golang.org/grpc/clientconn.go:799 +0x145
```

Rolling back to 7.3.23 resolves the issue for me

**Comment by zmb3** [comment]
This is a bug with Go 1.18 in a transitive dependency.

See: https://github.com/kubernetes/client-go/issues/1048

Looks like the bug is in `github.com/modern-go/reflect2` (a `k8s.io/client-go` dependency). It was fixed in v1.0.2 of reflect2, but we're still on 1.0.1.

@rosstimothy can we update this dependency on v7 during the next round of dependency updates?
