### ISSUE TITLE
CreateSessionTracker: `Invalid memory address or nil pointer dereference`

### ISSUE THREAD

**Issue by GunFood** [gravitational/teleport#18332]
**Expected behavior:**
Teleport Agent doesn't crash

**Current behavior:**
Teleport Agent crash with message "panic: runtime error: invalid memory address or nil pointer dereference
The service does restart and I can create a new connection, but large file transfers are impossible

**Bug details:**
- Teleport version: 11.0.1-1 OS
- Recreation steps: I can't reproduce, it just happens 
- Debug logs:
```
Nov 10 09:56:39 bastion teleport[630155]: 2022-11-10T09:56:39+01:00 [CLIENT]    INFO Connecting to proxy=localhost:443 login="root" using TLS Routing client/api.go:3187
Nov 10 09:56:39 bastion teleport[630155]: 2022-11-10T09:56:39+01:00 [CLIENT]    INFO Successful auth with proxy localhost:443. client/api.go:3192
Nov 10 09:56:39 bastion teleport[630155]: 2022-11-10T09:56:39+01:00 [CLIENT]    INFO Connecting to proxy=localhost:443 login="root" using TLS Routing client/api.go:3187
Nov 10 09:56:39 bastion teleport[630155]: 2022-11-10T09:56:39+01:00 [CLIENT]    INFO Successful auth with proxy localhost:443. client/api.go:3192
Nov 10 09:56:39 bastion teleport[630155]: 2022-11-10T09:56:39+01:00 [CLIENT]    INFO Client=217.5.129.98:55688 connecting to node=wiki.server.local on cluster bastion.server.local client/client.go:1514
**Nov 10 09:56:39 bastion teleport[630155]: panic: runtime error: invalid memory address or nil pointer dereference**
Nov 10 09:56:39 bastion teleport[630155]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x1c0 pc=0xc98d60]
Nov 10 09:56:39 bastion teleport[630155]: goroutine 26403 [running]:
Nov 10 09:56:39 bastion teleport[630155]: github.com/gravitational/teleport/api/types.(*SessionTrackerV1).GetHostPolicySets(0x0?)
Nov 10 09:56:39 bastion teleport[630155]: #011github.com/gravitational/teleport/api@v0.0.0/types/session_tracker.go:337
Nov 10 09:56:39 bastion teleport[630155]: github.com/gravitational/teleport/lib/auth.(*Server).CreateSessionTracker(0xc000ddc480, {0x7301878, 0xc0014ac5d0}, {0x733fb88?, 0x0?})
Nov 10 09:56:39 bastion teleport[630155]: #011github.com/gravitational/teleport/lib/auth/auth.go:3172 +0x4d
Nov 10 09:56:39 bastion teleport[630155]: github.com/gravitational/teleport/lib/auth.(*ServerWithRoles).CreateSessionTracker(0xc00370d730, {0x7301878, 0xc0014ac5d0}, {0x733fb88, 0x0})
Nov 10 09:56:39 bastion teleport[630155]: #011github.com/gravitational/teleport/lib/auth/auth_with_roles.go:271 +0x5c
Nov 10 09:56:39 bastion teleport[630155]: github.com/gravitational/teleport/lib/auth.(*GRPCServer).CreateSessionTracker(0x0?, {0x7301878, 0xc0014ac5d0}, 0xc0014ac090)
Nov 10 09:56:39 bastion teleport[630155]: #011github.com/gravitational/teleport/lib/auth/grpcserver.go:3912 +0x57
Nov 10 09:56:39 bastion teleport[630155]: github.com/gravitational/teleport/api/client/proto._AuthService_CreateSessionTracker_Handler.func1({0x7301878, 0xc0014ac5d0}, {0x5e58e60?, 0xc0014ac090})
Nov 10 09:56:39 bastion teleport[630155]: #011github.com/gravitational/teleport/api@v0.0.0/client/proto/authservice.pb.go:16405 +0x7b
Nov 10 09:56:39 bastion teleport[630155]: github.com/gravitational/teleport/lib/auth.(*Middleware).withAuthenticatedUserUnaryInterceptor(0xc0029c11b8?, {0x7301878?, 0xc0014ac2a0?}, {0x5e58e60, 0xc0014ac090}, 0x5666ce0?, 0xc001c0c198)
Nov 10 09:56:39 bastion teleport[630155]: #011github.com/gravitational/teleport/lib/auth/middleware.go:397 +0x8f
Nov 10 09:56:39 bastion teleport[630155]: github.com/gravitational/teleport/lib/utils.ChainUnaryServerInterceptors.func1.1({0x7301878?, 0xc0014ac2a0?}, {0x5e58e60?, 0xc0014ac090?})
Nov 10 09:56:39 bastion teleport[630155]: #011github.com/gravitational/teleport/lib/utils/grpc.go:104 +0x3a
Nov 10 09:56:39 bastion teleport[630155]: github.com/gravitational/teleport/lib/limiter.(*Limiter).UnaryServerInterceptorWithCustomRate.func1({0x7301878, 0xc0014ac2a0}, {0x5e58e60, 0xc0014ac090}, 0xc005ec7e80, 0xc005ec7ee0)
Nov 10 09:56:39 bastion teleport[630155]: #011github.com/gravitational/teleport/lib/limiter/limiter.go:150 +0x23a
Nov 10 09:56:39 bastion teleport[630155]: github.com/gravitational/teleport/lib/utils.ChainUnaryServerInterceptors.func1.1({0x7301878?, 0xc0014ac2a0?}, {0x5e58e60?, 0xc0014ac090?})
Nov 10 09:56:39 bastion teleport[630155]: #011github.com/gravitational/teleport/lib/utils/grpc.go:104 +0x3a
Nov 10 09:56:39 bastion teleport[630155]: github.com/gravitational/teleport/lib/utils.GRPCServerUnaryErrorInterceptor({0x7301878?, 0xc0014ac2a0?}, {0x5e58e60?, 0xc0014ac090?}, 0x715e34c71a?, 0xa36c320?)
Nov 10 09:56:39 bastion teleport[630155]: #011github.com/gravitational/teleport/lib/utils/grpc.go:64 +0x30
Nov 10 09:56:39 bastion teleport[630155]: github.com/gravitational/teleport/lib/utils.ChainUnaryServerInterceptors.func1.1({0x7301878?, 0xc0014ac2a0?}, {0x5e58e60?, 0xc0014ac090?})
Nov 10 09:56:39 bastion teleport[630155]: #011github.com/gravitational/teleport/lib/utils/grpc.go:104 +0x3a
Nov 10 09:56:39 bastion teleport[630155]: github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors.UnaryServerInterceptor.func1({0x7301878, 0xc0014ac2a0}, {0x5e58e60, 0xc0014ac090}, 0x19?, 0xc005ec7f20)
Nov 10 09:56:39 bastion teleport[630155]: #011github.com/grpc-ecosystem/go-grpc-middleware/v2@v2.0.0-rc.2.0.20220308023801-e4a6915ea237/interceptors/server.go:22 +0x2b0
Nov 10 09:56:39 bastion teleport[630155]: github.com/gravitational/teleport/lib/utils.ChainUnaryServerInterceptors.func1({0x7301878, 0xc0014ac2a0}, {0x5e58e60, 0xc0014ac090}, 0xc005ec7e80, 0x0?)
Nov 10 09:56:39 bastion teleport[630155]: #011github.com/gravitational/teleport/lib/utils/grpc.go:108 +0x119
Nov 10 09:56:39 bastion teleport[630155]: google.golang.org/grpc.chainUnaryInterceptors.func1.1({0x7301878?, 0xc0014ac2a0?}, {0x5e58e60?, 0xc0014ac090?})
Nov 10 09:56:39 bastion teleport[630155]: #011google.golang.org/grpc@v1.49.0/server.go:1135 +0x5b
Nov 10 09:56:39 bastion teleport[630155]: go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.UnaryServerInterceptor.func1({0x7301878, 0xc0014ac060}, {0x5e58e60, 0xc0014ac090}, 0xc005ec7e80, 0xc000b62b00)
Nov 10 09:56:39 bastion teleport[630155]: #011go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.36.1/interceptor.go:352 +0x724
Nov 10 09:56:39 bastion teleport[630155]: google.golang.org/grpc.chainUnaryInterceptors.func1.1({0x7301878?, 0xc0014ac060?}, {0x5e58e60?, 0xc0014ac090?})
Nov 10 09:56:39 bastion teleport[630155]: #011google.golang.org/grpc@v1.49.0/server.go:1138 +0x83
Nov 10 09:56:39 bastion teleport[630155]: google.golang.org/grpc.chainUnaryInterceptors.func1({0x7301878, 0xc0014ac060}, {0x5e58e60, 0xc0014ac090}, 0xc005ec7e80, 0xc001c0c198)
Nov 10 09:56:39 bastion teleport[630155]: #011google.golang.org/grpc@v1.49.0/server.go:1140 +0x12b
Nov 10 09:56:39 bastion teleport[630155]: github.com/gravitational/teleport/api/client/proto._AuthService_CreateSessionTracker_Handler({0x60a6f80?, 0xc001693040}, {0x7301878, 0xc0014ac060}, 0xc00370d6c0, 0xc001699560)
Nov 10 09:56:39 bastion teleport[630155]: #011github.com/gravitational/teleport/api@v0.0.0/client/proto/authservice.pb.go:16407 +0x138
Nov 10 09:56:39 bastion teleport[630155]: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0004b54a0, {0x7315040, 0xc002c59380}, 0xc000b79b00, 0xc0016bb6b0, 0xa2594e0, 0x0)
Nov 10 09:56:39 bastion teleport[630155]: #011google.golang.org/grpc@v1.49.0/server.go:1301 +0xb2b
Nov 10 09:56:39 bastion teleport[630155]: google.golang.org/grpc.(*Server).handleStream(0xc0004b54a0, {0x7315040, 0xc002c59380}, 0xc000b79b00, 0x0)
Nov 10 09:56:39 bastion teleport[630155]: #011google.golang.org/grpc@v1.49.0/server.go:1642 +0xa2f
Nov 10 09:56:39 bastion teleport[630155]: google.golang.org/grpc.(*Server).serveStreams.func1.2()
Nov 10 09:56:39 bastion teleport[630155]: #011google.golang.org/grpc@v1.49.0/server.go:938 +0x98
Nov 10 09:56:39 bastion teleport[630155]: created by google.golang.org/grpc.(*Server).serveStreams.func1
Nov 10 09:56:39 bastion teleport[630155]: #011google.golang.org/grpc@v1.49.0/server.go:936 +0x28a
Nov 10 09:56:39 bastion systemd[1]: teleport.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Nov 10 09:56:39 bastion systemd[1]: teleport.service: Failed with result 'exit-code'.
Nov 10 09:56:40 bastion systemd[1]: teleport.service: Service RestartSec=100ms expired, scheduling restart.
Nov 10 09:56:40 bastion systemd[1]: teleport.service: Scheduled restart job, restart counter is at 10.
Nov 10 09:56:40 bastion systemd[1]: Stopped Teleport Service.
Nov 10 09:56:40 bastion systemd[1]: Started Teleport Service.
Nov 10 09:56:40 bastion teleport[639108]: 2022-11-10T09:56:40+01:00 INFO             Starting Teleport v11.0.1 with a config file located at "" common/teleport.go:437
Nov 10 09:56:40 bastion teleport[639108]: 2022-11-10T09:56:40+01:00 INFO [AUTH]      Updating cluster networking configuration: Kind:"cluster_networking_config" Version:"v2" Metadata:<Name:"cluster-networking-config" Namespace:"default" Labels:<key:"teleport.dev/origin" value:"config-file" > > Spec:<KeepAliveInterval:300000000000 KeepAliveCountMax:3 ProxyListenerMode:Multiplex TunnelStrategy:<AgentMesh:<> > > . auth/init.go:469
Nov 10 09:56:40 bastion teleport[639108]: 2022-11-10T09:56:40+01:00 INFO [AUTH]      Updating session recording configuration: Kind:"session_recording_config" Version:"v2" Metadata:<Name:"session-recording-config" Namespace:"default" Labels:<key:"teleport.dev/origin" value:"defaults" > > Spec:<Mode pid:639108.1 service/service.go:386
```

**Comment by strideynet** [comment]
Thanks for raising this - I'm going to take a quick look and determine who can assign this to so we can get this resolved.

**Comment by strideynet** [comment]
Panic originates here:

```
// GetHostPolicySets returns a list of policy sets held by the host user at the time of session creation.
// This a subset of a role that contains some versioning and naming information in addition to the require policies
func (s *SessionTrackerV1) GetHostPolicySets() []*SessionTrackerPolicySet {
	return s.Spec.HostPolicies
}
```

This suggests a scenario where either `s.Spec` or `s` itself is nil. There are no checks above this point in the hierarchy that would prevent either of these occurring.

**Comment by strideynet** [comment]
@GunFood: can you please describe your setup ? Is this a single node/auth/proxy all in one? If there are separate components, are there any components running a version older than v11 ?

**Comment by GunFood** [comment]
We run teleport on a redhat 8 with a combined auth, proxy and ssh service.
Not all agents are up to Version 11, but at least they are teleport version 10.

I am able to reproduce the issue, if I try to open 3 ssh connections using the top "New session" option.

**Comment by GunFood** [comment]
OK, a next update. 
I get the error due to a connection refused on the target-side, because it thinks it's unable to connect to the proxy.
A restart of the service helps (and I'm updating the agents to be version 11).

teleport[1086]: 2022-11-10T06:48:53-05:00 [NODE:PROX] WARN Failed to create remote tunnel: failed to dial: all auth methods failed, conn: <nil>. leaseID:115 target:bastion.server.local:443 reversetunnel/agent.go:387
teleport[1086]: 2022-11-10T06:48:53-05:00 WARN [PROC:1]    Connection problem: sync rotation state: Get "https://teleport.cluster.local/v2/authorities/host/bastion.server.local.de?load_keys=false": dial tcp public_IP:443: connect: connection refused. service/connect.go:588

**Comment by strideynet** [comment]
Marking this as closed by https://github.com/gravitational/teleport/pull/18334
