### ISSUE TITLE
Integration Test Failure

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#1836]
Found the following panic running integration tests on our macOS cloud box on 90734503dca5359af660f428c0b90f72683a9752.

```
=== RUN   TestIntegrations
the connection was closed on the remote side on  02 Apr 18 10:21 PDT
PASS: integration_test.go:1692: IntSuite.TestAuditOff	2.752s
[AUTH]    Auth service is starting on localhost:20293.
[PROXY]   Reverse tunnel service is starting on localhost:20290.
[PROXY]   SSH proxy service is starting on localhost:20292.
[NODE]    Service is starting on localhost:20294.
[NODE]    Service is starting on localhost:20289.
the connection was closed on the remote side on  02 Apr 18 10:21 PDT
[AUTH]    Auth service is starting on localhost:20287.
[PROXY]   Reverse tunnel service is starting on localhost:20284.
[NODE]    Service is starting on localhost:20288.
[PROXY]   SSH proxy service is starting on localhost:20286.
[NODE]    Service is starting on localhost:20283.
the connection was closed on the remote side on  02 Apr 18 10:21 PDT
[AUTH]    Auth service is starting on localhost:20281.
[PROXY]   Reverse tunnel service is starting on localhost:20278.
[NODE]    Service is starting on localhost:20282.
[PROXY]   SSH proxy service is starting on localhost:20280.
[NODE]    Service is starting on localhost:20277.
the connection was closed on the remote side on  02 Apr 18 10:21 PDT
[AUTH]    Auth service is starting on localhost:20275.
[PROXY]   Reverse tunnel service is starting on localhost:20272.
[NODE]    Service is starting on localhost:20276.
[PROXY]   SSH proxy service is starting on localhost:20274.
[NODE]    Service is starting on localhost:20271.
the connection was closed on the remote side on  02 Apr 18 10:22 PDT
PASS: integration_test.go:162: IntSuite.TestAuditOn	44.908s
[PROXY]   Reverse tunnel service is starting on localhost:20259.
[PROXY]   SSH proxy service is starting on localhost:20257.
PASS: integration_test.go:1406: IntSuite.TestDiscovery	17.616s
PASS: integration_test.go:686: IntSuite.TestEnvironmentVariables	1.660s
PASS: integration_test.go:1512: IntSuite.TestExternalClient	20.876s
[NODE]    Service is starting on localhost:20221.
[PROXY]   SSH proxy service is starting on localhost:20219.
PASS: integration_test.go:960: IntSuite.TestHA	21.365s
the connection was closed on the remote side on  02 Apr 18 10:23 PDT
the connection was closed on the remote side on  02 Apr 18 10:23 PDT
PASS: integration_test.go:547: IntSuite.TestInteractive	5.505s
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x98 pc=0x413fe56]

goroutine 42859 [running]:
compress/gzip.(*Writer).Close(0x0, 0xc420906050, 0x0)
	/usr/local/go/src/compress/gzip/gzip.go:229 +0x26
github.com/gravitational/teleport/lib/events.(*gzipWriter).Close(0xc4204fde60, 0x571c4e0, 0xc4206d32f0)
	/tmp/test-teleport/src/github.com/gravitational/teleport/lib/events/sessionlog.go:423 +0x35
github.com/gravitational/teleport/lib/events.(*DiskSessionLogger).finalize(0xc4208da840, 0x4f6bb70, 0xc4208da8a0)
	/tmp/test-teleport/src/github.com/gravitational/teleport/lib/events/sessionlog.go:196 +0x344
github.com/gravitational/teleport/lib/events.(*DiskSessionLogger).Finalize(0xc4208da840, 0x0, 0x0)
	/tmp/test-teleport/src/github.com/gravitational/teleport/lib/events/sessionlog.go:170 +0x80
github.com/gravitational/teleport/lib/events.(*Forwarder).PostSessionSlice(0xc420760840, 0x4f20d2d, 0x7, 0xc4206068d0, 0x24, 0xc420a32800, 0x3, 0xfa, 0x2, 0x7d0, ...)
	/tmp/test-teleport/src/github.com/gravitational/teleport/lib/events/forward.go:93 +0x173
github.com/gravitational/teleport/lib/state.(*CachingAuditLog).postSlice(0xc420ddd400, 0x4f20d2d, 0x7, 0xc4206068d0, 0x24, 0xc420a32800, 0x3, 0xfa, 0x2, 0x4013b6c, ...)
	/tmp/test-teleport/src/github.com/gravitational/teleport/lib/state/log.go:369 +0x92
github.com/gravitational/teleport/lib/state.(*CachingAuditLog).flush(0xc420ddd400, 0x101)
	/tmp/test-teleport/src/github.com/gravitational/teleport/lib/state/log.go:342 +0x3e5
github.com/gravitational/teleport/lib/state.(*CachingAuditLog).run(0xc420ddd400)
	/tmp/test-teleport/src/github.com/gravitational/teleport/lib/state/log.go:272 +0x296
created by github.com/gravitational/teleport/lib/state.NewCachingAuditLog
	/tmp/test-teleport/src/github.com/gravitational/teleport/lib/state/log.go:245 +0x1ec
exit status 2
FAIL	github.com/gravitational/teleport/integration	115.339s
make: *** [integration] Error 1
```

**Comment by russjones** [comment]
Slightly different location, but probably same root cause:

```
=== RUN   TestIntegrations
the connection was closed on the remote side on  02 Apr 18 10:43 PDT
PASS: integration_test.go:1692: IntSuite.TestAuditOff	2.815s
[AUTH]    Auth service is starting on localhost:20293.
[PROXY]   Reverse tunnel service is starting on localhost:20290.
[PROXY]   SSH proxy service is starting on localhost:20292.
[NODE]    Service is starting on localhost:20294.
[NODE]    Service is starting on localhost:20289.
the connection was closed on the remote side on  02 Apr 18 10:43 PDT
[AUTH]    Auth service is starting on localhost:20287.
[PROXY]   Reverse tunnel service is starting on localhost:20284.
[PROXY]   SSH proxy service is starting on localhost:20286.
[NODE]    Service is starting on localhost:20288.
[NODE]    Service is starting on localhost:20283.
the connection was closed on the remote side on  02 Apr 18 10:43 PDT
[AUTH]    Auth service is starting on localhost:20281.
[PROXY]   Reverse tunnel service is starting on localhost:20278.
[PROXY]   SSH proxy service is starting on localhost:20280.
[NODE]    Service is starting on localhost:20282.
[NODE]    Service is starting on localhost:20277.
the connection was closed on the remote side on  02 Apr 18 10:43 PDT
[AUTH]    Auth service is starting on localhost:20275.
[PROXY]   Reverse tunnel service is starting on localhost:20272.
[NODE]    Service is starting on localhost:20276.
[PROXY]   SSH proxy service is starting on localhost:20274.
[NODE]    Service is starting on localhost:20271.
the connection was closed on the remote side on  02 Apr 18 10:44 PDT
PASS: integration_test.go:162: IntSuite.TestAuditOn	46.077s
[PROXY]   Reverse tunnel service is starting on localhost:20259.
[PROXY]   SSH proxy service is starting on localhost:20257.
PASS: integration_test.go:1406: IntSuite.TestDiscovery	22.527s
PASS: integration_test.go:686: IntSuite.TestEnvironmentVariables	1.667s
PASS: integration_test.go:1512: IntSuite.TestExternalClient	15.682s
[NODE]    Service is starting on localhost:20221.
[PROXY]   SSH proxy service is starting on localhost:20219.
PASS: integration_test.go:960: IntSuite.TestHA	28.460s
the connection was closed on the remote side on  02 Apr 18 10:45 PDT
the connection was closed on the remote side on  02 Apr 18 10:45 PDT
PASS: integration_test.go:547: IntSuite.TestInteractive	6.102s
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xa0 pc=0x413f619]

goroutine 43760 [running]:
compress/gzip.(*Writer).Write(0x0, 0xc42058c000, 0xc9, 0x126, 0x126, 0x0, 0x0)
	/usr/local/go/src/compress/gzip/gzip.go:140 +0x39
github.com/gravitational/teleport/lib/events.(*DiskSessionLogger).writeChunk(0xc420a78000, 0xc4213d9350, 0x24, 0xc42058fea0, 0x2, 0xc420afa0c0, 0xc420f0e000)
	/tmp/test-teleport/src/github.com/gravitational/teleport/lib/events/sessionlog.go:343 +0x215
github.com/gravitational/teleport/lib/events.(*DiskSessionLogger).PostSessionSlice(0xc420a78000, 0x4f20d2d, 0x7, 0xc4213d9350, 0x24, 0xc420289800, 0x2, 0xfa, 0x2, 0x0, ...)
	/tmp/test-teleport/src/github.com/gravitational/teleport/lib/events/sessionlog.go:300 +0xf0
github.com/gravitational/teleport/lib/events.(*Forwarder).PostSessionSlice(0xc4205acd20, 0x4f20d2d, 0x7, 0xc4213d9350, 0x24, 0xc420289800, 0x2, 0xfa, 0x2, 0x7d0, ...)
	/tmp/test-teleport/src/github.com/gravitational/teleport/lib/events/forward.go:81 +0x6c
github.com/gravitational/teleport/lib/state.(*CachingAuditLog).postSlice(0xc4202afd00, 0x4f20d2d, 0x7, 0xc4213d9350, 0x24, 0xc420289800, 0x2, 0xfa, 0x2, 0x0, ...)
	/tmp/test-teleport/src/github.com/gravitational/teleport/lib/state/log.go:369 +0x92
github.com/gravitational/teleport/lib/state.(*CachingAuditLog).flush(0xc4202afd00, 0x101)
	/tmp/test-teleport/src/github.com/gravitational/teleport/lib/state/log.go:342 +0x3e5
github.com/gravitational/teleport/lib/state.(*CachingAuditLog).run(0xc4202afd00)
	/tmp/test-teleport/src/github.com/gravitational/teleport/lib/state/log.go:272 +0x296
created by github.com/gravitational/teleport/lib/state.NewCachingAuditLog
	/tmp/test-teleport/src/github.com/gravitational/teleport/lib/state/log.go:245 +0x1ec
exit status 2
FAIL	github.com/gravitational/teleport/integration	123.428s
make: *** [integration] Error 1
```

**Comment by klizhentas** [comment]
One more catch:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xa0 pc=0x41402c9]

goroutine 45973 [running]:
compress/gzip.(*Writer).Write(0x0, 0xc4212e4640, 0xc9, 0x126, 0x126, 0x0, 0x0)
	/usr/local/go/src/compress/gzip/gzip.go:140 +0x39
github.com/gravitational/teleport/lib/events.(*DiskSessionLogger).writeChunk(0xc420c9def0, 0xc420468510, 0x24, 0xc42085c8c0, 0x2, 0xc420151500, 0xc420203500)
	/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp.tZdU1WCl/src/github.com/gravitational/teleport/lib/events/sessionlog.go:343 +0x215
github.com/gravitational/teleport/lib/events.(*DiskSessionLogger).PostSessionSlice(0xc420c9def0, 0x4f254b3, 0x7, 0xc420468510, 0x24, 0xc4207f8800, 0x2, 0xfa, 0x2, 0x0, ...)
	/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp.tZdU1WCl/src/github.com/gravitational/teleport/lib/events/sessionlog.go:300 +0xf0
github.com/gravitational/teleport/lib/events.(*Forwarder).PostSessionSlice(0xc420975560, 0x4f254b3, 0x7, 0xc420468510, 0x24, 0xc4207f8800, 0x2, 0xfa, 0x2, 0x7d0, ...)
	/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp.tZdU1WCl/src/github.com/gravitational/teleport/lib/events/forward.go:81 +0x6c
github.com/gravitational/teleport/lib/state.(*CachingAuditLog).postSlice(0xc42056d000, 0x4f254b3, 0x7, 0xc420468510, 0x24, 0xc4207f8800, 0x2, 0xfa, 0x2, 0x401481c, ...)
	/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp.tZdU1WCl/src/github.com/gravitational/teleport/lib/state/log.go:369 +0x92
github.com/gravitational/teleport/lib/state.(*CachingAuditLog).flush(0xc42056d000, 0x101)
	/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp.tZdU1WCl/src/github.com/gravitational/teleport/lib/state/log.go:342 +0x3e5
github.com/gravitational/teleport/lib/state.(*CachingAuditLog).run(0xc42056d000)
	/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp.tZdU1WCl/src/github.com/gravitational/teleport/lib/state/log.go:272 +0x296
created by github.com/gravitational/teleport/lib/state.NewCachingAuditLog
	/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp.tZdU1WCl/src/github.com/gravitational/teleport/lib/state/log.go:245 +0x1ec
exit status 2
```
