### ISSUE TITLE
ssh: could not start shell disconnected

### ISSUE THREAD

**Issue by fabriziocacicia** [gravitational/teleport#18828]
Expected behavior:
I expect that the shell starts in the opened web page as soon as i select the server i want to connect to

Current behavior:
As soon as the web page loads I see the message `ssh: could not start shell disconnected`:

<img width="314" alt="Screenshot 2022-11-28 at 19 22 16" src="https://user-images.githubusercontent.com/7525888/204352068-c4300ba6-ca9c-4b91-b40d-9a447137ee28.png">

Bug details:
- Teleport version: 11.0.4-dev.justinas.1
- Recreation steps
<details><summary>- Debug logs</summary>
<p>

```
2022-11-28T18:57:09Z INFO             Starting Teleport v11.0.4-dev.justinas.1 common/teleport.go:437
2022-11-28T18:57:11Z INFO [AUTH]      Updating cluster networking configuration: Kind:"cluster_networking_config" Version:"v2" Metadata:<Name:"cluster-networking-config" Namespace:"default" Labels:<key:"teleport.dev/origin" value:"config-file" > > Spec:<KeepAliveInterval:300000000000 KeepAliveCountMax:3 ProxyListenerMode:Multiplex TunnelStrategy:<AgentMesh:<> > > . auth/init.go:469
2022-11-28T18:57:11Z INFO [AUTH]      Updating session recording configuration: Kind:"session_recording_config" Version:"v2" Metadata:<Name:"session-recording-config" Namespace:"default" Labels:<key:"teleport.dev/origin" value:"defaults" > > Spec:<Mode:"node" ProxyChecksHostKeys:"\010\001" > . auth/init.go:487
2022-11-28T18:57:12Z INFO [AUTH]      Updating cluster auth preference: AuthPreference(Type="local",SecondFactor="otp"). auth/init.go:451
2022-11-28T18:57:12Z INFO [AUTH]      Updating cluster configuration: StaticTokens([]). auth/init.go:338
2022-11-28T18:57:12Z INFO [AUTH]      Created namespace: "default". auth/init.go:345
2022-11-28T18:57:12Z INFO [AUDIT]     role.created cluster_name:192.168.1.40 code:T9000I ei:0 event:role.created expires:0001-01-01T00:00:00Z name:editor time:2022-11-28T18:57:12.682Z uid:66c66beb-49e5-42de-b394-8459d4d8bf15 user:system events/emitter.go:263
2022-11-28T18:57:12Z INFO [AUDIT]     role.created cluster_name:192.168.1.40 code:T9000I ei:0 event:role.created expires:0001-01-01T00:00:00Z name:access time:2022-11-28T18:57:12.948Z uid:7db51e1f-cf80-41de-b805-7b27bfc0345b user:system events/emitter.go:263
2022-11-28T18:57:13Z INFO [AUDIT]     role.created cluster_name:192.168.1.40 code:T9000I ei:0 event:role.created expires:0001-01-01T00:00:00Z name:auditor time:2022-11-28T18:57:13.15Z uid:0eed8502-98c6-45aa-a587-f3ca2a9233a6 user:system events/emitter.go:263
2022-11-28T18:57:13Z INFO [AUTH]      Auth server is running periodic operations. auth/init.go:429
2022-11-28T18:57:13Z INFO [AUTH:1:CA] Cache "auth" first init succeeded. cache/cache.go:776
2022-11-28T18:57:13Z INFO [PROC:1]    Service auth is creating new listener on 0.0.0.0:3025. pid:9.1 service/signals.go:214
2022-11-28T18:57:13Z INFO [AUTH:1]    Starting Auth service with PROXY protocol support. pid:9.1 service/service.go:1683
2022-11-28T18:57:13Z WARN [AUTH:1]    Configuration setting auth_service/advertise_ip is not set. guessing 172.20.0.3:3025. pid:9.1 service/service.go:1766
2022-11-28T18:57:13Z WARN [PROC:1]    No TLS Keys provided, using self-signed certificate. pid:9.1 service/service.go:4699
2022-11-28T18:57:13Z INFO [AUTH:1]    Auth service 11.0.4-dev.justinas.1:v11.0.4-dev.justinas.1-0-g39e27a4 is starting on 172.20.0.3:3025. pid:9.1 utils/cli.go:285
2022-11-28T18:57:13Z INFO [PROC:1]    Connecting to the cluster 192.168.1.40 with TLS client certificate. pid:9.1 service/connect.go:258
2022-11-28T18:57:13Z INFO [PROC:1]    Connecting to the cluster 192.168.1.40 with TLS client certificate. pid:9.1 service/connect.go:258
2022-11-28T18:57:14Z INFO [PROC:1]    Proxy: features loaded from auth server: Kubernetes:true App:true DB:true Desktop:true  pid:9.1 service/connect.go:92
2022-11-28T18:57:14Z INFO [PROC:1]    Node: features loaded from auth server: Kubernetes:true App:true DB:true Desktop:true  pid:9.1 service/connect.go:92
2022-11-28T18:57:14Z INFO [NODE:1:CA] Cache "node" first init succeeded. cache/cache.go:776
2022-11-28T18:57:14Z INFO             debug -> starting control-stream based heartbeat. regular/sshserver.go:809
2022-11-28T18:57:14Z INFO [PROC:1]    Service node is creating new listener on 0.0.0.0:3022. pid:9.1 service/signals.go:214
2022-11-28T18:57:14Z INFO [NODE:1]    Service 11.0.4-dev.justinas.1:v11.0.4-dev.justinas.1-0-g39e27a4 is starting on 0.0.0.0:3022 in-memory cache. pid:9.1 service/service.go:2344
2022-11-28T18:57:14Z INFO [NODE:1]    Service 11.0.4-dev.justinas.1:v11.0.4-dev.justinas.1-0-g39e27a4 is starting on 0.0.0.0:3022. pid:9.1 utils/cli.go:285
2022-11-28T18:57:14Z INFO [PROXY:1:C] Cache "proxy" first init succeeded. cache/cache.go:776
2022-11-28T18:57:14Z INFO [PROC:1]    Service proxy:web is creating new listener on 0.0.0.0:3080. pid:9.1 service/signals.go:214
2022-11-28T18:57:14Z INFO [PROC:1]    Loading TLS certificate /var/lib/teleport/webproxy_cert.pem and key /var/lib/teleport/webproxy_key.pem. pid:9.1 service/service.go:4140
2022-11-28T18:57:14Z INFO [PROXY:SER] Reverse tunnel service 11.0.4-dev.justinas.1:v11.0.4-dev.justinas.1-0-g39e27a4 is starting on . pid:9.1 utils/cli.go:285
2022-11-28T18:57:14Z INFO [PROXY:SER] Starting 11.0.4-dev.justinas.1:v11.0.4-dev.justinas.1-0-g39e27a4 on  using in-memory cache pid:9.1 service/service.go:3439
2022-11-28T18:57:14Z WARN [WEB]       Invalid SSH proxy address "", will use default port 3023. error:[missing port in address] web/apiserver.go:295
2022-11-28T18:57:14Z INFO             debug -> starting legacy heartbeat. regular/sshserver.go:817
2022-11-28T18:57:14Z INFO [PROXY:SER] Web proxy service 11.0.4-dev.justinas.1:v11.0.4-dev.justinas.1-0-g39e27a4 is starting on 0.0.0.0:3080. pid:9.1 utils/cli.go:285
2022-11-28T18:57:14Z INFO [PROXY:SER] Web proxy service 11.0.4-dev.justinas.1:v11.0.4-dev.justinas.1-0-g39e27a4 is starting on 0.0.0.0:3080. pid:9.1 service/service.go:3558
2022-11-28T18:57:14Z INFO [PROXY:SER] SSH proxy service 11.0.4-dev.justinas.1:v11.0.4-dev.justinas.1-0-g39e27a4 is starting on . pid:9.1 utils/cli.go:285
2022-11-28T18:57:14Z INFO [PROXY:SER] SSH proxy service 11.0.4-dev.justinas.1:v11.0.4-dev.justinas.1-0-g39e27a4 is starting on {  } pid:9.1 service/service.go:3668
2022-11-28T18:57:14Z INFO [UPLOAD:1]  starting upload completer service pid:9.1 service/service.go:2444
2022-11-28T18:57:14Z INFO [UPLOAD:1]  Creating directory /var/lib/teleport/log. pid:9.1 service/service.go:2480
2022-11-28T18:57:14Z INFO [UPLOAD:1]  Creating directory /var/lib/teleport/log/upload. pid:9.1 service/service.go:2480
2022-11-28T18:57:14Z INFO [UPLOAD:1]  Creating directory /var/lib/teleport/log/upload/streaming. pid:9.1 service/service.go:2480
2022-11-28T18:57:14Z INFO [UPLOAD:1]  Creating directory /var/lib/teleport/log/upload/streaming/default. pid:9.1 service/service.go:2480
2022-11-28T18:57:14Z INFO [PROXY:AGE] Starting reverse tunnel agent pool. service/service.go:3697
2022-11-28T18:57:14Z INFO [PROXY:PRO] Starting Kube proxy on . service/service.go:3758
2022-11-28T18:57:14Z INFO [DB:SERVIC] Starting Database Postgres proxy server on [::]:3080. pid:9.1 service/service.go:3830
2022-11-28T18:57:14Z INFO [DB:SERVIC] Starting Database TLS proxy server on 0.0.0.0:3080. pid:9.1 service/service.go:3848
2022-11-28T18:57:14Z INFO [PROXY:SER] Starting proxy gRPC server on [::]:3080. pid:9.1 service/service.go:3899
2022-11-28T18:57:14Z INFO [PROXY:SER] Starting TLS ALPN SNI proxy server on [::]:3080. pid:9.1 service/service.go:3932
2022-11-28T18:57:14Z INFO [PROC:1]    The new service has started successfully. Starting syncing rotation status with period 10m0s. pid:9.1 service/connect.go:687
2022-11-28T18:59:10Z WARN [AUTH:1:CA] Encountered 1 stale event(s), may indicate degraded backend or event system performance. last_kind="node" cache/cache.go:1027
2022-11-28T18:59:10Z WARN [PROXY:1:C] Encountered 1 stale event(s), may indicate degraded backend or event system performance. last_kind="node" cache/cache.go:1027
2022-11-28T18:59:47Z WARN [SQLITE]    "SLOW TRANSACTION: 1.077859466s, goroutine 487 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x65\ngithub.com/gravitational/teleport/lib/backend/lite.(*Backend).inTransaction.func1()\n\tgithub.com/gravitational/teleport/lib/backend/lite/lite.go:938 +0x5b\ngithub.com/gravitational/teleport/lib/backend/lite.(*Backend).inTransaction(0xc000c73a20, {0x7392978, 0xc0015ba780}, 0xc0017194e0)\n\tgithub.com/gravitational/teleport/lib/backend/lite/lite.go:989 +0x230\ngithub.com/gravitational/teleport/lib/backend/lite.(*Backend).KeepAlive(0xc000c73a20, {0x7392978, 0xc0015ba780}, {{0xc0010b5e40?, 0x2?, 0x0?}, 0x0?}, {0x9e0dd76, 0xedb16fe7a, 0x0})\n\tgithub.com/gravitational/teleport/lib/backend/lite/lite.go:775 +0x1b4\ngithub.com/gravitational/teleport/lib/backend.(*Sanitizer).KeepAlive(0xc0004a9080, {0x7392978, 0xc0015ba780}, {{0xc0010b5e40?, 0xb81d68464a396d28?, 0x34d688a17fa64815?}, 0x801f09dae19f4eee?}, {0x9e0dd76, 0xedb16fe7a, 0x0})\n\tgithub.com/gravitational/teleport/lib/backend/sanitize.go:138 +0xcb\ngithub.com/gravitational/teleport/lib/backend.(*Reporter).KeepAlive(0xc0001071c0, {0x73928d0, 0xc000107b00}, {{0xc0010b5e40?, 0x32bbc06cbd54598?, 0xa126ca25b141a39c?}, 0x74f2b145ddf629d5?}, {0x9e0dd76, 0xedb16fe7a, 0x0})\n\tgithub.com/gravitational/teleport/lib/backend/report.go:314 +0x4bd\ngithub.com/gravitational/teleport/lib/services/local.(*PresenceService).KeepAliveServer(0xc00053bf00, {0x73928d0, 0xc000107b00}, {{0xc0016e5d40, 0x24}, {0x617f18a, 0x7}, 0x0, {0x9e0dd76, 0xedb16fe7a, ...}, ...})\n\tgithub.com/gravitational/teleport/lib/services/local/presence.go:1371 +0xa2b\ngithub.com/gravitational/teleport/lib/inventory.(*Controller).handleKeepAlive(0xc00026bb30, 0xc000e48000)\n\tgithub.com/gravitational/teleport/lib/inventory/controller.go:294 +0x4bd\ngithub.com/gravitational/teleport/lib/inventory.(*Controller).handleControlStream(0xc00026bb30, 0xc000e48000)\n\tgithub.com/gravitational/teleport/lib/inventory/controller.go:193 +0x3ef\ncreated by github.com/gravitational/teleport/lib/inventory.(*Controller).RegisterControlStream\n\tgithub.com/gravitational/teleport/lib/inventory/controller.go:132 +0x1ca\n." lite/lite.go:938
2022-11-28T18:59:47Z WARN [SQLITE]    "SLOW TRANSACTION: 1.043773613s, goroutine 68 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x65\ngithub.com/gravitational/teleport/lib/backend/lite.(*Backend).inTransaction.func1()\n\tgithub.com/gravitational/teleport/lib/backend/lite/lite.go:938 +0x5b\ngithub.com/gravitational/teleport/lib/backend/lite.(*Backend).inTransaction(0xc000c73a20, {0x73928d0, 0xc000106ec0}, 0xc0000a0e88)\n\tgithub.com/gravitational/teleport/lib/backend/lite/lite.go:989 +0x230\ngithub.com/gravitational/teleport/lib/backend/lite.(*Backend).removeExpiredKeys(0xc000c73a20)\n\tgithub.com/gravitational/teleport/lib/backend/lite/periodic.go:76 +0xe5\ngithub.com/gravitational/teleport/lib/backend/lite.(*Backend).runPeriodicOperations(0xc000c73a20)\n\tgithub.com/gravitational/teleport/lib/backend/lite/periodic.go:43 +0x116\ncreated by github.com/gravitational/teleport/lib/backend/lite.NewWithConfig\n\tgithub.com/gravitational/teleport/lib/backend/lite/lite.go:253 +0x69e\n." lite/lite.go:938
2022-11-28T19:52:57Z WARN [SQLITE]    "SLOW TRANSACTION: 1.097849997s, goroutine 68 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x65\ngithub.com/gravitational/teleport/lib/backend/lite.(*Backend).inTransaction.func1()\n\tgithub.com/gravitational/teleport/lib/backend/lite/lite.go:938 +0x5b\ngithub.com/gravitational/teleport/lib/backend/lite.(*Backend).inTransaction(0xc000c73a20, {0x73928d0, 0xc000106ec0}, 0xc0000a0e88)\n\tgithub.com/gravitational/teleport/lib/backend/lite/lite.go:989 +0x230\ngithub.com/gravitational/teleport/lib/backend/lite.(*Backend).removeOldEvents(0xc000c73a20)\n\tgithub.com/gravitational/teleport/lib/backend/lite/periodic.go:110 +0xe6\ngithub.com/gravitational/teleport/lib/backend/lite.(*Backend).runPeriodicOperations(0xc000c73a20)\n\tgithub.com/gravitational/teleport/lib/backend/lite/periodic.go:55 +0x211\ncreated by github.com/gravitational/teleport/lib/backend/lite.NewWithConfig\n\tgithub.com/gravitational/teleport/lib/backend/lite/lite.go:253 +0x69e\n." lite/lite.go:938
```
And these are the last lines of the logs after trying to connect to the shell of my server:

```
	github.com/gravitational/teleport/lib/services/local/sessiontracker.go:159 github.com/gravitational/teleport/lib/services/local.(*sessionTracker).getActiveSessionTrackers.func1
	runtime/asm_amd64.s:1594 runtime.goexit
User Message: context canceled] local/sessiontracker.go:161
2022-11-28T20:13:25Z ERRO             Failed to remove stale session tracker error:[
ERROR REPORT:
Original Error: *errors.errorString context canceled

Stack Trace:
	github.com/gravitational/teleport/lib/backend/lite/lite.go:943 github.com/gravitational/teleport/lib/backend/lite.(*Backend).inTransaction
	github.com/gravitational/teleport/lib/backend/lite/lite.go:853 github.com/gravitational/teleport/lib/backend/lite.(*Backend).Delete
	github.com/gravitational/teleport/lib/backend/sanitize.go:116 github.com/gravitational/teleport/lib/backend.(*Sanitizer).Delete
	github.com/gravitational/teleport/lib/backend/report.go:265 github.com/gravitational/teleport/lib/backend.(*Reporter).Delete
	github.com/gravitational/teleport/lib/services/local/sessiontracker.go:159 github.com/gravitational/teleport/lib/services/local.(*sessionTracker).getActiveSessionTrackers.func1
	runtime/asm_amd64.s:1594 runtime.goexit
User Message: context canceled] local/sessiontracker.go:161
2022-11-28T20:13:25Z ERRO             Failed to remove stale session tracker error:[
ERROR REPORT:
Original Error: *errors.errorString context canceled

Stack Trace:
	github.com/gravitational/teleport/lib/backend/lite/lite.go:943 github.com/gravitational/teleport/lib/backend/lite.(*Backend).inTransaction
	github.com/gravitational/teleport/lib/backend/lite/lite.go:853 github.com/gravitational/teleport/lib/backend/lite.(*Backend).Delete
	github.com/gravitational/teleport/lib/backend/sanitize.go:116 github.com/gravitational/teleport/lib/backend.(*Sanitizer).Delete
	github.com/gravitational/teleport/lib/backend/report.go:265 github.com/gravitational/teleport/lib/backend.(*Reporter).Delete
	github.com/gravitational/teleport/lib/services/local/sessiontracker.go:159 github.com/gravitational/teleport/lib/services/local.(*sessionTracker).getActiveSessionTrackers.func1
	runtime/asm_amd64.s:1594 runtime.goexit
User Message: context canceled] local/sessiontracker.go:161
2022-11-28T20:13:25Z ERRO             Failed to remove stale session tracker error:[
ERROR REPORT:
Original Error: *errors.errorString context canceled

Stack Trace:
	github.com/gravitational/teleport/lib/backend/lite/lite.go:943 github.com/gravitational/teleport/lib/backend/lite.(*Backend).inTransaction
	github.com/gravitational/teleport/lib/backend/lite/lite.go:853 github.com/gravitational/teleport/lib/backend/lite.(*Backend).Delete
	github.com/gravitational/teleport/lib/backend/sanitize.go:116 github.com/gravitational/teleport/lib/backend.(*Sanitizer).Delete
	github.com/gravitational/teleport/lib/backend/report.go:265 github.com/gravitational/teleport/lib/backend.(*Reporter).Delete
	github.com/gravitational/teleport/lib/services/local/sessiontracker.go:159 github.com/gravitational/teleport/lib/services/local.(*sessionTracker).getActiveSessionTrackers.func1
	runtime/asm_amd64.s:1594 runtime.goexit
User Message: context canceled] local/sessiontracker.go:161
2022-11-28T20:13:25Z ERRO             Failed to remove stale session tracker error:[
ERROR REPORT:
Original Error: *errors.errorString context canceled

Stack Trace:
	github.com/gravitational/teleport/lib/backend/lite/lite.go:943 github.com/gravitational/teleport/lib/backend/lite.(*Backend).inTransaction
	github.com/gravitational/teleport/lib/backend/lite/lite.go:853 github.com/gravitational/teleport/lib/backend/lite.(*Backend).Delete
	github.com/gravitational/teleport/lib/backend/sanitize.go:116 github.com/gravitational/teleport/lib/backend.(*Sanitizer).Delete
	github.com/gravitational/teleport/lib/backend/report.go:265 github.com/gravitational/teleport/lib/backend.(*Reporter).Delete
	github.com/gravitational/teleport/lib/services/local/sessiontracker.go:159 github.com/gravitational/teleport/lib/services/local.(*sessionTracker).getActiveSessionTrackers.func1
	runtime/asm_amd64.s:1594 runtime.goexit
User Message: context canceled] local/sessiontracker.go:161
2022-11-28T20:13:25Z ERRO             Failed to remove stale session tracker error:[
ERROR REPORT:
Original Error: *errors.errorString context canceled

Stack Trace:
	github.com/gravitational/teleport/lib/backend/lite/lite.go:943 github.com/gravitational/teleport/lib/backend/lite.(*Backend).inTransaction
	github.com/gravitational/teleport/lib/backend/lite/lite.go:853 github.com/gravitational/teleport/lib/backend/lite.(*Backend).Delete
	github.com/gravitational/teleport/lib/backend/sanitize.go:116 github.com/gravitational/teleport/lib/backend.(*Sanitizer).Delete
	github.com/gravitational/teleport/lib/backend/report.go:265 github.com/gravitational/teleport/lib/backend.(*Reporter).Delete
	github.com/gravitational/teleport/lib/services/local/sessiontracker.go:159 github.com/gravitational/teleport/lib/services/local.(*sessionTracker).getActiveSessionTrackers.func1
	runtime/asm_amd64.s:1594 runtime.goexit
User Message: context canceled] local/sessiontracker.go:161
2022-11-28T20:13:25Z ERRO             Failed to remove stale session tracker error:[
ERROR REPORT:
Original Error: *errors.errorString context canceled

Stack Trace:
	github.com/gravitational/teleport/lib/backend/lite/lite.go:943 github.com/gravitational/teleport/lib/backend/lite.(*Backend).inTransaction
	github.com/gravitational/teleport/lib/backend/lite/lite.go:853 github.com/gravitational/teleport/lib/backend/lite.(*Backend).Delete
	github.com/gravitational/teleport/lib/backend/sanitize.go:116 github.com/gravitational/teleport/lib/backend.(*Sanitizer).Delete
	github.com/gravitational/teleport/lib/backend/report.go:265 github.com/gravitational/teleport/lib/backend.(*Reporter).Delete
	github.com/gravitational/teleport/lib/services/local/sessiontracker.go:159 github.com/gravitational/teleport/lib/services/local.(*sessionTracker).getActiveSessionTrackers.func1
	runtime/asm_amd64.s:1594 runtime.goexit
User Message: context canceled] local/sessiontracker.go:161
2022-11-28T20:13:25Z ERRO             Failed to remove stale session tracker error:[
ERROR REPORT:
Original Error: *errors.errorString context canceled

Stack Trace:
	github.com/gravitational/teleport/lib/backend/lite/lite.go:943 github.com/gravitational/teleport/lib/backend/lite.(*Backend).inTransaction
	github.com/gravitational/teleport/lib/backend/lite/lite.go:853 github.com/gravitational/teleport/lib/backend/lite.(*Backend).Delete
	github.com/gravitational/teleport/lib/backend/sanitize.go:116 github.com/gravitational/teleport/lib/backend.(*Sanitizer).Delete
	github.com/gravitational/teleport/lib/backend/report.go:265 github.com/gravitational/teleport/lib/backend.(*Reporter).Delete
	github.com/gravitational/teleport/lib/services/local/sessiontracker.go:159 github.com/gravitational/teleport/lib/services/local.(*sessionTracker).getActiveSessionTrackers.func1
	runtime/asm_amd64.s:1594 runtime.goexit
User Message: context canceled] local/sessiontracker.go:161
2022-11-28T20:13:25Z ERRO             Failed to remove stale session tracker error:[
ERROR REPORT:
Original Error: *errors.errorString context canceled

Stack Trace:
	github.com/gravitational/teleport/lib/backend/lite/lite.go:943 github.com/gravitational/teleport/lib/backend/lite.(*Backend).inTransaction
	github.com/gravitational/teleport/lib/backend/lite/lite.go:853 github.com/gravitational/teleport/lib/backend/lite.(*Backend).Delete
	github.com/gravitational/teleport/lib/backend/sanitize.go:116 github.com/gravitational/teleport/lib/backend.(*Sanitizer).Delete
	github.com/gravitational/teleport/lib/backend/report.go:265 github.com/gravitational/teleport/lib/backend.(*Reporter).Delete
	github.com/gravitational/teleport/lib/services/local/sessiontracker.go:159 github.com/gravitational/teleport/lib/services/local.(*sessionTracker).getActiveSessionTrackers.func1
	runtime/asm_amd64.s:1594 runtime.goexit
User Message: context canceled] local/sessiontracker.go:161
2022-11-28T20:13:26Z INFO [CLIENT]    Connecting to proxy=localhost:3080 login="root" using TLS Routing client/api.go:3292
2022-11-28T20:13:26Z INFO [CLIENT]    Successful auth with proxy localhost:3080. client/api.go:3297
2022-11-28T20:13:26Z INFO [CLIENT]    Connecting to proxy=localhost:3080 login="root" using TLS Routing client/api.go:3292
2022-11-28T20:13:26Z INFO [CLIENT]    Successful auth with proxy localhost:3080. client/api.go:3297
2022-11-28T20:13:26Z INFO [CLIENT]    Client=172.20.0.1:59616 connecting to node=teleport-aspire on cluster 192.168.1.40 client/client.go:1526
2022-11-28T20:13:27Z ERRO [AUTH:GRPC] Missing SessionTracker in CreateSessionTrackerRequest. This can be caused by an outdated Teleport node running against your cluster. auth/grpcserver.go:3913
missing SessionTracker from CreateSessionTrackerRequest
2022-11-28T20:13:27Z WARN [WEBSOCKET] Unable to stream terminal: ssh: could not start shell. web/terminal.go:484
2022-11-28T20:13:27Z INFO [AUDIT]     session.data addr.local:192.168.1.40:3022 addr.remote:172.20.0.1:59616 cluster_name:192.168.1.40 code:T2006I ei:2.147483646e+09 event:session.data login:aspire namespace:default rx:4290 server_id:6135129e-bf73-47c3-9d53-eae588d06350 sid: time:2022-11-28T20:13:27.751Z tx:5316 uid:2524f009-8cf0-41fa-ae98-39d3b3c37cd8 user:fabryx92 events/emitter.go:263
```
</p>
</details>

**Comment by zmb3** [comment]
What version of teleport is running on the node you're trying to connect to? Based on the error, it looks like the node is out of date.

**Comment by fabriziocacicia** [comment]
That was correct. I solved the issue by updating the binaries on the node. Thanks @zmb3
