### ISSUE TITLE
Trusted Cluster regression in disabling from east cluster.

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#1950]
1. Create a Trusted Cluster relationship between `main <- east`.
2. Remove it from the `east` cluster: `tctl rm trusted_cluster/main`

The main cluster keeps logging the following:

```
DEBU [PROXY:SER] Requesting teleport-transport-dial connection to remote site with payload: @remote-auth-server cluster:two reversetunnel/remotesite.go:633
DEBU [PROXY:SER] Remote cluster two is offline. cluster:two reversetunnel/remotesite.go:400
```

I printed a stacktrace from `reversetunnel/remotesite.go:633`:

```
goroutine 249 [running]:
runtime/debug.Stack(0x0, 0x1e, 0x10000c420549740)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/gravitational/teleport/lib/reversetunnel.(*remoteSite).connThroughTunnel(0xc42057f9e0, 0x4edee13, 0x17, 0x4ed8f6f, 0x13, 0xc42023c860, 0x1a, 0x0, 0xc420430040)
	/Users/rjones/Development/go/src/github.com/gravitational/teleport/lib/reversetunnel/remotesite.go:631 +0x37
github.com/gravitational/teleport/lib/reversetunnel.(*remoteSite).DialAuthServer(0xc42057f9e0, 0x10, 0x10, 0x4d27cc0, 0xc420556090)
	/Users/rjones/Development/go/src/github.com/gravitational/teleport/lib/reversetunnel/remotesite.go:546 +0x55
github.com/gravitational/teleport/lib/reversetunnel.(*remoteSite).authServerContextDialer(0xc42057f9e0, 0x56a8c40, 0xc4200140a0, 0x4eca3b4, 0x3, 0xc4201cfee0, 0x1a, 0x2400202a2840, 0x110, 0x110, ...)
	/Users/rjones/Development/go/src/github.com/gravitational/teleport/lib/reversetunnel/remotesite.go:121 +0x2b
github.com/gravitational/teleport/lib/reversetunnel.(*remoteSite).(github.com/gravitational/teleport/lib/reversetunnel.authServerContextDialer)-fm(0x56a8c40, 0xc4200140a0, 0x4eca3b4, 0x3, 0xc4201cfee0, 0x1a, 0x4005b79, 0x60, 0x42476d9, 0xc4200140a0)
	/Users/rjones/Development/go/src/github.com/gravitational/teleport/lib/reversetunnel/remotesite.go:104 +0x73
net/http.(*Transport).dial(0xc4204700f0, 0x56a8c40, 0xc4200140a0, 0x4eca3b4, 0x3, 0xc4201cfee0, 0x1a, 0x72, 0xc420023370, 0xc420023300, ...)
	/usr/local/go/src/net/http/transport.go:884 +0x223
net/http.(*Transport).dialConn(0xc4204700f0, 0x56a8c40, 0xc4200140a0, 0x0, 0xc42001a140, 0x5, 0xc4201cfee0, 0x1a, 0x4b2a479, 0xc420394820, ...)
	/usr/local/go/src/net/http/transport.go:1060 +0x1d62
net/http.(*Transport).getConn.func4(0xc4204700f0, 0x56a8c40, 0xc4200140a0, 0xc420392fc0, 0xc4202a2780)
	/usr/local/go/src/net/http/transport.go:943 +0x78
created by net/http.(*Transport).getConn
	/usr/local/go/src/net/http/transport.go:942 +0x393
```

**Comment by klizhentas** [comment]
Confirmed that this is expected behavior and the state should be cleaned up using remote cluster resource. This is how teleport behaved pre 2.6. as well, it's just a new log line that is confusing. Feel free to reopen if you discover it otherwise.
