### ISSUE TITLE
Panic on session close in 2.6

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#2068]
```
=== RUN   TestSrv
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x98 pc=0x5cd56b]

goroutine 466 [running]:
compress/gzip.(*Writer).Write(0x0, 0xc420222dc0, 0xca, 0x126, 0x126, 0x0, 0x0)
	/opt/go/src/compress/gzip/gzip.go:140 +0x7b
github.com/gravitational/teleport/lib/events.(*DiskSessionLogger).writeChunk(0xc420511130, 0xc42050c0c0, 0x24, 0xc42095c0a0, 0xc4206176d0, 0xc42000e010, 0xc4205e3368)
	/gopath/src/github.com/gravitational/teleport/lib/events/sessionlog.go:343 +0x394
github.com/gravitational/teleport/lib/events.(*DiskSessionLogger).PostSessionSlice(0xc420511130, 0x117f682, 0x7, 0xc42050c0c0, 0x24, 0xc42000e008, 0x1, 0x1, 0x3, 0x0, ...)
	/gopath/src/github.com/gravitational/teleport/lib/events/sessionlog.go:300 +0x11c
github.com/gravitational/teleport/lib/events.(*Forwarder).PostSessionSlice(0xc4205e3300, 0x117f682, 0x7, 0xc42050c0c0, 0x24, 0xc42000e008, 0x1, 0x1, 0x3, 0x10, ...)
	/gopath/src/github.com/gravitational/teleport/lib/events/forward.go:116 +0xe1
github.com/gravitational/teleport/lib/events.(*Forwarder).EmitAuditEvent(0xc4205e3300, 0x11845ce, 0xd, 0xc420224480, 0xc4204cc1e8, 0xc4200fcb80)
	/gopath/src/github.com/gravitational/teleport/lib/events/forward.go:98 +0x420
github.com/gravitational/teleport/lib/srv.(*SessionRegistry).emitSessionLeaveEvent(0xc4200ed0b0, 0xc4206da600)
	/gopath/src/github.com/gravitational/teleport/lib/srv/sess.go:200 +0x4b6
github.com/gravitational/teleport/lib/srv.(*SessionRegistry).leaveSession(0xc4200ed0b0, 0xc4206da600, 0x0, 0x0)
	/gopath/src/github.com/gravitational/teleport/lib/srv/sess.go:227 +0xac
github.com/gravitational/teleport/lib/srv.(*party).Close.func1()
	/gopath/src/github.com/gravitational/teleport/lib/srv/sess.go:1093 +0x142
sync.(*Once).Do(0xc4206da6b0, 0xc420617b48)
	/opt/go/src/sync/once.go:44 +0xe2
github.com/gravitational/teleport/lib/srv.(*party).Close(0xc4206da600, 0x0, 0x0)
	/gopath/src/github.com/gravitational/teleport/lib/srv/sess.go:1091 +0xaf
github.com/gravitational/teleport/lib/srv.closeAll(0xc42000c060, 0x2, 0x2, 0x2, 0xc42029a6e0)
	/gopath/src/github.com/gravitational/teleport/lib/srv/ctx.go:412 +0xcc
github.com/gravitational/teleport/lib/srv.(*ServerContext).Close(0xc4203a2420, 0x7f82503fa828, 0xc4206daa80)
	/gopath/src/github.com/gravitational/teleport/lib/srv/ctx.go:351 +0x5f
github.com/gravitational/teleport/lib/srv/regular.(*Server).handleSessionRequests(0xc420465c20, 0xc420553f40, 0xc4204f3340, 0x7, 0xc42045de10, 0x7, 0xc4204b3b00, 0x44a, 0x480, 0x12b8cc0, ...)
	/gopath/src/github.com/gravitational/teleport/lib/srv/regular/sshserver.go:884 +0x814
created by github.com/gravitational/teleport/lib/srv/regular.(*Server).HandleNewChan
	/gopath/src/github.com/gravitational/teleport/lib/srv/regular/sshserver.go:729 +0x10b5
FAIL	github.com/gravitational/teleport/lib/srv/regular	5.161s
?   	github.com/gravitational/teleport/lib/sshca	[no test files]
=== RUN   TestSSHUtils
OK: 3 passed
```

**Comment by russjones** [comment]
This code has been refactored quite a bit.
