### ISSUE TITLE
`kube/proxy.TestModeratedSessions` race

### ISSUE THREAD

**Issue by rosstimothy** [gravitational/teleport#20998]
#### Link(s) to logs

- https://github.com/gravitational/teleport/actions/runs/4056205714/jobs/6980390339

#### Relevant snippet

```
===================================================
OUTPUT github.com/gravitational/teleport/lib/kube/proxy.TestModeratedSessions
===================================================
=== RUN   TestModeratedSessions
time="2023-01-31T16:36:44Z" level=warning msg="Mux serve failed." error="listener is closed\n\taccept tcp 127.0.0.1:34343: use of closed network connection" trace.component=auth
==================
WARNING: DATA RACE
Write at 0x00c001e2e7d0 by goroutine 1913:
  github.com/gravitational/teleport/lib/kube/proxy.(*TLSServer).Serve()
      /__w/teleport/teleport/lib/kube/proxy/server.go:251 +0x4a4
  github.com/gravitational/teleport/lib/kube/proxy.(*testContext).startKubeService.func1()
      /__w/teleport/teleport/lib/kube/proxy/utils_test.go:244 +0x70

Previous read at 0x00c001e2e7d0 by goroutine 1849:
  github.com/gravitational/teleport/lib/kube/proxy.(*TLSServer).Close()
      /__w/teleport/teleport/lib/kube/proxy/server.go:269 +0x286
  github.com/gravitational/teleport/lib/kube/proxy.(*testContext).Close()
      /__w/teleport/teleport/lib/kube/proxy/utils_test.go:256 +0x55
  github.com/gravitational/teleport/lib/kube/proxy.TestHeartbeat.func2()
      /__w/teleport/teleport/lib/kube/proxy/server_test.go:260 +0x39
  testing.(*common).Cleanup.func1()
      /opt/go/src/testing/testing.go:1041 +0x193
  testing.(*common).runCleanup()
      /opt/go/src/testing/testing.go:1210 +0x143
  testing.tRunner.func2()
      /opt/go/src/testing/testing.go:1440 +0x52
  runtime.deferreturn()
      /opt/go/src/runtime/panic.go:476 +0x32
  testing.(*T).Run.func1()
      /opt/go/src/testing/testing.go:1493 +0x47

Goroutine 1913 (running) created at:
  github.com/gravitational/teleport/lib/kube/proxy.(*testContext).startKubeService()
      /__w/teleport/teleport/lib/kube/proxy/utils_test.go:243 +0x197
  github.com/gravitational/teleport/lib/kube/proxy.setupTestContext()
      /__w/teleport/teleport/lib/kube/proxy/utils_test.go:229 +0x1a57
  github.com/gravitational/teleport/lib/kube/proxy.TestHeartbeat()
      /__w/teleport/teleport/lib/kube/proxy/server_test.go:252 +0x346
  testing.tRunner()
      /opt/go/src/testing/testing.go:1446 +0x216
  testing.(*T).Run.func1()
      /opt/go/src/testing/testing.go:1493 +0x47

Goroutine 1849 (finished) created at:
  testing.(*T).Run()
      /opt/go/src/testing/testing.go:1493 +0x75d
  testing.runTests.func1()
      /opt/go/src/testing/testing.go:1846 +0x99
  testing.tRunner()
      /opt/go/src/testing/testing.go:1446 +0x216
  testing.runTests()
      /opt/go/src/testing/testing.go:1844 +0x7ec
  testing.(*M).Run()
      /opt/go/src/testing/testing.go:1726 +0xa84
  main.main()
      _testmain.go:177 +0x3bc
==================
time="2023-01-31T16:36:44Z" level=info msg="Generating TLS certificate {0xc00045df20 0xc000e96080 1.3.9999.1.7=#1310726f6f742e6578616d706c652e[636](https://github.com/gravitational/teleport/actions/runs/4056205714/jobs/6980390339#step:6:637)f6d,CN=test-tls-server.root.example.com,O=Auth,POSTALCODE=null,STREET= 2033-01-28 16:36:44.285090911 +0000 UTC [*.teleport.cluster.local teleport.cluster.local] [] 5 []}." common_name=test-tls-server.root.example.com dns_names="[*.teleport.cluster.local teleport.cluster.local]" locality="[]" not_after="2033-01-28 16:36:44.285090911 +0000 UTC" org="[Auth]" org_unit="[]" trace.component=ca
time="2023-01-31T16:36:44Z" level=info msg="Generating TLS certificate {0xc00045df20 0xc000e6e480 1.3.9999.1.7=#1310726f6f742e6578616d706c[652](https://github.com/gravitational/teleport/actions/runs/4056205714/jobs/6980390339#step:6:653)e636f6d,CN=0b3c3d7a-9809-48ac-94ee-3057ad545859.root.example.com,O=Kube,POSTALCODE=null,STREET= 2033-01-28 16:36:44.285090911 +0000 UTC [*.teleport.cluster.local teleport.cluster.local] [] 5 []}." common_name=0b3c3d7a-9809-48ac-94ee-3057ad545859.root.example.com dns_names="[*.teleport.cluster.local teleport.cluster.local]" locality="[]" not_after="2033-01-28 16:36:44.285090911 +0000 UTC" org="[Kube]" org_unit="[]" trace.component=ca
time="2023-01-31T16:36:45Z" level=info msg="Generating TLS certificate {0xc00045df20 0xc000f40030 1.3.9999.1.7=#1310726f6f742e[657](https://github.com/gravitational/teleport/actions/runs/4056205714/jobs/6980390339#step:6:658)8616d706c652e636f6d,CN=Proxy.root.example.com,O=Proxy,POSTALCODE=null,STREET= 2033-01-28 16:36:44.285090911 +0000 UTC [*.teleport.cluster.local teleport.cluster.local] [] 5 []}." common_name=Proxy.root.example.com dns_names="[*.teleport.cluster.local teleport.cluster.local]" locality="[]" not_after="2033-01-28 16:36:44.285090911 +0000 UTC" org="[Proxy]" org_unit="[]" trace.component=ca
time="2023-01-31T16:36:45Z" level=info msg="Generating TLS certificate {0xc00045df20 0xc0016b88f0 1.3.9999.1.7=#1310726f6f742e6578616d706c652e636f6d,CN=0b3c3d7a-9809-48ac-94ee-3057ad545859.root.example.com,O=Auth,POSTALCODE=null,STREET= 2033-01-28 16:36:44.285090911 +0000 UTC [*.teleport.cluster.local teleport.cluster.local] [] 5 []}." common_name=0b3c3d7a-9809-48ac-94ee-3057ad545859.root.example.com dns_names="[*.teleport.cluster.local teleport.cluster.local]" locality="[]" not_after="2033-01-28 16:36:44.285090911 +0000 UTC" org="[Auth]" org_unit="[]" trace.component=ca
=== CONT  TestModeratedSessions
    testing.go:1319: race detected during execution of test
--- FAIL: TestModeratedSessions (1.58s)
===================================================
```

**Comment by smallinsky** [comment]
In v18  https://github.com/gravitational/teleport/actions/runs/17411469806/job/49429440992?pr=58614

```
=== FAIL: lib/kube/proxy  (0.00s)
-test.shuffle 1756835354754458316
panic: test timed out after 10m0s
	running tests:
		TestModeratedSessions/create_session_without_needing_moderation_but_leave_it_without_proper_closing (9m57s)

goroutine 9698 [running]:
testing.(*M).startAlarm.func1()
	/opt/go/src/testing/testing.go:2484 +0x605
created by time.goFunc
	/opt/go/src/time/sleep.go:215 +0x45

goroutine 1 [chan receive, 9 minutes, locked to thread]:
testing.(*T).Run(0xc00070ac40, {0xedec873, 0x15}, 0xf06e248)
	/opt/go/src/testing/testing.go:1859 +0x91e
testing.runTests.func1(0xc00070ac40)
	/opt/go/src/testing/testing.go:2279 +0x86
testing.tRunner(0xc00070ac40, 0xc0010bfaa8)
	/opt/go/src/testing/testing.go:1792 +0x226
testing.runTests(0xc000b64018, {0x142ca700, 0x36, 0x36}, {0x2?, 0x380af60?, 0x1453a940?})
	/opt/go/src/testing/testing.go:2277 +0x96d
testing.(*M).Run(0xc000a1f400)
	/opt/go/src/testing/testing.go:2142 +0xeeb
github.com/gravitational/teleport/lib/kube/proxy.TestMain(0xc000a1f400)
	/__w/teleport/teleport/lib/kube/proxy/forwarder_test.go:99 +0x31
main.main()
	_testmain.go:165 +0x172

goroutine 1672 [chan receive, 9 minutes]:
testing.(*T).Parallel(0xc002668c40)
	/opt/go/src/testing/testing.go:1577 +0x4ff
github.com/gravitational/teleport/lib/kube/proxy.TestSelfSubjectAccessReviewsRBAC(0xc002668c40)
	/__w/teleport/teleport/lib/kube/proxy/self_subject_reviews_test.go:35 +0x3f
testing.tRunner(0xc002668c40, 0xf06e290)
	/opt/go/src/testing/testing.go:1792 +0x226
created by testing.(*T).Run in goroutine 1
	/opt/go/src/testing/testing.go:1851 +0x8f3

goroutine 122 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc00085a1c0)
	/opt/go/src/testing/testing.go:1577 +0x4ff
github.com/gravitational/teleport/lib/kube/proxy.TestDirectTransportNotCached(0xc00085a1c0)
	/__w/teleport/teleport/lib/kube/proxy/transport_test.go:144 +0x3c
testing.tRunner(0xc00085a1c0, 0xf06e1b0)
	/opt/go/src/testing/testing.go:1792 +0x226
created by testing.(*T).Run in goroutine 1
	/opt/go/src/testing/testing.go:1851 +0x8f3

goroutine 121 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc00085a000)
	/opt/go/src/testing/testing.go:1577 +0x4ff
github.com/gravitational/teleport/lib/kube/proxy.TestGetKubeCreds(0xc00085a000)
	/__w/teleport/teleport/lib/kube/proxy/auth_test.go:131 +0x3f
testing.tRunner(0xc00085a000, 0xf06e1f8)
	/opt/go/src/testing/testing.go:1792 +0x226
created by testing.(*T).Run in goroutine 1
	/opt/go/src/testing/testing.go:1851 +0x8f3
```
