### ISSUE TITLE
Integration test panic

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#2292]
Intermittently occurred on 70aaa24f2162950bb2a05cdf053bddf97dcad04f.

```
PASS: integration_test.go:568: IntSuite.TestInteractive	3.116s
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xa0 pc=0x543aa9]

goroutine 16611 [running]:
compress/gzip.(*Writer).Write(0x0, 0xc4207186e0, 0x95, 0xa4, 0xa4, 0x0, 0x0)
	/opt/go/src/compress/gzip/gzip.go:140 +0x39
github.com/gravitational/teleport/lib/events.(*DiskSessionLogger).writeChunk(0xc420439ad0, 0xc420401e00, 0x24, 0xc4208d2280, 0x50, 0xc4208d2280, 0xc420e94480)
	/gopath/src/github.com/gravitational/teleport/lib/events/sessionlog.go:338 +0x215
github.com/gravitational/teleport/lib/events.(*DiskSessionLogger).PostSessionSlice(0xc420439ad0, 0x1b9540a, 0x7, 0xc420401e00, 0x24, 0xc420180148, 0x1, 0x1, 0x3, 0x0, ...)
	/gopath/src/github.com/gravitational/teleport/lib/events/sessionlog.go:295 +0xf0
github.com/gravitational/teleport/lib/events.(*Forwarder).PostSessionSlice(0xc420bb2b40, 0x1b9540a, 0x7, 0xc420401e00, 0x24, 0xc420180148, 0x1, 0x1, 0x3, 0x10, ...)
	/gopath/src/github.com/gravitational/teleport/lib/events/forward.go:139 +0xad
github.com/gravitational/teleport/lib/events.(*Forwarder).EmitAuditEvent(0xc420bb2b40, 0x1b9b0c3, 0xb, 0xc4209544b0, 0xc421268648, 0x1)
	/gopath/src/github.com/gravitational/teleport/lib/events/forward.go:121 +0x2f8
github.com/gravitational/teleport/lib/srv.(*SessionRegistry).leaveSession.func1()
	/gopath/src/github.com/gravitational/teleport/lib/srv/sess.go:255 +0x40d
created by github.com/gravitational/teleport/lib/srv.(*SessionRegistry).leaveSession
	/gopath/src/github.com/gravitational/teleport/lib/srv/sess.go:279 +0x124
exit status 2
FAIL	github.com/gravitational/teleport/integration	61.084s
```

**Comment by klizhentas** [comment]
k
