### ISSUE TITLE
Teleport tsh ssh crashing with nil pointer / invalid memory address SIGSEGV

### ISSUE THREAD

**Issue by astridlyre** [gravitational/teleport#24311]
Expected behavior:

```bash
tsh ssh -L 3306:mydatabase:3306 -N --proxy=secure.host.com root@bastion-host-1
```

I would expect this command to work as it did last week before I upgraded to *12.2.1-1*.

Current behavior:

Normally I proxy to my database using the `tsh ssh` command, but after upgrading from version *12.1.5-1* to version *12.2.1-1*, I am getting the following crash:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x35e404a]

goroutine 1 [running]:
github.com/gravitational/teleport/lib/client.(*TeleportClient).getSSHLoginFunc(0xc0004a0e00, 0xc000554000)
        github.com/gravitational/teleport/lib/client/api.go:3189 +0x12a
github.com/gravitational/teleport/lib/client.(*TeleportClient).Login(0xc0004a0e00, {0x4ef3780, 0xc000e6a360})
        github.com/gravitational/teleport/lib/client/api.go:3089 +0x1b8
github.com/gravitational/teleport/lib/client.RetryWithRelogin({0x4ef3780, 0xc000e6a360}, 0xc0004a0e00, 0xc00141e960)
        github.com/gravitational/teleport/lib/client/api.go:543 +0x205
main.onSSH.func1()
        github.com/gravitational/teleport/tool/tsh/tsh.go:3027 +0x90
main.retryWithAccessRequest(0xc000178e00, 0xc0004a0e00, 0xc00141eb10)
        github.com/gravitational/teleport/tool/tsh/tsh.go:2936 +0x66
main.onSSH(0xc000178e00)
        github.com/gravitational/teleport/tool/tsh/tsh.go:3026 +0xbd
main.Run({0x4ef4ee8, 0xc000e819c0}, {0xc000074080?, 0x6, 0x6}, {0x0, 0x0, 0x1613105?})
        github.com/gravitational/teleport/tool/tsh/tsh.go:1116 +0xbf25
main.main()
        github.com/gravitational/teleport/tool/tsh/tsh.go:499 +0x305
```

Bug details:
- Teleport version 12.2.1-1 (issue did not present in 12.1.5-1, so I have reverted to that for now)
- Recreation steps Try to proxy a port locally using the ssh command
- Debug logs:

```
2023-04-08T21:53:16+01:00 INFO [CLIENT]    ALPN connection upgrade required for "<secure bastion>:443": false. client/api.go:629
2023-04-08T21:53:16+01:00 DEBU [CLIENT]    Skipping connection to the local ssh-agent. client/keyagent.go:136
2023-04-08T21:53:16+01:00 WARN [CLIENT]    "Certificate was not loaded into agent because the agent at SSH_AUTH_SOCK does not appear\nto support SSH certificates. To force load the certificate into the running agent, use\nthe --add-keys-to-agent=yes flag." client/keyagent.go:139
2023-04-08T21:53:16+01:00 DEBU [KEYSTORE]  Reading certificates from path "/home/<user>/.tsh/keys/<secure bastion>/<user-email>-ssh/<secure bastion>-cert.pub". client/keystore.go:341
2023-04-08T21:53:16+01:00 DEBU [KEYSTORE]  Teleport TLS certificate valid until "2023-04-07 07:30:48 +0000 UTC". client/client_store.go:91
2023-04-08T21:53:16+01:00 INFO [KEYAGENT]  Loading SSH key for user "<user-email>" and cluster "<secure bastion>". client/keyagent.go:195
2023-04-08T21:53:16+01:00 DEBU [KEYSTORE]  Teleport TLS certificate valid until "2023-04-07 07:30:48 +0000 UTC". client/client_store.go:91
2023-04-08T21:53:16+01:00 DEBU [CLIENT]    Activating relogin on error ssh: cert has expired. client/api.go:530
2023-04-08T21:53:16+01:00 DEBU [CLIENT]    not using loopback pool for remote proxy addr: <secure bastion>:443 client/api.go:3950
2023-04-08T21:53:16+01:00 DEBU             Attempting GET <secure bastion>:443/webapi/ping/local webclient/webclient.go:129
2023-04-08T21:53:18+01:00 DEBU             ALPN connection upgrade required for "<secure bastion>:443": false. alpnproxy/conn_upgrade.go:81
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x35e404a]

goroutine 1 [running]:
github.com/gravitational/teleport/lib/client.(*TeleportClient).getSSHLoginFunc(0xc00029e380, 0xc00054a000)
        github.com/gravitational/teleport/lib/client/api.go:3189 +0x12a
github.com/gravitational/teleport/lib/client.(*TeleportClient).Login(0xc00029e380, {0x4ef3780, 0xc0001502d0})
        github.com/gravitational/teleport/lib/client/api.go:3089 +0x1b8
github.com/gravitational/teleport/lib/client.RetryWithRelogin({0x4ef3780, 0xc0001502d0}, 0xc00029e380, 0xc0014d4960)
        github.com/gravitational/teleport/lib/client/api.go:543 +0x205
main.onSSH.func1()
        github.com/gravitational/teleport/tool/tsh/tsh.go:3027 +0x90
main.retryWithAccessRequest(0xc00097a700, 0xc00029e380, 0xc0014d4b10)
        github.com/gravitational/teleport/tool/tsh/tsh.go:2936 +0x66
main.onSSH(0xc00097a700)
        github.com/gravitational/teleport/tool/tsh/tsh.go:3026 +0xbd
main.Run({0x4ef4ee8, 0xc000ba5400}, {0xc000074110?, 0x7, 0x7}, {0x0, 0x0, 0x1613105?})
        github.com/gravitational/teleport/tool/tsh/tsh.go:1116 +0xbf25
main.main()
        github.com/gravitational/teleport/tool/tsh/tsh.go:499 +0x305
```

OS details: `Linux <host> 6.2.9-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 30 Mar 2023 14:51:14 +0000 x86_64 GNU/Linux`

**Comment by computerphilosopher** [comment]
The getSSHLoginFunc function references the result of the ping. If you're not using a local user as your authentication method, chances are you'll see a nil pointer in this part.

https://github.com/gravitational/teleport/blob/40c113b8dad017613c154efaa16997a186eec7fb/lib/client/api.go#L3340

Can you tell us what you are using as the authentication method?

**Comment by astridlyre** [comment]
Sure! Here's the result of that ping. Sorry about the late reply @computerphilosopher, I was travelling back from London to Vancouver yesterday.

```
$ xhs https://{proxy-server-name}.com/webapi/ping
HTTP/1.1 200 OK
Cache-Control: no-cache, no-store, must-revalidate
Content-Length: 504
Content-Type: application/json
Date: Mon, 10 Apr 2023 16:23:56 GMT
Expires: 0
Pragma: no-cache

{
    "auth": {
        "type": "local",
        "second_factor": "otp",
        "preferred_local_mfa": "otp",
        "has_motd": false
    },
    "proxy": {
        "kube": {
            "enabled": true,
            "listen_addr": "0.0.0.0:3026"
        },
        "ssh": {
            "listen_addr": "[::]:3023",
            "tunnel_listen_addr": "0.0.0.0:3024",
            "web_listen_addr": "0.0.0.0:3080",
            "public_addr": "{proxy-server-name}.com:443"
        },
        "db": {
            "mysql_listen_addr": "0.0.0.0:3036"
        },
        "tls_routing_enabled": false
    },
    "server_version": "9.3.26",
    "min_client_version": "8.0.0",
    "cluster_name": "{proxy-server-name}.com"
}
```

**Comment by Joerger** [comment]
@astridlyre it looks like you are trying to use v12 `tsh` with a v9 Teleport server. Generally, we don't have any compatiblity guarentee for serers more than one major version apart, meaning you should use `tsh` between v8 and v11, not including v11.

In the case of this issue, new clients expect that the ping response will never return with a nil `auth.local` field when `auth.type = local`. I'll add a nil check for this since it's a simple incompatibility fix.
