### ISSUE TITLE
Pressing `t` in the Web UI as a moderator of a moderated session disconnects from the session/panics

### ISSUE THREAD

**Issue by ravicious** [gravitational/teleport#24728]
Expected behavior:

When I press `t` when viewing the session in the Web UI as a moderator, nothing happens.

Current behavior:

When I press `t` when viewing the session in the Web UI as a moderator, I get disconnected from the session. If I have per-session MFA enabled, pressing `t` causes the teleport process to panic:

```
2023-04-18T15:46:08+02:00 INFO [AUDIT]     session.join addr.local:127.0.0.1:3032 addr.remote:127.0.0.1:59761 cluster_name:enterprise-local code:T2001I ei:9 event:session.join login:-teleport-internal-join namespace:default server_addr:127.0.0.1:3032 server_hostname:mbp.enterprise-local server_id:339cc7f2-2d53-458a-92e2-09e96798c64d sid:8f57860c-b67a-4fd8-8b51-573a78e3f801 time:2023-04-18T13:46:08.213Z uid:7b124559-5ea6-4bd2-87b0-22d0e6f70f64 user:rav events/emitter.go:265
panic: repeated read on failed websocket connection

goroutine 2501 [running]:
github.com/gorilla/websocket.(*Conn).NextReader(0x14003544420)
	github.com/gorilla/websocket@v1.5.0/conn.go:1030 +0x270
github.com/gorilla/websocket.(*Conn).ReadMessage(0x10bb1ffc0?)
	github.com/gorilla/websocket@v1.5.0/conn.go:1093 +0x1c
github.com/gravitational/teleport/lib/web.(*TerminalStream).Read(0x1400303acd0, {0x14002eee7be, 0x1, 0x1400254c094?})
	github.com/gravitational/teleport/lib/web/terminal.go:1115 +0x4c
github.com/gravitational/teleport/lib/client.handleNonPeerControls({0x14003559a30, 0x9}, 0x140021c87e0, 0x140023f4fa0)
	github.com/gravitational/teleport/lib/client/session.go:645 +0x64
github.com/gravitational/teleport/lib/client.(*NodeSession).pipeInOut.func2()
	github.com/gravitational/teleport/lib/client/session.go:717 +0x90
created by github.com/gravitational/teleport/lib/client.(*NodeSession).pipeInOut
	github.com/gravitational/teleport/lib/client/session.go:714 +0x24c
```

Perhaps it has to do with escape sequences?

Bug details:
- Teleport version: first run into it on v13, tested on v12
- Recreation steps:
   1. Start a moderated session which requires a moderator to join.
   2. Press `t` in the Web UI after joining as the moderator.

**Comment by zmb3** [comment]
The expected behavior is that pressing `t` terminates the session. The panic with per-session MFA is unexpected, but it sounds like the rest is working as designed?

**Comment by avatus** [comment]
This happens with more than just `t` and actually happens with any input at all. Basically, any event that would cause the websocket to send information will break with this error
```
websocket: continuation after FIN, bad MASK
```

You can press any key or resize the window and it will break. If NOTHING is pressed after joining, the websocket is still open and working because as a moderator, you can still see input and output when the user is doing stuff. It's only when the moderator tries to take an action is when it breaks.
