### ISSUE TITLE
TSH - Runtime Error - identity file and host labels

### ISSUE THREAD

**Issue by sidmalik123** [gravitational/teleport#2611]
Have a question? Please use [Our Forum](https://community.gravitational.com)

**What happened**:
I wanted to ssh using tsh and an identity file to a node. The node has the hostname of `centos` and has a label `test=sid`.
When I run `tsh ssh -i sid --proxy=<proxy> ec2-user@centos`, `tsh ssh ec2-user@centos`, or `tsh ssh ec2-user@test=sid` I'm able to ssh in. However, when I use an identity file and try to filter the node using the label (`tsh ssh -i sid --proxy=<proxy> ec2-user@test=sid`), I get the following runtime error.

```
Siddharths-MacBook-Pro:tsh siddharth$ tsh ssh -i sid --proxy=<proxy> ec2-user@test=sid
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x80 pc=0x4c4fa17]

goroutine 1 [running]:
github.com/gravitational/teleport/lib/auth.NewTLSClientWithDialer(0xc00021a0a0, 0x0, 0x0, 0x0, 0x0, 0x41f0b32, 0xc0000d81e0, 0x4d55940)
	/tmp/20190313T121130/src/github.com/gravitational/teleport/lib/auth/clt.go:144 +0x37
github.com/gravitational/teleport/lib/client.(*ProxyClient).ConnectToCluster(0xc0003c6e00, 0x513d480, 0xc000432340, 0xc0002ea170, 0x9, 0x0, 0x4d55940, 0xc00058eaa0, 0x4d55940, 0x0)
	/tmp/20190313T121130/src/github.com/gravitational/teleport/lib/client/client.go:187 +0x7aa
github.com/gravitational/teleport/lib/client.(*ProxyClient).ClusterAccessPoint(0xc0003c6e00, 0x513d480, 0xc000432340, 0xc0002ea170, 0x9, 0x4045700, 0x0, 0x4f113c0, 0x4c9bd01, 0x5c7b788)
	/tmp/20190313T121130/src/github.com/gravitational/teleport/lib/client/client.go:156 +0x75
github.com/gravitational/teleport/lib/client.(*ProxyClient).CurrentClusterAccessPoint(0xc0003c6e00, 0x513d480, 0xc000432340, 0x5c7b700, 0x0, 0x0, 0x665c580, 0x100010000)
	/tmp/20190313T121130/src/github.com/gravitational/teleport/lib/client/client.go:147 +0xf1
github.com/gravitational/teleport/lib/client.(*ProxyClient).FindServersByLabels(0xc0003c6e00, 0x513d480, 0xc000432340, 0x4f942ba, 0x7, 0xc00043e6f0, 0x3, 0x4, 0x0, 0x0, ...)
	/tmp/20190313T121130/src/github.com/gravitational/teleport/lib/client/client.go:119 +0xa9
github.com/gravitational/teleport/lib/client.(*TeleportClient).getTargetNodes(0xc000262000, 0x513d480, 0xc000432340, 0xc0003c6e00, 0x0, 0x0, 0x0, 0x0, 0x0)
	/tmp/20190313T121130/src/github.com/gravitational/teleport/lib/client/api.go:792 +0x21f
github.com/gravitational/teleport/lib/client.(*TeleportClient).SSH(0xc000262000, 0x513d480, 0xc000432340, 0x0, 0x0, 0x0, 0x4037d00, 0x0, 0x0)
	/tmp/20190313T121130/src/github.com/gravitational/teleport/lib/client/api.go:826 +0x11e
main.onSSH(0xc0002b6200)
	/tmp/20190313T121130/src/github.com/gravitational/teleport/tool/tsh/tsh.go:678 +0xcc
main.Run(0xc0000ca130, 0x5, 0x5, 0x0)
	/tmp/20190313T121130/src/github.com/gravitational/teleport/tool/tsh/tsh.go:313 +0x4d53
main.main()
	/tmp/20190313T121130/src/github.com/gravitational/teleport/tool/tsh/tsh.go:163 +0x11c
```

**What you expected to happen**:

Expected to ssh into the node

**How to reproduce it (as minimally and precisely as possible)**:
- Use identity file with `tsh ssh` and instead of hostname use hostl abels

**Environment**:
- Teleport version (use `teleport version`): `Teleport v3.1.8 git:v3.1.8-0-g4cceea49 go1.11.4`
- Tsh version (use `tsh version`): `Teleport v3.1.8 git:v3.1.8-0-g4cceea49 go1.11.4`
- OS (e.g. from /etc/os-release): MacOS Mojave 10.14.2

**Browser environment**

- Browser Version (for UI-related issues):
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**
```
INFO [TSH]       Reading identity file: sid tsh/tsh.go:960
DEBU [TSH]       Extracted username "siddharth.malik" from the identity file sid. tsh/tsh.go:823
INFO [CLIENT]    Connecting proxy=<proxy> login='ec2-user' method=0 client/api.go:1434
INFO [CLIENT]    Successful auth with proxy <proxy>:3023 client/api.go:1425
DEBU [CLIENT]    Found clusters: [{"name":"us-east-1","lastconnected":"2019-03-18T17:32:52.223133074Z","status":"online"},{"name":"eu-central-1","lastconnected":"2019-03-18T17:32:47.424130901Z","status":"online"},{"name":"us-west-1","lastconnected":"2019-03-18T17:32:50.358823855Z","status":"online"}] client/client.go:102
DEBU [CLIENT]    Found clusters: [{"name":"us-east-1","lastconnected":"2019-03-18T17:32:52.269102621Z","status":"online"},{"name":"eu-central-1","lastconnected":"2019-03-18T17:32:47.424130901Z","status":"online"},{"name":"us-west-1","lastconnected":"2019-03-18T17:32:50.358823855Z","status":"online"}] client/client.go:102
```

- tsh --debug
- teleport --debug

**Comment by russjones** [comment]
@sidmalik123 I was not able to reproduce, can you try again, and if it's still an issue create another ticket?
