### ISSUE TITLE
Segmentation fault when running tsh ls with ssh certificate

### ISSUE THREAD

**Issue by venturel** [gravitational/teleport#2743]
Have a question? Please use [Our Forum](https://community.gravitational.com)

**What happened**:
We are trying to list the nodes in a teleport cluster using the certificate as per https://gravitational.com/teleport/docs/user-manual/#ssh-certificates-for-automation
. We are getting a runtime error.

**What you expected to happen**:
Get a list of teleport nodes

**How to reproduce it (as minimally and precisely as possible)**:
Create a certificate.
Use the certificate to list the nodes

**Environment**:
- Teleport version (use `teleport version`): 3.1.8
- Tsh version (use `tsh version`): 3.2.4
- OS (e.g. from /etc/os-release): Ubuntu 18.04

**Browser environment**

- Browser Version (for UI-related issues):
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**

```
tsh -i concourse.pem --proxy teleport.example.com -l root --user concourse -d ls --cluster main
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x80 pc=0xa9d707]

goroutine 1 [running]:
github.com/gravitational/teleport/lib/auth.NewTLSClientWithDialer(0xc00000c240, 0x0, 0x0, 0x0, 0x0, 0x8, 0xc000278280, 0xc0003226c0)
	/gopath/src/github.com/gravitational/teleport/lib/auth/clt.go:144 +0x37
github.com/gravitational/teleport/lib/client.(*ProxyClient).ConnectToCluster(0xc00051e880, 0x1540480, 0xc0000aa018, 0xc0002e8db0, 0x21, 0xc0002e8d00, 0x21, 0x2446cfc, 0xed47f2b9a, 0x0)
	/gopath/src/github.com/gravitational/teleport/lib/client/client.go:187 +0x7aa
github.com/gravitational/teleport/lib/client.(*ProxyClient).ClusterAccessPoint(0xc00051e880, 0x1540480, 0xc0000aa018, 0xc0002e8db0, 0x21, 0x444f00, 0x0, 0x1313a60, 0xae2101, 0x227bd18)
	/gopath/src/github.com/gravitational/teleport/lib/client/client.go:156 +0x75
github.com/gravitational/teleport/lib/client.(*ProxyClient).CurrentClusterAccessPoint(0xc00051e880, 0x1540480, 0xc0000aa018, 0x227bd00, 0x0, 0x0, 0x1540440, 0x100010000)
	/gopath/src/github.com/gravitational/teleport/lib/client/client.go:147 +0xf1
github.com/gravitational/teleport/lib/client.(*ProxyClient).FindServersByLabels(0xc00051e880, 0x1540480, 0xc0000aa018, 0x1396a41, 0x7, 0x0, 0x0, 0x0, 0x0, 0x1, ...)
	/gopath/src/github.com/gravitational/teleport/lib/client/client.go:119 +0xa9
github.com/gravitational/teleport/lib/client.(*TeleportClient).ListNodes(0xc0004beb40, 0x1540480, 0xc0000aa018, 0x0, 0x0, 0x0, 0x0, 0x0)
	/gopath/src/github.com/gravitational/teleport/lib/client/api.go:1279 +0xfd
main.onListNodes(0xc000530000)
	/gopath/src/github.com/gravitational/teleport/tool/tsh/tsh.go:597 +0x81
main.Run(0xc0000a40e0, 0xc, 0xc, 0x0)
	/gopath/src/github.com/gravitational/teleport/tool/tsh/tsh.go:330 +0x4dc4
main.main()
	/gopath/src/github.com/gravitational/teleport/tool/tsh/tsh.go:167 +0x11c
```

**Comment by klizhentas** [comment]
That's a missing piece of a functionality. After `tsh` has been switched to the TLS, this pem is misisng X509 creds, so we have to make it work.
