### ISSUE TITLE
Teleport Agents frequently loose connection to Proxy Servers in AWS Chart mode when there are more than one Proxy Server pod

### ISSUE THREAD

**Issue by gsadhani-px** [gravitational/teleport#29314]
Expected behavior:
Teleport Agents connection to Proxy Servers is stable and highly available in HA mode.

Current behavior:
Teleport Agents frequently loose connection to Proxy Servers in AWS Chart mode when there are more than one Proxy Server pod.

Auth Server Config:
```
  teleport.yaml: |
    auth_service:
      authentication:
        local_auth: true
        second_factor: "on"
        type: local
        webauthn:
          rp_id: xxxxxx.io
      cluster_name: xxxxxx.io
      enabled: true
      proxy_listener_mode: multiplex
      tunnel_strategy:
        type: agent_mesh
    kubernetes_service:
      enabled: true
      kube_cluster_name: xxxxxx.io
      listen_addr: 0.0.0.0:3026
      public_addr: teleport-auth.teleport.svc.cluster.local:3026
    proxy_service:
      enabled: false
    ssh_service:
      enabled: false
    teleport:
      auth_server: 127.0.0.1:3025
      log:
        format:
          extra_fields:
          - timestamp
          - level
          - component
          - caller
          output: json
        output: stderr
        severity: INFO
      storage:
        audit_events_uri:
        - file:///var/lib/teleport/audit/events
        audit_retention_period: 7d
        audit_sessions_uri: s3://teleport-session-recordings-yyyyyyy/records
        auto_scaling: false
        continuous_backups: false
        region: us-west-2
        table_name: teleport-backend
        type: dynamodb
    version: v3
```

Bug details:
- Teleport version
v13.2.1
- Recreation steps:
1. Deploy Teleport Cluster Chart in `aws` mode with replica count > 1
2. Join Kubernetes clusters to Teleport Cluster by deploying Teleport Kube Agent chart
3. Monitor teleport agent logs on the Kubernetes clusters
- Debug logs
Agent logs:
```
2023-07-19T10:25:53Z [PROXY:AGE] INFO Connection closed, returning leaseID:67 target:xxxxxx.io:443 localCluster: targetCluster:xxxxxx.io reversetunnel/agent.go:644
2023-07-19T10:25:53Z [PROXY:AGE] WARN Failed to close discovery channel: EOF leaseID:67 target:xxxxxx.io:443 localCluster: targetCluster:xxxxxx.io reversetunnel/agent.go:633
2023-07-19T10:25:53Z [PROXY:AGE] DEBU Failed to handle drainable channels. error:[
ERROR REPORT:
Original Error: *trace.ConnectionProblemError heartbeat: connection closed
Stack Trace:
	github.com/gravitational/teleport/lib/reversetunnel/agent.go:549 github.com/gravitational/teleport/lib/reversetunnel.(*agent).handleDrainChannels
	github.com/gravitational/teleport/lib/reversetunnel/agent.go:338 github.com/gravitational/teleport/lib/reversetunnel.(*agent).Start.func3
	runtime/asm_amd64.s:1598 runtime.goexit
User Message: heartbeat: connection closed] leaseID:67 target:xxxxxx.io:443 localCluster: targetCluster:xxxxxx.io reversetunnel/agent.go:339
2023-07-19T10:25:53Z [PROXY:AGE] DEBU Changing state connected -> closed. leaseID:67 target:xxxxxx.io:443 localCluster: targetCluster:xxxxxx.io reversetunnel/agent.go:287
2023-07-19T10:25:53Z [PROXY:AGE] DEBU Failed to handle channels. error:[
ERROR REPORT:
Original Error: *errors.errorString context canceled
Stack Trace:
	github.com/gravitational/teleport/lib/reversetunnel/agent.go:601 github.com/gravitational/teleport/lib/reversetunnel.(*agent).handleChannels
	github.com/gravitational/teleport/lib/reversetunnel/agent.go:347 github.com/gravitational/teleport/lib/reversetunnel.(*agent).Start.func4
	runtime/asm_amd64.s:1598 runtime.goexit
User Message: context canceled] leaseID:67 target:xxxxxx.io:443 localCluster: targetCluster:xxxxxx.io reversetunnel/agent.go:348
2023-07-19T10:25:53Z [PROXY:AGE] DEBU Runtime config: tunnel_strategy: agent_mesh connection_count: 1 localCluster: targetCluster:xxxxxx.io reversetunnel/agentpool.go:329
2023-07-19T10:25:53Z [PROXY:AGE] DEBU Failed to handle global requests. error:[
ERROR REPORT:
Original Error: *errors.errorString global request channel is closing
Stack Trace:
	github.com/gravitational/teleport/lib/reversetunnel/agent.go:457 github.com/gravitational/teleport/lib/reversetunnel.(*agent).handleGlobalRequests
	github.com/gravitational/teleport/lib/reversetunnel/agent.go:327 github.com/gravitational/teleport/lib/reversetunnel.(*agent).Start.func2
	runtime/asm_amd64.s:1598 runtime.goexit
User Message: global request channel is closing] leaseID:67 target:xxxxxx.io:443 localCluster: targetCluster:xxxxxx.io reversetunnel/agent.go:328
2023-07-19T10:25:59Z [PROC:1]    INFO Teleport component "kubernetes" has recovered from a degraded state. pid:7.1 service/state.go:124
2023-07-19T10:26:08Z [PROC:1]    WARN Sync rotation state cycle failed. Retrying in ~10s pid:7.1 service/connect.go:826
2023-07-19T10:26:08Z             WARN Inventory control stream failed: inventory control stream closed: error reading from server: EOF inventory/inventory.go:191
2023-07-19T10:26:08Z             DEBU Re-attempt control stream acquisition in ~4.31462085s. inventory/inventory.go:170
2023-07-19T10:26:08Z [PROXY:AGE] DEBU Received discovery request: [dbd8ca1b-c0cd-431e-af39-033d77f21b5e f2637c2f-8d46-4059-bf23-912e037f1f7d] leaseID:76 target:xxxxxx.io:443 localCluster: targetCluster:xxxxxx.io reversetunnel/agent.go:655
2023-07-19T10:26:12Z [PROC:1]    WARN Sync rotation state cycle failed. Retrying in ~10s pid:7.1 service/connect.go:826
2023-07-19T10:26:12Z [KUBERNETE] DEBU Attempting to restart watch after waiting 1.157126ms. pid:7.1 resource-kind:lock services/watcher.go:239
2023-07-19T10:26:12Z [KUBERNETE] WARN Restart watch on error: watcher is closed: error reading from server: EOF. pid:7.1 resource-kind:lock services/watcher.go:246
2023-07-19T10:26:12Z [KUBERNETE] DEBU Starting watch. pid:7.1 resource-kind:lock services/watcher.go:210
2023-07-19T10:26:14Z             DEBU Attempting GET xxxxxx.io:443/webapi/find webclient/webclient.go:129
2023-07-19T10:26:17Z             DEBU ALPN connection upgrade required for "xxxxxx.io:443": false. client/alpn_conn_upgrade.go:91
2023-07-19T10:26:17Z [HTTP:PROX] DEBU No proxy set in environment, returning direct dialer. proxy/proxy.go:195
2023-07-19T10:26:17Z [PROC:1]    ERRO Failed to resolve tunnel address: Get "https://xxxxxx.io:443/webapi/find": dial tcp xxx.xxx.xxx.xxx:443: i/o timeout pid:7.1 reversetunnel/transport.go:96
2023-07-19T10:26:17Z [PROC:1]    ERRO Failed to resolve tunnel address: Get "https://xxxxxx.io:443/webapi/find": dial tcp xxx.xxx.xxx.xxx:443: i/o timeout pid:7.1 reversetunnel/transport.go:96
2023-07-19T10:26:17Z [PROC:1]    WARN Connection problem: sync rotation state: connection error: desc = "transport: Error while dialing: failed to dial: Get \"https://xxxxxx.io:443/webapi/find\": dial tcp xxx.xxx.xxx.xxx:443: i/o timeout". pid:7.1 service/connect.go:927
2023-07-19T10:26:17Z [PROC:1]    WARN Sync rotation state cycle failed. Retrying in ~10s pid:7.1 service/connect.go:826
2023-07-19T10:26:17Z [PROC:1]    WARN Connection problem: sync rotation state: connection error: desc = "transport: Error while dialing: failed to dial: Get \"https://xxxxxx.io:443/webapi/find\": dial tcp xxx.xxx.xxx.xxx:443: i/o timeout". pid:7.1 service/connect.go:927
2023-07-19T10:26:17Z [PROC:1]    WARN Sync rotation state cycle failed. Retrying in ~10s pid:7.1 service/connect.go:826
2023-07-19T10:26:17Z [PROXY:AGE] DEBU Failed to connect agent. error:[
ERROR REPORT:
Original Error: *url.Error Get &#34;https://xxxxxx.io:443/webapi/find&#34;: dial tcp xxx.xxx.xxx.xxx:443: i/o timeout
Stack Trace:
	github.com/gravitational/teleport/api@v0.0.0/client/webclient/webclient.go:142 github.com/gravitational/teleport/api/client/webclient.doWithFallback
	github.com/gravitational/teleport/api@v0.0.0/client/webclient/webclient.go:177 github.com/gravitational/teleport/api/client/webclient.Find
	github.com/gravitational/teleport/lib/reversetunnel/resolver.go:78 github.com/gravitational/teleport/lib/reversetunnel.WebClientResolver.func1
	github.com/gravitational/teleport/lib/reversetunnel/resolver.go:53 github.com/gravitational/teleport/lib/reversetunnel.CachingResolver.func1.1
	github.com/gravitational/teleport/lib/utils/fncache.go:135 github.com/gravitational/teleport/lib/utils.FnCacheGet[...].func1
	github.com/gravitational/teleport/lib/utils/fncache.go:199 github.com/gravitational/teleport/lib/utils.(*FnCache).get.func1
	runtime/asm_amd64.s:1598 runtime.goexit
User Message: Get &#34;https://xxxxxx.io:443/webapi/find&#34;: dial tcp xxx.xxx.xxx.xxx:443: i/o timeout] localCluster: targetCluster:xxxxxx.io reversetunnel/agentpool.go:275
2023-07-19T10:26:17Z [PROXY:AGE] DEBU Active agent count: 1 localCluster: targetCluster:xxxxxx.io reversetunnel/agentpool.go:456
2023-07-19T10:26:17Z [PROXY:AGE] DEBU Runtime config: tunnel_strategy: agent_mesh connection_count: 1 localCluster: targetCluster:xxxxxx.io reversetunnel/agentpool.go:329
2023-07-19T10:26:17Z [PROXY:AGE] DEBU Failed to connect agent. error:[
ERROR REPORT:
Original Error: *url.Error Get &#34;https://xxxxxx.io:443/webapi/find&#34;: dial tcp xxx.xxx.xxx.xxx:443: i/o timeout
Stack Trace:
	github.com/gravitational/teleport/api@v0.0.0/client/webclient/webclient.go:142 github.com/gravitational/teleport/api/client/webclient.doWithFallback
	github.com/gravitational/teleport/api@v0.0.0/client/webclient/webclient.go:177 github.com/gravitational/teleport/api/client/webclient.Find
	github.com/gravitational/teleport/lib/reversetunnel/resolver.go:78 github.com/gravitational/teleport/lib/reversetunnel.WebClientResolver.func1
	github.com/gravitational/teleport/lib/reversetunnel/resolver.go:53 github.com/gravitational/teleport/lib/reversetunnel.CachingResolver.func1.1
	github.com/gravitational/teleport/lib/utils/fncache.go:135 github.com/gravitational/teleport/lib/utils.FnCacheGet[...].func1
	github.com/gravitational/teleport/lib/utils/fncache.go:199 github.com/gravitational/teleport/lib/utils.(*FnCache).get.func1
	runtime/asm_amd64.s:1598 runtime.goexit
User Message: Get &#34;https://xxxxxx.io:443/webapi/find&#34;: dial tcp xxx.xxx.xxx.xxx:443: i/o timeout] localCluster: targetCluster:xxxxxx.io reversetunnel/agentpool.go:275
2023-07-19T10:26:18Z [PROXY:AGE] DEBU Runtime config: tunnel_strategy: agent_mesh connection_count: 1 localCluster: targetCluster:xxxxxx.io reversetunnel/agentpool.go:329
2023-07-19T10:26:18Z [PROXY:AGE] DEBU Failed to connect agent. error:[
ERROR REPORT:
Original Error: *url.Error Get &#34;https://xxxxxx.io:443/webapi/find&#34;: dial tcp xxx.xxx.xxx.xxx:443: i/o timeout
Stack Trace:
	github.com/gravitational/teleport/api@v0.0.0/client/webclient/webclient.go:142 github.com/gravitational/teleport/api/client/webclient.doWithFallback
	github.com/gravitational/teleport/api@v0.0.0/client/webclient/webclient.go:177 github.com/gravitational/teleport/api/client/webclient.Find
	github.com/gravitational/teleport/lib/reversetunnel/resolver.go:78 github.com/gravitational/teleport/lib/reversetunnel.WebClientResolver.func1
	github.com/gravitational/teleport/lib/reversetunnel/resolver.go:53 github.com/gravitational/teleport/lib/reversetunnel.CachingResolver.func1.1
	github.com/gravitational/teleport/lib/utils/fncache.go:135 github.com/gravitational/teleport/lib/utils.FnCacheGet[...].func1
	github.com/gravitational/teleport/lib/utils/fncache.go:199 github.com/gravitational/teleport/lib/utils.(*FnCache).get.func1
	runtime/asm_amd64.s:1598 runtime.goexit
User Message: Get &#34;https://xxxxxx.io:443/webapi/find&#34;: dial tcp xxx.xxx.xxx.xxx:443: i/o timeout] localCluster: targetCluster:xxxxxx.io reversetunnel/agentpool.go:275
2023-07-19T10:26:19Z [KUBERNETE] WARN Re-init the cache on error error:[
ERROR REPORT:
Original Error: *trace.ConnectionProblemError context deadline exceeded (Client.Timeout exceeded while awaiting headers)
Stack Trace:
	github.com/gravitational/teleport/lib/httplib/httplib.go:196 github.com/gravitational/teleport/lib/httplib.ConvertResponse
	github.com/gravitational/teleport/lib/auth/http_client.go:315 github.com/gravitational/teleport/lib/auth.(*HTTPClient).Get
	github.com/gravitational/teleport/lib/auth/http_client.go:1028 github.com/gravitational/teleport/lib/auth.(*HTTPClient).GetClusterName
	github.com/gravitational/teleport/lib/cache/collections.go:1063 github.com/gravitational/teleport/lib/cache.clusterNameExecutor.getAll
	github.com/gravitational/teleport/lib/cache/collections.go:91 github.com/gravitational/teleport/lib/cache.(*genericCollection[...]).fetch
	github.com/gravitational/teleport/lib/cache/cache.go:1421 github.com/gravitational/teleport/lib/cache.(*Cache).fetch.func2
	golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 golang.org/x/sync/errgroup.(*Group).Go.func1
	runtime/asm_amd64.s:1598 runtime.goexit
User Message: failed to fetch resource: &#34;cluster_name&#34;
	context deadline exceeded (Client.Timeout exceeded while awaiting headers)] cache/cache.go:950
2023-07-19T10:26:19Z [KUBERNETE] DEBU Reloading cache. cache/cache.go:954
2023-07-19T10:26:20Z [PROXY:AGE] DEBU Runtime config: tunnel_strategy: agent_mesh connection_count: 1 localCluster: targetCluster:xxxxxx.io reversetunnel/agentpool.go:329
2023-07-19T10:26:20Z [PROXY:AGE] DEBU Failed to connect agent. error:[
ERROR REPORT:
Original Error: *url.Error Get &#34;https://xxxxxx.io:443/webapi/find&#34;: dial tcp xxx.xxx.xxx.xxx:443: i/o timeout
Stack Trace:
	github.com/gravitational/teleport/api@v0.0.0/client/webclient/webclient.go:142 github.com/gravitational/teleport/api/client/webclient.doWithFallback
	github.com/gravitational/teleport/api@v0.0.0/client/webclient/webclient.go:177 github.com/gravitational/teleport/api/client/webclient.Find
	github.com/gravitational/teleport/lib/reversetunnel/resolver.go:78 github.com/gravitational/teleport/lib/reversetunnel.WebClientResolver.func1
	github.com/gravitational/teleport/lib/reversetunnel/resolver.go:53 github.com/gravitational/teleport/lib/reversetunnel.CachingResolver.func1.1
	github.com/gravitational/teleport/lib/utils/fncache.go:135 github.com/gravitational/teleport/lib/utils.FnCacheGet[...].func1
	github.com/gravitational/teleport/lib/utils/fncache.go:199 github.com/gravitational/teleport/lib/utils.(*FnCache).get.func1
	runtime/asm_amd64.s:1598 runtime.goexit
User Message: Get &#34;https://xxxxxx.io:443/webapi/find&#34;: dial tcp xxx.xxx.xxx.xxx:443: i/o timeout] localCluster: targetCluster:xxxxxx.io reversetunnel/agentpool.go:275
2023-07-19T10:26:22Z [PROXY:AGE] DEBU Runtime config: tunnel_strategy: agent_mesh connection_count: 1 localCluster: targetCluster:xxxxxx.io reversetunnel/agentpool.go:329
2023-07-19T10:26:22Z             DEBU Attempting GET xxxxxx.io:443/webapi/find webclient/webclient.go:129
2023-07-19T10:26:22Z [PROXY:AGE] DEBU Starting agent {xxxxxx.io:443 tcp } leaseID:81 target:xxxxxx.io:443 localCluster: targetCluster:xxxxxx.io reversetunnel/agent.go:299
2023-07-19T10:26:22Z [PROXY:AGE] DEBU Changing state initial -> connecting. leaseID:81 target:xxxxxx.io:443 localCluster: targetCluster:xxxxxx.io reversetunnel/agent.go:287
2023-07-19T10:26:22Z [HTTP:PROX] DEBU No proxy set in environment, returning direct dialer. proxy/proxy.go:195
2023-07-19T10:26:22Z [SQLITE]    WARN "SLOW TRANSACTION: 1.417283443s, goroutine 43 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x65\ngithub.com/gravitational/teleport/lib/backend/lite.(*Backend).inTransaction.func1()\n\tgithub.com/gravitational/teleport/lib/backend/lite/lite.go:938 +0x5b\ngithub.com/gravitational/teleport/lib/backend/lite.(*Backend).inTransaction(0xc0015b1810, {0x8d3ce00, 0xc001591a90}, 0xc001757e88)\n\tgithub.com/gravitational/teleport/lib/backend/lite/lite.go:989 +0x230\ngithub.com/gravitational/teleport/lib/backend/lite.(*Backend).removeExpiredKeys(0xc0015b1810)\n\tgithub.com/gravitational/teleport/lib/backend/lite/periodic.go:76 +0xe5\ngithub.com/gravitational/teleport/lib/backend/lite.(*Backend).runPeriodicOperations(0xc0015b1810)\n\tgithub.com/gravitational/teleport/lib/backend/lite/periodic.go:43 +0x116\ncreated by github.com/gravitational/teleport/lib/backend/lite.NewWithConfig\n\tgithub.com/gravitational/teleport/lib/backend/lite/lite.go:253 +0x5ca\n." lite/lite.go:938
2023-07-19T10:26:27Z             INFO ALPN connection upgrade test failed for "xxxxxx.io:443": dial tcp 54.149.28.159:443: i/o timeout. client/alpn_conn_upgrade.go:83
2023-07-19T10:26:27Z [HTTP:PROX] DEBU No proxy set in environment, returning direct dialer. proxy/proxy.go:195
2023-07-19T10:26:28Z [KUBERNETE] DEBU Attempting to restart watch after waiting 10.757848231s. pid:7.1 resource-kind:lock services/watcher.go:239
2023-07-19T10:26:28Z [KUBERNETE] WARN Restart watch on error: connection error: desc = "transport: Error while dialing: failed to dial: Get \"https://xxxxxx.io:443/webapi/find\": dial tcp xxx.xxx.xxx.xxx:443: i/o timeout". pid:7.1 resource-kind:lock services/watcher.go:246
2023-07-19T10:26:28Z [KUBERNETE] DEBU Starting watch. pid:7.1 resource-kind:lock services/watcher.go:210
2023-07-19T10:26:38Z [PROXY:AGE] DEBU Aborting SSH handshake because the proxy "f
```

**Comment by webvictim** [comment]
I don't think this is a Teleport issue. The `dial tcp xxx.xxx.xxx.xxx:443: i/o timeout` error means that the agent isn't even able to actually connect to the load balancer or service which is in front of the Teleport proxies.

How do you have Teleport deployed here? Are you using a Kubernetes `LoadBalancer`? What annotations do you have on your Kubernetes `Service`? What sort of load balancer has been provisioned in AWS?

**Comment by webvictim** [comment]
If your proxy replicas are constantly reporting their state as unhealthy, I would speculate that you have bigger problems in your cluster than the traffic. What size are the nodes for your Kubernetes cluster and how many pods/workloads are you running? It sounds like the cluster is very overloaded.

**Comment by zmb3** [comment]
Closing due to inactivity
