### ISSUE TITLE
Apps may not display in the UI when displaying certain Okta applications

### ISSUE THREAD

**Issue by mdwn** [gravitational/teleport#29372]
Expected behavior:

Apps in the UI don't return an error.

Current behavior:

Apps in the UI display an error if a corresponding user group lookup fails, which can happen when the user doesn't have access to lookup the group in the backend. User groups are only populated for Okta applications.

Bug details:
- Teleport version 13.2.3
- Recreation step

Create an Okta service.
Import apps which are associated with a number of user groups.
Try to display apps where the user has access to the application but only a subset of the app's associated user groups.

- Debug logs

```
Jul 19 18:45:13 ip-172-31-22-213 teleport[306515]: 2023-07-19T18:45:13Z ERRO [PROXY:SER] "proxy2023/07/19 18:45:13 http: panic serving 99.82.195.46:63188: ru
ntime error: invalid memory address or nil pointer dereference\ngoroutine 4854426 [running]:\nnet/http.(*conn).serve.func1()\n\tnet/http/server.go:1854 +0xbf
\npanic({0x6f153e0, 0xd0a8c70})\n\truntime/panic.go:890 +0x263\ngithub.com/gravitational/teleport/lib/web/ui.MakeApps({{0xc00276ac8c, 0x4}, {0xc0016985c0, 0x
15}, {0xc0012d39fc, 0x4}, {0xc00513f960, 0x1, 0x1}, 0xc00468e930, ...})\n\tgithub.com/gravitational/teleport/lib/web/ui/app.go:90 +0x5b0\ngithub.com/gravitat
ional/teleport/lib/web.(*Handler).clusterAppsGet(0xc0030bca80, {0x9bba8c3e45348b01?, 0x0?}, 0xc003c01500, {0x577fc7?, 0x10?, 0x6a88720?}, 0xc003afd600?, {0x9
222c50, 0xc0030c0bb0})\n\tgithub.com/gravitational/teleport/lib/web/apps.go:104 +0x9d8\ngithub.com/gravitational/teleport/lib/web.(*Handler).WithClusterAuth.
func1({0x91fd660, 0xc00312c5a0}, 0x3?, {0xc00312c600, 0x1, 0x3})\n\tgithub.com/gravitational/teleport/lib/web/apiserver.go:3500 +0xe5\ngithub.com/gravitation
al/teleport/lib/httplib.MakeHandlerWithErrorWriter.func1({0x91fd660, 0xc00312c5a0}, 0xc001f600e0?, {0xc00312c600, 0x1, 0x3})\n\tgithub.com/gravitational/tele
port/lib/httplib/httplib.go:117 +0x9e\ngithub.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc0030bca98, {0x91fd660, 0xc00312c5a0}, 0xc003c01500)\n\tgith
ub.com/julienschmidt/httprouter@v1.3.0/router.go:399 +0x85c\nnet/http.StripPrefix.func1({0x91fd660, 0xc00312c5a0}, 0xc003c01400)\n\tnet/http/server.go:2165 +
0x332\nnet/http.HandlerFunc.ServeHTTP(0x7bfa6f3?, {0x91fd660?, 0xc00312c5a0?}, 0xc0030bca80?)\n\tnet/http/server.go:2122 +0x2f\ngithub.com/gravitational/tele
port/lib/web.NewHandler.func1({0x91fd660, 0xc00312c5a0}, 0xc003c01400)\n\tgithub.com/gravitational/teleport/lib/web/apiserver.go:418 +0x686\nnet/http.Handler
Func.ServeHTTP(0x6e07860?, {0x91fd660?, 0xc00312c5a0?}, 0x3?)\n\tnet/http/server.go:2122 +0x2f\ngithub.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc00
30bca98, {0x91fd660, 0xc00312c5a0}, 0xc003c01400)\n\tgithub.com/julienschmidt/httprouter@v1.3.0/router.go:460 +0x669\ngithub.com/gravitational/teleport/lib/w
eb.(*APIHandler).ServeHTTP(0xc00072b530, {0x91fd660, 0xc00312c5a0}, 0xc003c01400)\n\tgithub.com/gravitational/teleport/lib/web/apiserver.go:294 +0x10b\ngithu
b.com/gravitational/oxy/ratelimit.(*TokenLimiter).ServeHTTP(0xc001a6c780, {0x91fd660, 0xc00312c5a0}, 0xc003c01400)\n\tgithub.com/gravitational/oxy@v0.0.0-202
21029012416-9fbf4c444680/ratelimit/tokenlimiter.go:118 +0x1ce\ngithub.com/gravitational/oxy/connlimit.(*ConnLimiter).ServeHTTP(0xc001e5ad20, {0x91fd660, 0xc0
0312c5a0}, 0xc003afd4a0?)\n\tgithub.com/gravitational/oxy@v0.0.0-20221029012416-9fbf4c444680/connlimit/connlimit.go:75 +0x31d\ngithub.com/gravitational/telep
ort/lib/httplib.MakeTracingHandler.func1({0x91fd660, 0xc00312c5a0}, 0xc003c01400)\n\tgithub.com/gravitational/teleport/lib/httplib/httplib.go:94 +0x1ad\nnet/
http.HandlerFunc.ServeHTTP(0x91fe028?, {0x91fd660?, 0xc00312c5a0?}, 0x915c410?)\n\tnet/http/server.go:2122 +0x2f\ngo.opentelemetry.io/contrib/instrumentation
/net/http/otelhttp.(*Handler).ServeHTTP(0xc003006840, {0x91fb110?, 0xc001af70a0}, 0xc002531400)\n\tgo.opentelemetry.io/contrib/instrumentation/net/http/otelh
ttp@v0.40.0/handler.go:213 +0x1231\nnet/http.serverHandler.ServeHTTP({0xc003f78e70?}, {0x91fb110, 0xc001af70a0}, 0xc002531400)\n\tnet/http/server.go:2936 +0x
316\nnet/http.(*conn).serve(0xc003ca3320, {0x91fe028, 0xc003f78e10})\n\tnet/http/server.go:1995 +0x612\ncreated by net/http.(*Server).Serve\n\tnet/http/serve
```

**Comment by mdwn** [comment]
Fixed by https://github.com/gravitational/teleport/pull/29325, which is already checked in. Wanted to file this issue to make sure it was tracked.
