### ISSUE TITLE
Discovery service panics on GKE clusters without labels

### ISSUE THREAD

**Issue by vkhromov** [gravitational/teleport#30619]
Expected behavior:
Teleport's discovery service handles a GKE cluster without labels

Current behavior:
Teleport crashes with the following message:
```
panic: assignment to entry in nil map
goroutine 363 [running]:
github.com/gravitational/teleport/lib/services.labelsFromGCPKubeCluster(...)
        github.com/gravitational/teleport/lib/services/kubernetes.go:260
github.com/gravitational/teleport/lib/services.NewKubeClusterFromGCPGKE({{0xc0024572b8, 0x4}, {0x0, 0x0}, {0xc002457560, 0xc}, {0xc00159a198, 0x17}, 0x2, 0x0})
        github.com/gravitational/teleport/lib/services/kubernetes.go:235 +0x1dc
github.com/gravitational/teleport/lib/srv/discovery/fetchers.(*gkeFetcher).getMatchingKubeCluster(0xc001580190, {{0xc0024572b8, 0x4}, {0x0, 0x0}, {0xc002457560, 0xc}, {0xc00159a198, 0x17}, 0x2, ...})
        github.com/gravitational/teleport/lib/srv/discovery/fetchers/gke.go:137 +0x58
github.com/gravitational/teleport/lib/srv/discovery/fetchers.(*gkeFetcher).getGKEClusters(0xc001580190, {0x98466c0?, 0xc0015806e0?})
        github.com/gravitational/teleport/lib/srv/discovery/fetchers/gke.go:96 +0x145
github.com/gravitational/teleport/lib/srv/discovery/fetchers.(*gkeFetcher).Get(0x0?, {0x98466c0?, 0xc0015806e0?})
        github.com/gravitational/teleport/lib/srv/discovery/fetchers/gke.go:82 +0x3b
github.com/gravitational/teleport/lib/srv/discovery/common.(*Watcher).fetchAndSend.func1()
        github.com/gravitational/teleport/lib/srv/discovery/common/watcher.go:129 +0x70
golang.org/x/sync/errgroup.(*Group).Go.func1()
        golang.org/x/sync@v0.3.0/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
        golang.org/x/sync@v0.3.0/errgroup/errgroup.go:72 +0xa5
```

Bug details:
- Teleport version: both `v13.3.2` and `master`
- Recreation steps: create a GKE cluster without the labels, in `/etc/teleport.yaml` add `discovery_service` section for GKE, and launch Teleport.
- Debug logs: see above.

**Comment by vkhromov** [comment]
Could be fixed by #30618
