### ISSUE TITLE
`TestChaosUpload` flakiness

### ISSUE THREAD

**Issue by zmb3** [gravitational/teleport#33099]
#### Link(s) to logs

- https://github.com/gravitational/teleport/actions/runs/6436546168/job/17480093775

#### Relevant snippet

```
{"caller":"filesessions/fileasync.go:283","component":"upload","level":"debug","message":"Scan is skipping recording 95c94596-9c0d-4579-ba78-c1e079ee3c34.tar that is locked by another process.","timestamp":"2023-10-06T21:17:11Z"}
{"caller":"filesessions/fileasync.go:460","component":"upload","error":"failed to create stream","level":"warning","message":"Upload failed.","timestamp":"2023-10-06T21:17:11Z"}
{"caller":"filesessions/fileasync.go:283","component":"upload","level":"debug","message":"Scan is skipping recording 95c94596-9c0d-4579-ba78-c1e079ee3c34.tar that is locked by another process.","timestamp":"2023-10-06T21:17:11Z"}
{"caller":"filesessions/fileasync.go:283","component":"upload","level":"debug","message":"Scan is skipping recording a120e7cc-28b2-47a9-98b1-e47bb627fb12.tar that is locked by another process.","timestamp":"2023-10-06T21:17:11Z"}
{"caller":"filesessions/fileasync.go:283","component":"upload","level":"debug","message":"Scan is skipping recording a120e7cc-28b2-47a9-98b1-e47bb627fb12.tar that is locked by another process.","timestamp":"2023-10-06T21:17:11Z"}
{"caller":"filesessions/fileasync.go:283","component":"upload","level":"debug","message":"Scan is skipping recording bc9852b4-2f15-484e-9ed2-95f721529d00.tar that is locked by another process.","timestamp":"2023-10-06T21:17:11Z"}
{"caller":"filesessions/fileasync.go:283","component":"upload","level":"debug","message":"Scan is skipping recording bc9852b4-2f15-484e-9ed2-95f721529d00.tar that is locked by another process.","timestamp":"2023-10-06T21:17:11Z"}
{"caller":"filesessions/fileasync.go:283","component":"upload","level":"debug","message":"Scan is skipping recording 95c94596-9c0d-4579-ba78-c1e079ee3c34.tar that is locked by another process.","timestamp":"2023-10-06T21:17:11Z"}
{"caller":"filesessions/fileasync.go:283","component":"upload","level":"debug","message":"Scan is skipping recording d49505b5-4e36-4d0d-a7a2-b967ecf8a068.tar that is locked by another process.","timestamp":"2023-10-06T21:17:11Z"}
    fileasync_chaos_test.go:182: 
        	Error Trace:	/__w/teleport/teleport/lib/events/filesessions/fileasync_chaos_test.go:182
        	Error:      	Received unexpected error:
        	            	could not acquire file lock for "/tmp/TestChaosUpload1617912356/001/95c94596-9c0d-4579-ba78-c1e079ee3c34.tar"
        	            		could not acquire lock on the file at this time
        	Test:       	TestChaosUpload
```

**Comment by zmb3** [comment]
https://github.com/gravitational/teleport/actions/runs/6436546168/job/17480093775

**Comment by zmb3** [comment]
Different error at https://github.com/gravitational/teleport/actions/runs/6532400059/job/17735495302

```
{"caller":"filesessions/fileasync.go:300","component":"upload","level":"debug","message":"Scanned 18 uploads, started 18, found 0 corrupted in /tmp/TestChaosUpload2291559035/001.","timestamp":"2023-10-16T10:38:19Z"}
    fileasync_chaos_test.go:212: 
        	Error Trace:	/__w/teleport/teleport/lib/events/filesessions/fileasync_chaos_test.go:212
        	Error:      	Not equal: 
        	            	expected: 4098
        	            	actual  : 0
        	Test:       	TestChaosUpload
        	Messages:   	event: {e4355040-c8b6-42bd-a042-9d8f815141b0 c6fcd8f4-215f-4526-9f06-97df57ce4bfe <nil> 0001-01-01 00:00:00 +0000 UTC}
```

**Comment by zmb3** [comment]
New flakes

- https://github.com/gravitational/teleport/actions/runs/9471562428/job/26095056939
- https://github.com/gravitational/teleport/actions/runs/9471583787/job/26095127554
- https://github.com/gravitational/teleport/actions/runs/9471705078/job/26095539388

```
    fileasync_chaos_test.go:171: 
        	Error Trace:	/__w/teleport/teleport/lib/events/filesessions/fileasync_chaos_test.go:171
        	Error:      	Received unexpected error:
        	            	could not acquire file lock for "/tmp/TestChaosUpload3766249775/001/d27b437c-1bdc-4033-8993-a33ffd60f6a5.tar"
        	            		could not acquire lock on the file at this time
        	Test:       	TestChaosUpload
```

**Comment by greedy52** [comment]
Run into this back-to-back:
 - https://github.com/gravitational/teleport/actions/runs/9502114262/job/26189320288
 - https://github.com/gravitational/teleport/actions/runs/9501923969/job/26188671287

**Comment by ravicious** [comment]
https://github.com/gravitational/teleport/actions/runs/9516771039/job/26233775055#step:6:786

**Comment by ibeckermayer** [comment]
v16, same lock error as above

https://github.com/gravitational/teleport/actions/runs/9586049321/job/26433207978

**Comment by ibeckermayer** [comment]
https://github.com/gravitational/teleport/actions/runs/9586281355/job/26433915335

**Comment by ravicious** [comment]
v15 https://github.com/gravitational/teleport/actions/runs/9601609355/job/26480549524
v16 https://github.com/gravitational/teleport/actions/runs/9601893528/job/26481450762

**Comment by Tener** [comment]
Another instance https://github.com/gravitational/teleport/actions/runs/9869750695/job/27254084334?pr=43993

```
=== FAIL: lib/events/filesessions TestChaosUpload (0.54s)
make: *** [Makefile:856: test-go-chaos] Error 1
make: *** Waiting for unfinished jobs....
{"caller":"filesessions/fileasync.go:196","component":"upload","level":"info","message":"uploader will scan /tmp/TestChaosUpload1493473856/001 every 3s","timestamp":"2024-07-10T07:12:30Z"}
{"caller":"filesessions/fileasync.go:298","component":"upload","level":"debug","message":"Scanned 4 uploads, started 4, found 0 corrupted in /tmp/TestChaosUpload1493473856/001.","timestamp":"2024-07-10T07:12:30Z"}
{"caller":"filesessions/fileasync.go:281","component":"upload","level":"debug","message":"Scan is skipping recording 07ba7367-5f67-4055-bb58-2e19b[678](https://github.com/gravitational/teleport/actions/runs/9869750695/job/27254084334?pr=43993#step:6:679)ead1.tar that is locked by another process.","timestamp":"2024-07-10T07:12:30Z"}
{"caller":"filesessions/fileasync.go:281","component":"upload","level":"debug","message":"Scan is skipping recording 44db35f7-b23d-4942-bed7-d22efa325846.tar that is locked by another process.","timestamp":"2024-07-10T07:12:30Z"}
{"caller":"filesessions/fileasync.go:281","component":"upload","level":"debug","message":"Scan is skipping recording 5dfcfc65-8add-4f6c-869a-0b376252feaa.tar that is locked by another process.","timestamp":"2024-07-10T07:12:30Z"}
{"caller":"filesessions/fileasync.go:281","component":"upload","level":"debug","message":"Scan is skipping recording b31c5d54-45a9-4faf-aee6-7d0d33418a5d.tar that is locked by another process.","timestamp":"2024-07-10T07:12:30Z"}
{"caller":"filesessions/fileasync.go:298","component":"upload","level":"debug","message":"Scanned 4 uploads, started 0, found 0 corrupted in /tmp/TestChaosUpload1493473856/001.","timestamp":"2024-07-10T07:12:30Z"}
{"caller":"filesessions/fileasync.go:465","component":"upload","error":"failed to create stream","level":"warning","message":"Upload failed.","session":"b31c5d54-45a9-4faf-aee6-7d0d33418a5d","timestamp":"2024-07-10T07:12:30Z"}
{"caller":"filesessions/fileasync.go:465","component":"upload","error":"failed to create stream","level":"warning","message":"Upload failed.","session":"07ba7367-5f67-4055-bb58-2e19b678ead1","timestamp":"2024-07-10T07:12:30Z"}
{"caller":"filesessions/fileasync.go:465","component":"upload","error":"failed to create stream","level":"warning","message":"Upload failed.","session":"44db35f7-b23d-4942-bed7-d22efa325846","timestamp":"2024-07-10T07:12:30Z"}
{"caller":"filesessions/fileasync.go:465","component":"upload","error":"failed to create stream","level":"warning","message":"Upload failed.","session":"5dfcfc65-8add-4f6c-869a-0b376252feaa","timestamp":"2024-07-10T07:12:30Z"}
{"caller":"filesessions/fileasync.go:298","component":"upload","level":"debug","message":"Scanned 4 uploads, started 4, found 0 corrupted in /tmp/TestChaosUpload1493473856/001.","timestamp":"2024-07-10T07:12:30Z"}
{"caller":"filesessions/fileasync.go:228","component":"upload","level":"warning","message":"Increasing session upload backoff due to error, will retry after 2.696697593s.","timestamp":"2024-07-10T07:12:30Z"}
{"caller":"filesessions/fileasync.go:228","component":"upload","level":"warning","message":"Increasing session upload backoff due to error, will retry after 5.365369537s.","timestamp":"2024-07-10T07:12:30Z"}
{"caller":"filesessions/fileasync.go:228","component":"upload","level":"warning","message":"Increasing session upload backoff due to error, will retry after 8.270141348s.","timestamp":"2024-07-10T07:12:30Z"}
{"caller":"filesessions/fileasync.go:228","component":"upload","level":"warning","message":"Increasing session upload backoff due to error, will retry after 11.816963592s.","timestamp":"2024-07-10T07:12:30Z"}
{"caller":"filesessions/fileasync.go:473","component":"upload","duration":10284270,"level":"debug","message":"Session upload completed.","session":"5dfcfc65-8add-4f6c-869a-0b376252feaa","timestamp":"2024-07-10T07:12:30Z"}
{"caller":"filesessions/fileasync.go:473","component":"upload","duration":16088712,"level":"debug","message":"Session upload completed.","session":"44db35f7-b23d-4942-bed7-d22efa325846","timestamp":"2024-07-10T07:12:30Z"}
{"caller":"filesessions/fileasync.go:473","component":"upload","duration":25034782,"level":"debug","message":"Session upload completed.","session":"07ba7367-5f67-4055-bb58-2e19b678ead1","timestamp":"2024-07-10T07:12:31Z"}
{"caller":"filesessions/fileasync_chaos_test.go:76","component":null,"level":"debug","message":"Terminating connection at event 701","timestamp":"2024-07-10T07:12:31Z"}
{"caller":"filesessions/fileasync.go:465","component":"upload","error":"connection terminated","level":"warning","message":"Upload failed.","session":"b31c5d54-45a9-4faf-aee6-7d0d33418a5d","timestamp":"2024-07-10T07:12:31Z"}
{"caller":"filesessions/fileasync.go:228","component":"upload","level":"warning","message":"Increasing session upload backoff due to error, will retry after 5.327808907s.","timestamp":"2024-07-10T07:12:31Z"}
    fileasync_chaos_test.go:187: 
        	Error Trace:	/__w/teleport/teleport/lib/events/filesessions/fileasync_chaos_test.go:187
        	Error:      	Not equal: 
        	            	expected: 4098
        	            	actual  : 0
        	Test:       	TestChaosUpload
        	Messages:   	event: {44db35f7-b23d-4942-bed7-d22efa325846 acc7d657-bb13-444b-afdf-042315efeaa9 <nil> 0001-01-01 00:00:00 +0000 UTC}

DONE 1 tests, 1 failure in 61.653s
```

**Comment by nklaassen** [comment]
Another new hit https://github.com/gravitational/teleport/actions/runs/9899495633/job/27348508602

**Comment by zmb3** [comment]
v16: https://github.com/gravitational/teleport/actions/runs/9944320156/job/27470134323

**Comment by GavinFrazar** [comment]
master: https://github.com/gravitational/teleport/actions/runs/9963965848/job/27531191205

```
    fileasync_chaos_test.go:187: 
        	Error Trace:	/__w/teleport/teleport/lib/events/filesessions/fileasync_chaos_test.go:187
        	Error:      	Not equal: 
        	            	expected: 4098
        	            	actual  : 0
        	Test:       	TestChaosUpload
        	Messages:   	event: {fc19b7f9-4a2c-4739-b2fd-aca8fbec639c ea23c703-0ee8-48f7-8eb8-6d36c362f17e <nil> 0001-01-01 00:00:00 +0000 UTC}
```

**Comment by dboslee** [comment]
https://github.com/gravitational/teleport/actions/runs/10460720846/job/28967501228
```
    fileasync_chaos_test.go:187: 
        	Error Trace:	/__w/teleport/teleport/lib/events/filesessions/fileasync_chaos_test.go:187
        	Error:      	Not equal: 
        	            	expected: 4098
        	            	actual  : 0
        	Test:       	TestChaosUpload
        	Messages:   	event: {836cf748-71d8-4996-b8e2-4b60840b3117 9da5ef40-7884-43e2-b511-86bbb174c78d <nil> 0001-01-01 00:00:00 +0000 UTC}
```

**Comment by nklaassen** [comment]
another one https://github.com/gravitational/teleport/actions/runs/10511727923/job/29123375212

**Comment by ravicious** [comment]
https://github.com/gravitational/teleport/actions/runs/10850988905/job/30113684110#step:6:800

**Comment by nklaassen** [comment]
had a bit of a look, I see lots of logs like this for the session ID that triggers the test failure:
```
{"caller":"filesessions/fileasync.go:281","component":"upload","level":"debug","message":"Scan is skipping recording e4cee587-cb2a-44e3-8f55-b24b059c744a.tar that is locked by another process.","timestamp":"2024-09-17T09:52:39-07:00"}
```
@rosstimothy this looks quite related to your last fix for this

**Comment by ptgott** [comment]
Another: https://github.com/gravitational/teleport/actions/runs/11348835620/job/31563554135#step:6:634

**Comment by hugoShaka** [comment]
https://github.com/gravitational/teleport/actions/runs/11635082092/job/32403673622?pr=48316

**Comment by hugoShaka** [comment]
https://github.com/gravitational/teleport/actions/runs/11688957859/job/32550621226?pr=48359#step:6:690

**Comment by hugoShaka** [comment]
https://github.com/gravitational/teleport/actions/runs/11827427618/job/32955545346?pr=48944#step:6:673

**Comment by hugoShaka** [comment]
https://github.com/gravitational/teleport/actions/runs/12166248956/job/33932050219#step:6:679

**Comment by hugoShaka** [comment]
```
    fileasync_chaos_test.go:186: 
        	Error Trace:	/__w/teleport/teleport/lib/events/filesessions/fileasync_chaos_test.go:186
        	Error:      	Not equal: 
        	            	expected: 4098
        	            	actual  : 0
        	Test:       	TestChaosUpload
        	Messages:   	event: {94742208-2ce3-454d-a48e-15abd61489e8 2f003403-40e0-4d24-a136-296e556d62b9 <nil> 0001-01-01 00:00:00 +0000 UTC}
```

https://github.com/gravitational/teleport/actions/runs/12323078201/job/34397988190#step:6:698

**Comment by nklaassen** [comment]
I got 2 hits today in merge queue to master https://github.com/gravitational/teleport/actions/runs/12758905393/job/35561760599

**Comment by nklaassen** [comment]
still hitting https://github.com/gravitational/teleport/actions/runs/13554874505/job/37886862420

**Comment by ravicious** [comment]
v17 https://github.com/gravitational/teleport/actions/runs/14107381138/job/39516975045#step:6:880

**Comment by ravicious** [comment]
v16 https://github.com/gravitational/teleport/actions/runs/17038798341/job/48297394535#step:6:900

```
    fileasync_chaos_test.go:187: 
        	Error Trace:	/__w/teleport/teleport/lib/events/filesessions/fileasync_chaos_test.go:187
        	Error:      	
        	Test:       	TestChaosUpload
        	Messages:   	event: {c9751da7-53f1-44bb-af2f-8a823461fd6f 06638a01-1150-4f1d-ab78-9f040a6dbcf4 <nil> 0001-01-01 00:00:00 +0000 UTC}
```

**Comment by kshi36** [comment]
merge queue to master https://github.com/gravitational/teleport/actions/runs/19148172340/job/54731188943#step:6:999
```
    fileasync_chaos_test.go:188: 
        	Error Trace:	/__w/teleport/teleport/lib/events/filesessions/fileasync_chaos_test.go:188
        	Error:      	
        	Test:       	TestChaosUpload
        	Messages:   	event: {e90ded9c-62a3-4600-bee6-e198e62d6210 c53774a4-c52c-43a0-99c6-44626abcd909 <nil> 0001-01-01 00:00:00 +0000 UTC}
```

**Comment by ravicious** [comment]
v17 https://github.com/gravitational/teleport/actions/runs/19296181628/job/55178597965#step:6:932

**Comment by kshi36** [comment]
master https://github.com/gravitational/teleport/actions/runs/19680451126/job/56372821089?pr=61787#step:6:2239
<details><summary>Details</summary>
<p>

```
panic: test timed out after 10m0s
	running tests:
		TestChaosUpload (10m0s)

goroutine 918 [running]:
testing.(*M).startAlarm.func1()
	/opt/go/src/testing/testing.go:2682 +0x345
created by time.goFunc
	/opt/go/src/time/sleep.go:215 +0x2d

goroutine 1 [chan receive, 10 minutes]:
testing.(*T).Run(0xc000383180, {0x292c7e3?, 0xc00091fb08?}, 0x2b33ac8)
	/opt/go/src/testing/testing.go:2005 +0x485
testing.runTests.func1(0xc000383180)
	/opt/go/src/testing/testing.go:2477 +0x37
testing.tRunner(0xc000383180, 0xc00091fc48)
	/opt/go/src/testing/testing.go:1934 +0xea
testing.runTests(0xc0003c01f8, {0x45cf480, 0x11, 0x11}, {0x0?, 0x0?, 0x46010a0?})
	/opt/go/src/testing/testing.go:2475 +0x4b4
testing.(*M).Run(0xc0003479a0)
	/opt/go/src/testing/testing.go:2337 +0x63a
github.com/gravitational/teleport/lib/events/filesessions.TestMain(0xc0003479a0)
	/__w/teleport/teleport/lib/events/filesessions/fileuploader_test.go:37 +0x29
main.main()
	_testmain.go:79 +0xa5

goroutine 42 [select, 9 minutes]:
github.com/gravitational/teleport/lib/events/filesessions.TestChaosUpload(0xc000383340)
	/__w/teleport/teleport/lib/events/filesessions/fileasync_chaos_test.go:181 +0xabd
testing.tRunner(0xc000383340, 0x2b33ac8)
	/opt/go/src/testing/testing.go:1934 +0xea
created by testing.(*T).Run in goroutine 1
	/opt/go/src/testing/testing.go:1997 +0x465

goroutine 43 [select]:
github.com/gravitational/teleport/lib/events/filesessions.(*Uploader).Serve(0xc000000460, {0x2dbee28, 0xc00060e910})
	/__w/teleport/teleport/lib/events/filesessions/fileasync.go:221 +0x525
created by github.com/gravitational/teleport/lib/events/filesessions.TestChaosUpload in goroutine 42
	/__w/teleport/teleport/lib/events/filesessions/fileasync_chaos_test.go:123 +0x66b
```

</p>
</details>

**Comment by nklaassen** [comment]
got a 10 minute timeout https://github.com/gravitational/teleport/actions/runs/19746142362/job/56580687605?pr=61837

**Comment by kshi36** [comment]
v18 https://github.com/gravitational/teleport/actions/runs/19831846802/job/56819632425#step:6:2120

**Comment by ravicious** [comment]
timeout https://github.com/gravitational/teleport/actions/runs/19856015934/job/56894011007#step:6:2247

**Comment by Tener** [comment]
another timeout https://github.com/gravitational/teleport/actions/runs/19887448139/job/56999230905

**Comment by Tener** [comment]
@Joerger this timeout looks to be much more frequent these days. I wonder if the encrypted recordings changes made the underlying issue more visible?

**Comment by ravicious** [comment]
v18 timeout https://github.com/gravitational/teleport/actions/runs/19900110949/job/57041227425#step:6:2117

**Comment by ravicious** [comment]
https://github.com/gravitational/teleport/actions/runs/20024925984/job/57420008426?pr=61881#step:6:2249

**Comment by ravicious** [comment]
v18 https://github.com/gravitational/teleport/actions/runs/20026571031/job/57425208478?pr=62052#step:6:2081

**Comment by strideynet** [comment]
I feel like I'm hitting this timing out multiple times in a row in the merge queue 😓 

- v18: https://github.com/gravitational/teleport/actions/runs/20095352914/job/57652282322?pr=62120

**Comment by ravicious** [comment]
master https://github.com/gravitational/teleport/actions/runs/20096550064/job/57656343454?pr=62096#step:6:2215

**Comment by ravicious** [comment]
v18 https://github.com/gravitational/teleport/actions/runs/20137174248/job/57793651829#step:6:2130

**Comment by ravicious** [comment]
Not reopening yet, but I was hit with [a flake on v17](https://github.com/gravitational/core/actions/runs/34849629526/job/103993995936#step:6:1047) despite the fact that https://github.com/gravitational/teleport/pull/62189 was backported as https://github.com/gravitational/teleport/pull/64501.

```
    fileasync_chaos_test.go:174: 
        	Error Trace:	/__w/core/core/lib/events/filesessions/fileasync_chaos_test.go:174
        	Error:      	
        	Test:       	TestChaosUpload
        	Messages:   	event: {6e16529a-fc88-4e6e-bd35-c7cad2377e89 5df11269-8e35-41e1-883a-72278181e0f2 <nil> 0001-01-01 00:00:00 +0000 UTC}
```
