### ISSUE TITLE
Connection to Teleport with Redshift driver doesn't with with DBeaver or DBVisualizer

### ISSUE THREAD

**Issue by khpatelupgrade** [gravitational/teleport#34897]
Expected behavior:

The connection to Redshift instance via Teleport only works when using postgres driver. However, using Redshift driver should work but it doesn't

Current behavior:

We get an error `javax.net.ssl.SSLHandshakeException: Received fatal alert: certificate_required` when connecting with Redshift driver. We're using SSL connection with the sslrootcert, sslcert and sslkey properties. The connection through postgres driver works with these SSL settings.

```
ssl=true
sslkey=~/.tsh/keys/access.upgrade.com/khpatel@upgrade.com
sslrootcert=~/.tsh/keys/access.upgrade.com/cas/access.upgrade.com.pem
sslcert=~/.tsh/keys/access.upgrade.com/cas/rs-edw.pem&sslmode=verify-full
```

Bug details:
- Teleport version
- Teleport v13.3.8 git: go1.21.0

- Recreation steps
- Debug logs

```
Product: DbVisualizer Pro 23.2.3 (build: 3853)
OS: Mac OS X
OS Version: 13.6
OS Arch: x86_64
Java Version: 17.0.7
Java VM: OpenJDK 64-Bit Server VM
Java Vendor: Eclipse Adoptium
Java Home: /Applications/DbVisualizer.app/Contents/Resources/jre.bundle/Contents/Home
DbVis Home: /Applications/DbVisualizer.app/Contents/Resources/app
User Home: /Users/khpatel
PrefsDir: /Users/khpatel/.dbvis
SessionId: 667
BindDir: /Users/khpatel/.dbvis/[0]

An error occurred while establishing the connection:

Long Message:
The connection attempt failed.

Details:
   Type: java.sql.SQLException
   SQL State: 08001

Stack Trace:
javax.net.ssl.SSLHandshakeException: Received fatal alert: certificate_required
   at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
   at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
   at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:365)
   at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293)
   at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:204)
   at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
   at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1513)
   at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1484)
   at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1069)
   at com.amazon.redshift.core.CompressedInputStream.readFromNetwork(CompressedInputStream.java:336)
   at com.amazon.redshift.core.CompressedInputStream.tryReadMessage(CompressedInputStream.java:166)
   at com.amazon.redshift.core.CompressedInputStream.read(CompressedInputStream.java:387)
   at com.amazon.redshift.core.VisibleBufferedInputStream.readMore(VisibleBufferedInputStream.java:167)
   at com.amazon.redshift.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:134)
   at com.amazon.redshift.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:119)
   at com.amazon.redshift.core.VisibleBufferedInputStream.read(VisibleBufferedInputStream.java:79)
   at com.amazon.redshift.core.RedshiftStream.receiveChar(RedshiftStream.java:440)
   at com.amazon.redshift.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:682)
   at com.amazon.redshift.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:128)
   at com.amazon.redshift.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:239)
   at com.amazon.redshift.core.ConnectionFactory.openConnection(ConnectionFactory.java:51)
   at com.amazon.redshift.jdbc.RedshiftConnectionImpl.<init>(RedshiftConnectionImpl.java:353)
   at com.amazon.redshift.Driver.makeConnection(Driver.java:481)
   at com.amazon.redshift.Driver.connect(Driver.java:302)
[wrapped] java.sql.SQLException: The connection attempt failed.
   at com.amazon.redshift.util.RedshiftException.getSQLException(RedshiftException.java:56)
   at com.amazon.redshift.Driver.connect(Driver.java:326)
   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
   at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   at java.base/java.lang.reflect.Method.invoke(Method.java:568)
   at com.onseven.dbvis.jdbc.b.e.b(Z:525)
   at com.onseven.dbvis.jdbc.b.g$_b.call(Z:618)
   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
   at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by greedy52** [comment]
duplicate of https://github.com/gravitational/teleport/issues/29417
