### ISSUE TITLE
Connect: Tab with cluster resources opened in v14 crashes after upgrade to v15

### ISSUE THREAD

**Issue by ravicious** [gravitational/teleport#36936]
```
[19-01-24 17:21:40] [UI] error: TypeError: Cannot read properties of undefined (reading 'h2')
    at a (file:///Users/rav/Downloads/teleport-v15-alpha.5/Teleport%20Connect.app/Contents/Resources/app.asar/build/app/dist/renderer/app.d3ac6869373a339d6f83.js:1:416739)
    at _e (file:///Users/rav/Downloads/teleport-v15-alpha.5/Teleport%20Connect.app/Contents/Resources/app.asar/build/app/dist/renderer/36.544a5f6d328abd06d990.js:2:624603)
    at e.generateAndInjectStyles (file:///Users/rav/Downloads/teleport-v15-alpha.5/Teleport%20Connect.app/Contents/Resources/app.asar/build/app/dist/renderer/36.544a5f6d328abd06d990.js:2:621685)
    at file:///Users/rav/Downloads/teleport-v15-alpha.5/Teleport%20Connect.app/Contents/Resources/app.asar/build/app/dist/renderer/36.544a5f6d328abd06d990.js:2:627616
    at file:///Users/rav/Downloads/teleport-v15-alpha.5/Teleport%20Connect.app/Contents/Resources/app.asar/build/app/dist/renderer/36.544a5f6d328abd06d990.js:2:627647
    at D (file:///Users/rav/Downloads/teleport-v15-alpha.5/Teleport%20Connect.app/Contents/Resources/app.asar/build/app/dist/renderer/36.544a5f6d328abd06d990.js:2:628033)
    at Cs (file:///Users/rav/Downloads/teleport-v15-alpha.5/Teleport%20Connect.app/Contents/Resources/app.asar/build/app/dist/renderer/36.544a5f6d328abd06d990.js:2:434724)
    at Sa (file:///Users/rav/Downloads/teleport-v15-alpha.5/Teleport%20Connect.app/Contents/Resources/app.asar/build/app/dist/renderer/36.544a5f6d328abd06d990.js:2:444773)
    at Cu (file:///Users/rav/Downloads/teleport-v15-alpha.5/Teleport%20Connect.app/Contents/Resources/app.asar/build/app/dist/renderer/36.544a5f6d328abd06d990.js:2:493603)
    at bl (file:///Users/rav/Downloads/teleport-v15-alpha.5/Teleport%20Connect.app/Contents/Resources/app.asar/build/app/dist/renderer/36.544a5f6d328abd06d990.js:2:480708)
```

```javascript
        function a(e) {
            const {typography: t, theme: M} = e;
            return D(D(D(D(D({}, M.typography[t]), function(e) {
                return e.caps ? {
                    textTransform: "uppercase"
                } : null
            }(e)), function(e) {
                return e.breakAll ? {
                    wordBreak: "break-all"
                } : null
            }(e)), function(e) {
                return e.bold ? {
                    fontWeight: e.theme.fontWeights.bold
                } : null
            }(e)), function(e) {
                return e.mono ? {
                    fontFamily: e.theme.fonts.mono
                } : null
            }(e))
```

Presumably this fails at `M.typography["h2"]`.

**Comment by ravicious** [comment]
This is probably [`<Empty>`](https://github.com/gravitational/teleport/blob/7e2f4924af086a5d92867a3a940a9dfa339ce242/web/packages/teleport/src/components/Empty/Empty.tsx) being rendered, but why is `typography` not available?

**Comment by ravicious** [comment]
No wait, it cannot be this `<Empty>`, it's only used in teleport.

**Comment by ravicious** [comment]
There's not that many components with `typography="h2"`.

```
$ rg "typography.*\bh2\b" -g '!*.story.*'
e/web/teleport/src/Welcome/Questionnaire/Questionnaire.tsx
159:          <Text typography="h2" mb={4}></Text>

web/packages/teleport/src/HeadlessRequest/Cards.tsx
28:        <Text typography="h2" mb="4">

web/packages/teleport/src/components/MfaDeviceList/RemoveDialog/RemoveDialog.tsx
37:        <Text typography="h2" mb={2}>

web/packages/teleport/src/components/Empty/Empty.tsx
69:        <Text typography="h2" mb="3">

web/packages/design/src/CardSuccess/CardSuccess.jsx
30:        <Text typography="h2" mb="4">

web/packages/design/src/CardError/CardError.jsx
40:  <Text typography="h2" mb={4} textAlign="center" children={props.children} />
```

**Comment by ravicious** [comment]
I did run into problems with theme not being properly passed in the past: https://github.com/gravitational/teleport/pull/29046

Maybe there's some other error happening here, we catch it and then `FailedApp` cannot render it?

**Comment by ravicious** [comment]
Though I don't think we render `FailedApp` on unhandled rejections so that's probably not it.

**Comment by ravicious** [comment]
```
Uncaught TypeError: Cannot read properties of undefined (reading 'map')
    at updateStateFromQueryParams (SearchContext.tsx:66:46)
    at SearchContextProvider (SearchContext.tsx:79:13)
    at renderWithHooks (react-dom.development.js:16305:18)
    at updateFunctionComponent (react-dom.development.js:19583:20)
    at beginWork (react-dom.development.js:21596:16)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at beginWork$1 (react-dom.development.js:27446:7)
    at performUnitOfWork (react-dom.development.js:26552:12)
```

```javascript
    function updateStateFromQueryParams(queryParams) {
        setActivePicker(actionPicker);
        setInputValue(queryParams.search);
        setAdvancedSearchEnabled(queryParams.advancedSearchEnabled);
        setFilters(queryParams.resourceKinds.map(resourceType => ({
            filter: 'resource-type',
            resourceType,
        })));
    }
```

`CatchError` catches this and then tries to render `Failed`. `Failed` doesn't have access to a theme, because `ThemeProvider` is defined below `CatchError`. We have to change `CatchError` so that it renders `Failed` with `StaticThemeProvider`, just like `FailedApp`.

**Comment by ravicious** [comment]
I have a fix for the `CatchError` part on `r7s/failed-app-theme`, I'll push a PR on Monday.
