### ISSUE TITLE
Kube access test panic

### ISSUE THREAD

**Issue by zmb3** [gravitational/teleport#37884]
## Failure

Hard to say exactly which test failed, as there are a lot of failures in this run, but the panic doesn't look good.

#### Link(s) to logs

https://github.com/gravitational/teleport/actions/runs/7718611520/job/21040254286

#### Relevant snippet

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xc224b32]

goroutine 13440 [running]:
testing.tRunner.func1.2({0xd816540, 0x150779d0})
	/opt/go/src/testing/testing.go:1545 +0x3f7
testing.tRunner.func1()
	/opt/go/src/testing/testing.go:1548 +0x716
panic({0xd816540?, 0x150779d0?})
	/opt/go/src/runtime/panic.go:920 +0x270
github.com/gravitational/teleport/lib/kube/proxy.(*TLSServer).close(0xc00e8fdc00, {0x105f2298, 0xc00acb0aa0})
	/__w/teleport/teleport/lib/kube/proxy/server.go:408 +0x512
github.com/gravitational/teleport/lib/kube/proxy.(*TLSServer).Close(0xc00e8fdc00)
	/__w/teleport/teleport/lib/kube/proxy/server.go:372 +0x53
github.com/gravitational/teleport/lib/web.startKube.func1()
	/__w/teleport/teleport/lib/web/apiserver_test.go:8472 +0x45
testing.(*common).Cleanup.func1()
	/opt/go/src/testing/testing.go:1169 +0x197
testing.(*common).runCleanup(0xc005b124e0, 0x0)
	/opt/go/src/testing/testing.go:1347 +0x219
testing.tRunner.func2()
	/opt/go/src/testing/testing.go:1589 +0x51
testing.tRunner(0xc005b124e0, 0xe98aa38)
	/opt/go/src/testing/testing.go:1601 +0x295
created by testing.(*T).Run in goroutine 1
	/opt/go/src/testing/testing.go:1648 +0x846
```

**Comment by tigrato** [comment]
The test that failed can be either `TestDiagnoseKubeConnection` or any test that uses `createProxy` in `lib/web/apiserver_test.go` but I don't think that panic is the root cause.

In kube, when we create the server we don't pass the `listener`. We only pass it at runtime with `server.Serve(listener)` in a separate goroutine. 

https://github.com/gravitational/teleport/blob/60583da630fc0592aba796c80f053464e48125a0/lib/web/apiserver_test.go#L8643-L8651

Then, when you close the server, we assume the listener was populated and we try to close it, but in this case the listener is `nil` and it panics. 

https://github.com/gravitational/teleport/blob/4d24ff40e3672518022fcc130be7549315e1e839/lib/kube/proxy/server.go#L407-L409

This means that the cleanup function triggered by `t.Cleanup` executed before the spawned goroutine that calls  `Serve` executed and the test panic. We should add a protection to it to avoid the panic in close but this is not the root cause of the issue. Something different than this panic caused the test to fail which triggered the cleanup routine out of order.
