### ISSUE TITLE
Failed to find WebAuthNGetApiVersionNumber procedure in WebAuthn.dll: The specified procedure could not be found.

### ISSUE THREAD

**Issue by jayvee359** [gravitational/teleport#38599]
Expected behavior:
Start normally

Current behavior:
panic: Failed to find WebAuthNGetApiVersionNumber procedure in WebAuthn.dll: The specified procedure could not be found.

goroutine 1 [running]:
golang.org/x/sys/windows.(*LazyProc).mustFind(...)
        C:/Users/runneradmin/go/pkg/mod/golang.org/x/sys@v0.16.0/windows/dll_windows.go:325
golang.org/x/sys/windows.(*LazyProc).Addr(...)
        C:/Users/runneradmin/go/pkg/mod/golang.org/x/sys@v0.16.0/windows/dll_windows.go:333
github.com/gravitational/teleport/lib/auth/webauthnwin.webAuthNGetApiVersionNumber()
        C:/a/teleport.e/teleport.e/lib/auth/webauthnwin/zsyscall_windows.go:83 +0xb4
github.com/gravitational/teleport/lib/auth/webauthnwin.newNativeImpl()
        C:/a/teleport.e/teleport.e/lib/auth/webauthnwin/webauthn_windows.go:65 +0xad
github.com/gravitational/teleport/lib/auth/webauthnwin.init()
        C:/a/teleport.e/teleport.e/lib/auth/webauthnwin/webauthn_windows.go:36 +0x169

Bug details:
- Teleport version 15.0.2
- Recreation steps
- Debug logs

OS info - Windows 10 LTSC Microsoft Windows [Version 10.0.17763.5458]

Probably the same issue as "Avoid tsh panic on Windows Server 2019 #38444" since LTSC versions seemed to have less updates and DLL changes than regular ones.

**Comment by codingllama** [comment]
Yes, that looks just like #38444. The next patch should fix it, otherwise give me a shout and I'll take another look.
