### ISSUE TITLE
tsh does not set the correct SNI when talking to auth server

### ISSUE THREAD

**Issue by awly** [gravitational/teleport#3870]
### Description

**What happened**:

Auth server uses SNI to match a client to the correct TLS CA for validation.
Client may have certs issued by a trusted cluster, so auth server can't always validate against its own CA.

If SNI match fails (it's empty or the format isn't correct), auth server validates client against all known CAs. The list of CA Subjects is sent during TLS handshake. The size of this list (in bytes) can't exceed `MaxUint16`, due to encoding defined in https://tools.ietf.org/html/rfc5246#section-7.4.4.

So, if client doesn't send the correct SNI and auth server has **many** trusted clusters, TLS handshake will fail.  

**What you expected to happen**:

Client sends the correct SNI for the cluster that issued its client cert.
Auth server never falls back to sending all CAs in TLS handshake.

**How to reproduce it (as minimally and precisely as possible)**:

Create an auth server with ~550 trusted clusters.
Run `tsh login` against the root cluster.

**Relevant Debug Logs If Applicable**

```
2020-06-18 09:42:08.688519 I | http: panic serving 127.0.0.1:12345: cryptobyte: pending child length 66235 exceeds 2-byte length prefix
goroutine 680382 [running]:
net/http.(*conn).serve.func1(0xc0027ae320)
        /opt/go/src/net/http/server.go:1767 +0x139
panic(0x1ccd560, 0xc0016bbe80)
        /opt/go/src/runtime/panic.go:679 +0x1b2
vendor/golang.org/x/crypto/cryptobyte.(*Builder).BytesOrPanic(...)
        /opt/go/src/vendor/golang.org/x/crypto/cryptobyte/builder.go:72
crypto/tls.(*certificateRequestMsgTLS13).marshal(0xc001107890, 0xc001d98000, 0x212, 0x212)
        /opt/go/src/crypto/tls/handshake_messages.go:1138 +0x30d
crypto/tls.(*serverHandshakeStateTLS13).sendServerCertificate(0xc001107aa8, 0x0, 0x0)
        /opt/go/src/crypto/tls/handshake_server_tls13.go:603 +0xf8
crypto/tls.(*serverHandshakeStateTLS13).handshake(0xc001107aa8, 0xc0002e4400, 0x0)
        /opt/go/src/crypto/tls/handshake_server_tls13.go:59 +0xc7
crypto/tls.(*Conn).serverHandshake(0xc001744a80, 0x1fe3470, 0xc000334700)
        /opt/go/src/crypto/tls/handshake_server.go:53 +0xe7
crypto/tls.(*Conn).Handshake(0xc001744a80, 0x0, 0x0)
        /opt/go/src/crypto/tls/conn.go:1364 +0x23a
net/http.(*conn).serve(0xc0027ae320, 0x2387420, 0xc00145f8f0)
        /opt/go/src/net/http/server.go:1783 +0x19d
created by net/http.(*Server).Serve
        /opt/go/src/net/http/server.go:2927 +0x38e
```

**Comment by awly** [comment]
This is fixed in 4.3 (still alpha) and 4.2.11 (releasing a bit later today).
