### ISSUE TITLE
Panic when running unit tests.

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#3923]
Saw the following panic when running unit tests.

```
panic: runtime error: invalid memory address or nil pointer dereference | 86s
98 | panic: runtime error: invalid memory address or nil pointer dereference | 86s
99 | [signal SIGSEGV: segmentation violation code=0x1 addr=0x90 pc=0x10bd77b] | 86s
100 |   | 86s
101 | goroutine 429 [running]: | 86s
102 | github.com/gravitational/teleport/lib/srv.(*Heartbeat).setState(...) | 86s
103 | /gopath/src/github.com/gravitational/teleport/lib/srv/heartbeat.go:270 | 86s
104 | github.com/gravitational/teleport/lib/srv.(*Heartbeat).reset(0x0, 0x0) | 86s
105 | /gopath/src/github.com/gravitational/teleport/lib/srv/heartbeat.go:277 +0x2b | 86s
106 | github.com/gravitational/teleport/lib/srv.(*Heartbeat).Run.func1(0x0) | 86s
107 | /gopath/src/github.com/gravitational/teleport/lib/srv/heartbeat.go:235 +0x34 | 86s
108 | panic(0x217dac0, 0x404cfc0) | 86s
109 | /opt/go/src/runtime/panic.go:679 +0x1b2 | 86s
110 | github.com/gravitational/teleport/lib/srv.(*Heartbeat).fetch(0x0, 0x952c468906d84fbe, 0x65534a8c40398f8a) | 86s
111 | /gopath/src/github.com/gravitational/teleport/lib/srv/heartbeat.go:294 +0x37 | 86s
112 | github.com/gravitational/teleport/lib/srv.(*Heartbeat).fetchAndAnnounce(0x0, 0x24cbd0e, 0x7) | 86s
113 | /gopath/src/github.com/gravitational/teleport/lib/srv/heartbeat.go:434 +0x2f | 86s
114 | github.com/gravitational/teleport/lib/srv.(*Heartbeat).Run(0x0, 0x0, 0x0) | 86s
115 | /gopath/src/github.com/gravitational/teleport/lib/srv/heartbeat.go:239 +0x85 | 86s
116 | created by github.com/gravitational/teleport/lib/srv/regular.(*Server).Serve | 86s
117 | /gopath/src/github.com/gravitational/teleport/lib/srv/regular/sshserver.go:281 +0x6e | 86s
118 | FAIL	github.com/gravitational/teleport/tool/tsh	3.740s | 86s
119 | ?   	github.com/gravitational/teleport/tool/tsh/common	[no test files] | 86s
120 | FAIL | 86s
121
```

See: https://drone.gravitational.io/gravitational/teleport/228

**Comment by webvictim** [comment]
I saw this again too. Also this message in the Drone logs stuck out:

`WARNING: the certificate has expired on 2017-06-11 07:27:06 +0000 UTC`

**Comment by zmb3** [comment]
This issue is old and doesn't have appropriate context as to what test was failing, so I'm going to close it out.
