### ISSUE TITLE
Teleport panic / SIGSEGV with PAM

### ISSUE THREAD

**Issue by jkendzorra** [gravitational/teleport#3956]
### Description

**What happened**:
Teleport crashed and closed three established connections in the process:
```
Jun 30 16:32:36 hostname teleport: PAM _pam_load_conf_file: unable to open /etc/pam.d/common-auth
Jun 30 16:32:36 hostname teleport: PAM error loading (null)
Jun 30 16:32:36 hostname teleport: PAM _pam_init_handlers: error reading /etc/pam.d/teleport
Jun 30 16:32:36 hostname teleport: PAM _pam_init_handlers: [Critical error - immediate abort]
Jun 30 16:32:36 hostname teleport: PAM error reading PAM configuration file
Jun 30 16:32:36 hostname teleport: PAM pam_start: failed to initialize handlers
Jun 30 16:32:36 hostname /usr/local/bin/teleport[28097]: ERRO [NODE]      Unable to open PAM context for direct-tcpip request: Critical error - immediate abort. id:14477 local:10.191.82.11:55114 login:ubuntu remote:{IP}:52958 teleportUser:user@example.com regular/sshserver.go:944
Jun 30 16:32:37 hostname teleport: PAM _pam_load_conf_file: unable to open /etc/pam.d/common-auth
Jun 30 16:32:37 hostname teleport: PAM error loading (null)
Jun 30 16:32:37 hostname teleport: PAM _pam_init_handlers: error reading /etc/pam.d/teleport
Jun 30 16:32:37 hostname teleport: PAM _pam_init_handlers: [Critical error - immediate abort]
Jun 30 16:32:37 hostname teleport: PAM error reading PAM configuration file
Jun 30 16:32:37 hostname teleport: PAM pam_start: failed to initialize handlers
Jun 30 16:32:37 hostname /usr/local/bin/teleport[28097]: ERRO [NODE]      Unable to open PAM context for direct-tcpip request: Critical error - immediate abort. id:14478 local:10.191.82.11:55114 login:ubuntu remote:{IP}:52958 teleportUser:user@example.com regular/sshserver.go:944
Jun 30 16:32:37 hostname teleport: PAM _pam_load_conf_file: unable to open /etc/pam.d/common-auth
Jun 30 16:32:37 hostname teleport: PAM error loading (null)
Jun 30 16:32:37 hostname teleport: PAM _pam_init_handlers: error reading /etc/pam.d/teleport
Jun 30 16:32:37 hostname teleport: PAM _pam_init_handlers: [Critical error - immediate abort]
Jun 30 16:32:37 hostname teleport: PAM error reading PAM configuration file
Jun 30 16:32:37 hostname teleport: PAM pam_start: failed to initialize handlers
Jun 30 16:32:37 hostname /usr/local/bin/teleport[28097]: ERRO [NODE]      Unable to open PAM context for direct-tcpip request: Critical error - immediate abort. id:14479 local:10.191.82.11:55114 login:ubuntu remote:{IP}:52958 teleportUser:user@example.com regular/sshserver.go:944
Jun 30 16:32:37 hostname teleport[28097]: panic: runtime error: invalid memory address or nil pointer dereference
Jun 30 16:32:37 hostname teleport[28097]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x19595fb]
Jun 30 16:32:37 hostname teleport[28097]: goroutine 2740255 [running]:
Jun 30 16:32:37 hostname teleport[28097]: github.com/gravitational/teleport/lib/srv/regular.(*Server).handleDirectTCPIPRequest(0xc000533200, 0x2373fa0, 0xc00420e940, 0xc0042a31a0, 0xc0027aa3e0, 0x18, 0xc00419e658, 0x6, 0xc001d96700, 0x6ca, ...)
Jun 30 16:32:37 hostname teleport[28097]: #011/gopath/src/github.com/gravitational/teleport/lib/srv/regular/sshserver.go:908 +0xcb
Jun 30 16:32:37 hostname teleport[28097]: created by github.com/gravitational/teleport/lib/srv/regular.(*Server).HandleNewChan
Jun 30 16:32:37 hostname teleport[28097]: #011/gopath/src/github.com/gravitational/teleport/lib/srv/regular/sshserver.go:896 +0xcee
```

### Environment
- Teleport version (use `teleport version`): Teleport Enterprise v4.2.0git:v4.2.0-0-g30908063 go1.13.2
- OS (e.g. from `/etc/os-release`): Ubuntu 16.04.6 LTS

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS

**Relevant Debug Logs If Applicable**

- `getenforce`: Disabled

**Comment by russjones** [comment]
Best: 3
Worst: 5

**Comment by russjones** [comment]
@jkendzorra Is this still occurring in the latest release of Teleport?

**Comment by jkendzorra** [comment]
> @jkendzorra Is this still occurring in the latest release of Teleport?

We're planning a major upgrade to 4.3.6 / 4.4, let me update you once that's done and we have more experience with that version.

**Comment by russjones** [comment]
@jkendzorra I believe this has been resolved. If you are still running into this issue please reopen or create another ticket.
