### ISSUE TITLE
panic on tunnel shutdown

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#398]
## Description

TSH panics when tunnel remote side goes away:

```go
Unable to connect to the server: read tcp 127.0.0.1:8080: connection reset by peer
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4cff67]

goroutine 7975 [running]:
github.com/gravitational/teleport/lib/client.(*NodeClient).listenAndForward.func1(0x7f85ed88c570, 0xc820034550, 0xc820487160, 0xe, 0xc820487100)
	/home/sasha/go/src/github.com/gravitational/teleport/lib/client/client.go:559 +0x627
created by github.com/gravitational/teleport/lib/client.(*NodeClient).listenAndForward
	/home/sasha/go/src/github.com/gravitational/teleport/lib/client/client.go:573 +0x1df
```

**Comment by kontsevoy** [comment]
This one was closed a couple of days ago, we forgot to mention it in the commits.
