### ISSUE TITLE
`Account.test.tsx` flakiness

### ISSUE THREAD

**Issue by ravicious** [gravitational/teleport#41402]
#### Link(s) to logs

- No logs because I was running this locally.

```bash
for i in {1..100}; do yarn test web/packages/teleport/src/Account/Account.test.tsx  || {echo "Failed after $i attempts" && break}; done
```

#### Relevant snippet

```
 FAIL  web/packages/teleport/src/Account/Account.test.tsx
  ● passkey + mfa button state: 2fa(optional) with pwdless(true) => passkey(true) mfa(true)

    expect(received).toBe(expected) // Object.is equality

    Expected: null
    Received: ""

      79 |
      80 |     // eslint-disable-next-line jest-dom/prefer-to-have-attribute
    > 81 |     expect(screen.getByText(/add a passkey/i).getAttribute('disabled')).toBe(
         |                                                                         ^
      82 |       pkEnabled ? null : ''
      83 |     );
      84 |

      at toBe (web/packages/teleport/src/Account/Account.test.tsx:81:73)
```

**Comment by ravicious** [comment]
Got another failure after 64 attempts. I suspect it might be a similar issue to #41401. Maybe `renderComponent` could wait for something to be in the document rather than waiting for the lack of it?

Also, this line should probably use `getBy` to fail immediately:

```typescript
    const statePill = screen.queryByTestId('passwordless-state-pill');
```

```
Passkey state pill: passwordless=true, 1 passkey(s) => state='active'

    expect(received).toHaveTextContent()

    received value must be a Node.
    Received has value: null

      122 |       // Note: every alternative approach is even more complicated.
      123 |       // eslint-disable-next-line jest/no-conditional-expect
    > 124 |       expect(statePill).toHaveTextContent(state);
          |                         ^
      125 |     } else {
      126 |       // eslint-disable-next-line jest/no-conditional-expect
      127 |       expect(statePill).not.toBeInTheDocument();

      at __EXTERNAL_MATCHER_TRAP__ (node_modules/expect/build/index.js:325:30)
      at Object.throwingMatcher [as toHaveTextContent] (node_modules/expect/build/index.js:326:15)
      at toHaveTextContent (web/packages/teleport/src/Account/Account.test.tsx:124:25)
```

**Comment by bl-nero** [comment]
(The problem is probably caused not by the fact that we're waiting for a component to disappear, but by the fact that spinners have a built-in small delay to prevent them from showing up every time.)
