### ISSUE TITLE
`TestInterruptsDelay` flakiness

### ISSUE THREAD

**Issue by nklaassen** [gravitational/teleport#43559]
#### Link(s) to logs

- https://github.com/gravitational/teleport/actions/runs/9685351735/job/26725238503
#### Relevant snippet

```
=== FAIL: lib/player  (0.00s)
-test.shuffle 1719429247097369590
panic: test timed out after 10m0s
running tests:
	TestInterruptsDelay (10m0s)

goroutine 82 [running]:
testing.(*M).startAlarm.func1()
	/opt/go/src/testing/testing.go:2366 +0x265
created by time.goFunc
	/opt/go/src/time/sleep.go:177 +0x45

goroutine 1 [chan receive, 10 minutes]:
testing.(*T).Run(0xc000131040, {0x36660ff, 0x13}, 0x37acd48)
	/opt/go/src/testing/testing.go:1750 +0x851
testing.runTests.func1(0xc000131040)
	/opt/go/src/testing/testing.go:2161 +0x86
testing.tRunner(0xc000131040, 0xc000b01b00)
	/opt/go/src/testing/testing.go:1689 +0x21f
testing.runTests(0xc0008e0258, {0x6605760, 0x7, 0x7}, {0x2?, 0xc000b01bf0?, 0x66302a0?})
	/opt/go/src/testing/testing.go:2159 +0x8bf
testing.(*M).Run(0xc00086d7c0)
	/opt/go/src/testing/testing.go:2027 +0xf18
main.main()
	_testmain.go:95 +0x2e5

goroutine 66 [chan receive, 10 minutes]:
github.com/gravitational/teleport/lib/player_test.TestInterruptsDelay(0xc0001311e0)
	/__w/teleport/teleport/lib/player/player_test.go:219 +0x599
testing.tRunner(0xc0001311e0, 0x37acd48)
	/opt/go/src/testing/testing.go:1689 +0x21f
created by testing.(*T).Run in goroutine 1
	/opt/go/src/testing/testing.go:1742 +0x826

goroutine 67 [select, 10 minutes]:
github.com/gravitational/teleport/lib/player.(*Player).applyDelay(0xc000585560, 0x0, 0x1388)
	/__w/teleport/teleport/lib/player/player.go:322 +0x32f
github.com/gravitational/teleport/lib/player.(*Player).stream(0xc000585560)
	/__w/teleport/teleport/lib/player/player.go:213 +0x6bc
created by github.com/gravitational/teleport/lib/player.New in goroutine 66
	/__w/teleport/teleport/lib/player/player.go:133 +0x845

goroutine 68 [select, 10 minutes]:
github.com/gravitational/teleport/lib/player_test.(*simpleStreamer).StreamSessionEvents.func1()
	/__w/teleport/teleport/lib/player/player_test.go:278 +0x4fd
created by github.com/gravitational/teleport/lib/player_test.(*simpleStreamer).StreamSessionEvents in goroutine 67
	/__w/teleport/teleport/lib/player/player_test.go:274 +0x147
FAIL	github.com/gravitational/teleport/lib/player	600.217s

=== FAIL: lib/player TestInterruptsDelay (unknown)
```

**Comment by GavinFrazar** [comment]
failed on master: https://github.com/gravitational/teleport/actions/runs/10167215810/job/28119097666

```
=== Failed
=== FAIL: lib/player  (0.00s)
-test.shuffle 1722362028531675143
panic: test timed out after 10m0s
running tests:
	TestInterruptsDelay (10m0s)

goroutine 50 [running]:
testing.(*M).startAlarm.func1()
	/opt/go/src/testing/testing.go:2366 +0x265
created by time.goFunc
	/opt/go/src/time/sleep.go:177 +0x45
...
```

**Comment by GavinFrazar** [comment]
on v16 backport: https://github.com/gravitational/teleport/actions/runs/11220253255/job/31188004797?pr=47246

```
=== FAIL: lib/player  (0.00s)
-test.shuffle 1728320451797324441
panic: test timed out after 10m0s
running tests:
	TestInterruptsDelay (10m0s)

goroutine 108 [running]:
testing.(*M).startAlarm.func1()
	/opt/go/src/testing/testing.go:2366 +0x265
created by time.goFunc
	/opt/go/src/time/sleep.go:177 +0x45

goroutine 1 [chan receive, 10 minutes]:
testing.(*T).Run(0xc0009da4e0, {0x37a27e2, 0x13}, 0x38ed098)
	/opt/go/src/testing/testing.go:1750 +0x851
testing.runTests.func1(0xc0009da4e0)
	/opt/go/src/testing/testing.go:2161 +0x86
testing.tRunner(0xc0009da4e0, 0xc000b87b00)
	/opt/go/src/testing/testing.go:1689 +0x21f
testing.runTests(0xc0009a6ab0, {0x67fcb80, 0x8, 0x8}, {0x2?, 0xc000b87bf0?, 0x6827e40?})
	/opt/go/src/testing/testing.go:2159 +0x8bf
testing.(*M).Run(0xc000940fa0)
	/opt/go/src/testing/testing.go:2027 +0xf18
main.main()
	_testmain.go:97 +0x2e5
```

**Comment by ptgott** [comment]
Another timeout after 10m: https://github.com/gravitational/teleport/actions/runs/11386545720/job/31679039485#step:6:1969

**Comment by zmb3** [comment]
The flakiness here is a result of clockwork not actually allowing you to block waiting for tickers.

I am optimistic that Go 1.24's synctest package will allow us to rewrite this test in a way that passes every time, but I'm not sure if it's ready for us yet given that it's still experimental and only enabled via env var.

**Comment by rosstimothy** [comment]
@zmb3 we're still seeing these failures on release branches. See https://github.com/gravitational/teleport/actions/runs/18850751585/job/53786444251 and  https://github.com/gravitational/teleport/actions/runs/18906267336/job/53965182641. 

Can we backport #53744 to release branches since both v17 and v18 are using Go 1.24?
