### ISSUE TITLE
Microsoft Teams Access request workflow plugin run into issues when they validate the plugin workflow.

### ISSUE THREAD

**Issue by pnrao1983** [gravitational/teleport#44953]
Expected behavior:
When Starting the Microsoft Teams plugin in validation mode using the below command, It should return successfully as is in the [docs](https://goteleport.com/docs/access-controls/access-request-plugins/ssh-approval-msteams/#test-microsoft-teams-connectivity)

`teleport-msteams validate <email of your teams account>`

Current behavior:
When  validating the plugin workflow it returns the below output

```
$teleport-msteams validate user.name@example.com
- Checking application afef04c7-df7e-4060-9070-36cf437973cb status...
- Application found in the team app store (internal ID: 3ece9daf-5728-4a60-ba58-81ea544211a5)
- User user.name@example.com found: a7dea46d-a932-4224-85d9-370986cf808b
panic: errors: target must be a non-nil pointer
goroutine 1 [running]:
errors.As({0x17ecd80?, 0xc000648300?}, {0x13c80e0?, 0x0?})
        /home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.5.linux-amd64/src/errors/wrap.go:107 +0x219
github.com/gravitational/teleport/integrations/access/msteams/msapi.GetErrorCode(...)
        /home/runner/work/teleport.e/teleport.e/integrations/access/msteams/msapi/graph_client.go:105
github.com/gravitational/teleport/integrations/access/msteams.(*Bot).FetchRecipient(0xc0002da000, {0x1807e10, 0x24a6e40}, {0xc0002a2c00, 0x24})
        /home/runner/work/teleport.e/teleport.e/integrations/access/msteams/bot.go:211 +0x629
github.com/gravitational/teleport/integrations/access/msteams.Validate({0x163ff35?, 0xc00018e490?}, {0x7fff6413ccbe, 0x19})
        /home/runner/work/teleport.e/teleport.e/integrations/access/msteams/validate.go:59 +0x26d
main.main()
        /home/runner/work/teleport.e/teleport.e/integrations/access/msteams/cmd/teleport-msteams/main.go:91 +0x12a6`
```

**Bug details:**
- Teleport version v15.4.9
   teleport-msteams version
   teleport-msteams v15.4.9 go1.22.5
- Recreation steps
   NA
- Debug logs

**Comment by hugoShaka** [comment]
Fixed by https://github.com/gravitational/teleport/pull/44984
