### ISSUE TITLE
panic: protobuf tag not enough fields in IndexOperationMetadata.state:

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#4508]
### Description

**What happened**:
When creating GCP new  Firestore backend, I ran into this panic.  While testing Teleport 4.4 https://github.com/gravitational/teleport/issues/4359 

```log
benarent@teleport-4-4:/var/lib/teleport$ sudo teleport start -d
DEBU [SQLITE]    Connected to: file:/var/lib/teleport/proc/sqlite.db?_busy_timeout=10000&_sync=OFF, poll stream period: 1s lite/lite.go:173
DEBU [SQLITE]    Synchronous: 0, busy timeout: 10000 lite/lite.go:218
DEBU [KEYGEN]    SSH cert authority is going to pre-compute 25 keys. native/native.go:104
DEBU [PROC:1]    Using firestore backend. service/service.go:2533
INFO [FIRESTORE] Firestore: initializing backend. firestore/firestorebk.go:248
DEBU [FIRESTORE] Firestore: backend created. runtime/panic.go:969
panic: protobuf tag not enough fields in IndexOperationMetadata.state:

goroutine 1 [running, locked to thread]:
github.com/gogo/protobuf/proto.(*unmarshalInfo).computeUnmarshalInfo(0xc00040b680)
	/go/src/github.com/gravitational/teleport/vendor/github.com/gogo/protobuf/proto/table_unmarshal.go:341 +0x1834
github.com/gogo/protobuf/proto.(*unmarshalInfo).unmarshal(0xc00040b680, 0xc000366720, 0xc000c2a150, 0x6c, 0x70, 0x41d368, 0x20)
	/go/src/github.com/gravitational/teleport/vendor/github.com/gogo/protobuf/proto/table_unmarshal.go:138 +0xe02
github.com/gogo/protobuf/proto.(*InternalMessageInfo).Unmarshal(0xc0003fed20, 0x2c0b920, 0xc000366720, 0xc000c2a150, 0x6c, 0x70, 0xc000366701, 0x0)
	/go/src/github.com/gravitational/teleport/vendor/github.com/gogo/protobuf/proto/table_unmarshal.go:63 +0x66
github.com/gogo/protobuf/proto.(*Buffer).Unmarshal(0xc000c85048, 0x2c0b920, 0xc000366720, 0x0, 0x0)
	/go/src/github.com/gravitational/teleport/vendor/github.com/gogo/protobuf/proto/decode.go:424 +0x1ec
github.com/gogo/protobuf/proto.Unmarshal(0xc000c2a150, 0x6c, 0x70, 0x2c0b920, 0xc000366720, 0x0, 0x0)
	/go/src/github.com/gravitational/teleport/vendor/github.com/gogo/protobuf/proto/decode.go:342 +0x170
github.com/gravitational/teleport/lib/backend/firestore.EnsureIndexes(0x2c26da0, 0xc0003fa700, 0xc000720ba0, 0xc000c85538, 0x1, 0x1, 0xc000732050, 0x45, 0xc, 0xc000732050)
	/go/src/github.com/gravitational/teleport/lib/backend/firestore/firestorebk.go:737 +0x491
github.com/gravitational/teleport/lib/backend/firestore.(*FirestoreBackend).ensureIndexes(0xc000776000, 0xc000720ba0, 0xc0000fe000, 0xc0003fac40)
	/go/src/github.com/gravitational/teleport/lib/backend/firestore/firestorebk.go:692 +0x124
github.com/gravitational/teleport/lib/backend/firestore.New(0x2c26de0, 0xc00011c018, 0xc0005856e0, 0x0, 0x0, 0x0)
	/go/src/github.com/gravitational/teleport/lib/backend/firestore/firestorebk.go:280 +0x8fe
github.com/gravitational/teleport/lib/service.(*TeleportProcess).initAuthStorage(0xc00073a000, 0xc00071d988, 0x41cce4, 0xc000738000, 0x90)
	/go/src/github.com/gravitational/teleport/lib/service/service.go:2539 +0x5bf
github.com/gravitational/teleport/lib/service.(*TeleportProcess).initAuthService(0xc00073a000, 0xc0003fa500, 0x3)
	/go/src/github.com/gravitational/teleport/lib/service/service.go:938 +0x4f
github.com/gravitational/teleport/lib/service.NewTeleport(0xc000471800, 0x0, 0x0, 0x0)
	/go/src/github.com/gravitational/teleport/lib/service/service.go:651 +0x878
github.com/gravitational/teleport/lib/service.newTeleportProcess(0xc000471800, 0xc000471800, 0x0, 0x0, 0xc0005fec90)
	/go/src/github.com/gravitational/teleport/lib/service/service.go:394 +0x2b
github.com/gravitational/teleport/lib/service.Run(0x2c26de0, 0xc00011c018, 0xc00043e240, 0x11, 0xc000275770, 0xc, 0xc0002757b8, 0x4, 0xc000585ad0, 0x1, ...)
	/go/src/github.com/gravitational/teleport/lib/service/service.go:404 +0x9d
github.com/gravitational/teleport/tool/teleport/common.OnStart(...)
	/go/src/github.com/gravitational/teleport/tool/teleport/common/teleport.go:188
github.com/gravitational/teleport/tool/teleport/common.Run(0xc000116070, 0x2, 0x2, 0x0, 0x0, 0x0, 0xc000102058)
	/go/src/github.com/gravitational/teleport/tool/teleport/common/teleport.go:165 +0x2c19
main.main()
	/go/src/github.com/gravitational/teleport/tool/teleport/main.go:26 +0x69
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

### Environment
- Teleport version (use `teleport version`):
- Tsh version (use `tsh version`):
- OS (e.g. from `/etc/os-release`):

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware):

**Browser environment**

- Browser Version (for UI-related issues):
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**

- `tsh --debug`
- `teleport --debug`

**Comment by benarent** [comment]
While testing this more, it's something up with `audit_events_uri` that it's not liking. 

`audit_events_uri: 'firestore://events?projectID=example_Teleport-Project-Name&credentialsPath=/var/lib/teleport/gcs_creds'` 

Going to test a few variants and at least fix the docs.

**Comment by benarent** [comment]
Also confirming that `teleport-v4.4.0-rc.5` fix this issue on my GCP Instance .
