### ISSUE TITLE
`TestHSMRevert` flakiness

### ISSUE THREAD

**Issue by GavinFrazar** [gravitational/teleport#47301]
#### Link(s) to logs

- https://github.com/gravitational/teleport/actions/runs/11222764169/job/31195893398?pr=47224

#### Relevant snippet

```
==================
WARNING: DATA RACE
Write at 0x00c0034e4c40 by goroutine 16704:
  github.com/gravitational/teleport/lib/service.readOrGenerateHostID()
      /__w/teleport/teleport/lib/service/service.go:6442 +0xe4
  github.com/gravitational/teleport/lib/service.NewTeleport()
      /__w/teleport/teleport/lib/service/service.go:1050 +0x1004
  github.com/gravitational/teleport/integration/hsm.newTeleportService()
      /__w/teleport/teleport/integration/hsm/helpers.go:65 +0x259
  github.com/gravitational/teleport/integration/hsm.TestHSMRevert()
      /__w/teleport/teleport/integration/hsm/hsm_test.go:545 +0x69e
  testing.tRunner()
      /opt/go/src/testing/testing.go:1690 +0x226
  testing.(*T).Run.gowrap1()
      /opt/go/src/testing/testing.go:1743 +0x44

Previous read at 0x00c0034e4c40 by goroutine 17394:
  github.com/gravitational/teleport/lib/service.(*TeleportProcess).initAuthService.func5()
      /__w/teleport/teleport/lib/service/service.go:2388 +0x129
  github.com/gravitational/teleport/lib/srv.(*Heartbeat).fetch()
      /__w/teleport/teleport/lib/srv/heartbeat.go:338 +0x55
  github.com/gravitational/teleport/lib/srv.(*Heartbeat).fetchAndAnnounce()
      /__w/teleport/teleport/lib/srv/heartbeat.go:623 +0x2e
  github.com/gravitational/teleport/lib/srv.(*Heartbeat).Run()
      /__w/teleport/teleport/lib/srv/heartbeat.go:281 +0xe7
  github.com/gravitational/teleport/lib/srv.(*Heartbeat).Run-fm()
      <autogenerated>:1 +0x33
  github.com/gravitational/teleport/lib/service.(*LocalService).Serve()
      /__w/teleport/teleport/lib/service/supervisor.go:581 +0x35
  github.com/gravitational/teleport/lib/service.(*LocalSupervisor).serve.func1()
      /__w/teleport/teleport/lib/service/supervisor.go:307 +0x488

...

    testing.go:1399: race detected during execution of test
```

**Comment by zmb3** [comment]
Another hit here: https://github.com/gravitational/teleport/actions/runs/12171714313/job/33949121490

```
==================
WARNING: DATA RACE
Read at 0x00c002e97220 by goroutine 18252:
  github.com/gravitational/teleport/lib/service.(*TeleportProcess).initAuthService.func5()
      /__w/teleport/teleport/lib/service/service.go:2391 +0x129
  github.com/gravitational/teleport/lib/srv.(*Heartbeat).fetch()
      /__w/teleport/teleport/lib/srv/heartbeat.go:338 +0x55
  github.com/gravitational/teleport/lib/srv.(*Heartbeat).fetchAndAnnounce()
      /__w/teleport/teleport/lib/srv/heartbeat.go:623 +0x2e
  github.com/gravitational/teleport/lib/srv.(*Heartbeat).Run()
      /__w/teleport/teleport/lib/srv/heartbeat.go:281 +0xe7
  github.com/gravitational/teleport/lib/srv.(*Heartbeat).Run-fm()
      <autogenerated>:1 +0x33
  github.com/gravitational/teleport/lib/service.(*LocalService).Serve()
      /__w/teleport/teleport/lib/service/supervisor.go:581 +0x35
  github.com/gravitational/teleport/lib/service.(*LocalSupervisor).serve.func1()
      /__w/teleport/teleport/lib/service/supervisor.go:307 +0x488

Previous write at 0x00c002e97220 by goroutine 17578:
  github.com/gravitational/teleport/lib/service.readOrGenerateHostID()
      /__w/teleport/teleport/lib/service/service.go:6463 +0xe4
  github.com/gravitational/teleport/lib/service.NewTeleport()
      /__w/teleport/teleport/lib/service/service.go:1053 +0x1004
  github.com/gravitational/teleport/integration/hsm.newTeleportService()
      /__w/teleport/teleport/integration/hsm/helpers.go:65 +0x259
  github.com/gravitational/teleport/integration/hsm.TestHSMRevert()
      /__w/teleport/teleport/integration/hsm/hsm_test.go:547 +0x698
  testing.tRunner()
      /opt/go/src/testing/testing.go:1690 +0x226
  testing.(*T).Run.gowrap1()
      /opt/go/src/testing/testing.go:1743 +0x44

Goroutine 18252 (running) created at:
  github.com/gravitational/teleport/lib/service.(*LocalSupervisor).serve()
      /__w/teleport/teleport/lib/service/supervisor.go:296 +0x104
  github.com/gravitational/teleport/lib/service.(*LocalSupervisor).Start()
      /__w/teleport/teleport/lib/service/supervisor.go:339 +0x304
  github.com/gravitational/teleport/integration/hsm.newTeleportService()
      /__w/teleport/teleport/integration/hsm/helpers.go:69 +0x2ba
  github.com/gravitational/teleport/integration/hsm.TestHSMRevert()
      /__w/teleport/teleport/integration/hsm/hsm_test.go:537 +0x374
  testing.tRunner()
      /opt/go/src/testing/testing.go:1690 +0x226
  testing.(*T).Run.gowrap1()
      /opt/go/src/testing/testing.go:1743 +0x44

Goroutine 17578 (running) created at:
  testing.(*T).Run()
      /opt/go/src/testing/testing.go:1743 +0x825
  testing.runTests.func1()
      /opt/go/src/testing/testing.go:2168 +0x85
  testing.tRunner()
      /opt/go/src/testing/testing.go:1690 +0x226
  testing.runTests()
      /opt/go/src/testing/testing.go:2166 +0x8be
  testing.(*M).Run()
      /opt/go/src/testing/testing.go:2034 +0xf17
  github.com/gravitational/teleport/integration/hsm.TestMain()
      /__w/teleport/teleport/integration/hsm/hsm_test.go:65 +0x153
  main.main()
      _testmain.go:53 +0x171
==================
```

**Comment by hugoShaka** [comment]
https://github.com/gravitational/teleport/actions/runs/12241719850/job/34147463725#step:6:1554

```
==================
WARNING: DATA RACE
Write at 0x00c0032f4c28 by goroutine 18620:
  github.com/gravitational/teleport/lib/service.readOrGenerateHostID()
      /__w/teleport/teleport/lib/service/service.go:6465 +0xe4
  github.com/gravitational/teleport/lib/service.NewTeleport()
      /__w/teleport/teleport/lib/service/service.go:1053 +0x1004
  github.com/gravitational/teleport/integration/hsm.newTeleportService()
      /__w/teleport/teleport/integration/hsm/helpers.go:65 +0x259
  github.com/gravitational/teleport/integration/hsm.TestHSMRevert()
      /__w/teleport/teleport/integration/hsm/hsm_test.go:547 +0x698
  testing.tRunner()
      /opt/go/src/testing/testing.go:1690 +0x226
  testing.(*T).Run.gowrap1()
      /opt/go/src/testing/testing.go:1743 +0x44

Previous read at 0x00c0032f4c28 by goroutine 19297:
  github.com/gravitational/teleport/lib/service.(*TeleportProcess).initAuthService.func5()
      /__w/teleport/teleport/lib/service/service.go:2391 +0x129
  github.com/gravitational/teleport/lib/srv.(*Heartbeat).fetch()
      /__w/teleport/teleport/lib/srv/heartbeat.go:341 +0x55
  github.com/gravitational/teleport/lib/srv.(*Heartbeat).fetchAndAnnounce()
      /__w/teleport/teleport/lib/srv/heartbeat.go:626 +0x2e
  github.com/gravitational/teleport/lib/srv.(*Heartbeat).Run()
      /__w/teleport/teleport/lib/srv/heartbeat.go:284 +0xe9
  github.com/gravitational/teleport/lib/srv.(*Heartbeat).Run-fm()
      <autogenerated>:1 +0x33
  github.com/gravitational/teleport/lib/service.(*LocalService).Serve()
      /__w/teleport/teleport/lib/service/supervisor.go:581 +0x35
  github.com/gravitational/teleport/lib/service.(*LocalSupervisor).serve.func1()
      /__w/teleport/teleport/lib/service/supervisor.go:307 +0x488

Goroutine 18620 (running) created at:
  testing.(*T).Run()
      /opt/go/src/testing/testing.go:1743 +0x825
  testing.runTests.func1()
      /opt/go/src/testing/testing.go:2168 +0x85
  testing.tRunner()
      /opt/go/src/testing/testing.go:1690 +0x226
  testing.runTests()
      /opt/go/src/testing/testing.go:2166 +0x8be
  testing.(*M).Run()
      /opt/go/src/testing/testing.go:2034 +0xf17
  github.com/gravitational/teleport/integration/hsm.TestMain()
      /__w/teleport/teleport/integration/hsm/hsm_test.go:65 +0x153
  main.main()
      _testmain.go:53 +0x171

Goroutine 19297 (running) created at:
  github.com/gravitational/teleport/lib/service.(*LocalSupervisor).serve()
      /__w/teleport/teleport/lib/service/supervisor.go:296 +0x104
  github.com/gravitational/teleport/lib/service.(*LocalSupervisor).Start()
      /__w/teleport/teleport/lib/service/supervisor.go:339 +0x304
  github.com/gravitational/teleport/integration/hsm.newTeleportService()
      /__w/teleport/teleport/integration/hsm/helpers.go:69 +0x2ba
  github.com/gravitational/teleport/integration/hsm.TestHSMRevert()
      /__w/teleport/teleport/integration/hsm/hsm_test.go:537 +0x374
  testing.tRunner()
      /opt/go/src/testing/testing.go:1690 +0x226
  testing.(*T).Run.gowrap1()
      /opt/go/src/testing/testing.go:1743 +0x44
==================
```

**Comment by ravicious** [comment]
v18 https://github.com/gravitational/teleport/actions/runs/17491852386/job/49683230354?pr=58790#step:6:1180

```
     hsm_test.go:629: Running test with SoftHSM
    hsm_test.go:561: 
        	Error Trace:	/__w/teleport/teleport/integration/hsm/hsm_test.go:561
        	Error:      	"[]" should have 1 item(s), but has 0
        	Test:       	TestHSMRevert
```

**Comment by GavinFrazar** [comment]
master https://github.com/gravitational/teleport/actions/runs/17570793604/job/49906491780

**Comment by smallinsky** [comment]
v18 https://github.com/gravitational/teleport/actions/runs/17926518115/job/50973809085?pr=59459

```
=== Failed
=== FAIL: integration/hsm TestHSMRevert (34.76s)
    hsm_test.go:628: Running test with SoftHSM
    hsm_test.go:560: 
        	Error Trace:	/__w/teleport/teleport/integration/hsm/hsm_test.go:560
        	Error:      	"[]" should have 1 item(s), but has 0
        	Test:       	TestHSMRevert
```

**Comment by greedy52** [comment]
master

https://github.com/gravitational/teleport/actions/runs/17956147794/job/51067853321?pr=59500


```
    hsm_test.go:628: Running test with SoftHSM
    hsm_test.go:560: 
        	Error Trace:	/__w/teleport/teleport/integration/hsm/hsm_test.go:560
        	Error:      	"[]" should have 1 item(s), but has 0
        	Test:       	TestHSMRevert
```

**Comment by rosstimothy** [comment]
https://github.com/gravitational/teleport/actions/runs/18278750883/job/52036770488?pr=59952

```
==================
WARNING: DATA RACE
Write at 0x00c0049ca538 by goroutine 26475:
  github.com/gravitational/teleport/lib/auth/storage.readOrGenerateHostID()
      /__w/teleport/teleport/lib/auth/storage/storage.go:326 +0xda
  github.com/gravitational/teleport/lib/auth/storage.(*ProcessStorage).ReadOrGenerateHostID.func1()
      /__w/teleport/teleport/lib/auth/storage/storage.go:313 +0x75
  k8s.io/client-go/util/retry.OnError.func1()
      /go/pkg/mod/k8s.io/client-go@v0.33.3/util/retry/util.go:51 +0x41
  k8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection()
      /go/pkg/mod/k8s.io/apimachinery@v0.33.3/pkg/util/wait/wait.go:150 +0x53
  k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff()
      /go/pkg/mod/k8s.io/apimachinery@v0.33.3/pkg/util/wait/backoff.go:477 +0x5e
  k8s.io/client-go/util/retry.OnError()
      /go/pkg/mod/k8s.io/client-go@v0.33.3/util/retry/util.go:50 +0x130
  github.com/gravitational/teleport/lib/auth/storage.(*ProcessStorage).ReadOrGenerateHostID()
      /__w/teleport/teleport/lib/auth/storage/storage.go:312 +0x129
  github.com/gravitational/teleport/lib/service.NewTeleport()
      /__w/teleport/teleport/lib/service/service.go:1099 +0x1524
  github.com/gravitational/teleport/lib/service.NewTeleport()
      /__w/teleport/teleport/lib/service/service.go:1011 +0x441
  github.com/gravitational/teleport/integration/hsm.newTeleportService()
      /__w/teleport/teleport/integration/hsm/helpers.go:65 +0x252
  github.com/gravitational/teleport/integration/hsm.TestHSMRevert()
      /__w/teleport/teleport/integration/hsm/hsm_test.go:551 +0x693
  github.com/gravitational/teleport/integration/hsm.TestHSMRevert()
      /__w/teleport/teleport/integration/hsm/hsm_test.go:541 +0x372
  testing.tRunner()
      /opt/go/src/testing/testing.go:1792 +0x225
  testing.(*T).Run.gowrap1()
      /opt/go/src/testing/testing.go:1851 +0x44

Previous read at 0x00c0049ca538 by goroutine 27650:
  github.com/gravitational/teleport/lib/service.NewTeleport.func6()
      /__w/teleport/teleport/lib/service/service.go:1275 +0x115
  github.com/gravitational/teleport/lib/inventory.NewDownstreamHandle.func1.1()
      /__w/teleport/teleport/lib/inventory/inventory.go:156 +0xaf
  github.com/gravitational/teleport/lib/utils.FnCacheGetWithTTL[go.shape.string,go.shape.fada184d689976abc85a18a58340b45d17d92cf50d155ef46c22d6d07e7a2627].func1()
      /__w/teleport/teleport/lib/utils/fncache.go:241 +0x8f
  github.com/gravitational/teleport/lib/utils.(*FnCache).get.func1()
      /__w/teleport/teleport/lib/utils/fncache.go:313 +0xf4

Goroutine 26475 (running) created at:
  testing.(*T).Run()
      /opt/go/src/testing/testing.go:1851 +0x8f2
  testing.runTests.func1()
      /opt/go/src/testing/testing.go:2279 +0x85
  testing.tRunner()
      /opt/go/src/testing/testing.go:1792 +0x225
  testing.runTests()
      /opt/go/src/testing/testing.go:2277 +0x96c
  testing.(*M).Run()
      /opt/go/src/testing/testing.go:2142 +0xeea
  github.com/gravitational/teleport/integration/hsm.TestMain()
      /__w/teleport/teleport/integration/hsm/hsm_test.go:71 +0x15e
  main.main()
      _testmain.go:53 +0x171

Goroutine 27650 (finished) created at:
  github.com/gravitational/teleport/lib/utils.(*FnCache).get()
      /__w/teleport/teleport/lib/utils/fncache.go:309 +0x65c
  github.com/gravitational/teleport/lib/utils.FnCacheGetWithTTL[go.shape.string,go.shape.fada184d689976abc85a18a58340b45d17d92cf50d155ef46c22d6d07e7a2627]()
      /__w/teleport/teleport/lib/utils/fncache.go:240 +0x1b4
  github.com/gravitational/teleport/lib/utils.FnCacheGet[go.shape.string,go.shape.fada184d689976abc85a18a58340b45d17d92cf50d155ef46c22d6d07e7a2627]()
      /__w/teleport/teleport/lib/utils/fncache.go:234 +0x1d9
  github.com/gravitational/teleport/lib/inventory.NewDownstreamHandle.func1()
      /__w/teleport/teleport/lib/inventory/inventory.go:155 +0xc8
  github.com/gravitational/teleport/lib/inventory.(*downstreamHandle).handleStream()
      /__w/teleport/teleport/lib/inventory/inventory.go:311 +0x185
  github.com/gravitational/teleport/lib/inventory.(*downstreamHandle).tryRun()
      /__w/teleport/teleport/lib/inventory/inventory.go:294 +0x1ab
  github.com/gravitational/teleport/lib/inventory.(*downstreamHandle).run()
      /__w/teleport/teleport/lib/inventory/inventory.go:269 +0xc4
  github.com/gravitational/teleport/lib/inventory.NewDownstreamHandle.gowrap1()
      /__w/teleport/teleport/lib/inventory/inventory.go:169 +0x44
==================
```

**Comment by rosstimothy** [comment]
https://github.com/gravitational/teleport/actions/runs/19345020508/job/55343035931

```
=== FAIL: integration/hsm TestHSMRevert (63.90s)
    hsm_test.go:630: Running test with SoftHSM
    hsm_test.go:558: 
        	Error Trace:	/__w/teleport/teleport/integration/hsm/hsm_test.go:561
        	            				/opt/go/src/runtime/asm_amd64.s:1693
        	Error:      	"[]" should have 1 item(s), but has 0
    hsm_test.go:558: 
        	Error Trace:	/__w/teleport/teleport/integration/hsm/hsm_test.go:558
        	Error:      	Condition never satisfied
        	Test:       	TestHSMRevert
        	Messages:   	waiting for cluster alert to be created
```

https://github.com/gravitational/teleport/actions/runs/19247742450/job/55025906954

```
2025-11-10T22:21:11.9513796Z ##[group][31mFAIL[0m integration/hsm.TestHSMRevert (62.83s)
2025-11-10T22:21:11.9514152Z     hsm_test.go:630: Running test with SoftHSM
2025-11-10T22:21:11.9514393Z     hsm_test.go:558: 
2025-11-10T22:21:11.9514686Z         	Error Trace:	/__w/teleport/teleport/integration/hsm/hsm_test.go:561
2025-11-10T22:21:11.9515668Z         	            				/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.4.linux-amd64/src/runtime/asm_amd64.s:1693
2025-11-10T22:21:11.9516099Z         	Error:      	"[]" should have 1 item(s), but has 0
2025-11-10T22:21:11.9516346Z     hsm_test.go:558: 
2025-11-10T22:21:11.9516615Z         	Error Trace:	/__w/teleport/teleport/integration/hsm/hsm_test.go:558
2025-11-10T22:21:11.9517041Z         	Error:      	Condition never satisfied
2025-11-10T22:21:11.9517285Z         	Test:       	TestHSMRevert
2025-11-10T22:21:11.9517550Z         	Messages:   	waiting for cluster alert to be created
2025-11-10T22:21:11.9517745Z 
2025-11-10T22:21:11.9517958Z ##[endgroup]
```

**Comment by nklaassen** [comment]
I enabled debug logs in https://github.com/gravitational/teleport/pull/61458, if you see another hit of this please link the logs here

**Comment by smallinsky** [comment]
On `master` https://github.com/gravitational/teleport/actions/runs/19703377858/job/56444864951?pr=61788

```
{"timestamp":"2025-11-26T12:24:10Z","level":"debug","caller":"lite/periodic.go:52","message":"Failed to run remove expired keys","component":"sqlite","error":"database is in readonly mode"}
    hsm_test.go:567: 
        	Error Trace:	/__w/teleport/teleport/integration/hsm/hsm_test.go:570
        	            				/opt/go/src/runtime/asm_amd64.s:1693
        	Error:      	"[]" should have 1 item(s), but has 0
    hsm_test.go:567: 
        	Error Trace:	/__w/teleport/teleport/integration/hsm/hsm_test.go:567
        	Error:      	Condition never satisfied
        	Test:       	TestHSMRevert
        	Messages:   	waiting for cluster alert to be created
{"timestamp":"2025-11-26T12:24:10Z","level":"debug","caller":"service/supervisor.go:435","message":"Broadcasting 
```

**Comment by zmb3** [comment]
New hit on master: https://github.com/gravitational/teleport/actions/runs/21964469281/job/63450527351

```
file:/tmp/TestHSMRevert155380475/002/proc/sqlite.db?_pragma=busy_timeout%2810000%29&_pragma=synchronous%28FULL%29&_txlock=immediate\n\tdatabase is locked (5) (SQLITE_BUSY)"}
    hsm_test.go:567: 
        	Error Trace:	/__w/teleport/teleport/integration/hsm/hsm_test.go:567
        	Error:      	Received unexpected error:
        	            	error creating schema: file:/tmp/TestHSMRevert155380475/002/proc/sqlite.db?_pragma=busy_timeout%2810000%29&_pragma=synchronous%28FULL%29&_txlock=immediate
        	            		database is locked (5) (SQLITE_BUSY)
        	Test:       	TestHSMRevert
panic: runtime error: invalid memory address or nil pointer dereference [recovered, repanicked]
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x181445ee]

goroutine 20184 [running]:
testing.tRunner.func1.2({0x18f7e9c0, 0x232a1910})
	/opt/go/src/testing/testing.go:1872 +0x419
testing.tRunner.func1()
	/opt/go/src/testing/testing.go:1875 +0x683
panic({0x18f7e9c0?, 0x232a1910?})
	/opt/go/src/runtime/panic.go:783 +0x132
github.com/gravitational/teleport/integration/hsm.TestHSMRevert.func1()
	/__w/teleport/teleport/integration/hsm/hsm_test.go:557 +0x6e
testing.(*common).Cleanup.func1()
	/opt/go/src/testing/testing.go:1308 +0x169
testing.(*common).runCleanup(0xc002a336c0, 0x0)
	/opt/go/src/testing/testing.go:1572 +0x226
testing.tRunner.func2()
	/opt/go/src/testing/testing.go:1928 +0x4d
runtime.Goexit()
	/opt/go/src/runtime/panic.go:615 +0x5e
testing.(*common).FailNow(0xc002a336c0)
	/opt/go/src/testing/testing.go:1013 +0x7b
github.com/stretchr/testify/require.NoError({0x1beac6e8, 0xc002a336c0}, {0x1be434a0, 0xc0030987e0}, {0x0, 0x0, 0x0})
	/go/pkg/mod/github.com/stretchr/testify@v1.11.1/require/require.go:1401 +0xe4
github.com/gravitational/teleport/integration/hsm.TestHSMRevert(0xc002a336c0)
	/__w/teleport/teleport/integration/hsm/hsm_test.go:567 +0x6e5
testing.tRunner(0xc002a336c0, 0x1abea740)
	/opt/go/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/go/src/testing/testing.go:1997 +0x9d3

DONE 647 tests, 11 skipped, 1 failure in 798.772s
```

@rosstimothy looks related to modernc/sqlite.

**Comment by ravicious** [comment]
Another one: https://github.com/gravitational/teleport/actions/runs/21975484497/job/63505780514?pr=63790

**Comment by rosstimothy** [comment]
Still looking into the cause of the `database is locked` errors, but I have opened https://github.com/gravitational/teleport/pull/63802 to prevent the panic on errors.

**Comment by rosstimothy** [comment]
While investigating if and what could be keeping connections open I did find a couple issues - though none of which was the source of the latest failures.

With both https://github.com/gravitational/teleport/pull/63826 and https://github.com/gravitational/teleport/pull/63826 the test was still failing locally. I ran the tests again with the `sqlite.dmesg` tag to get a more detailed view at what the sqlite driver was doing. I was reasonably confident that we were now appropriately closing all connections and the database correctly and still got `database is locked` errors. 

After conferring with @espadolini he was able to get the same behavior with a smaller reproduction. He poked through the issue tracker and changelogs and discovered a merged MR in a recent version which looked like it could potentially resolve the issue. We both bumped `modernc.org/sqlite` to the latest version and reran our tests separately and haven't been able to reproduce since. I'm going to open a PR to update from `modernc.org/sqlite@v1.39.0` to  `modernc.org/sqlite@v1.46.0` to see if the issue goes away. If not, I will open a PR to revert the conversion to `modernc.org/sqlite`.
