### ISSUE TITLE
Teleport SAML Integration with Keycloak IdP - Signature Validation Incompatibility

### ISSUE THREAD

**Issue by oshati** [gravitational/teleport#47971]
**Expected behaviour:**
Teleport, when configured with Keycloak as a SAML IdP, should successfully authenticate requests, accepting the SAML signature format as per Keycloak's HTTP-Redirect binding expectations. The integration should allow seamless communication between Teleport and Keycloak using standard SAML IDP configurations.

**Current behaviour:**
When "Client signature required" is enabled with the appropriate signing keys for signing SAML requests and responses, it results in an invalid requester error as shown in the image below. On the Keycloak side, the system fails to validate the SAML signature resulting in an `invalid_signature`  and `request validation failed: org.keycloak.common.VerificationException: SigAlg was null` error. See full error logs below The issue seems linked to how Teleport currently formats and transmits the SAML request signature, with the HTTP-Redirect binding not meeting Keycloak's strict signature requirements.  

To resolve the issue temporarily, `spec.provider: ping` parameter was added in the Teleport SAML auth connector, suggesting possible hardcoded behaviours that differ from Keycloak’s expectations.

Note: SSO works without enabling client signature. 

**Additional Details:** 
While this has been spotted with Keycloak IDP, this issue aligns with previous cases involving SAML signature format discrepancies when using other IdPs with strict adherence to SAML 2.0 standards. Adjusting the signature parameters or allowing configuration flexibility for HTTP-Redirect binding settings might enable broader IdP compatibility. 

**Bug details:**
- Teleport version
Teleport v16.1.0 also observed in 16.2.0

**Recreation steps**
- Configure Keycloak as a SAML IdP integration with Teleport.
- in the Signing Keys config section on Keycloak Enable client signature validation
- Either import the signing key pair cert from the from the Teleport  saml auth connector or export the one generated by KeyCloak
- Attempt to authenticate through Teleport using Keycloak.
- Observe the behaviour
![Image](https://github.com/user-attachments/assets/7acc3ece-915c-438d-8f9a-539ac5ea76bb)

**Debug logs**

Teleport auth
```
2024-10-25T20:06:03Z INFO [AUTH.ENTE] Reconciling users. auth/usermonitor.go:138
2024-10-25T20:06:44Z DEBU             [SAML] Successfully fetched entity descriptor from https://idp.example.com/realms/teleports/protocol/saml/descriptor for connector keycloak services/saml.go:66
2024-10-25T20:06:44Z DEBU             [SAML] SSO: https://idp.example.com/realms/teleports/protocol/saml services/saml.go:124
2024-10-25T20:06:44Z DEBU             [SAML] Issuer: https://idp.example.com/realms/teleports services/saml.go:125
2024-10-25T20:06:44Z DEBU             [SAML] ACS: https://teleport.example.com/v1/webapi/saml/acs/keycloak services/saml.go:126
2024-10-25T20:06:45Z DEBU             [SAML] Successfully fetched entity descriptor from https://idp.example.com/realms/teleports/protocol/saml/descriptor for connector keycloak services/saml.go:66
2024-10-25T20:06:45Z DEBU             [SAML] SSO: https://idp.example.com/realms/teleports/protocol/saml services/saml.go:124
2024-10-25T20:06:45Z DEBU             [SAML] Issuer: https://idp.example.com/realms/teleports services/saml.go:125
2024-10-25T20:06:45Z DEBU             [SAML] ACS: https://teleport.example.com/v1/webapi/saml/acs/keycloak services/saml.go:126
2024-10-25T20:06:48Z DEBU             [SAML] Successfully fetched entity descriptor from https://idp.example.com/realms/teleports/protocol/saml/descriptor for connector keycloak services/saml.go:66
2024-10-25T20:06:48Z DEBU             [SAML] SSO: https://idp.example.com/realms/teleports/protocol/saml services/saml.go:124
2024-10-25T20:06:48Z DEBU             [SAML] Issuer: https://idp.example.com/realms/teleports services/saml.go:125
2024-10-25T20:06:48Z DEBU             [SAML] ACS: https://teleport.example.com/v1/webapi/saml/acs/keycloak services/saml.go:126
2024-10-25T20:07:12Z DEBU             [SAML] Successfully fetched entity descriptor from https://idp.example.com/realms/teleports/protocol/saml/descriptor for connector keycloak services/saml.go:66
2024-10-25T20:07:12Z DEBU             [SAML] SSO: https://idp.example.com/realms/teleports/protocol/saml services/saml.go:124
2024-10-25T20:07:12Z DEBU             [SAML] SSO: https://idp.example.com/realms/teleports/protocol/saml services/saml.go:124
2024-10-25T20:07:12Z DEBU             [SAML] Issuer: https://idp.example.com/realms/teleports services/saml.go:125
2024-10-25T20:07:12Z DEBU             [SAML] ACS: https://teleport.example.com/v1/webapi/saml/acs/keycloak services/saml.go:126
2024-10-25T20:07:13Z DEBU             [SAML] Successfully fetched entity descriptor from https://idp.example.com/realms/teleports/protocol/saml/descriptor for connector keycloak services/saml.go:66
2024-10-25T20:07:13Z DEBU             [SAML] SSO: https://idp.example.com/realms/teleports/protocol/saml services/saml.go:124
2024-10-25T20:07:13Z DEBU             [SAML] Issuer: https://idp.example.com/realms/teleports services/saml.go:125
2024-10-25T20:07:13Z DEBU             [SAML] ACS: https://teleport.example.com/v1/webapi/saml/acs/keycloak services/saml.go:126
2024-10-25T20:07:14Z DEBU [AUTH:COMP] d00bae72-9dc4-4be0-a02e-b107603cfc6b: acquiring semaphore in order to complete uploads events/complete.go:181
2024-10-25T20:07:18Z DEBU             [SAML] Successfully fetched entity descriptor from https://idp.example.com/realms/teleports/protocol/saml/descriptor for connector keycloak services/saml.go:66
2024-10-25T20:07:18Z DEBU             [SAML] SSO: https://idp.example.com/realms/teleports/protocol/saml services/saml.go:124
2024-10-25T20:07:18Z DEBU             [SAML] Issuer: https://idp.example.com/realms/teleports services/saml.go:125
2024-10-25T20:07:18Z DEBU             [SAML] ACS: https://teleport.example.com/v1/webapi/saml/acs/keycloak services/saml.go:126
2024-10-25T20:08:47Z DEBU             [SAML] Successfully fetched entity descriptor from https://idp.example.com/realms/teleports/protocol/saml/descriptor for connector keycloak services/saml.go:66
2024-10-25T20:08:47Z DEBU             [SAML] SSO: https://idp.example.com/realms/teleports/protocol/saml services/saml.go:124
2024-10-25T20:08:47Z DEBU             [SAML] Issuer: https://idp.example.com/realms/teleports services/saml.go:125
2024-10-25T20:08:47Z DEBU             [SAML] ACS: https://teleport.example.com/v1/webapi/saml/acs/keycloak services/saml.go:126
2024-10-25T20:08:49Z DEBU             [SAML] Successfully fetched entity descriptor from https://idp.example.com/realms/teleports/protocol/saml/descriptor for connector keycloak services/saml.go:66
2024-10-25T20:08:49Z DEBU             [SAML] SSO: https://idp.example.com/realms/teleports/protocol/saml services/saml.go:124
2024-10-25T20:08:49Z DEBU             [SAML] Issuer: https://idp.example.com/realms/teleports services/saml.go:125
2024-10-25T20:08:49Z DEBU             [SAML] ACS: https://teleport.example.com/v1/webapi/saml/acs/keycloak services/saml.go:126
2024-10-25T20:09:08Z DEBU             [SAML] Successfully fetched entity descriptor from https://idp.example.com/realms/teleports/protocol/saml/descriptor for connector keycloak services/saml.go:66
2024-10-25T20:09:08Z DEBU             [SAML] SSO: https://idp.example.com/realms/teleports/protocol/saml services/saml.go:124
2024-10-25T20:09:08Z DEBU             [SAML] Issuer: https://idp.example.com/realms/teleports services/saml.go:125
2024-10-25T20:09:08Z DEBU             [SAML] ACS: https://teleport.example.com/v1/webapi/saml/acs/keycloak services/saml.go:126
```

**Keyloak Logs**
```
keycloak-1     | 2024-10-24 15:12:12,138 DEBUG [org.keycloak.protocol.saml.SamlService] (executor-thread-587) SAML GET
keycloak-1     | 2024-10-24 15:12:12,138 DEBUG [org.keycloak.saml.SAMLRequestParser] (executor-thread-587) SAML Redirect Binding
keycloak-1     | 2024-10-24 15:12:12,139 DEBUG [org.keycloak.saml.SAMLRequestParser] (executor-thread-587) <samlp:AuthnRequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" ID="_427d29d2-4168-46f1-9f0e-448ea7bbeab2" Version="2.0" ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" AssertionConsumerServiceURL="https://teleport.example.com/v1/webapi/saml/acs/keycloak" IssueInstant="2024-10-24T15:12:11Z" Destination="https://idp.example.com/realms/teleports/protocol/saml"><saml:Issuer>https://teleport.example.com/v1/webapi/saml/acs/keycloak</saml:Issuer><ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#"><ds:SignedInfo><ds:CanonicalizationMethod Algorithm="http://www.w3.org/2006/12/xml-c14n11"/><ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/><ds:Reference URI="#_427d29d2-4168-46f1-9f0e-448ea7bbeab2"><ds:Transforms><ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/><ds:Transform Algorithm="http://www.w3.org/2006/12/xml-c14n11"/></ds:Transforms><ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/><ds:DigestValue>h2ECSMeiKtQ1q+RkzgHzn/CZCkHPP4dbFNgKn7OytVc=</ds:DigestValue></ds:Reference></ds:SignedInfo><ds:SignatureValue>awUc2OPmDpo820BLrbIzkoJcUI0ERgST8zTD7tKnG3Igr7wLw60Z1Sx7hC20/K2hKHoUwjj4gzmwfvOsWtPCS+ewESp4uRGbI28sevV8QC0PX7oZvi52zlJrrJ+hsFJsnwQLYVYCVC3iGdkKQIFK1D62Byt9AJ7o/79D854cikFqT/HuaXjcS55+/Sve9PutTTXTJlEyerHW0oyVd/hhS3ExwLb397OThBw9Bp4hdXvtLk6K5ytuZ0rG3I6/U2P7pZ4NeE1zNOQPDTlFKNnsMvYaMvckriNLt0zvIKrej1XuJQVo2NslKcVLj3PR1ADT5zbtFAuMhrx202a+XGfGTQ==</ds:SignatureValue><ds:KeyInfo><ds:X509Data><ds:X509Certificate>MIIDKzCCAhOgAwIBAgIRAInNLVLu2LNR6knBKz8zbyMwDQYJKoZIhvcNAQELBQAwQDEVMBMGA1UEChMMVGVsZXBvcnQgT1NTMScwJQYDVQQDEx50ZWxlcG9ydC5sb2NhbGhvc3QubG9jYWxkb21haW4wHhcNMjQxMDI0MTQ0MzIxWhcNMzQxMDIyMTQ0MzIxWjBAMRUwEwYDVQQKEwxUZWxlcG9ydCBPU1MxJzAlBgNVBAMTHnRlbGVwb3J0LmxvY2FsaG9zdC5sb2NhbGRvbWFpbjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAO747BjIJGo61//X5QzZHO/PVGUc0Sfig/f7f5zPrzZh7YrKXSJWyKE2XvJKG9nDiRQwZn9f19uXmi2M2ncATztnZXMLvcvWzjnuBoUYTGFmib1vb9QnrDT1892Z4hwTC8zGpNIYYaco+xUki9sFWCNpJA5I7zZCVQhF+0XUg6ukqAP8Z4YivSdbxiZPfWfb8F60tni/YLMjA65TPGyU9W1ze15OV81U39mKFRuoM9axi0bnnaYGoi4NwXdKr6rOXPDTzrPVlDKNgRP9HEoRAiTDWhjfriOtA0niyd6+UN0f+2f4Uk11B5GpzxhRKpc/gTe99HPHJggE0iCFDViGUf8CAwEAAaMgMB4wDgYDVR0PAQH/BAQDAgeAMAwGA1UdEwEB/wQCMAAwDQYJKoZIhvcNAQELBQADggEBAALB5L/hoIJynRdeBkGLNVFJ/JXtUWC9rpeyH0zx0h31obrhtgdj8c1YhShTShB6zib8HwCo5P+dr/5LUldd2avtBzmHooxfrOgVUfEdzLs2oOpsT2EoRqqHwuya1BV+/d8G33q6mJaxD6Qi7c95QDaasNj2vtWSWN37QvZkhGopHxpzuRzo6xECDsD6R2+QxcUMYvjE6q3DqK9piYOyIeSWT3vmVJk3bFE8ti0MXmqLMxGxySQCMItAuqY5zSoZZ+RJGNp6IN30vfgDRyWCeMuwdo8kB6lgBL0EPoK0xI571Ml66pHv9f6CcCUb5kZ26ImZUtGVhTH13Q6MdXfQ//Y=</ds:X509Certificate></ds:X509Data></ds:KeyInfo></ds:Signature><samlp:NameIDPolicy AllowCreate="true" Format="urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified"/></samlp:AuthnRequest>
keycloak-1     | 2024-10-24 15:12:12,143 DEBUG [org.keycloak.protocol.saml.SamlService] (executor-thread-587) ** login request
keycloak-1     | 2024-10-24 15:12:12,144 DEBUG [org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl] (executor-thread-587) `hibernate.connection.provider_disables_autocommit` was enabled.  This setting should only be enabled when you are certain that the Connections given to Hibernate by the ConnectionProvider have auto-commit disabled.  Enabling this setting when the Connections do not have auto-commit disabled will lead to Hibernate executing SQL operations outside of any JDBC/SQL transaction.
keycloak-1     | 2024-10-24 15:12:12,144 DEBUG [org.hibernate.resource.transaction.backend.jta.internal.JtaTransactionCoordinatorImpl] (executor-thread-587) Hibernate RegisteredSynchronization successfully registered with JTA platform
keycloak-1     | 2024-10-24 15:12:12,144 DEBUG [org.hibernate.orm.sql.exec] (executor-thread-587) Skipping reading Query result cache data: cache-enabled = false, cache-mode = NORMAL
keycloak-1     | 2024-10-24 15:12:12,144 DEBUG [org.hibernate.orm.results] (executor-thread-587) Initializer list is empty
keycloak-1     | 2024-10-24 15:12:12,144 DEBUG [org.hibernate.SQL] (executor-thread-587) select ce1_0.ID from public.CLIENT ce1_0 where ce1_0.CLIENT_ID=? and ce1_0.REALM_ID=?
keycloak-1     | 2024-10-24 15:12:12,144 FINE  [org.postgresql.jdbc.PgConnection] (executor-thread-587)   setAutoCommit = false
keycloak-1     | 2024-10-24 15:12:12,145 DEBUG [org.hibernate.orm.results.loading] (executor-thread-587) Calling top-level assembler (0 / 1) : org.hibernate.sql.results.graph.basic.BasicResultAssembler@4bb70ca7
keycloak-1     | 2024-10-24 15:12:12,145 DEBUG [org.hibernate.orm.results] (executor-thread-587) Extracted JDBC value [0] - [296a2302-b625-4f24-983c-1e11526833bb]
keycloak-1     | 2024-10-24 15:12:12,146 DEBUG [jdk.event.security] (executor-thread-587) X509Certificate: Alg:SHA256WITHRSA, Serial:89cd2d52eed8b351ea49c12b3f336f23, Subject:CN=teleport.localhost.localdomain, O=Teleport OSS, Issuer:CN=teleport.localhost.localdomain, O=Teleport OSS, Key type:RSA, Length:2048, Cert Id:1486966778, Valid from:10/24/24, 2:43 PM, Valid until:10/22/34, 2:43 PM
keycloak-1     | 2024-10-24 15:12:12,147 ERROR [org.keycloak.protocol.saml.SamlService] (executor-thread-587) request validation failed: org.keycloak.common.VerificationException: SigAlg was null
keycloak-1     | 	at org.keycloak.protocol.saml.SamlProtocolUtils.verifyRedirectSignature(SamlProtocolUtils.java:154)
keycloak-1     | 	at org.keycloak.protocol.saml.SamlProtocolUtils.verifyRedirectSignature(SamlProtocolUtils.java:144)
keycloak-1     | 	at org.keycloak.protocol.saml.SamlService$RedirectBindingProtocol.verifySignature(SamlService.java:836)
keycloak-1     | 	at org.keycloak.protocol.saml.SamlService$BindingProtocol.handleSamlRequest(SamlService.java:314)
keycloak-1     | 	at org.keycloak.protocol.saml.SamlService$BindingProtocol.execute(SamlService.java:720)
keycloak-1     | 	at org.keycloak.protocol.saml.SamlService.redirectBinding(SamlService.java:888)
keycloak-1     | 	at org.keycloak.protocol.saml.SamlService$quarkusrestinvoker$redirectBinding_f029009a8f864880d0a24aa96e434ce2f5c9e801.invoke(Unknown Source)
keycloak-1     | 	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
keycloak-1     | 	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
keycloak-1     | 	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
keycloak-1     | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
keycloak-1     | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
keycloak-1     | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
keycloak-1     | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
keycloak-1     | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
keycloak-1     | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
keycloak-1     | 	at java.base/java.lang.Thread.run(Thread.java:1583)
keycloak-1     |
keycloak-1     | 2024-10-24 15:12:12,149 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (executor-thread-587) new JtaTransactionWrapper
keycloak-1     | 2024-10-24 15:12:12,150 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (executor-thread-587) was existing? true
keycloak-1     | 2024-10-24 15:12:12,150 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (executor-thread-587) JtaTransactionWrapper  commit
keycloak-1     | 2024-10-24 15:12:12,150 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (executor-thread-587) JtaTransactionWrapper end
keycloak-1     | 2024-10-24 15:12:12,150 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (executor-thread-587) JtaTransactionWrapper resuming suspended
keycloak-1     | 2024-10-24 15:12:12,150 WARN  [org.keycloak.events] (executor-thread-587) type="LOGIN_ERROR", realmId="bf32ea85-e282-4bad-b76c-e22429e55ecb", realmName="teleports", clientId="null", userId="null", ipAddress="82.44.53.79", error="invalid_signature"
keycloak-1     | 2024-10-24 15:12:12,152 FINE  [freemarker.cache] (executor-thread-587) Couldn't find template in cache for "error.ftl"("en_US", UTF-8, parsed); will try to load it.
keycloak-1     | 2024-10-24 15:12:12,152 FINE  [freemarker.cache] (executor-thread-587) TemplateLoader.findTemplateSource("error_en_US.ftl"): Not found
keycloak-1     | 2024-10-24 15:12:12,152 FINE  [freemarker.cache] (executor-thread-587) TemplateLoader.findTemplateSource("error_en.ftl"): Not found
keycloak-1     | 2024-10-24 15:12:12,153 FINE  [freemarker.cache] (executor-thread-587) TemplateLoader.findTemplateSource("error.ftl"): Found
keycloak-1     | 2024-10-24 15:12:12,153 FINE  [freemarker.cache] (executor-thread-587) Loading template for "error.ftl"("en_US", UTF-8, parsed) from "jar:file:/opt/keycloak/lib/lib/main/org.keycloak.keycloak-themes-25.0.1.jar!/theme/base/login/error.ftl"
keycloak-1     | 2024-10-24 15:12:12,153 FINE  [freemarker.cache] (executor-thread-587) Couldn't find template in cache for "template.ftl"("en_US", UTF-8, parsed); will try to load it.
keycloak-1     | 2024-10-24 15:12:12,154 FINE  [freemarker.cache] (executor-thread-587) TemplateLoader.findTemplateSource("template_en_US.ftl"): Not found
keycloak-1     | 2024-10-24 15:12:12,154 FINE  [freemarker.cache] (executor-thread-587) TemplateLoader.findTemplateSource("template_en.ftl"): Not found
keycloak-1     | 2024-10-24 15:12:12,154 FINE  [freemarker.cache] (executor-thread-587) TemplateLoader.findTemplateSource("template.ftl"): Found
keycloak-1     | 2024-10-24 15:12:12,154 FINE  [freemarker.cache] (executor-thread-587) Loading template for "template.ftl"("en_US", UTF-8, parsed) from "jar:file:/opt/keycloak/lib/lib/main/org.keycloak.keycloak-themes-25.0.1.jar!/theme/base/login/template.ftl"
keycloak-1     | 2024-10-24 15:12:12,158 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (executor-thread-587) JtaTransactionWrapper  commit
keycloak-1     | 2024-10-24 15:12:12,158 DEBUG [org.hibernate.engine.transaction.internal.TransactionImpl] (executor-thread-587) On TransactionImpl creation, JpaCompliance#isJpaTransactionComplianceEnabled == false
keycloak-1     | 2024-10-24 15:12:12,159 DEBUG [org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl] (executor-thread-587) Initiating JDBC connection release from beforeTransactionCompletion
keycloak-1     | 2024-10-24 15:12:12,159 FINE  [org.postgresql.jdbc.PgConnection] (executor-thread-587)   setAutoCommit = true
keycloak-1     | 2024-10-24 15:12:12,159 DEBUG [org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl] (executor-thread-587) Initiating JDBC connection release from afterTransaction
keycloak-1     | 2024-10-24 15:12:12,160 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (executor-thread-587) JtaTransactionWrapper end
keycloak-1     | 2024-10-24 15:12:12,355 DEBUG [com.arjuna.ats.arjuna] (Periodic Recovery) Periodic recovery second pass at Thu, 24 Oct 2024 15:12:12
keycloak-1     | 2024-10-24 15:12:12,355 DEBUG [com.arjuna.ats.arjuna] (Periodic Recovery) AtomicActionRecoveryModule second pass
keycloak-1     | 2024-10-24 15:12:12,355 DEBUG [com.arjuna.ats.arjuna] (Periodic Recovery) Recovery module 'com.arjuna.ats.internal.arjuna.recovery.AtomicActionRecoveryModule@5bc30bde' second pass processed
keycloak-1     | 2024-10-24 15:12:12,355 DEBUG [com.arjuna.ats.jta] (Periodic Recovery) XARecoveryModule state change BETWEEN_PASSES->SECOND_PASS
keycloak-1     |
```

More info:

```
<samlp:AuthnRequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" ID="_427d29d2-4168-46f1-9f0e-448ea7bbeab2" Version="2.0" ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" AssertionConsumerServiceURL="https://teleport.example.com/v1/webapi/saml/acs/keycloak" IssueInstant="2024-10-24T15:12:11Z" Destination="https://idp.example.com/realms/teleports/protocol/saml">
    <saml:Issuer>https://teleport.example.com/v1/webapi/saml/acs/keycloak</saml:Issuer>
    <ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
        <ds:SignedInfo>
            <ds:CanonicalizationMethod Algorithm="http://www.w3.org/2006/12/xml-c14n11"/>
            <ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/>
            <ds:Reference URI="#_427d29d2-4168-46f1-9f0e-448ea7bbeab2">
                <ds:Transforms>
                    <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
                    <ds:Transform Algorithm="http://www.w3.org/2006/12/xml-c14n11"/>
                </ds:Transforms>
                <ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
                <ds:DigestValue>h2ECSMeiKtQ1q+RkzgHzn/CZCkHPP4dbFNgKn7OytVc=</ds:DigestValue>
            </ds:Reference>
        </ds:SignedInfo>
        <ds:SignatureValue>awUc2OPmDpo820BLrbIzkoJcUI0ERgST8zTD7tKnG3Igr7wLw60Z1Sx7hC20/K2hKHoUwjj4gzmwfvOsWtPCS+ewESp4uRGbI28sevV8QC0PX7oZvi52zlJrrJ+hsFJsnwQLYVYCVC3iGdkKQIFK1D62Byt9AJ7o/79D854cikFqT/HuaXjcS55+/Sve9PutTTXTJlEyerHW0oyVd/hhS3ExwLb397OThBw9Bp4hdXvtLk6K5ytuZ0rG3I6/U2P7pZ4NeE1zNOQPDTlFKNnsMvYaMvckriNLt0zvIKrej1XuJQVo2NslKcVLj3PR1ADT5zbtFAuMhrx202a+XGfGTQ==</ds:SignatureValue>
        <ds:KeyInfo>
            <ds:X509Data>
                <ds:X509Certificate></ds:X509Certificate>
            </ds:X509Data>
        </ds:KeyInfo>
    </ds:Signature>
    <samlp:NameIDPolicy AllowCreate="true" Format="urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified"/>
</samlp:AuthnRequest>
```

**Comment by flyinghermit** [comment]
I sightly updated the title to make it clear that the issue is related to auth connector and not the Teleport SAML IdP. Also removed `saml-idp` label for the same reason.
