### ISSUE TITLE
blank page shown after selecting home link from session player

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#48333]
Expected behavior:

Home menu link navigates to home

Current behavior:

A blank white page is shown after a user select the Home Link from the upper right menu in the session player page. Video attached. 

This was consistent in incognito browser sessions and regular browser sessions in Google chrome `130.0.6723.92` on macos. In Safari, Firefox the behavior is not observed and it navigates home as expected.

![Image](https://github.com/user-attachments/assets/b907b8fc-09f3-42ac-a469-fcd0a948edd4)

https://github.com/user-attachments/assets/06ea66e7-e6f8-44d2-aabc-57510cf8e4bb

Refreshing the page will show the home resources as expected

Bug details:
- Teleport version: 16.4.6 and 17 alpha
- Recreation steps
1. Open a Teleport Web UI session in Google Chrome (macos confirmed)
2. Open a session to replay
3. Select the `...` upper right menu and click Home

Web developer console:

![Image](https://github.com/user-attachments/assets/1d38bd5e-2729-412f-b35e-5f821e15a4e8)

![Image](https://github.com/user-attachments/assets/dc7a3f1e-efc2-41b1-8d94-2ca1ab5a7856)

**Comment by bl-nero** [comment]
The real culprit here was the error that started it all:

```
Uncaught InvalidStateError: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.
    at TtyPlayer.stop (ttyPlayer.js:251:20)
    at SshPlayer.tsx:117:11
    at safelyCallDestroy (chunk-A6E3XU77.js?v=5ad3bb1d:16748:13)
    at commitHookEffectListUnmount (chunk-A6E3XU77.js?v=5ad3bb1d:16875:19)
    at commitPassiveUnmountInsideDeletedTreeOnFiber (chunk-A6E3XU77.js?v=5ad3bb1d:18283:17)
    at commitPassiveUnmountEffectsInsideOfDeletedTree_begin (chunk-A6E3XU77.js?v=5ad3bb1d:18245:13)
    at commitPassiveUnmountEffects_begin (chunk-A6E3XU77.js?v=5ad3bb1d:18181:19)
    at commitPassiveUnmountEffects (chunk-A6E3XU77.js?v=5ad3bb1d:18169:11)
    at flushPassiveEffectsImpl (chunk-A6E3XU77.js?v=5ad3bb1d:19489:11)
    at flushPassiveEffects (chunk-A6E3XU77.js?v=5ad3bb1d:19447:22)
```
