### ISSUE TITLE
Error during desktop session playback with directory sharing

### ISSUE THREAD

**Issue by probakowski** [gravitational/teleport#48400]
Expected behavior:
Session recording should work even if directory sharing was used during the session.

Current behavior:
When recording gets to the point when you open shared directory error shows up:
```
panicked at /Users/runner/.cargo/git/checkouts/ironrdp-cc592b0b50166368/92efe2a/crates/ironrdp-session/src/fast_path.rs:436:65:
called `Option::unwrap()` on a `None` value

Stack:

Error
    at e.wbg.__wbg_new_abda76e883ba8a5f (https://cluster:3080/web/app/app.js:2142:4811)
    at https://cluster:3080/web/app/ironrdp_bg.wasm:wasm-function[594]:0x5899c
    at https://cluster:3080/web/app/ironrdp_bg.wasm:wasm-function[271]:0x4f0c3
    at https://cluster:3080/web/app/ironrdp_bg.wasm:wasm-function[400]:0x56017
    at https://cluster:3080/web/app/ironrdp_bg.wasm:wasm-function[410]:0x562cd
    at https://cluster:3080/web/app/ironrdp_bg.wasm:wasm-function[544]:0x57883
    at https://cluster:3080/web/app/ironrdp_bg.wasm:wasm-function[23]:0x1bad
    at D6e.process (https://cluster:3080/web/app/app.js:2142:3797)
    at U6e.handleRdpFastPathPDU (https://cluster:3080/web/app/app.js:2142:28201)
    at U6e.processMessage (https://cluster:3080/web/app/app.js:2142:25533)
```

```
[TDPClient] RuntimeError: unreachable
    at ironrdp_bg.wasm:0x4f0e7
    at ironrdp_bg.wasm:0x56017
    at ironrdp_bg.wasm:0x562cd
    at ironrdp_bg.wasm:0x57883
    at ironrdp_bg.wasm:0x1bad
    at D6e.process (app.js:2142:3797)
    at U6e.handleRdpFastPathPDU (app.js:2142:28201)
    at U6e.processMessage (app.js:2142:25533)
    at U6e.processMessage (app.js:2142:36783)
    at socket.onmessage [as onmessageInternal] (app.js:2142:24640)
```
Bug details:
- Teleport version
   `v17.0.0-alpha.2` but I assume it's there from v15
- Recreation steps
  Start desktop session, enable directory sharing, open shared folder. Go to session recording for that session, it should error out when folder is open during playback
- Debug logs

**Comment by zmb3** [comment]
Fixed upstream in https://github.com/Devolutions/IronRDP/pull/597.
