### ISSUE TITLE
`TestRootUTMPEntryExists` flakiness

### ISSUE THREAD

**Issue by rosstimothy** [gravitational/teleport#49698]
#### Link(s) to logs

- https://github.com/gravitational/teleport/actions/runs/12141893578/job/33855069443

#### Relevant snippet

```
panic: Assertion failed

goroutine 11438 [running]:
github.com/stretchr/testify/assert.(*CollectT).FailNow(0x17de2da0?)
	/go/pkg/mod/github.com/stretchr/testify@v1.9.0/assert/assertions.go:1924 +0x2b
github.com/stretchr/testify/require.NoError({0x17e3b898, 0xc00576e420}, {0x17de5040, 0xc005910d20}, {0x0, 0x0, 0x0})
	/go/pkg/mod/github.com/stretchr/testify@v1.9.0/require/require.go:1357 +0xe4
github.com/gravitational/teleport/integration.TestRootUTMPEntryExists.func1.2(0xc00576e420)
	/__w/teleport/teleport/integration/utmp_integration_test.go:121 +0xad
github.com/stretchr/testify/assert.EventuallyWithT.func1()
	/go/pkg/mod/github.com/stretchr/testify@v1.9.0/assert/assertions.go:1983 +0xb8
created by github.com/stretchr/testify/assert.EventuallyWithT in goroutine 11411
	/go/pkg/mod/github.com/stretchr/testify@v1.9.0/assert/assertions.go:1978 +0x42b
```

**Comment by kopiczko** [comment]
I ran into this:

https://github.com/gravitational/core/actions/runs/32309151034/job/96248433474

```
    utmp_integration_test.go:142: 
        	Error Trace:	/__w/core/core/integration/utmp_integration_test.go:150
        	            				/opt/go/src/runtime/asm_amd64.s:1771
        	Error:      	Should be true
    utmp_integration_test.go:142: 
        	Error Trace:	/__w/core/core/integration/utmp_integration_test.go:142
        	Error:      	Condition never satisfied
        	Test:       	TestRootUTMPEntryExists/successful_login_is_logged_in_utmp_and_wtmp
        	Messages:   	did not detect utmp entry within 5 minutes
```

**Comment by smallinsky** [comment]
https://github.com/gravitational/core/actions/runs/32855811928/job/97827503355

```
{"timestamp":"2026-08-25T14:04:50Z","level":"debug","caller":"events/stream.go:703","message":"Inactivity timer ticked and did not exceeded threshold. Resetting ticker.","tick":"2026-08-25T14:04:50.464808404Z","inactivity_period":299986562446,"next_tick":13437554}
    utmp_integration_test.go:142: 
        	Error Trace:	/__w/core/core/integration/utmp_integration_test.go:150
        	            				/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.26.7.linux-amd64/src/runtime/asm_amd64.s:1771
        	Error:      	Should be true
    utmp_integration_test.go:142: 
        	Error Trace:	/__w/core/core/integration/utmp_integration_test.go:142
        	Error:      	Condition never satisfied
        	Test:       	TestRootUTMPEntryExists/successful_login_is_logged_in_utmp_and_wtmp
        	Messages:   	did not detect utmp entry within 5 minutes
    --- FAIL: TestRootUTMPEntryExists/successful_login_is_logged_in_utmp_and_wtmp (300.18s)
```

**Comment by smallinsky** [comment]
https://github.com/gravitational/core/actions/runs/33055288312/job/98460462296?pr=823

```
{"timestamp":"2026-08-27T08:57:06Z","level":"debug","caller":"events/stream.go:703","message":"Inactivity timer ticked and did not exceeded threshold. Resetting ticker.","tick":"2026-08-27T08:57:06.190942958Z","inactivity_period":299987359045,"next_tick":12640955}
    utmp_integration_test.go:142: 
        	Error Trace:	/__w/core/core/integration/utmp_integration_test.go:150
        	            				/opt/go/src/runtime/asm_amd64.s:1771
        	Error:      	Should be true
    utmp_integration_test.go:142: 
        	Error Trace:	/__w/core/core/integration/utmp_integration_test.go:142
        	Error:      	Condition never satisfied
        	Test:       	TestRootUTMPEntryExists/successful_login_is_logged_in_utmp_and_wtmp
        	Messages:   	did not detect utmp entry within 5 minutes
{"timestamp":"2026-08-27T08:57:06Z","level":"debug","caller":"sshutils/server.go:578","message":"Closed connection","component":"ssh:node","remote_addr":"127.0.0.1:48056"}
    --- FAIL: TestRootUTMPEntryExists/successful_login_is_logged_in_utmp_and_wtmp (300.18s)
```

**Comment by ravicious** [comment]
https://github.com/gravitational/core/actions/runs/33259867490/job/99119864377?pr=931#step:5:611

**Comment by ravicious** [comment]
https://github.com/gravitational/core/actions/runs/33395812338/job/99499979245?pr=945#step:5:611

**Comment by smallinsky** [comment]
https://github.com/gravitational/core/actions/runs/33395283251/job/99498340782?pr=599

**Comment by smallinsky** [comment]
https://github.com/gravitational/core/actions/runs/33424813710/job/99595750854

**Comment by rosstimothy** [comment]
@atburke is looking into this.

**Comment by ravicious** [comment]
* https://github.com/gravitational/core/actions/runs/33498572776/job/99826431347#step:5:623
* https://github.com/gravitational/core/actions/runs/33498572776/job/99826431347
