### ISSUE TITLE
Panic when setting up SCIM-only Okta integration

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#49903]
Running this:
```
tctl plugins install okta  \
  --org https://dev-xxx.oktapreview.com/ \
  --saml-connector "okta" \
  --no-users-sync \
  --no-accesslist-sync \
  --no-appgroup-sync \
  --scim
```
Results in this panic:
```
http: panic serving 34.194.59.11:19979: runtime error: invalid memory address or nil pointer dereference
goroutine 29783 [running]:
net/http.(*conn).serve.func1()
	net/http/server.go:1947 +0xb0
panic({0xc990f9cbba20?, 0xc99101323750?})
	runtime/panic.go:785 +0x124
github.com/gravitational/teleport/e/lib/scim/sdk.UnmarshalResource({0xc990fb374a88?, 0x40043c4f90?})
	github.com/gravitational/teleport/e/lib/scim/sdk/conv.go:77 +0xd4
github.com/gravitational/teleport/e/lib/web.(*Plugin).scimCreateResource(0x40034f1440, {0xc990fb46a180, 0x4003c704e0}, 0x4002629e00, {0x400459b580, 0x2, 0x40044fac18?})
	github.com/gravitational/teleport/e/lib/web/scim.go:228 +0x2fc
github.com/gravitational/teleport/e/lib/web.(*Plugin).registerSCIMHandlers.(*Plugin).wrapSCIMRequest.func4({0xc990fb46a180, 0x4003c704e0}, 0x4002629e00, {0x400459b580, 0x2, 0x2})
	github.com/gravitational/teleport/e/lib/web/scim.go:86 +0x1d4
github.com/gravitational/teleport/lib/web.(*Handler).WithHighLimiterHandlerFunc-fm.(*Handler).WithHighLimiterHandlerFunc.func1({0xc990fb46a180, 0x4003c704e0}, 0x4002629e00, {0x400459b580, 0x2, 0x2})
	github.com/gravitational/teleport/lib/web/apiserver.go:4754 +0xa4
github.com/gravitational/teleport/e/lib/web.(*Plugin).registerSCIMHandlers.(*Handler).WithUnauthenticatedHighLimiter.(*Handler).unauthenticatedLimiterFunc.func13({0xc990fb46a180, 0x4003c704e0}, 0x4002629e00, {0x400459b580, 0x2, 0x2})
	github.com/gravitational/teleport/lib/web/apiserver.go:4708 +0xf0
github.com/gravitational/teleport/e/lib/web.(*Plugin).registerSCIMHandlers.(*Handler).WithUnauthenticatedHighLimiter.(*Handler).unauthenticatedLimiterFunc.MakeHandler.MakeHandlerWithErrorWriter.func22({0xc990fb46a180, 0x4003c704e0}, 0x4002629e00, {0x400459b580, 0x2, 0x2})
	github.com/gravitational/teleport/lib/httplib/httplib.go:127 +0x8c
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0x4002360528, {0xc990fb46a180, 0x4003c704e0}, 0x4002629e00)
	github.com/julienschmidt/httprouter@v1.3.0/router.go:399 +0x718
github.com/gravitational/teleport/lib/web.NewHandler.func1.StripPrefix.1({0xc990fb46a180, 0x4003c704e0}, 0x4002629cc0)
	net/http/server.go:2282 +0x228
net/http.HandlerFunc.ServeHTTP(0x4003f91710?, {0xc990fb46a180?, 0x4003c704e0?}, 0xc990fa7588e0?)
	net/http/server.go:2220 +0x38
github.com/gravitational/teleport/lib/web.NewHandler.func1({0xc990fb46a180, 0x4003c704e0}, 0x4002629cc0)
	github.com/gravitational/teleport/lib/web/apiserver.go:622 +0x654
net/http.HandlerFunc.ServeHTTP(0xc990f9c21dc0?, {0xc990fb46a180?, 0x4003c704e0?}, 0x4?)
	net/http/server.go:2220 +0x38
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0x4002360528, {0xc990fb46a180, 0x4003c704e0}, 0x4002629cc0)
	github.com/julienschmidt/httprouter@v1.3.0/router.go:460 +0x574
github.com/gravitational/teleport/lib/web.(*APIHandler).ServeHTTP(0x4002467170, {0xc990fb46a180, 0x4003c704e0}, 0x4002629cc0)
	github.com/gravitational/teleport/lib/web/apiserver.go:450 +0x174
github.com/gravitational/teleport/lib/limiter/internal/ratelimit.(*TokenLimiter).ServeHTTP(0x40036d3b00, {0xc990fb46a180, 0x4003c704e0}, 0x4002629cc0)
	github.com/gravitational/teleport/lib/limiter/internal/ratelimit/ratelimit.go:106 +0x1a4
github.com/gravitational/teleport/lib/limiter.(*ConnectionsLimiter).ServeHTTP(0x400376ade0, {0xc990fb46a180, 0x4003c704e0}, 0x4002629cc0)
	github.com/gravitational/teleport/lib/limiter/connlimiter.go:82 +0x1cc
github.com/gravitational/teleport/lib/limiter.(*Limiter).ServeHTTP(0x4003f916b0?, {0xc990fb46a180?, 0x4003c704e0?}, 0xb?)
	github.com/gravitational/teleport/lib/limiter/limiter.go:82 +0x28
github.com/gravitational/teleport/lib/httplib.MakeTracingHandler.func1({0xc990fb46a180, 0x4003c704e0}, 0x4002629cc0)
	github.com/gravitational/teleport/lib/httplib/httplib.go:104 +0x190
net/http.HandlerFunc.ServeHTTP(0xc990fb4758f8?, {0xc990fb46a180?, 0x4003c704e0?}, 0xc990f7faaf00?)
	net/http/server.go:2220 +0x38
go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*middleware).serveHTTP(0x4004319a00, {0xc990fb449260, 0x400416eee0}, 0x4002629b80, {0xc990fb374d80, 0x40025b0480})
	go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.55.0/handler.go:177 +0xda0
go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.NewMiddleware.func1.1({0xc990fb449260?, 0x400416eee0?}, 0x0?)
	go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.55.0/handler.go:65 +0x40
net/http.HandlerFunc.ServeHTTP(0x10?, {0xc990fb449260?, 0x400416eee0?}, 0x400416eee0?)
	net/http/server.go:2220 +0x38
net/http.serverHandler.ServeHTTP({0xc990fb3cf4d0?}, {0xc990fb449260?, 0x400416eee0?}, 0x6?)
	net/http/server.go:3210 +0xbc
net/http.(*conn).serve(0x400418bef0, {0xc990fb4758f8, 0x4003f915c0})
	net/http/server.go:2092 +0x4fc
created by net/http.(*Server).Serve in goroutine 439
	net/http/server.go:3360 +0x3dc 
```

**Comment by r0mant** [comment]
Fixed in https://github.com/gravitational/teleport.e/pull/5653.
