### ISSUE TITLE
Data race in AuditLog/GRPC server

### ISSUE THREAD

**Issue by a-palchikov** [gravitational/teleport#5970]
<details><summary><code>Logs</code></summary>

```
==================
WARNING: DATA RACE
Read at 0x00c0003ec5f8 by goroutine 744:
  github.com/gravitational/teleport/lib/events.(*AuditLog).EmitAuditEvent()
      /go/src/github.com/gravitational/teleport/lib/events/auditlog.go:972 +0x232
  github.com/gravitational/teleport/lib/auth.(*ServerWithRoles).EmitAuditEvent()
      /go/src/github.com/gravitational/teleport/lib/auth/auth_with_roles.go:1646 +0x846
  github.com/gravitational/teleport/lib/auth.(*GRPCServer).EmitAuditEvent()
      /go/src/github.com/gravitational/teleport/lib/auth/grpcserver.go:80 +0x1a6
  github.com/gravitational/teleport/api/client/proto._AuthService_EmitAuditEvent_Handler.func1()
      /go/src/github.com/gravitational/teleport/vendor/github.com/gravitational/teleport/api/client/proto/authservice.pb.go:8013 +0xa4
  github.com/gravitational/teleport/lib/auth.(*Middleware).UnaryInterceptor()
      /go/src/github.com/gravitational/teleport/lib/auth/middleware.go:355 +0x822
  github.com/gravitational/teleport/lib/auth.(*Middleware).UnaryInterceptor-fm()
      /go/src/github.com/gravitational/teleport/lib/auth/middleware.go:327 +0x96
  github.com/gravitational/teleport/api/client/proto._AuthService_EmitAuditEvent_Handler()
      /go/src/github.com/gravitational/teleport/vendor/github.com/gravitational/teleport/api/client/proto/authservice.pb.go:8015 +0x1dd
  google.golang.org/grpc.(*Server).processUnaryRPC()
      /go/src/github.com/gravitational/teleport/vendor/google.golang.org/grpc/server.go:1082 +0xa05
  google.golang.org/grpc.(*Server).handleStream()
      /go/src/github.com/gravitational/teleport/vendor/google.golang.org/grpc/server.go:1405 +0x1397
  google.golang.org/grpc.(*Server).serveStreams.func1.1()
      /go/src/github.com/gravitational/teleport/vendor/google.golang.org/grpc/server.go:746 +0xdc

Previous write at 0x00c0003ec5f8 by goroutine 741:
  github.com/gravitational/teleport/lib/events.(*AuditLog).Close()
      /go/src/github.com/gravitational/teleport/lib/events/auditlog.go:1061 +0x21a
  github.com/gravitational/teleport/lib/auth.(*TestAuthServer).Close()
      /go/src/github.com/gravitational/teleport/lib/auth/helpers.go:250 +0xae
  github.com/gravitational/teleport/lib/web.newWebPack.func1()
      /go/src/github.com/gravitational/teleport/lib/web/apiserver_test.go:2354 +0x4e
  testing.(*common).Cleanup.func1()
      /opt/go/src/testing/testing.go:880 +0x103
  testing.(*common).Cleanup.func1.1()
      /opt/go/src/testing/testing.go:874 +0x91
  testing.(*common).Cleanup.func1()
      /opt/go/src/testing/testing.go:881 +0x104
  testing.(*common).Cleanup.func1.1()
      /opt/go/src/testing/testing.go:874 +0x91
  testing.(*common).Cleanup.func1()
      /opt/go/src/testing/testing.go:881 +0x104
  testing.(*common).Cleanup.func1.1()
      /opt/go/src/testing/testing.go:874 +0x91
  testing.(*common).Cleanup.func1()
      /opt/go/src/testing/testing.go:881 +0x104
  testing.(*common).Cleanup.func1.1()
      /opt/go/src/testing/testing.go:874 +0x91
  testing.(*common).Cleanup.func1()
      /opt/go/src/testing/testing.go:881 +0x104
  testing.(*common).Cleanup.func1.1()
      /opt/go/src/testing/testing.go:874 +0x91
  testing.(*common).Cleanup.func1()
      /opt/go/src/testing/testing.go:881 +0x104
  testing.(*common).Cleanup.func1.1()
      /opt/go/src/testing/testing.go:874 +0x91
  testing.(*common).Cleanup.func1()
      /opt/go/src/testing/testing.go:881 +0x104
  testing.(*common).Cleanup.func1.1()
      /opt/go/src/testing/testing.go:874 +0x91
  testing.(*common).Cleanup.func1()
      /opt/go/src/testing/testing.go:881 +0x104
  testing.(*common).Cleanup.func1.1()
      /opt/go/src/testing/testing.go:874 +0x91
  testing.(*common).Cleanup.func1()
      /opt/go/src/testing/testing.go:881 +0x104
  testing.(*common).Cleanup.func1.1()
      /opt/go/src/testing/testing.go:874 +0x91
  testing.(*common).Cleanup.func1()
      /opt/go/src/testing/testing.go:881 +0x104
  testing.(*common).Cleanup.func1.1()
      /opt/go/src/testing/testing.go:874 +0x91
  testing.(*common).Cleanup.func1()
      /opt/go/src/testing/testing.go:881 +0x104
  testing.(*common).Cleanup.func1.1()
      /opt/go/src/testing/testing.go:874 +0x91
  testing.(*common).Cleanup.func1()
      /opt/go/src/testing/testing.go:881 +0x104
  testing.(*common).Cleanup.func1.1()
      /opt/go/src/testing/testing.go:874 +0x91
  testing.(*common).Cleanup.func1()
      /opt/go/src/testing/testing.go:881 +0x104
  testing.(*common).Cleanup.func1.1()
      /opt/go/src/testing/testing.go:874 +0x91
  testing.(*common).Cleanup.func1()
      /opt/go/src/testing/testing.go:881 +0x104
  testing.(*common).Cleanup.func1.1()
      /opt/go/src/testing/testing.go:874 +0x91
  testing.(*common).Cleanup.func1()
      /opt/go/src/testing/testing.go:881 +0x104
  testing.(*common).runCleanup()
      /opt/go/src/testing/testing.go:957 +0xca
  testing.tRunner.func2()
      /opt/go/src/testing/testing.go:1117 +0x74
  testing.tRunner()
      /opt/go/src/testing/testing.go:1127 +0x22a

Goroutine 744 (running) created at:
  google.golang.org/grpc.(*Server).serveStreams.func1()
      /go/src/github.com/gravitational/teleport/vendor/google.golang.org/grpc/server.go:744 +0xb8
  google.golang.org/grpc/internal/transport.(*http2Server).operateHeaders()
      /go/src/github.com/gravitational/teleport/vendor/google.golang.org/grpc/internal/transport/http2_server.go:442 +0x16fd
  google.golang.org/grpc/internal/transport.(*http2Server).HandleStreams()
      /go/src/github.com/gravitational/teleport/vendor/google.golang.org/grpc/internal/transport/http2_server.go:483 +0x3e4
  google.golang.org/grpc.(*Server).serveStreams()
      /go/src/github.com/gravitational/teleport/vendor/google.golang.org/grpc/server.go:742 +0x1c1
  google.golang.org/grpc.(*Server).handleRawConn.func1()
      /go/src/github.com/gravitational/teleport/vendor/google.golang.org/grpc/server.go:703 +0x4c

Goroutine 741 (running) created at:
  testing.(*T).Run()
      /opt/go/src/testing/testing.go:1168 +0x5bb
  testing.runTests.func1()
      /opt/go/src/testing/testing.go:1439 +0xa6
  testing.tRunner()
      /opt/go/src/testing/testing.go:1123 +0x202
  testing.runTests()
      /opt/go/src/testing/testing.go:1437 +0x612
  testing.(*M).Run()
      /opt/go/src/testing/testing.go:1345 +0x3b3
  github.com/gravitational/teleport/lib/web.TestMain()
      /go/src/github.com/gravitational/teleport/lib/web/apiserver_test.go:124 +0x5c
  main.main()
      _testmain.go:155 +0x371
==================
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x174a018]

goroutine 7705 [running]:
github.com/gravitational/teleport/lib/events.(*FileLog).rotateLog(0x0, 0x0, 0x0)
	/go/src/github.com/gravitational/teleport/lib/events/filelog.go:314 +0x58
github.com/gravitational/teleport/lib/events.(*FileLog).EmitAuditEvent(0x0, 0x32907a0, 0xc00274ab40, 0x32b3b20, 0xc002010200, 0x4d7c060, 0xc0029ae750)
	/go/src/github.com/gravitational/teleport/lib/events/filelog.go:119 +0x56
github.com/gravitational/teleport/lib/events.(*AuditLog).EmitAuditEvent(0xc0003ec500, 0x32907a0, 0xc00274ab40, 0x32b3b20, 0xc002010200, 0x0, 0xa)
	/go/src/github.com/gravitational/teleport/lib/events/auditlog.go:974 +0x10e
github.com/gravitational/teleport/lib/auth.(*ServerWithRoles).EmitAuditEvent(0xc0011bb5e0, 0x32907a0, 0xc00274ab40, 0x32b3b20, 0xc002010200, 0x0, 0x32b3b20)
	/go/src/github.com/gravitational/teleport/lib/auth/auth_with_roles.go:1646 +0x847
github.com/gravitational/teleport/lib/auth.(*GRPCServer).EmitAuditEvent(0xc002470900, 0x32907a0, 0xc00274ab40, 0xc00090ca80, 0xc002470900, 0xc00274ab40, 0x1)
	/go/src/github.com/gravitational/teleport/lib/auth/grpcserver.go:80 +0x1a7
github.com/gravitational/teleport/api/client/proto._AuthService_EmitAuditEvent_Handler.func1(0x32907a0, 0xc00274ab40, 0x2ebec20, 0xc00090ca80, 0x2db1d20, 0xc002001c20, 0x32907a0, 0xc00274ab40)
	/go/src/github.com/gravitational/teleport/vendor/github.com/gravitational/teleport/api/client/proto/authservice.pb.go:8013 +0xa5
github.com/gravitational/teleport/lib/auth.(*Middleware).UnaryInterceptor(0xc001fd91c0, 0x32907a0, 0xc00090cb10, 0x2ebec20, 0xc00090ca80, 0xc001a883e0, 0xc001a88400, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/gravitational/teleport/lib/auth/middleware.go:355 +0x823
github.com/gravitational/teleport/api/client/proto._AuthService_EmitAuditEvent_Handler(0x2ecdd40, 0xc002470900, 0x32907a0, 0xc00090ca50, 0xc000a5ec60, 0xc003306f50, 0x32907a0, 0xc00090ca50, 0xc000e8e140, 0x9e)
	/go/src/github.com/gravitational/teleport/vendor/github.com/gravitational/teleport/api/client/proto/authservice.pb.go:8015 +0x1de
google.golang.org/grpc.(*Server).processUnaryRPC(0xc002046b60, 0x32a95c0, 0xc00102a300, 0xc000a2cd00, 0xc001df7140, 0x42a62c8, 0x0, 0x0, 0x0)
	/go/src/github.com/gravitational/teleport/vendor/google.golang.org/grpc/server.go:1082 +0xa06
google.golang.org/grpc.(*Server).handleStream(0xc002046b60, 0x32a95c0, 0xc00102a300, 0xc000a2cd00, 0x0)
	/go/src/github.com/gravitational/teleport/vendor/google.golang.org/grpc/server.go:1405 +0x1398
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc001979120, 0xc002046b60, 0x32a95c0, 0xc00102a300, 0xc000a2cd00)
	/go/src/github.com/gravitational/teleport/vendor/google.golang.org/grpc/server.go:746 +0xdd
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/src/github.com/gravitational/teleport/vendor/google.golang.org/grpc/server.go:744 +0xb9
FAIL	github.com/gravitational/teleport/lib/web	148.877s
```
</details>

Caught in https://drone.gravitational.io/gravitational/teleport/7719/1/6.

**Comment by webvictim** [comment]
At a guess, I'd say this flake is responsible for the majority of our test failures at the moment.

**Comment by Joerger** [comment]
This seems to have become less flaky and more serious, as today it has been failing every one of my tests. It also seems to reproduce locally with `make -C build.assets test` on master, for at least the last 3 commits. Going to try plain old `go test ./... -race` and see what happens.
