### ISSUE TITLE
Data race in tests

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#6155]
This seems to happen more when CI is under load.

```
432 | OK: 31 passed
433 | ==================
434 | WARNING: DATA RACE
435 | Read at 0x00c000bbd8f8 by goroutine 688:
436 | github.com/gravitational/teleport/lib/events.(*AuditLog).EmitAuditEvent()
437 | /go/src/github.com/gravitational/teleport/lib/events/auditlog.go:972 +0x232
438 | github.com/gravitational/teleport/lib/auth.(*ServerWithRoles).EmitAuditEvent()
439 | /go/src/github.com/gravitational/teleport/lib/auth/auth_with_roles.go:1829 +0x867
440 | github.com/gravitational/teleport/lib/auth.(*GRPCServer).EmitAuditEvent()
441 | /go/src/github.com/gravitational/teleport/lib/auth/grpcserver.go:80 +0x1a6
442 | github.com/gravitational/teleport/api/client/proto._AuthService_EmitAuditEvent_Handler.func1()
443 | /go/src/github.com/gravitational/teleport/vendor/github.com/gravitational/teleport/api/client/proto/authservice.pb.go:8131 +0xa4
444 | github.com/gravitational/teleport/lib/auth.(*Middleware).UnaryInterceptor()
445 | /go/src/github.com/gravitational/teleport/lib/auth/middleware.go:354 +0x822
446 | github.com/gravitational/teleport/lib/auth.(*Middleware).UnaryInterceptor-fm()
447 | /go/src/github.com/gravitational/teleport/lib/auth/middleware.go:326 +0x96
448 | github.com/gravitational/teleport/api/client/proto._AuthService_EmitAuditEvent_Handler()
449 | /go/src/github.com/gravitational/teleport/vendor/github.com/gravitational/teleport/api/client/proto/authservice.pb.go:8133 +0x1dd
450 | google.golang.org/grpc.(*Server).processUnaryRPC()
451 | /go/src/github.com/gravitational/teleport/vendor/google.golang.org/grpc/server.go:1082 +0xa05
452 | google.golang.org/grpc.(*Server).handleStream()
453 | /go/src/github.com/gravitational/teleport/vendor/google.golang.org/grpc/server.go:1405 +0x1397
454 | google.golang.org/grpc.(*Server).serveStreams.func1.1()
455 | /go/src/github.com/gravitational/teleport/vendor/google.golang.org/grpc/server.go:746 +0xdc
456 |  
457 | Previous write at 0x00c000bbd8f8 by goroutine 502:
458 | github.com/gravitational/teleport/lib/events.(*AuditLog).Close()
459 | /go/src/github.com/gravitational/teleport/lib/events/auditlog.go:1061 +0x21a
460 | github.com/gravitational/teleport/lib/auth.(*TestAuthServer).Close()
461 | /go/src/github.com/gravitational/teleport/lib/auth/helpers.go:251 +0xae
462 | github.com/gravitational/teleport/lib/web.newWebPack.func1()
463 | /go/src/github.com/gravitational/teleport/lib/web/apiserver_test.go:2369 +0x4e
464 | testing.(*common).Cleanup.func1()
465 | /opt/go/src/testing/testing.go:880 +0x103
466 | testing.(*common).Cleanup.func1.1()
467 | /opt/go/src/testing/testing.go:874 +0x91
468 | testing.(*common).Cleanup.func1()
469 | /opt/go/src/testing/testing.go:881 +0x104
470 | testing.(*common).Cleanup.func1.1()
471 | /opt/go/src/testing/testing.go:874 +0x91
472 | testing.(*common).Cleanup.func1()
473 | /opt/go/src/testing/testing.go:881 +0x104
474 | testing.(*common).Cleanup.func1.1()
475 | /opt/go/src/testing/testing.go:874 +0x91
476 | testing.(*common).Cleanup.func1()
477 | /opt/go/src/testing/testing.go:881 +0x104
478 | testing.(*common).Cleanup.func1.1()
479 | /opt/go/src/testing/testing.go:874 +0x91
480 | testing.(*common).Cleanup.func1()
481 | /opt/go/src/testing/testing.go:881 +0x104
482 | testing.(*common).Cleanup.func1.1()
483 | /opt/go/src/testing/testing.go:874 +0x91
484 | testing.(*common).Cleanup.func1()
485 | /opt/go/src/testing/testing.go:881 +0x104
486 | testing.(*common).Cleanup.func1.1()
487 | /opt/go/src/testing/testing.go:874 +0x91
488 | testing.(*common).Cleanup.func1()
489 | /opt/go/src/testing/testing.go:881 +0x104
490 | testing.(*common).Cleanup.func1.1()
491 | /opt/go/src/testing/testing.go:874 +0x91
492 | testing.(*common).Cleanup.func1()
493 | /opt/go/src/testing/testing.go:881 +0x104
494 | testing.(*common).Cleanup.func1.1()
495 | /opt/go/src/testing/testing.go:874 +0x91
496 | testing.(*common).Cleanup.func1()
497 | /opt/go/src/testing/testing.go:881 +0x104
498 | testing.(*common).Cleanup.func1.1()
499 | /opt/go/src/testing/testing.go:874 +0x91
500 | testing.(*common).Cleanup.func1()
501 | /opt/go/src/testing/testing.go:881 +0x104
502 | testing.(*common).Cleanup.func1.1()
503 | /opt/go/src/testing/testing.go:874 +0x91
504 | testing.(*common).Cleanup.func1()
505 | /opt/go/src/testing/testing.go:881 +0x104
506 | testing.(*common).Cleanup.func1.1()
507 | /opt/go/src/testing/testing.go:874 +0x91
508 | testing.(*common).Cleanup.func1()
509 | /opt/go/src/testing/testing.go:881 +0x104
510 | testing.(*common).Cleanup.func1.1()
511 | /opt/go/src/testing/testing.go:874 +0x91
512 | testing.(*common).Cleanup.func1()
513 | /opt/go/src/testing/testing.go:881 +0x104
514 | testing.(*common).Cleanup.func1.1()
515 | /opt/go/src/testing/testing.go:874 +0x91
516 | testing.(*common).Cleanup.func1()
517 | /opt/go/src/testing/testing.go:881 +0x104
518 | testing.(*common).Cleanup.func1.1()
519 | /opt/go/src/testing/testing.go:874 +0x91
520 | testing.(*common).Cleanup.func1()
521 | /opt/go/src/testing/testing.go:881 +0x104
522 | testing.(*common).runCleanup()
523 | /opt/go/src/testing/testing.go:957 +0xca
524 | testing.tRunner.func2()
525 | /opt/go/src/testing/testing.go:1117 +0x74
526 | testing.tRunner()
527 | /opt/go/src/testing/testing.go:1127 +0x22a
528 |  
529 | Goroutine 688 (running) created at:
530 | google.golang.org/grpc.(*Server).serveStreams.func1()
531 | /go/src/github.com/gravitational/teleport/vendor/google.golang.org/grpc/server.go:744 +0xb8
532 | google.golang.org/grpc/internal/transport.(*http2Server).operateHeaders()
533 | /go/src/github.com/gravitational/teleport/vendor/google.golang.org/grpc/internal/transport/http2_server.go:442 +0x16fd
534 | google.golang.org/grpc/internal/transport.(*http2Server).HandleStreams()
535 | /go/src/github.com/gravitational/teleport/vendor/google.golang.org/grpc/internal/transport/http2_server.go:483 +0x3e4
536 | google.golang.org/grpc.(*Server).serveStreams()
537 | /go/src/github.com/gravitational/teleport/vendor/google.golang.org/grpc/server.go:742 +0x1c1
538 | google.golang.org/grpc.(*Server).handleRawConn.func1()
539 | /go/src/github.com/gravitational/teleport/vendor/google.golang.org/grpc/server.go:703 +0x4c
540 |  
541 | Goroutine 502 (running) created at:
542 | testing.(*T).Run()
543 | /opt/go/src/testing/testing.go:1168 +0x5bb
544 | testing.runTests.func1()
545 | /opt/go/src/testing/testing.go:1439 +0xa6
546 | testing.tRunner()
547 | /opt/go/src/testing/testing.go:1123 +0x202
548 | testing.runTests()
549 | /opt/go/src/testing/testing.go:1437 +0x612
550 | testing.(*M).Run()
551 | /opt/go/src/testing/testing.go:1345 +0x3b3
552 | github.com/gravitational/teleport/lib/web.TestMain()
553 | /go/src/github.com/gravitational/teleport/lib/web/apiserver_test.go:125 +0x5c
554 | main.main()
555 | _testmain.go:155 +0x371
556 | ==================
557 | panic: runtime error: invalid memory address or nil pointer dereference
558 | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x17aad78]
559 |  
560 | goroutine 7934 [running]:
561 | github.com/gravitational/teleport/lib/events.(*FileLog).rotateLog(0x0, 0x0, 0x0)
562 | /go/src/github.com/gravitational/teleport/lib/events/filelog.go:314 +0x58
563 | github.com/gravitational/teleport/lib/events.(*FileLog).EmitAuditEvent(0x0, 0x3310240, 0xc001366bd0, 0x3333a60, 0xc00145b800, 0x4e1e9a0, 0xc00252e698)
564 | /go/src/github.com/gravitational/teleport/lib/events/filelog.go:119 +0x56
565 | github.com/gravitational/teleport/lib/events.(*AuditLog).EmitAuditEvent(0xc000bbd800, 0x3310240, 0xc001366bd0, 0x3333a60, 0xc00145b800, 0x0, 0xa)
566 | /go/src/github.com/gravitational/teleport/lib/events/auditlog.go:974 +0x10e
567 | github.com/gravitational/teleport/lib/auth.(*ServerWithRoles).EmitAuditEvent(0xc00016ba40, 0x3310240, 0xc001366bd0, 0x3333a60, 0xc00145b800, 0x0, 0x3333a60)
568 | /go/src/github.com/gravitational/teleport/lib/auth/auth_with_roles.go:1829 +0x868
569 | github.com/gravitational/teleport/lib/auth.(*GRPCServer).EmitAuditEvent(0xc002dac000, 0x3310240, 0xc001366bd0, 0xc002b95b30, 0xc002dac000, 0xc001366bd0, 0x1)
570 | /go/src/github.com/gravitational/teleport/lib/auth/grpcserver.go:80 +0x1a7
571 | github.com/gravitational/teleport/api/client/proto._AuthService_EmitAuditEvent_Handler.func1(0x3310240, 0xc001366bd0, 0x2f31e80, 0xc002b95b30, 0x2e207c0, 0xc00145ba00, 0x3310240, 0xc001366bd0)
572 | /go/src/github.com/gravitational/teleport/vendor/github.com/gravitational/teleport/api/client/proto/authservice.pb.go:8131 +0xa5
573 | github.com/gravitational/teleport/lib/auth.(*Middleware).UnaryInterceptor(0xc0021132c0, 0x3310240, 0xc002b95b90, 0x2f31e80, 0xc002b95b30, 0xc000d17b60, 0xc000d17ba0, 0x0, 0x0, 0x0, ...)
574 | /go/src/github.com/gravitational/teleport/lib/auth/middleware.go:354 +0x823
575 | github.com/gravitational/teleport/api/client/proto._AuthService_EmitAuditEvent_Handler(0x2f3f7e0, 0xc002dac000, 0x3310240, 0xc002b95b00, 0xc0018d7bc0, 0xc001bcbbd0, 0x3310240, 0xc002b95b00, 0xc0012e12c0, 0x9e)
576 | /go/src/github.com/gravitational/teleport/vendor/github.com/gravitational/teleport/api/client/proto/authservice.pb.go:8133 +0x1de
577 | google.golang.org/grpc.(*Server).processUnaryRPC(0xc003338ea0, 0x3329460, 0xc000c64480, 0xc001d83300, 0xc0010358c0, 0x4348320, 0x0, 0x0, 0x0)
578 | /go/src/github.com/gravitational/teleport/vendor/google.golang.org/grpc/server.go:1082 +0xa06
579 | google.golang.org/grpc.(*Server).handleStream(0xc003338ea0, 0x3329460, 0xc000c64480, 0xc001d83300, 0x0)
580 | /go/src/github.com/gravitational/teleport/vendor/google.golang.org/grpc/server.go:1405 +0x1398
581 | google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc001e1a000, 0xc003338ea0, 0x3329460, 0xc000c64480, 0xc001d83300)
582 | /go/src/github.com/gravitational/teleport/vendor/google.golang.org/grpc/server.go:746 +0xdd
583 | created by google.golang.org/grpc.(*Server).serveStreams.func1
584 | /go/src/github.com/gravitational/teleport/vendor/google.golang.org/grpc/server.go:744 +0xb9
585 | FAIL  github.com/gravitational/teleport/lib/web   132.408s
586 | ok    github.com/gravitational/teleport/lib/web/app   0.209s  coverage: 16.7% of statements
587 | ok    github.com/gravitational/teleport/lib/web/ui    0.183s  coverage: 32.2% of statements
588 | ?     github.com/gravitational/teleport/tool/tctl [no test files]
589 | ok    github.com/gravitational/teleport/tool/tctl/common  3.073s  coverage: 4.4% of statements
590 | ?     github.com/gravitational/teleport/tool/teleport [no test files]
591 | ok    github.com/gravitational/teleport/tool/teleport/common  0.158s  coverage: 57.1% of statements
592 | ok    github.com/gravitational/teleport/tool/tsh  15.872s coverage: 27.3% of statements
593 | FAIL
594 | Makefile:279: recipe for target 'test-go' failed
595 | make: *** [test-go] Error 1
```

**Comment by webvictim** [comment]
Duplicate of #5970
