### ISSUE TITLE
segfault on teleport running db and kube service

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#6309]
### Description

**What happened**:

The teleport node stops responding. Upon looking at the logs, there's a SIGSEGV with accompanying stacktrace related to the file uploader. Restarting the service via `systemctl restart` fixes the issue.

**What you expected to happen**:

SIGSEGV shouldn't happen.

### Reproduction Steps

There's not currently a solid set of repro steps, but we wanted to call attention to the stacktrace.

As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1.
2.
3.

### Server Details
- Teleport version (run `teleport version`): `Teleport v6.0.2 git:v6.0.2-0-g1cb1420b7 go1.15.5`
- Server OS (e.g. from `/etc/os-release`): `Amazon Linux 2` `4.14.214-160.339.amzn2.x86_64`
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS
- Additional details:

### Client Details
- Tsh version (`tsh version`):
- Computer OS (e.g. Linux, macOS, Windows):
- Browser version (for UI-related issues):
- Installed via (e.g. apt, yum, brew, website download):
- Additional details:

### Debug Logs

```
Apr 03 20:22:28 node1.example.com teleport[17017]: DEBU [KUBERNETE] Ping -> 203.0.113.228:3024. leaseID:4 target:auth.example.com:3024 reversetunnel/agent.go:426
Apr 03 20:23:24 node1.example.com teleport[17017]: DEBU [AUTH:COMP] Upload Upload(session=9e05119e-3086-4490-881c-201d52b49522, id=54c49e57-bdd5-46ce-97bc-5dab7a89dbef, initiated=2021-04-02 20:23:20.950744476 +0000 UTC) grace period is over. Trying to complete. events/complete.go:136
Apr 03 20:23:24 node1.example.com teleport[17017]: DEBU [AUTH:COMP] Completed upload Upload(session=9e05119e-3086-4490-881c-201d52b49522, id=54c49e57-bdd5-46ce-97bc-5dab7a89dbef, initiated=2021-04-02 20:23:20.950744476 +0000 UTC). events/complete.go:140
Apr 03 20:23:24 node1.example.com teleport[17017]: DEBU [PROC:1]    Service is completed and removed. service:fileuploader.service service/supervisor.go:222
Apr 03 20:23:24 node1.example.com teleport[17017]: panic: runtime error: invalid memory address or nil pointer dereference
Apr 03 20:23:24 node1.example.com teleport[17017]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xfd46ef]
Apr 03 20:23:24 node1.example.com teleport[17017]: goroutine 412 [running]:
Apr 03 20:23:24 node1.example.com teleport[17017]: github.com/gravitational/teleport/lib/events.(*UploadCompleter).CheckUploads(0xc0000f1b00, 0x2ffb2e0, 0xc00033c740, 0x2, 0x1)
Apr 03 20:23:24 node1.example.com teleport[17017]: /go/src/github.com/gravitational/teleport/lib/events/complete.go:154 +0x74f
Apr 03 20:23:24 node1.example.com teleport[17017]: github.com/gravitational/teleport/lib/events/filesessions.(*Uploader).Serve(0xc00051c240, 0xc000114120, 0xc0008d2140)
Apr 03 20:23:24 node1.example.com teleport[17017]: /go/src/github.com/gravitational/teleport/lib/events/filesessions/fileasync.go:220 +0xa05
Apr 03 20:23:24 node1.example.com teleport[17017]: github.com/gravitational/teleport/lib/service.(*TeleportProcess).initUploaderService.func3(0x14, 0x14)
Apr 03 20:23:24 node1.example.com teleport[17017]: /go/src/github.com/gravitational/teleport/lib/service/service.go:1953 +0x48
Apr 03 20:23:24 node1.example.com teleport[17017]: github.com/gravitational/teleport/lib/service.(*LocalService).Serve(0xc00098d020, 0x5, 0xc000891f58)
Apr 03 20:23:24 node1.example.com teleport[17017]: /go/src/github.com/gravitational/teleport/lib/service/supervisor.go:457 +0x2a
Apr 03 20:23:24 node1.example.com teleport[17017]: github.com/gravitational/teleport/lib/service.(*LocalSupervisor).serve.func1(0xc00023e270, 0x2ffbc60, 0xc00098d020)
Apr 03 20:23:24 node1.example.com teleport[17017]: /go/src/github.com/gravitational/teleport/lib/service/supervisor.go:246 +0x197
Apr 03 20:23:24 node1.example.com teleport[17017]: created by github.com/gravitational/teleport/lib/service.(*LocalSupervisor).serve
Apr 03 20:23:24 node1.example.com teleport[17017]: /go/src/github.com/gravitational/teleport/lib/service/supervisor.go:241 +0x6e
lines 419-501/501 (END)
```

Here's the config file for the teleport instance in question (some values redacted. This is a node that connects to a teleport cloud backend):

```
teleport:
  # Note: auth_servers points at the default proxy listening port.
  auth_servers: [""]
  auth_token: 
  ca_pin: 
  data_dir: /var/lib/teleport-qa
auth_service:
  enabled: no
proxy_service:
  enabled: no
ssh_service:
  enabled: no
kubernetes_service:
  enabled: yes
  kubeconfig_file: /var/lib/teleport-qa/kubeconfig
db_service:
  enabled: "yes"
  # This section contains definitions of all databases proxied by this
  # service, can contain multiple items.
  databases:
    # Name of the database proxy instance, used to reference in CLI.
  - name: "qa"
    # Free-form description of the database proxy instance.
    description: "QA DB"
    # Database protocol.
    protocol: "postgres"
    # Database address, example of a AWS Aurora endpoint in this case.
    uri: "qa-db-cluster.cluster-cl4nbofytqnu.us-west-2.rds.amazonaws.com:5432"
    # AWS specific configuration, only required for RDS and Aurora.
    aws:
      # Region the database is deployed in.
      region: us-west-2
    # Labels to assign to the database, used in RBAC.
    static_labels:
      env: qa
```

**Comment by xacrimon** [comment]
Submitted a PR for a possible fix. Reproduction is a bit tricky but I managed to reproduce it once.
This issue seems to trigger when an upload exceeds the grace period and gets completed in post by `events.UploadCompleter`.
