### ISSUE TITLE
"Failed to Fetch" error when creating OpenIAM SAML connector

### ISSUE THREAD

**Issue by jon-can** [gravitational/teleport#6329]
### Description

**What happened**:
Trying to create an OpenIAM SAML connector. When I click "Save Changes" in the UI I see an error that says "Failed to Fetch".
**What you expected to happen**:
I expect my SAML connector to be saved.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Go into the UI
2. Create a new SAML connector
3. Try to save an OpenIAM SAML connector

### Server Details
- Teleport version (run `teleport version`): 6.0.2
- Server OS (e.g. from `/etc/os-release`): Ubuntu 20
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS

### Client Details
- Tsh version (`tsh version`):
- Computer OS (e.g. Linux, macOS, Windows): macOS
- Browser version (for UI-related issues): Chrome 89.0.4389.114

### Debug Logs
```
Apr 06 18:13:56 ip-172-31-25-182 teleport[723468]: ERRO [PROXY:SER] "proxy2021/04/06 18:13:56 http: panic serving 73.241.165.136:50057: runtime error: invalid memory address or nil pointer dereference\ngoroutine 19543844 [running]:\nnet/http.(*conn).serve.func1(0xc0020f8b40)\n\t/opt/go/src/net/http/server.go:1801 +0x147\npanic(0x286bf60, 0x45268e0)\n\t/opt/go/src/runtime/panic.go:975 +0x47a\ngithub.com/gravitational/teleport/lib/services.ValidateSAMLConnector(0x30e1220, 0xc002231760, 0x0, 0x0)\n\t/go/src/github.com/gravitational/teleport/lib/services/saml.go:71 +0x99c\ngithub.com/gravitational/teleport/lib/services.UnmarshalSAMLConnector(0xc000a14880, 0xd19, 0xd19, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0018ffe40, 0xc00231f428)\n\t/go/src/github.com/gravitational/teleport/lib/services/saml.go:296 +0x265\ngithub.com/gravitational/teleport/e/lib/web.upsertSAMLConnector(0x309dac0, 0xc001b68e80, 0x7f0dcb9a9928, 0xc001e18360, 0xc001ca6000, 0xeaf, 0xc0010fb740, 0x4, 0x10, 0x10, ...)\n\t/go/src/github.com/gravitational/teleport/e/lib/web/resources.go:109 +0x207\ngithub.com/gravitational/teleport/e/lib/web.(*Plugin).upsertSAMLConnectorHandle(0xc000830d80, 0x3090580, 0xc0022faa80, 0xc0014db400, 0x0, 0x0, 0x0, 0xc000d79c20, 0xc00231f530, 0xd5b18641772ac8b7, ...)\n\t/go/src/github.com/gravitational/teleport/e/lib/web/resources.go:91 +0x135\ngithub.com/gravitational/teleport/lib/web.(*Handler).WithAuth.func1(0x3090580, 0xc0022faa80, 0xc0014db400, 0x0, 0x0, 0x0, 0x2e62b55b858a7eed, 0x1, 0x0, 0x0)\n\t/go/src/github.com/gravitational/teleport/lib/web/apiserver.go:2260 +0x139\ngithub.com/gravitational/teleport/lib/httplib.MakeHandlerWithErrorWriter.func1(0x3090580, 0xc0022faa80, 0xc0014db400, 0x0, 0x0, 0x0)\n\t/go/src/github.com/gravitational/teleport/lib/httplib/httplib.go:61 +0xa6\ngithub.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc00028e298, 0x3090580, 0xc0022faa80, 0xc0014db400)\n\t/go/src/github.com/gravitational/teleport/vendor/github.com/julienschmidt/httprouter/router.go:387 +0xc7e\nnet/http.StripPrefix.func1(0x3090580, 0xc0022faa80, 0xc0003bbe00)\n\t/opt/go/src/net/http/server.go:2081 +0x1a2\nnet/http.HandlerFunc.ServeHTTP(0xc0016dca20, 0x3090580, 0xc0022faa80, 0xc0003bbe00)\n\t/opt/go/src/net/http/server.go:2042 +0x44\ngithub.com/gravitational/teleport/lib/web.NewHandler.func1(0x3090580, 0xc0022faa80, 0xc0003bbe00)\n\t/go/src/github.com/gravitational/teleport/lib/web/apiserver.go:374 +0x7c2\nnet/http.HandlerFunc.ServeHTTP(0xc000b21c80, 0x3090580, 0xc0022faa80, 0xc0003bbe00)\n\t/opt/go/src/net/http/server.go:2042 +0x44\ngithub.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc00028e298, 0x3090580, 0xc0022faa80, 0xc0003bbe00)\n\t/go/src/github.com/gravitational/teleport/vendor/github.com/julienschmidt/httprouter/router.go:448 +0x1d2\ngithub.com/gravitational/teleport/lib/httplib.RewritePaths.func1(0x3090580, 0xc0022faa80, 0xc0003bbe00)\n\t/go/src/github.com/gravitational/teleport/lib/httplib/httplib.go:173 +0x116\nnet/http.HandlerFunc.ServeHTTP(0xc000c63e00, 0x3090580, 0xc0022faa80, 0xc0003bbe00)\n\t/opt/go/src/net/http/server.go:2042 +0x44\ngithub.com/gravitational/teleport/lib/web.(*RewritingHandler).ServeHTTP(0xc000c63e30, 0x3090580, 0xc0022faa80, 0xc0003bbe00)\n\t/go/src/github.com/gravitational/teleport/lib/web/apiserver.go:184 +0x155\ngithub.com/gravitational/oxy/ratelimit.(*TokenLimiter).ServeHTTP(0xc000359f80, 0x3090580, 0xc0022faa80, 0xc0003bbe00)\n\t/go/src/github.com/gravitational/teleport/vendor/github.com/gravitational/oxy/ratelimit/tokenlimiter.go:118 +0x25a\ngithub.com/gravitational/oxy/connlimit.(*ConnLimiter).ServeHTTP(0xc000c21680, 0x3090580, 0xc0022faa80, 0xc0003bbe00)\n\t/go/src/github.com/gravitational/teleport/vendor/github.com/gravitational/oxy/connlimit/connlimit.go:75 +0x3e9\nnet/http.serverHandler.ServeHTTP(0xc0008b1260, 0x3090580, 0xc0022faa80, 0xc0003bbe00)\n\t/opt/go/src/net/http/server.go:2843 +0xa3\nnet/http.(*conn).serve(0xc0020f8b40, 0x309dac0, 0xc001db0200)\n\t/opt/go/src/net/http/server.go:1925 +0x8ad\ncreated by net/http.(*Server).Serve\n\t/opt/go/src/net/http/server.go:2969 +0x36c\n" utils/cli.go:287
Apr 06 18:13:56 ip-172-31-25-182 teleport[723468]: ERRO [PROXY:SER] "proxy2021/04/06 18:13:56 http: panic serving 73.241.165.136:50062: runtime error: invalid memory address or nil pointer dereference\ngoroutine 19544555 [running]:\nnet/http.(*conn).serve.func1(0xc0020f8820)\n\t/opt/go/src/net/http/server.go:1801 +0x147\npanic(0x286bf60, 0x45268e0)\n\t/opt/go/src/runtime/panic.go:975 +0x47a\ngithub.com/gravitational/teleport/lib/services.ValidateSAMLConnector(0x30e1220, 0xc00249fe40, 0x0, 0x0)\n\t/go/src/github.com/gravitational/teleport/lib/services/saml.go:71 +0x99c\ngithub.com/gravitational/teleport/lib/services.UnmarshalSAMLConnector(0xc000a16380, 0xd19, 0xd19, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0023db0b0, 0xc00231f428)\n\t/go/src/github.com/gravitational/teleport/lib/services/saml.go:296 +0x265\ngithub.com/gravitational/teleport/e/lib/web.upsertSAMLConnector(0x309dac0, 0xc0010cae40, 0x7f0dcb9a9928, 0xc001e18360, 0xc001cf5000, 0xeaf, 0xc002c2c3c0, 0x4, 0x10, 0x10, ...)\n\t/go/src/github.com/gravitational/teleport/e/lib/web/resources.go:109 +0x207\ngithub.com/gravitational/teleport/e/lib/web.(*Plugin).upsertSAMLConnectorHandle(0xc000830d80, 0x3090580, 0xc0029f68c0, 0xc002b91a00, 0x0, 0x0, 0x0, 0xc000d79c20, 0xc00231f530, 0xedddde0cd11cebf9, ...)\n\t/go/src/github.com/gravitational/teleport/e/lib/web/resources.go:91 +0x135\ngithub.com/gravitational/teleport/lib/web.(*Handler).WithAuth.func1(0x3090580, 0xc0029f68c0, 0xc002b91a00, 0x0, 0x0, 0x0, 0xdb3fd369ec46ac26, 0x1, 0x0, 0x0)\n\t/go/src/github.com/gravitational/teleport/lib/web/apiserver.go:2260 +0x139\ngithub.com/gravitational/teleport/lib/httplib.MakeHandlerWithErrorWriter.func1(0x3090580, 0xc0029f68c0, 0xc002b91a00, 0x0, 0x0, 0x0)\n\t/go/src/github.com/gravitational/teleport/lib/httplib/httplib.go:61 +0xa6\ngithub.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc00028e298, 0x3090580, 0xc0029f68c0, 0xc002b91a00)\n\t/go/src/github.com/gravitational/teleport/vendor/github.com/julienschmidt/httprouter/router.go:387 +0xc7e\nnet/http.StripPrefix.func1(0x3090580, 0xc0029f68c0, 0xc002b91700)\n\t/opt/go/src/net/http/server.go:2081 +0x1a2\nnet/http.HandlerFunc.ServeHTTP(0xc000642300, 0x3090580, 0xc0029f68c0, 0xc002b91700)\n\t/opt/go/src/net/http/server.go:2042 +0x44\ngithub.com/gravitational/teleport/lib/web.NewHandler.func1(0x3090580, 0xc0029f68c0, 0xc002b91700)\n\t/go/src/github.com/gravitational/teleport/lib/web/apiserver.go:374 +0x7c2\nnet/http.HandlerFunc.ServeHTTP(0xc000b21c80, 0x3090580, 0xc0029f68c0, 0xc002b91700)\n\t/opt/go/src/net/http/server.go:2042 +0x44\ngithub.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc00028e298, 0x3090580, 0xc0029f68c0, 0xc002b91700)\n\t/go/src/github.com/gravitational/teleport/vendor/github.com/julienschmidt/httprouter/router.go:448 +0x1d2\ngithub.com/gravitational/teleport/lib/httplib.RewritePaths.func1(0x3090580, 0xc0029f68c0, 0xc002b91700)\n\t/go/src/github.com/gravitational/teleport/lib/httplib/httplib.go:173 +0x116\nnet/http.HandlerFunc.ServeHTTP(0xc000c63e00, 0x3090580, 0xc0029f68c0, 0xc002b91700)\n\t/opt/go/src/net/http/server.go:2042 +0x44\ngithub.com/gravitational/teleport/lib/web.(*RewritingHandler).ServeHTTP(0xc000c63e30, 0x3090580, 0xc0029f68c0, 0xc002b91700)\n\t/go/src/github.com/gravitational/teleport/lib/web/apiserver.go:184 +0x155\ngithub.com/gravitational/oxy/ratelimit.(*TokenLimiter).ServeHTTP(0xc000359f80, 0x3090580, 0xc0029f68c0, 0xc002b91700)\n\t/go/src/github.com/gravitational/teleport/vendor/github.com/gravitational/oxy/ratelimit/tokenlimiter.go:118 +0x25a\ngithub.com/gravitational/oxy/connlimit.(*ConnLimiter).ServeHTTP(0xc000c21680, 0x3090580, 0xc0029f68c0, 0xc002b91700)\n\t/go/src/github.com/gravitational/teleport/vendor/github.com/gravitational/oxy/connlimit/connlimit.go:75 +0x3e9\nnet/http.serverHandler.ServeHTTP(0xc0008b1260, 0x3090580, 0xc0029f68c0, 0xc002b91700)\n\t/opt/go/src/net/http/server.go:2843 +0xa3\nnet/http.(*conn).serve(0xc0020f8820, 0x309dac0, 0xc0010caa80)\n\t/opt/go/src/net/http/server.go:1925 +0x8ad\ncreated by net/http.(*Server).Serve\n\t/opt/go/src/net/http/server.go:2969 +0x36c\n" utils/cli.go:287

```
SAML connector:
```
kind: saml
version: v2
metadata:
  # The name of the connector
  name: openiam
spec:
  # Connector display name that will be appended to the title of "Login with"
  # button on the cluster login screen so it will say "Login with Okta"
  display: OpenIAM
  # SAML provider will make a callback to this URL after successful authentication
  # cluster-url is the address the cluster UI is reachable at
  acs: https://demotest.gravitational.io:3080/v1/webapi/saml/acs
  attributes_to_roles:
    - {name: "groups", value: "Super Admin Group", roles: ["admin"]}
  # Note that the entire XML document is indented by 4 spaces. This is
  # required because the pipe symbol indicates what follows is raw text.
  # Below is an Example. Replace with your XML
  entity_descriptor: |
    <md:EntityDescriptor xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" ID="_86aedbfbdae3a13812c8c03bef001f36" cacheDuration="PT1M12.000S" entityID="https://demotest.gravitational.io:3080/v1/webapi/saml/acs">
    <md:SPSSODescriptor AuthnRequestsSigned="false" WantAssertionsSigned="false" protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol urn:oasis:names:tc:SAML:2.0:assertion">
    <md:KeyDescriptor use="signing">
    <ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
    <ds:X509Data>
    <ds:X509Certificate>REDACTED</ds:X509Certificate>
    </ds:X509Data>
    </ds:KeyInfo>
    </md:KeyDescriptor>
    <md:SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="http://3.101.21.185/idp/saml2/sp/logout" ResponseLocation="http://3.101.21.185/idp/saml2/idp/logout"/>
    <md:SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="http://3.101.21.185/idp/saml2/sp/logout" ResponseLocation="http://3.101.21.185/idp/saml2/idp/logout"/>
    <md:NameIDFormat>urn:oasis:names:tc:SAML:2.0:nameid-format:persistent</md:NameIDFormat>
    <md:NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress</md:NameIDFormat>
    <md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="http://3.101.21.185/idp/saml2/sp/login" ResponseLocation="http://3.101.21.185/idp/saml2/idp/login" index="0" isDefault="true"/>
    <md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="http://3.101.21.185/idp/saml2/sp/login" ResponseLocation="http://3.101.21.185/idp/saml2/idp/login" index="1" isDefault="false"/>
    </md:SPSSODescriptor>
    </md:EntityDescriptor>

**Comment by jon-can** [comment]
Trying to use tctl results in this:
```
tctl create -f openiam.yaml 
DEBU[0000] Connected to: file:/var/lib/teleport/proc/sqlite.db?_busy_timeout=10000&_sync=OFF, poll stream period: 1s  trace.component=sqlite
DEBU[0000] Synchronous: 0, busy timeout: 10000           trace.component=sqlite
DEBU[0000] Connecting to auth servers: [{0.0.0.0:3025 tcp }]. 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0xd5357c]

goroutine 1 [running, locked to thread]:
github.com/gravitational/teleport/lib/services.ValidateSAMLConnector(0x23e7ce0, 0xc0002fcf20, 0x0, 0x0)
	/go/src/github.com/gravitational/teleport/lib/services/saml.go:71 +0x99c
github.com/gravitational/teleport/lib/services.UnmarshalSAMLConnector(0xc00069ed80, 0xd19, 0xd19, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/gravitational/teleport/lib/services/saml.go:296 +0x265
main.(*ResourceCommandE).createConnector(0xc0002c6f70, 0x23eeb60, 0xc0002e45a0, 0xc00086d5d8, 0x4, 0x0, 0x0, 0xc00086d5e8, 0x2, 0xc00086d5e0, ...)
	/go/src/github.com/gravitational/teleport/e/tool/tctl/resource_command.go:56 +0x170
github.com/gravitational/teleport/tool/tctl/common.(*ResourceCommand).Create(0xc0002c6f70, 0x23eeb60, 0xc0002e45a0, 0x0, 0x0)
	/go/src/github.com/gravitational/teleport/tool/tctl/common/resource_command.go:258 +0x1da
github.com/gravitational/teleport/tool/tctl/common.(*ResourceCommand).TryRun(0xc0002c6f70, 0x2084963, 0x6, 0x23eeb60, 0xc0002e45a0, 0x1, 0x1, 0x0)
	/go/src/github.com/gravitational/teleport/tool/tctl/common/resource_command.go:134 +0x214
main.(*ResourceCommandE).TryRun(0xc0002c6f70, 0x2084963, 0x6, 0x23eeb60, 0xc0002e45a0, 0xc0002e4500, 0x0, 0x0)
	/go/src/github.com/gravitational/teleport/e/tool/tctl/resource_command.go:41 +0x55
github.com/gravitational/teleport/tool/tctl/common.Run(0xc000a9fec8, 0xb, 0xb)
	/go/src/github.com/gravitational/teleport/tool/tctl/common/tctl.go:165 +0xca7
main.main()
	/go/src/github.com/gravitational/teleport/e/tool/tctl/main.go:29 +0x2d9

**Comment by xacrimon** [comment]
Did some investigation and recorded some debug notes
- The error occurs because the `IDPSSO` descriptor is missing from the SAML metadata. The validation code naively assumed it to be there and does not perform a nil check. Relevant code is `lib/services/saml.go:71` and `IDPSSODescriptor` field of `metadata` is `nil`.
- The malformed connector created by tctl somehow skips validation and gets saved. The `IDPSSO` descriptor must also be missing from the metadata that was used to create this connector. tctl should validate this.
- Since this only happens with OpenIAM, something weird is happening on that side since it is providing incomplete SAML metadata during connector creation.

**Comment by stevenGravy** [comment]
Not seeing this as a requested fix from customers.
