### ISSUE TITLE
error when streaming session

### ISSUE THREAD

**Issue by BoTranVan** [gravitational/teleport#6506]
### Description
I was met an error that is systemd restart auto restart teleport when teleport error streaming with log as under:

### Server Details
- Teleport version (run `teleport version`):

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware):
- Additional details:

### Server Details
- Teleport version (`teleport version`): Teleport v6.0.1 git:v6.0.1-0-g6166fd56e go1.15.5
- Server OS (e.g. from `/etc/os-release`):
  ```bash
    NAME="Ubuntu"
    VERSION="18.04.4 LTS (Bionic Beaver)"
    ID=ubuntu
    ID_LIKE=debian
    PRETTY_NAME="Ubuntu 18.04.4 LTS"
    VERSION_ID="18.04"
    HOME_URL="https://www.ubuntu.com/"
    SUPPORT_URL="https://help.ubuntu.com/"
    BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
    PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
    VERSION_CODENAME=bionic
    UBUNTU_CODENAME=bionic
    ```
  `uname -a`: Linux thor-admin-1 4.15.0-46-generic #49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Installed via: website download

### Debug Logs
Run command: journalctl -xeu teleport

```bash
Apr 20 08:22:02 thor-admin-1 teleport[22141]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xfd1e6f]
Apr 20 08:22:02 thor-admin-1 teleport[22141]: goroutine 248 [running]:
Apr 20 08:22:02 thor-admin-1 teleport[22141]: github.com/gravitational/teleport/lib/events.(*UploadCompleter).CheckUploads(0xc0008d8380, 0x2ff61e0, 0xc000217000, 0x2, 0x1)
Apr 20 08:22:02 thor-admin-1 teleport[22141]:         /go/src/github.com/gravitational/teleport/lib/events/complete.go:154 +0x74f
Apr 20 08:22:02 thor-admin-1 teleport[22141]: github.com/gravitational/teleport/lib/events/filesessions.(*Uploader).Serve(0xc000179bc0, 0xc0005cbdc0, 0xc0005cbdc0)
Apr 20 08:22:02 thor-admin-1 teleport[22141]:         /go/src/github.com/gravitational/teleport/lib/events/filesessions/fileasync.go:220 +0xa05
Apr 20 08:22:02 thor-admin-1 teleport[22141]: github.com/gravitational/teleport/lib/service.(*TeleportProcess).initUploaderService.func3(0x0, 0x0)
Apr 20 08:22:02 thor-admin-1 teleport[22141]:         /go/src/github.com/gravitational/teleport/lib/service/service.go:1943 +0x48
Apr 20 08:22:02 thor-admin-1 teleport[22141]: github.com/gravitational/teleport/lib/service.(*LocalService).Serve(0xc00041eec0, 0x5, 0xc0005cbf58)
Apr 20 08:22:02 thor-admin-1 teleport[22141]:         /go/src/github.com/gravitational/teleport/lib/service/supervisor.go:457 +0x2a
Apr 20 08:22:02 thor-admin-1 teleport[22141]: github.com/gravitational/teleport/lib/service.(*LocalSupervisor).serve.func1(0xc000433860, 0x2ff6b20, 0xc00041eec0)
Apr 20 08:22:02 thor-admin-1 teleport[22141]:         /go/src/github.com/gravitational/teleport/lib/service/supervisor.go:246 +0x197
Apr 20 08:22:02 thor-admin-1 teleport[22141]: created by github.com/gravitational/teleport/lib/service.(*LocalSupervisor).serve
Apr 20 08:22:02 thor-admin-1 teleport[22141]:         /go/src/github.com/gravitational/teleport/lib/service/supervisor.go:241 +0x6e
Apr 20 08:22:02 thor-admin-1 systemd[1]: teleport.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 20 08:22:02 thor-admin-1 systemd[1]: teleport.service: Failed with result 'exit-code'.
Apr 20 08:22:02 thor-admin-1 systemd[1]: teleport.service: Service hold-off time over, scheduling restart.
Apr 20 08:22:02 thor-admin-1 systemd[1]: teleport.service: Scheduled restart job, restart counter is at 11.
```

**Comment by russjones** [comment]
This will be fixed in the next 6.1 patch release.
