### ISSUE TITLE
Teleport client on armv7: SIGSEGV on connect

### ISSUE THREAD

**Issue by aluedt** [gravitational/teleport#6703]
### Description
We get a segmentation fault for the teleport client on armv7.

**What happened**:
The client connects successfully to the teleport proxy. The client then crashes when a connection through the web UI is established.

**What you expected to happen**:
The client should not crash. The web UI should connect normally.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. connect client node to proxy 
2. try to connect through web UI

### Server Details (Teleport Proxy)
- Teleport version (run `teleport version`): docker image: quay.io/gravitational/teleport:6
- Server OS (e.g. from `/etc/os-release`): Debian GNU/Linux 10 (buster)
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): dedicated hardware
- Additional details:
amd64 clients work fine when connected to the same proxy machine

### Client Details (Node)
- Tsh version (`tsh version`): not applicable
- Teleport version (run `teleport version`): Teleport v6.1.3 git:v6.1.3-0-g16f4ea392 go1.15.5
- Computer OS (e.g. Linux, macOS, Windows): Raspbian GNU/Linux 10 (buster)
- Browser version (for UI-related issues): not applicable
- Installed via (e.g. apt, yum, brew, website download): download
- Additional details:
Raspberry Pi armv7

### Debug Logs
Please include or attach debug logs, when appropriate. Ob
fuscate sensitive information!
- Start Teleport with --debug flag (`teleport --debug`)
- Run tsh with --debug flag (`tsh --debug`)

Proxy:
```
teleport     | DEBU [PROXY:SER] Dialing from: "10.0.12.6:36408" to: "10.0.13.61:3022". trace.fields:map[cluster:localhost] reversetunnel/localsite.go:185
teleport     | DEBU [PROXY:SER] Error occurred while dialing through a tunnel. address:10.0.13.61:3022 error:[
teleport     | ERROR REPORT:
teleport     | Original Error: *trace.NotFoundError no tunnel connection found: no node reverse tunnel for xxxxx.localhost found
teleport     | Stack Trace:
teleport     |         /go/src/github.com/gravitational/teleport/lib/reversetunnel/localsite.go:265 github.com/gravitational/teleport/lib/reversetunnel.(*localSite).dialTunnel
teleport     |         /go/src/github.com/gravitational/teleport/lib/reversetunnel/localsite.go:289 github.com/gravitational/teleport/lib/reversetunnel.(*localSite).getConn
teleport     |         /go/src/github.com/gravitational/teleport/lib/reversetunnel/localsite.go:187 github.com/gravitational/teleport/lib/reversetunnel.(*localSite).DialTCP
teleport     |         /go/src/github.com/gravitational/teleport/lib/reversetunnel/localsite.go:180 github.com/gravitational/teleport/lib/reversetunnel.(*localSite).Dial
teleport     |         /go/src/github.com/gravitational/teleport/lib/srv/regular/proxy.go:427 github.com/gravitational/teleport/lib/srv/regular.(*proxySubsys).proxyToHost
teleport     |         /go/src/github.com/gravitational/teleport/lib/srv/regular/proxy.go:249 github.com/gravitational/teleport/lib/srv/regular.(*proxySubsys).Start
teleport     |         /go/src/github.com/gravitational/teleport/lib/srv/regular/sshserver.go:1390 github.com/gravitational/teleport/lib/srv/regular.(*Server).handleSubsystem
teleport     |         /go/src/github.com/gravitational/teleport/lib/srv/regular/sshserver.go:1279 github.com/gravitational/teleport/lib/srv/regular.(*Server).dispatch
teleport     |         /go/src/github.com/gravitational/teleport/lib/srv/regular/sshserver.go:1242 github.com/gravitational/teleport/lib/srv/regular.(*Server).handleSessionRequests
teleport     |         /opt/go/src/runtime/asm_amd64.s:1374 runtime.goexit
teleport     | User Message: no tunnel connection found: no node reverse tunnel for xxxxx.localhost found] trace.fields:map[cluster:localhost] reversetunnel/localsite.go:298
teleport     | DEBU [HTTP:PROX] No valid environment variables found. proxy/proxy.go:207
teleport     | DEBU [HTTP:PROX] No proxy set in environment, returning direct dialer. proxy/proxy.go:122
teleport     | DEBU [PROXY:SER] Succeeded dialing from: "10.0.12.6:36408" to: "10.0.13.61:3022". trace.fields:map[cluster:localhost] reversetunnel/localsite.go:191
teleport     | WARN [WEBSOCKET] Unable to stream terminal: EOF. web/terminal.go:463
```

Client node (crash log with --debug):
see attached file
[client-node.log](https://github.com/gravitational/teleport/files/6414256/client-node.log)

Sufficient nemory is available:
```
root@XXX:/mnt/storage/teleport# free -h
              total        used        free      shared  buff/cache   available
Mem:          927Mi        52Mi       287Mi        46Mi       587Mi       813Mi
Swap:            0B          0B          0B
```

**Comment by maxdwit** [comment]
Verified this bug with v6.1.3. 
v6.0.0 did work ( GOARCH=arm, make full )

**Comment by webvictim** [comment]
Relevant panic section from the logs:

```
INFO [AUDIT]     session.data addr.local:10.0.13.61:3022 addr.remote:10.0.12.6:36408 code:T2006I ei:2.147483646e+09 event:session.data login:root namespace:default rx:3690 server_id:XXX sid:18c16188-4efc-4e7f-bf2d-a930a612ffc8 time:2021-05-03T10:13:01.76Z tx:4453 uid:6f01b9db-c83b-4eff-85aa-cb4a1a0856ef user:admin events/emitter.go:323
panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1f84c]

goroutine 92 [running]:
runtime/internal/atomic.goXadd64(0x50d218c, 0x1, 0x0, 0x0, 0x0)
	/opt/go/src/runtime/internal/atomic/atomic_arm.go:103 +0x1c
go.uber.org/atomic.(*Int64).Add(...)
	/go/src/github.com/gravitational/teleport/vendor/go.uber.org/atomic/int64.go:50
go.uber.org/atomic.(*Int64).Inc(...)
	/go/src/github.com/gravitational/teleport/vendor/go.uber.org/atomic/int64.go:60
github.com/gravitational/teleport/lib/events.(*AuditWriter).EmitAuditEvent(0x50d20d0, 0x24349f0, 0x53cc780, 0x2448640, 0x52f0c00, 0x0, 0x0)
	/go/src/github.com/gravitational/teleport/lib/events/auditwriter.go:270 +0x8c
github.com/gravitational/teleport/lib/srv.(*SessionRegistry).emitSessionLeaveEvent(0x53ccba0, 0x51b1110)
	/go/src/github.com/gravitational/teleport/lib/srv/sess.go:274 +0x2a4
github.com/gravitational/teleport/lib/srv.(*SessionRegistry).leaveSession(0x53ccba0, 0x51b1110, 0x0, 0x0)
	/go/src/github.com/gravitational/teleport/lib/srv/sess.go:303 +0x78
github.com/gravitational/teleport/lib/srv.(*party).Close.func1()
	/go/src/github.com/gravitational/teleport/lib/srv/sess.go:1418 +0xac
sync.(*Once).doSlow(0x51b1174, 0x579b694)
	/opt/go/src/sync/once.go:66 +0xe4
sync.(*Once).Do(0x51b1174, 0x579b694)
	/opt/go/src/sync/once.go:57 +0x44
github.com/gravitational/teleport/lib/srv.(*party).Close(0x51b1110, 0x0, 0x0)
	/go/src/github.com/gravitational/teleport/lib/srv/sess.go:1416 +0x64
github.com/gravitational/teleport/lib/srv.closeAll(0x5790fc0, 0x6, 0x6, 0x6, 0x0)
	/go/src/github.com/gravitational/teleport/lib/srv/ctx.go:850 +0x68
github.com/gravitational/teleport/lib/srv.(*ServerContext).Close(0x50d88c0, 0x0, 0x0)
	/go/src/github.com/gravitational/teleport/lib/srv/ctx.go:610 +0xac
panic(0x1d9ceb8, 0x3381420)
	/opt/go/src/runtime/panic.go:969 +0x158
runtime/internal/atomic.goXadd64(0x50d218c, 0x1, 0x0, 0x0, 0x0)
	/opt/go/src/runtime/internal/atomic/atomic_arm.go:103 +0x1c
go.uber.org/atomic.(*Int64).Add(...)
	/go/src/github.com/gravitational/teleport/vendor/go.uber.org/atomic/int64.go:50
go.uber.org/atomic.(*Int64).Inc(...)
	/go/src/github.com/gravitational/teleport/vendor/go.uber.org/atomic/int64.go:60
github.com/gravitational/teleport/lib/events.(*AuditWriter).EmitAuditEvent(0x50d20d0, 0x24349f0, 0x53cc780, 0x2448760, 0x5148480, 0x0, 0x0)
	/go/src/github.com/gravitational/teleport/lib/events/auditwriter.go:270 +0x8c
github.com/gravitational/teleport/lib/srv.(*session).startInteractive(0x5632300, 0x243c6b8, 0x53b0400, 0x50d88c0, 0x579bc64, 0x1)
	/go/src/github.com/gravitational/teleport/lib/srv/sess.go:773 +0x974
github.com/gravitational/teleport/lib/srv.(*SessionRegistry).OpenSession(0x53ccba0, 0x243c6b8, 0x53b0400, 0x5663180, 0x50d88c0, 0x0, 0x0)
	/go/src/github.com/gravitational/teleport/lib/srv/sess.go:216 +0x284
github.com/gravitational/teleport/lib/srv.(*TermHandlers).HandleShell(0x509f0e0, 0x243c6b8, 0x53b0400, 0x5663180, 0x50d88c0, 0x2, 0x2)
	/go/src/github.com/gravitational/teleport/lib/srv/termhandlers.go:113 +0xa8
github.com/gravitational/teleport/lib/srv/regular.(*Server).dispatch(0x5198480, 0x243c6b8, 0x53b0400, 0x5663180, 0x50d88c0, 0x0, 0x0)
	/go/src/github.com/gravitational/teleport/lib/srv/regular/sshserver.go:1303 +0x554
github.com/gravitational/teleport/lib/srv/regular.(*Server).handleSessionRequests(0x5198480, 0x24349f0, 0x574d160, 0x51a9d10, 0x55414b4, 0x6, 0x0, 0x0, 0x574e430, 0x4, ...)
	/go/src/github.com/gravitational/teleport/lib/srv/regular/sshserver.go:1242 +0x524
github.com/gravitational/teleport/lib/srv/regular.(*Server).HandleNewChan.func1(0x5198480, 0x24349f0, 0x574d160, 0x51a9d10, 0x55414b4, 0x6, 0x0, 0x0, 0x574e430, 0x4, ...)
	/go/src/github.com/gravitational/teleport/lib/srv/regular/sshserver.go:1022 +0x58
created by github.com/gravitational/teleport/lib/srv/regular.(*Server).HandleNewChan
	/go/src/github.com/gravitational/teleport/lib/srv/regular/sshserver.go:1021 +0xbd4
```

@xacrimon Does this look related to #6431?

**Comment by xacrimon** [comment]
This looks different @webvictim, will investigate.

**Comment by xacrimon** [comment]
note: this looks to be a case of a Go ARMv7 bug if I am correct where it doesn't ensure that everything is aligned properly and we got unlucky with a non-aligned variable.

**Comment by xacrimon** [comment]
Hi @aluedt. I wrote a patch and can no longer reproduce the issue but I'd like additional confirmation on your end. Are you able to clone, check out `joel/armv7-atomic-align`, build and test if you can reproduce on this branch? ?

**Comment by xacrimon** [comment]
Great, we will either put this in a 6.1.5 patch release or it will be part of 6.2. Thanks for the help.
