### ISSUE TITLE
Potential data race in Client.EmitAuditEvent - CI panic

### ISSUE THREAD

**Issue by jakule** [gravitational/teleport#9150]
CI build https://drone.teleport.dev/gravitational/teleport/8239/1/7 failed with 
```
2021-11-20T00:10:19Z DEBU [NODE]      conn(127.0.0.1:46562->127.0.0.1:39757, user=ci) auth attempt fingerprint:ecdsa-sha2-nistp256-cert-v01@openssh.com SHA256:W7tHUfxIqT/aNBpHvcMZbZr2fF4vFuDfSZYsH+857NE local:127.0.0.1:39757 remote:127.0.0.1:46562 user:ci srv/authhandlers.go:211
2021-11-20T00:10:19Z DEBU [NODE]      Releasing associated resources - context has been closed. id:9 local:127.0.0.1:34835 login:ci remote:127.0.0.1:34604 teleportUser:ci srv/monitor.go:251
2021-11-20T00:10:19Z DEBU [NODE]      Successfully authenticated fingerprint:ssh-rsa-cert-v01@openssh.com SHA256:qwHmaGc3FcEr3Et4jugVeujq9XV31lL+v8hS0s0YGpE local:127.0.0.1:37401 remote:127.0.0.1:34902 user:ci srv/authhandlers.go:274
2021-11-20T00:10:19Z WARN [NODE]      Failed to emit session data event. error:[
ERROR REPORT:
Original Error: *status.Error rpc error: code = Canceled desc = context canceled
Stack Trace:
	/go/src/github.com/gravitational/teleport/vendor/github.com/gravitational/teleport/api/client/client.go:636 github.com/gravitational/teleport/api/client.(*Client).EmitAuditEvent
	/go/src/github.com/gravitational/teleport/lib/srv/ctx.go:649 github.com/gravitational/teleport/lib/srv.(*ServerContext).reportStats
	/go/src/github.com/gravitational/teleport/lib/srv/ctx.go:671 github.com/gravitational/teleport/lib/srv.(*ServerContext).Close
	/go/src/github.com/gravitational/teleport/lib/srv/regular/sshserver.go:1391 github.com/gravitational/teleport/lib/srv/regular.(*Server).handleSessionRequests
	/go/src/github.com/gravitational/teleport/lib/srv/regular/sshserver.go:1114 github.com/gravitational/teleport/lib/srv/regular.(*Server).HandleNewChan.func1
	/opt/go/src/runtime/asm_amd64.s:1581 runtime.goexit
User Message: rpc error: code = Canceled desc = context canceled] id:9 local:127.0.0.1:34835 login:ci remote:127.0.0.1:34604 teleportUser:ci srv/ctx.go:650
2021-11-20T00:10:19Z DEBU [NODE]      conn(127.0.0.1:46562->127.0.0.1:39757, user=ci) auth attempt with key ecdsa-sha2-nistp256-cert-v01@openssh.com SHA256:W7tHUfxIqT/aNBpHvcMZbZr2fF4vFuDfSZYsH+857NE, &ssh.Certificate{Nonce:[]uint8{0x69, 0x9c, 0x8d, 0x4f, 0x64, 0xb4, 0xc7, 0x19, 0x80, 0x3b, 0xef, 0xef, 0xd, 0x80, 0xf, 0xd, 0x9a, 0xfd, 0x78, 0xe0, 0xb, 0xb3, 0x39, 0xa, 0x8e, 0x43, 0x2f, 0x6c, 0x5c, 0x2, 0x98, 0x3d}, Key:(*ssh.ecdsaPublicKey)(0xc002339600), Serial:0x0, CertType:0x1, KeyId:"foo", ValidPrincipals:[]string{"foo"}, ValidAfter:0x61983caf, ValidBefore:0x61983d27, Permissions:ssh.Permissions{CriticalOptions:map[string]string{}, Extensions:map[string]string{}}, Reserved:[]uint8{}, SignatureKey:(*ssh.ecdsaPublicKey)(0xc002339680), Signature:(*ssh.Signature)(0xc002cc9700)} fingerprint:ecdsa-sha2-nistp256-cert-v01@openssh.com SHA256:W7tHUfxIqT/aNBpHvcMZbZr2fF4vFuDfSZYsH+857NE local:127.0.0.1:39757 remote:127.0.0.1:46562 user:ci srv/authhandlers.go:214
2021-11-20T00:10:19Z DEBU [SSH:NODE]  Closed connection 127.0.0.1:34604. sshutils/server.go:471
2021-11-20T00:10:19Z DEBU [NODE:BEAT] Heartbeat exited. srv/heartbeat.go:278
2021-11-20T00:10:19Z DEBU [NODE]      Checking permissions for (ci,ci) to login to node with RBAC checks. srv/authhandlers.go:403
2021-11-20T00:10:19Z DEBU [NODE:BEAT] Heartbeat exited. srv/heartbeat.go:278
2021-11-20T00:10:19Z DEBU [AUTH:GRPC] Failed to receive heartbeat: rpc error: code = Canceled desc = context canceled auth/grpcserver.go:139
2021-11-20T00:10:19Z DEBU [SSH:NODE]  Closed connection 127.0.0.1:38612. sshutils/server.go:471
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x98bd0e]

goroutine 2149 [running]:
github.com/sirupsen/logrus.(*Entry).WithFields(0x0, 0xc001e9cd08)
	/go/src/github.com/gravitational/teleport/vendor/github.com/sirupsen/logrus/entry.go:126 +0x4e
github.com/sirupsen/logrus.(*Entry).WithField(...)
	/go/src/github.com/gravitational/teleport/vendor/github.com/sirupsen/logrus/entry.go:121
github.com/sirupsen/logrus.(*Entry).WithError(...)
	/go/src/github.com/gravitational/teleport/vendor/github.com/sirupsen/logrus/entry.go:107
github.com/gravitational/teleport/lib/srv.(*ServerContext).reportStats(0xc002404900, {0x4a0a900, 0xc001728820})
	/go/src/github.com/gravitational/teleport/lib/srv/ctx.go:650 +0xaaf
github.com/gravitational/teleport/lib/srv.(*ServerContext).Close(0xc002404900)
	/go/src/github.com/gravitational/teleport/lib/srv/ctx.go:674 +0x1b4
github.com/gravitational/teleport/lib/srv.NewServerContext({0x4a79a68, 0xc002eff100}, 0xc0020b5b90, {0x4adaf40, 0xc000cacc80}, {{0xc0006359ae, 0x2}, {0x0, 0x0}, {0xc0014abaae, ...}, ...}, ...)
	/go/src/github.com/gravitational/teleport/lib/srv/ctx.go:353 +0x1514
github.com/gravitational/teleport/lib/srv/regular.(*Server).handleSessionRequests(0xc000cacc80, {0x4a79a68, 0xc002eff100}, 0xc0020b5b90, {{0xc0006359ae, 0x2}, {0x0, 0x0}, {0xc0014abaae, 0x2}, ...}, ...)
	/go/src/github.com/gravitational/teleport/lib/srv/regular/sshserver.go:1311 +0x2db
github.com/gravitational/teleport/lib/srv/regular.(*Server).HandleNewChan.func1()
	/go/src/github.com/gravitational/teleport/lib/srv/regular/sshserver.go:1114 +0x170
created by github.com/gravitational/teleport/lib/srv/regular.(*Server).HandleNewChan
	/go/src/github.com/gravitational/teleport/lib/srv/regular/sshserver.go:1113 +0x1489
FAIL	github.com/gravitational/teleport/lib/srv/regular	5.940s
===================================================
exit status 1
```

**Comment by zmb3** [comment]
@jakule I don't think we've seen this in a long time. Good to close?
