### ISSUE TITLE
teleport-cluster pod crash - sqlite3.Error database is locked 

### ISSUE THREAD

**Issue by dove-young** [gravitational/teleport#9380]
### Description

**What happened**:

teleport-cluster pod crashes with error Original Error: sqlite3.Error database is locked

**What you expected to happen**:

teleport-cluster pod is running

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Install teleport to OpenShift 7.3
```
EMAIL=alice@gmail.com
CLUSTER_NAME=teleport-cluster-teleport-cluster.apps.st2-bastion-2.cp.fyre.ibm.com

helm install teleport-cluster teleport/teleport-cluster --create-namespace --namespace=teleport-cluster \
  --set clusterName=${CLUSTER_NAME?} --set acme=false --set acmeEmail=${EMAIL?} \
  --set insecureSkipProxyTLSVerify=true --set logLevel=DEBUG
```
2. Create a local admin as https://goteleport.com/docs/kubernetes-access/getting-started/cluster/
3. Set password for the local admin in browser, scan authentication app
4. Edit `configmap/teleport-cluster`, set `second_factor: off`
```
  authentication:
    second_factor: off
```
6. Restart pod, pod crash, check log 
```
 oc logs -f pod/teleport-cluster-7566d5985c-k6rhj
ERROR: failed parsing the config file: yaml: unmarshal errors:  line 10: field authentication already set in type config.Auth
```
8.  Edit `configmap/teleport-cluster`, remove `second_factor: off`
9. Restart pod, pod crash, check log
```
2021-12-14T04:53:29Z DEBU [AUDIT]     Uploader is exiting. events/uploader.go:158
2021-12-14T04:53:29Z INFO [AUDIT:1]   File uploader is shutting down. service/service.go:2170
2021-12-14T04:53:29Z DEBU             Closing. reversetunnel/rc_manager.go:150
2021-12-14T04:53:29Z INFO [AUDIT:1]   File uploader has shut down. service/service.go:2172
2021-12-14T04:53:29Z INFO [AUDIT:1]   Exited. service/service.go:2146
2021-12-14T04:53:29Z DEBU [DIAG:1]    Teleport is exiting, returning. service/service.go:2311

ERROR REPORT:
Original Error: sqlite3.Error database is locked
Stack Trace:
        /go/src/github.com/gravitational/teleport/lib/backend/lite/lite.go:859 github.com/gravitational/teleport/lib/backend/lite.(*Backend).inTransaction.func4
        /go/src/github.com/gravitational/teleport/lib/backend/lite/lite.go:863 github.com/gravitational/teleport/lib/backend/lite.(*Backend).inTransaction
        /go/src/github.com/gravitational/teleport/lib/backend/lite/lite.go:729 github.com/gravitational/teleport/lib/backend/lite.(*Backend).Delete
        /go/src/github.com/gravitational/teleport/lib/backend/report.go:192 github.com/gravitational/teleport/lib/backend.(*Reporter).Delete
        /go/src/github.com/gravitational/teleport/lib/backend/wrap.go:100 github.com/gravitational/teleport/lib/backend.(*Wrapper).Delete
        /go/src/github.com/gravitational/teleport/lib/cache/cache.go:651 github.com/gravitational/teleport/lib/cache.New
        /go/src/github.com/gravitational/teleport/lib/service/service.go:1592 github.com/gravitational/teleport/lib/service.(*TeleportProcess).newAccessCache
        /go/src/github.com/gravitational/teleport/lib/service/service.go:1740 github.com/gravitational/teleport/lib/service.(*TeleportProcess).newLocalCache
        /go/src/github.com/gravitational/teleport/lib/service/service.go:1637 github.com/gravitational/teleport/lib/service.(*TeleportProcess).newLocalCacheForKubernetes
        /go/src/github.com/gravitational/teleport/lib/service/kubernetes.go:80 github.com/gravitational/teleport/lib/service.(*TeleportProcess).initKubernetesService
        /go/src/github.com/gravitational/teleport/lib/service/kubernetes.go:61 github.com/gravitational/teleport/lib/service.(*TeleportProcess).initKubernetes.func1
        /go/src/github.com/gravitational/teleport/lib/service/supervisor.go:494 github.com/gravitational/teleport/lib/service.(*LocalService).Serve
        /go/src/github.com/gravitational/teleport/lib/service/supervisor.go:263 github.com/gravitational/teleport/lib/service.(*LocalSupervisor).serve.func1
        /opt/go/src/runtime/asm_amd64.s:1581 runtime.goexit
User Message: database is locked
2021-12-14T04:53:29Z INFO [DIAG:1]    Shutting down immediately. service/service.go:2364
```
11. 

### Server Details
- Teleport version (run `teleport version`):
- Server OS (e.g. from `/etc/os-release`):
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware):  OpenShift OCP 7.3
- Additional details:

### Client Details
- Tsh version (`tsh version`):
- Computer OS (e.g. Linux, macOS, Windows):
- Browser version (for UI-related issues):
- Installed via (e.g. apt, yum, brew, website download):
- Additional details:

### Debug Logs
Please include or attach debug logs, when appropriate. Obfuscate sensitive information!
- Start Teleport with --debug flag (`teleport --debug`)
- Run tsh with --debug flag (`tsh --debug`)

**Comment by dove-young** [comment]
This problem can be reproduced in many conditions in which teleport configuration failed and then restored. 

for example
1. Edit `oc edit configmap/teleport-cluster`
2. set 
```
    proxy_service:
      public_addr: 'teleport-cluster-teleport-cluster.apps.st2-bastion-2.cp.fyre.ibm.com:443'
      kube_listen_addr: 0.0.0.0:3026
      mysql_listen_addr: 0.0.0.0:3036
```
to 
```
    proxy_service:
      public_addr: 'teleport-cluster-teleport-cluster.apps.st2-bastion-2.cp.fyre.ibm.com:443'
      listen_addr: teleport-cluster-teleport-cluster.apps.st2-bastion-2.cp.fyre.ibm.com:3023
      kube_listen_addr: 0.0.0.0:3026
      mysql_listen_addr: 0.0.0.0:3036
```
3. Restart `teleport-cluster` pod, it crashes
4.  Edit `oc edit configmap/teleport-cluster` and remove ` listen_addr: teleport-cluster-teleport-cluster.apps.st2-bastion-2.cp.fyre.ibm.com:3023` line.
5.  Restart  `teleport-cluster` pod, it crashes
6. check pod log
```
ERROR REPORT:
Original Error: sqlite3.Error database is locked
```

**Comment by dove-young** [comment]
full pod log looks like this

```
2021-12-14T06:01:37Z [PROC:1]    DEBU Connected to Auth Server with direct connection. auth-addrs:[0.0.0.0:3025] service/connect.go:838
2021-12-14T06:01:37Z [PROC:1]    DEBU Connected client: Identity(Proxy, cert(48c167f9-cad9-4e8e-a67b-2489fa7d6dce.teleport-cluster-teleport-cluster.apps.st2-bastion-2.cp.fyre.ibm.com issued by teleport-cluster-teleport-cluster.ap
ps.st2-bastion-2.cp.fyre.ibm.com:81371383102322912040480200376290786837),trust root(teleport-cluster-teleport-cluster.apps.st2-bastion-2.cp.fyre.ibm.com:81371383102322912040480200376290786837)) service/connect.go:87
2021-12-14T06:01:37Z [PROC:1]    INFO Proxy: features loaded from auth server: Kubernetes:true App:true DB:true  service/connect.go:59
2021-12-14T06:01:37Z [PROC:1]    DEBU Broadcasting event. event:ProxyIdentity service/supervisor.go:370
2021-12-14T06:01:37Z [PROC:1]    DEBU Service is completed and removed. service:register.proxy service/supervisor.go:239
2021-12-14T06:01:37Z [PROC:1]    DEBU Received event "ProxyIdentity". service/service.go:2491
2021-12-14T06:01:37Z [PROC:1]    DEBU Creating sqlite backend for [proxy]. service/service.go:1566
2021-12-14T06:01:37Z DEBU [SQLITE]    Connected to: file:/var/lib/teleport/cache/proxy/sqlite.db?_busy_timeout=10000&_sync=OFF, poll stream period: 100ms lite/lite.go:172
2021-12-14T06:01:37Z [PROC:1]    DEBU Connected to Auth Server with direct connection. auth-addrs:[0.0.0.0:3025] service/connect.go:838
2021-12-14T06:01:37Z [PROC:1]    DEBU Connected client: Identity(Kube, cert(48c167f9-cad9-4e8e-a67b-2489fa7d6dce.teleport-cluster-teleport-cluster.apps.st2-bastion-2.cp.fyre.ibm.com issued by teleport-cluster-teleport-cluster.app
s.st2-bastion-2.cp.fyre.ibm.com:81371383102322912040480200376290786837),trust root(teleport-cluster-teleport-cluster.apps.st2-bastion-2.cp.fyre.ibm.com:81371383102322912040480200376290786837)) service/connect.go:87
2021-12-14T06:01:37Z [PROC:1]    INFO Kube: features loaded from auth server: Kubernetes:true App:true DB:true  service/connect.go:59
2021-12-14T06:01:37Z [PROC:1]    DEBU Broadcasting event. event:KubeIdentity service/supervisor.go:370
2021-12-14T06:01:37Z [PROC:1]    DEBU Service is completed and removed. service:register.kube service/supervisor.go:239
2021-12-14T06:01:37Z [KUBERNETE] DEBU Received event "KubeIdentity". service/kubernetes.go:50
2021-12-14T06:01:37Z [PROC:1]    DEBU Creating sqlite backend for [kubernetes]. service/service.go:1566
2021-12-14T06:01:37Z DEBU [SQLITE]    Connected to: file:/var/lib/teleport/cache/kubernetes/sqlite.db?_busy_timeout=10000&_sync=OFF, poll stream period: 100ms lite/lite.go:172
2021-12-14T06:01:37Z DEBU [SQLITE]    Synchronous: 0, busy timeout: 10000 lite/lite.go:217
2021-12-14T06:01:37Z DEBU [SQLITE]    Synchronous: 0, busy timeout: 10000 lite/lite.go:217
2021-12-14T06:01:47Z WARN [SQLITE]    "SLOW TRANSACTION: 10.125544013s, goroutine 383 [running]:\nruntime/debug.Stack()\n\t/opt/go/src/runtime/debug/stack.go:24 +0x65\ngithub.com/gravitational/teleport/lib/backend/lite.(*Backend)
.inTransaction.func1()\n\t/go/src/github.com/gravitational/teleport/lib/backend/lite/lite.go:812 +0x5b\ngithub.com/gravitational/teleport/lib/backend/lite.(*Backend).inTransaction(0xc0009d3040, {0x50be8f0, 0xc000d71680}, 0xc000ce
bb58)\n\t/go/src/github.com/gravitational/teleport/lib/backend/lite/lite.go:863 +0x230\ngithub.com/gravitational/teleport/lib/backend/lite.(*Backend).Delete(0x0, {0x50be8f0, 0xc000d71680}, {0xc0012a22a0, 0xc0012a22a0, 0x19})\n\t/
go/src/github.com/gravitational/teleport/lib/backend/lite/lite.go:729 +0xbe\ngithub.com/gravitational/teleport/lib/backend.(*Reporter).Delete(0xc000c00870, {0x50be8f0, 0xc000d71680}, {0xc0012a22a0, 0x19, 0x20})\n\t/go/src/github.
com/gravitational/teleport/lib/backend/report.go:192 +0xb5\ngithub.com/gravitational/teleport/lib/backend.(*Wrapper).Delete(...)\n\t/go/src/github.com/gravitational/teleport/lib/backend/wrap.go:100\ngithub.com/gravitational/telep
ort/lib/cache.New({{0x40ca0b0, 0x5}, {0x50be8f0, 0xc0001c1080}, {0xc0005d4900, 0x1a, 0x1a}, {0x502f140, 0xc000d2a270}, {0x7f78741304c8, ...}, ...})\n\t/go/src/github.com/gravitational/teleport/lib/cache/cache.go:651 +0xef6\ngithu
b.com/gravitational/teleport/lib/service.(*TeleportProcess).newAccessCache(0xc0004e0000, {{0x7f787412eed0, 0xc000d2a270}, 0x4ac5588, {0xc000d2b570, 0x1, 0x1}, 0x0, 0x0, 0x1dcd6500})\n\t/go/src/github.com/gravitational/teleport/li
b/service/service.go:1592 +0xb65\ngithub.com/gravitational/teleport/lib/service.(*TeleportProcess).newLocalCache(0xc0004e0000, {0x51732c8, 0xc000d2a270}, 0x4ac5588, {0xc000d2b570, 0x1, 0x1})\n\t/go/src/github.com/gravitational/te
leport/lib/service/service.go:1740 +0x159\ngithub.com/gravitational/teleport/lib/service.(*TeleportProcess).newLocalCacheForProxy(0x0, {0x51732c8, 0xc000d2a270}, {0xc000d2b570, 0xfa, 0x0})\n\t/go/src/github.com/gravitational/tele
port/lib/service/service.go:1667 +0x5a\ngithub.com/gravitational/teleport/lib/service.(*TeleportProcess).initProxyEndpoint(0xc0004e0000, 0xc00000e438)\n\t/go/src/github.com/gravitational/teleport/lib/service/service.go:2737 +0x22
5\ngithub.com/gravitational/teleport/lib/service.(*TeleportProcess).initProxy.func1()\n\t/go/src/github.com/gravitational/teleport/lib/service/service.go:2502 +0x225\ngithub.com/gravitational/teleport/lib/service.(*LocalService).
Serve(0xc0002f8ee0)\n\t/go/src/github.com/gravitational/teleport/lib/service/supervisor.go:494 +0x1a\ngithub.com/gravitational/teleport/lib/service.(*LocalSupervisor).serve.func1()\n\t/go/src/github.com/gravitational/teleport/lib
/service/supervisor.go:263 +0x17e\ncreated by github.com/gravitational/teleport/lib/service.(*LocalSupervisor).serve\n\t/go/src/github.com/gravitational/teleport/lib/service/supervisor.go:258 +0xaf\n." lite/lite.go:812
2021-12-14T06:01:47Z [PROC:1]    WARN Teleport process has exited with error. error:[
ERROR REPORT:
Original Error: sqlite3.Error database is locked
Stack Trace:
        /go/src/github.com/gravitational/teleport/lib/backend/lite/lite.go:859 github.com/gravitational/teleport/lib/backend/lite.(*Backend).inTransaction.func4
        /go/src/github.com/gravitational/teleport/lib/backend/lite/lite.go:863 github.com/gravitational/teleport/lib/backend/lite.(*Backend).inTransaction
        /go/src/github.com/gravitational/teleport/lib/backend/lite/lite.go:729 github.com/gravitational/teleport/lib/backend/lite.(*Backend).Delete
        /go/src/github.com/gravitational/teleport/lib/backend/report.go:192 github.com/gravitational/teleport/lib/backend.(*Reporter).Delete
        /go/src/github.com/gravitational/teleport/lib/backend/wrap.go:100 github.com/gravitational/teleport/lib/backend.(*Wrapper).Delete
        /go/src/github.com/gravitational/teleport/lib/cache/cache.go:651 github.com/gravitational/teleport/lib/cache.New
```

**Comment by alwaysastudent** [comment]
DId you solve this issue? How are you working around this?

**Comment by zmb3** [comment]
Closing due to inactivity
