### ISSUE TITLE
Cannot start Auth/Proxy

### ISSUE THREAD

**Issue by deurk** [gravitational/teleport#9419]
### Description

**What happened**:
After upgrading from 7.1.3 to 8.0.6, teleport auth and proxy server won't start and displays this error message:
```
2021-12-15T16:44:54Z [AUTH]      INFO Updating cluster networking configuration: Kind:"cluster_networking_config" Version:"v2" Metadata:<Name:"cluster-networking-config" Namespace:"default" Labels:<key:"teleport.dev/origin" value:"config-file" > > Spec:<KeepAliveInterval:300000000000 KeepAliveCountMax:3 > . auth/init.go:432
2021-12-15T16:44:54Z [AUTH]      INFO Updating session recording configuration: Kind:"session_recording_config" Version:"v2" Metadata:<Name:"session-recording-config" Namespace:"default" Labels:<key:"teleport.dev/origin" value:"config-file" > > Spec:<Mode:"node" ProxyChecksHostKeys:"\010\001" > . auth/init.go:450
ERROR: initialization failed
cluster ID is required
```

**What you expected to happen**:
Service to start as usual

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Use systemctl start teleport

### Server Details
- Teleport version (run `teleport version`): 8.06
- Server OS (e.g. from `/etc/os-release`): Ubuntu 20.04.3 LTS
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): Dedicated VM

### Debug Logs
Please include or attach debug logs, when appropriate. Obfuscate sensitive information!
- Start Teleport with --debug flag (`teleport --debug`)
```
2021-12-15T16:49:00Z DEBU [SQLITE]    Connected to: file:/var/lib/teleport/proc/sqlite.db?_busy_timeout=10000&_sync=OFF, poll stream period: 1s lite/lite.go:172
2021-12-15T16:49:00Z DEBU [SQLITE]    Synchronous: 0, busy timeout: 10000 lite/lite.go:217
2021-12-15T16:49:00Z DEBU [KEYGEN]    SSH cert authority is going to pre-compute 25 keys. native/native.go:102
2021-12-15T16:49:00Z DEBU [PROC:1]    Using sqlite backend. service/service.go:3716
2021-12-15T16:49:00Z DEBU [SQLITE]    Connected to: file:/var/lib/teleport/backend/sqlite.db?_busy_timeout=10000&_sync=OFF, poll stream period: 1s lite/lite.go:172
2021-12-15T16:49:00Z DEBU [SQLITE]    Synchronous: 0, busy timeout: 10000 lite/lite.go:217
2021-12-15T16:49:00Z INFO [AUTH]      Updating cluster networking configuration: Kind:"cluster_networking_config" Version:"v2" Metadata:<Name:"cluster-networking-config" Namespace:"default" Labels:<key:"teleport.dev/origin" value:"config-file" > > Spec:<KeepAliveInterval:300000000000 KeepAliveCountMax:3 > . auth/init.go:432
2021-12-15T16:49:00Z INFO [AUTH]      Updating session recording configuration: Kind:"session_recording_config" Version:"v2" Metadata:<Name:"session-recording-config" Namespace:"default" Labels:<key:"teleport.dev/origin" value:"config-file" > > Spec:<Mode:"node" ProxyChecksHostKeys:"\010\001" > . auth/init.go:450

ERROR REPORT:
Original Error: *trace.BadParameterError cluster ID is required
Stack Trace:
        /go/src/github.com/gravitational/teleport/vendor/github.com/gravitational/teleport/api/types/clustername.go:154 github.com/gravitational/teleport/api/types.(*ClusterNameV2).CheckAndSetDefaults
        /go/src/github.com/gravitational/teleport/lib/services/clustername.go:54 github.com/gravitational/teleport/lib/services.UnmarshalClusterName
        /go/src/github.com/gravitational/teleport/lib/services/local/configuration.go:68 github.com/gravitational/teleport/lib/services/local.(*ClusterConfigurationService).GetClusterName
        /go/src/github.com/gravitational/teleport/lib/auth/init.go:284 github.com/gravitational/teleport/lib/auth.Init
        /go/src/github.com/gravitational/teleport/lib/service/service.go:1217 github.com/gravitational/teleport/lib/service.(*TeleportProcess).initAuthService
        /go/src/github.com/gravitational/teleport/lib/service/service.go:772 github.com/gravitational/teleport/lib/service.NewTeleport
        /go/src/github.com/gravitational/teleport/lib/service/service.go:489 github.com/gravitational/teleport/lib/service.newTeleportProcess
        /go/src/github.com/gravitational/teleport/lib/service/service.go:499 github.com/gravitational/teleport/lib/service.Run
        /go/src/github.com/gravitational/teleport/tool/teleport/common/teleport.go:289 github.com/gravitational/teleport/tool/teleport/common.OnStart
        /go/src/github.com/gravitational/teleport/tool/teleport/common/teleport.go:266 github.com/gravitational/teleport/tool/teleport/common.Run
        /go/src/github.com/gravitational/teleport/tool/teleport/main.go:32 main.main
        /opt/go/src/runtime/proc.go:255 runtime.main
        /opt/go/src/runtime/asm_amd64.s:1581 runtime.goexit
User Message: initialization failed
        cluster ID is required
```

**Comment by deurk** [comment]
Here is my `teleport.yaml`:
```
teleport:
  nodename: random.fqdn.name
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
  ca_pin: ""
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  cluster_name: random.fqdn.name
ssh_service:
  enabled: "yes"
  labels:
    env: production
proxy_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3023
  web_listen_addr: :443
  public_addr: random.fqdn.name:443
  https_keypairs: []
  acme:
    enabled: "yes"
    email: my@email.address
```

**Comment by tcannonfodder** [comment]
Same here

**Comment by wadells** [comment]
https://github.com/gravitational/teleport/pull/7363/files seems to have some related code changes -- with a note about 8.0.0 too.

**Comment by deurk** [comment]
Still the same in 8.0.7 :(

**Comment by russjones** [comment]
@deurk I was not able to reproduce this by starting from a new 7.1.3 cluster then upgrading to 8.0.6.

Did you upgrade to 7.1.3 from another version of Teleport? Do you recall which version?

**Comment by deurk** [comment]
As far as I'm aware it was 7.1.3 as I don't recall installing before that but i check the logs to be sure.

**Comment by PierrickBrun** [comment]
Same here, no idea if this is related but I have a `-` in the `cluster_name`

**Comment by deurk** [comment]
@russjones I confirm the initial installation was 7.1.3

**Comment by deurk** [comment]
> Same here, no idea if this is related but I have a `-` in the `cluster_name`. (Upgraded from v6.2.7)

How do you check this?

**Comment by PierrickBrun** [comment]
> > Same here, no idea if this is related but I have a `-` in the `cluster_name`. (Upgraded from v6.2.7)
> 
> How do you check this?

In my `teleport.yaml` :smile:

**Comment by PierrickBrun** [comment]
> Mine doesn't mention a `cluster_name`

In the `auth_service` part
```
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
 >>> cluster_name: random.fqdn.name
```

**Comment by deurk** [comment]
Sorry, I should check my glasses, they are getting opaque apparently.
I do have a `cluster_name`, and it's set to my used FQDN.

**Comment by 1inh** [comment]
I'm not sure if that's related either but I have a `-` in my cluster_name as well and faced the same issue when I tried to upgrade from v6 to v8.0.7. After that, I upgraded to v7.3.8 without any issue

**Comment by PierrickBrun** [comment]
> I'm not sure if that's related either but I have a `-` in my cluster_name as well and faced the same issue when I tried to upgrade from v6 to v8.0.7. After that, I upgraded to v7.3.8 without any issue

In fact I have 2 clusters. I upgraded the first one without any problem and had a problem with the second. The first one does not have a `-` in cluster name and the second has one (the config is almost the same in both).
From what I understand here: https://github.com/gravitational/teleport/pull/7363/files , there is a link between `cluster_name` and the `cluster ID is required` message.
That's why I assumed it may be caused by the `-`.

**Comment by matslindh** [comment]
Faced the same issue - upgrading from latest 6.x to 8.x. Downgrading from 8.x to 7.3.9 worked, then upgrading from that to 8.x again. This did however end up with the message "Access to read cluster_config in namespace default denied to roles Node,default-implicit-role: no allow rule matched. services/role.go:1839" being spammed in the log every other second; I've been unable to find a decent solution for that yet.

**Comment by corpix** [comment]
Same issue with 8.0.6 and 8.1.0 (I have FQDN in `cluster_name`). Wasted a couple of hours debugging this with no results... building highlevel abstractions in Go is a horrible idea.

But I think I could share something.
I inserted a code doing `debug.PrintStack()` into `github.com/gravitational/teleport/api/types.(*ClusterNameV2).CheckAndSetDefaults` and I've got it called 3 times. Last one without a cluster id.
Have no idea why.

```
Jan 11 16:08:17 bastion-0 systemd[1]: Started teleport.service.
Jan 11 16:08:17 bastion-0 teleport-start[766834]: goroutine 1 [running]:
Jan 11 16:08:17 bastion-0 teleport-start[766834]: runtime/debug.Stack()
Jan 11 16:08:17 bastion-0 teleport-start[766834]:         runtime/debug/stack.go:24 +0x65
Jan 11 16:08:17 bastion-0 teleport-start[766834]: runtime/debug.PrintStack()
Jan 11 16:08:17 bastion-0 teleport-start[766834]:         runtime/debug/stack.go:16 +0x19
Jan 11 16:08:17 bastion-0 teleport-start[766834]: github.com/gravitational/teleport/api/types.(*ClusterNameV2).CheckAndSetDefaults(0xc00013ef00)
Jan 11 16:08:17 bastion-0 teleport-start[766834]:         github.com/gravitational/teleport/api@v0.0.0/types/clustername.go:158 +0xd7
Jan 11 16:08:17 bastion-0 teleport-start[766834]: github.com/gravitational/teleport/api/types.NewClusterName({{0xc0000769c0, 0x13}, {0xc000676300, 0x24}, {}, {0x0, 0x0, 0x0}, 0x0})
Jan 11 16:08:17 bastion-0 teleport-start[766834]:         github.com/gravitational/teleport/api@v0.0.0/types/clustername.go:53 +0x16f
Jan 11 16:08:17 bastion-0 teleport-start[766834]: github.com/gravitational/teleport/lib/services.NewClusterNameWithRandomID({{0xc0000769c0, 0x13}, {0xc000676300, 0x24}, {}, {0x0, 0x0, 0x0}, 0x0})
Jan 11 16:08:17 bastion-0 teleport-start[766834]:         github.com/gravitational/teleport/lib/services/clustername.go:36 +0x90
Jan 11 16:08:17 bastion-0 teleport-start[766834]: github.com/gravitational/teleport/lib/config.ClusterName.Parse(...)
Jan 11 16:08:17 bastion-0 teleport-start[766834]:         github.com/gravitational/teleport/lib/config/fileconf.go:627
Jan 11 16:08:17 bastion-0 teleport-start[766834]: github.com/gravitational/teleport/lib/config.applyAuthConfig(0xc0008ca400, 0xc00064a400)
Jan 11 16:08:17 bastion-0 teleport-start[766834]:         github.com/gravitational/teleport/lib/config/configuration.go:525 +0x3db
Jan 11 16:08:17 bastion-0 teleport-start[766834]: github.com/gravitational/teleport/lib/config.ApplyFileConfig(0xc0008ca400, 0xc00064a400)
Jan 11 16:08:17 bastion-0 teleport-start[766834]:         github.com/gravitational/teleport/lib/config/configuration.go:376 +0x1025
Jan 11 16:08:17 bastion-0 teleport-start[766834]: github.com/gravitational/teleport/lib/config.Configure(0xc00000c960, 0xc00064a400)
Jan 11 16:08:17 bastion-0 teleport-start[766834]:         github.com/gravitational/teleport/lib/config/configuration.go:1675 +0x7a6
Jan 11 16:08:17 bastion-0 teleport-start[766834]: github.com/gravitational/teleport/tool/teleport/common.Run({{0xc0000700b0, 0x67fbb18, 0x332a920}, 0xa0})
Jan 11 16:08:17 bastion-0 teleport-start[766834]:         github.com/gravitational/teleport/tool/teleport/common/teleport.go:264 +0x8192
Jan 11 16:08:17 bastion-0 teleport-start[766834]: main.main()
Jan 11 16:08:17 bastion-0 teleport-start[766834]:         github.com/gravitational/teleport/tool/teleport/main.go:32 +0x52
Jan 11 16:08:17 bastion-0 teleport-start[766834]: сука блять многоэтажка: types.ClusterNameSpecV2{ClusterName:"REDACTED.ru", ClusterID:"962ed12c-ee3f-42f2-925e-64f6b6942a4a", XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0}
Jan 11 16:08:17 bastion-0 teleport-start[766834]: goroutine 1 [running]:
Jan 11 16:08:17 bastion-0 teleport-start[766834]: runtime/debug.Stack()
Jan 11 16:08:17 bastion-0 teleport-start[766834]:         runtime/debug/stack.go:24 +0x65
Jan 11 16:08:17 bastion-0 teleport-start[766834]: runtime/debug.PrintStack()
Jan 11 16:08:17 bastion-0 teleport-start[766834]:         runtime/debug/stack.go:16 +0x19
Jan 11 16:08:17 bastion-0 teleport-start[766834]: github.com/gravitational/teleport/api/types.(*ClusterNameV2).CheckAndSetDefaults(0xc00013ef00)
Jan 11 16:08:17 bastion-0 teleport-start[766834]:         github.com/gravitational/teleport/api@v0.0.0/types/clustername.go:158 +0xd7
Jan 11 16:08:17 bastion-0 teleport-start[766834]: github.com/gravitational/teleport/lib/services.MarshalClusterName({0x4b26ed8, 0xc00013ef00}, {0x0, 0x0, 0x0})
Jan 11 16:08:17 bastion-0 teleport-start[766834]:         github.com/gravitational/teleport/lib/services/clustername.go:76 +0x3a
Jan 11 16:08:17 bastion-0 teleport-start[766834]: github.com/gravitational/teleport/lib/services/local.(*ClusterConfigurationService).SetClusterName(0xc000925da0, {0x4b26ed8, 0xc00013ef00})
Jan 11 16:08:17 bastion-0 teleport-start[766834]:         github.com/gravitational/teleport/lib/services/local/configuration.go:87 +0x53
Jan 11 16:08:17 bastion-0 teleport-start[766834]: github.com/gravitational/teleport/lib/auth.Init({{0x4b1e568, 0xc0003d6510}, {0x4ac0b98, 0xc000274680}, {0xc0002208d0, {0x0, 0x0}, 0x0, {0x0, 0x0}, ...}, ...}, ...)
Jan 11 16:08:17 bastion-0 teleport-start[766834]:         github.com/gravitational/teleport/lib/auth/init.go:276 +0xd0d
Jan 11 16:08:17 bastion-0 teleport-start[766834]: github.com/gravitational/teleport/lib/service.(*TeleportProcess).initAuthService(0xc00090d680)
Jan 11 16:08:17 bastion-0 teleport-start[766834]:         github.com/gravitational/teleport/lib/service/service.go:1218 +0xe7f
Jan 11 16:08:17 bastion-0 teleport-start[766834]: github.com/gravitational/teleport/lib/service.NewTeleport(0xc00064b000)
Jan 11 16:08:17 bastion-0 teleport-start[766834]:         github.com/gravitational/teleport/lib/service/service.go:772 +0x12f2
Jan 11 16:08:17 bastion-0 teleport-start[766834]: github.com/gravitational/teleport/lib/service.newTeleportProcess(0xc0009bd788)
Jan 11 16:08:17 bastion-0 teleport-start[766834]:         github.com/gravitational/teleport/lib/service/service.go:489 +0x19
Jan 11 16:08:17 bastion-0 teleport-start[766834]: github.com/gravitational/teleport/lib/service.Run({_, _}, {{0x3a8e71e, 0x2}, {0xc0000771d0, 0x12}, {0xc000916600, 0x9}, {0xc00085cfc0, 0x20}, ...}, ...)
Jan 11 16:08:17 bastion-0 teleport-start[766834]:         github.com/gravitational/teleport/lib/service/service.go:499 +0xba
Jan 11 16:08:17 bastion-0 teleport-start[766834]: github.com/gravitational/teleport/tool/teleport/common.OnStart(...)
Jan 11 16:08:17 bastion-0 teleport-start[766834]:         github.com/gravitational/teleport/tool/teleport/common/teleport.go:291
Jan 11 16:08:17 bastion-0 teleport-start[766834]: github.com/gravitational/teleport/tool/teleport/common.Run({{0xc0000700b0, 0x67fbb18, 0x332a920}, 0xa0})
Jan 11 16:08:17 bastion-0 teleport-start[766834]:         github.com/gravitational/teleport/tool/teleport/common/teleport.go:268 +0x8229
Jan 11 16:08:17 bastion-0 teleport-start[766834]: main.main()
Jan 11 16:08:17 bastion-0 teleport-start[766834]:         github.com/gravitational/teleport/tool/teleport/main.go:32 +0x52
Jan 11 16:08:17 bastion-0 teleport-start[766834]: сука блять многоэтажка: types.ClusterNameSpecV2{ClusterName:"REDACTED.ru", ClusterID:"962ed12c-ee3f-42f2-925e-64f6b6942a4a", XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0}
Jan 11 16:08:17 bastion-0 teleport-start[766834]: goroutine 1 [running]:
Jan 11 16:08:17 bastion-0 teleport-start[766834]: runtime/debug.Stack()
Jan 11 16:08:17 bastion-0 teleport-start[766834]:         runtime/debug/stack.go:24 +0x65
Jan 11 16:08:17 bastion-0 teleport-start[766834]: runtime/debug.PrintStack()
Jan 11 16:08:17 bastion-0 teleport-start[766834]:         runtime/debug/stack.go:16 +0x19
Jan 11 16:08:17 bastion-0 teleport-start[766834]: github.com/gravitational/teleport/api/types.(*ClusterNameV2).CheckAndSetDefaults(0xc00013f200)
Jan 11 16:08:17 bastion-0 teleport-start[766834]:         github.com/gravitational/teleport/api@v0.0.0/types/clustername.go:158 +0xd7
Jan 11 16:08:17 bastion-0 teleport-start[766834]: github.com/gravitational/teleport/lib/services.UnmarshalClusterName({0xc000035400, 0x77, 0x77}, {0xc00087fbf8, 0x1, 0x1})
Jan 11 16:08:17 bastion-0 teleport-start[766834]:         github.com/gravitational/teleport/lib/services/clustername.go:56 +0xf3
Jan 11 16:08:17 bastion-0 teleport-start[766834]: github.com/gravitational/teleport/lib/services/local.(*ClusterConfigurationService).GetClusterName(0xc000925da0, {0x0, 0x0, 0x0})
Jan 11 16:08:17 bastion-0 teleport-start[766834]:         github.com/gravitational/teleport/lib/services/local/configuration.go:68 +0x35a
Jan 11 16:08:17 bastion-0 teleport-start[766834]: github.com/gravitational/teleport/lib/auth.Init({{0x4b1e568, 0xc0003d6510}, {0x4ac0b98, 0xc000274680}, {0xc0002208d0, {0x0, 0x0}, 0x0, {0x0, 0x0}, ...}, ...}, ...)
Jan 11 16:08:17 bastion-0 teleport-start[766834]:         github.com/gravitational/teleport/lib/auth/init.go:284 +0xd70
Jan 11 16:08:17 bastion-0 teleport-start[766834]: github.com/gravitational/teleport/lib/service.(*TeleportProcess).initAuthService(0xc00090d680)
Jan 11 16:08:17 bastion-0 teleport-start[766834]:         github.com/gravitational/teleport/lib/service/service.go:1218 +0xe7f
Jan 11 16:08:17 bastion-0 teleport-start[766834]: github.com/gravitational/teleport/lib/service.NewTeleport(0xc00064b000)
Jan 11 16:08:17 bastion-0 teleport-start[766834]:         github.com/gravitational/teleport/lib/service/service.go:772 +0x12f2
Jan 11 16:08:17 bastion-0 teleport-start[766834]: github.com/gravitational/teleport/lib/service.newTeleportProcess(0xc0009bd788)
Jan 11 16:08:17 bastion-0 teleport-start[766834]:         github.com/gravitational/teleport/lib/service/service.go:489 +0x19
Jan 11 16:08:17 bastion-0 teleport-start[766834]: github.com/gravitational/teleport/lib/service.Run({_, _}, {{0x3a8e71e, 0x2}, {0xc0000771d0, 0x12}, {0xc000916600, 0x9}, {0xc00085cfc0, 0x20}, ...}, ...)
Jan 11 16:08:17 bastion-0 teleport-start[766834]:         github.com/gravitational/teleport/lib/service/service.go:499 +0xba
Jan 11 16:08:17 bastion-0 teleport-start[766834]: github.com/gravitational/teleport/tool/teleport/common.OnStart(...)
Jan 11 16:08:17 bastion-0 teleport-start[766834]:         github.com/gravitational/teleport/tool/teleport/common/teleport.go:291
Jan 11 16:08:17 bastion-0 teleport-start[766834]: github.com/gravitational/teleport/tool/teleport/common.Run({{0xc0000700b0, 0x67fbb18, 0x332a920}, 0xa0})
Jan 11 16:08:17 bastion-0 teleport-start[766834]:         github.com/gravitational/teleport/tool/teleport/common/teleport.go:268 +0x8229
Jan 11 16:08:17 bastion-0 teleport-start[766834]: main.main()
Jan 11 16:08:17 bastion-0 teleport-start[766834]:         github.com/gravitational/teleport/tool/teleport/main.go:32 +0x52
Jan 11 16:08:17 bastion-0 teleport-start[766834]: сука блять многоэтажка: types.ClusterNameSpecV2{ClusterName:"REDACTED.ru", ClusterID:"", XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0}
Jan 11 16:08:17 bastion-0 teleport-start[766834]: ERROR: initialization failed
Jan 11 16:08:17 bastion-0 teleport-start[766834]: cluster ID is required
```

**Comment by russjones** [comment]
@deurk @PierrickBrun @1inh @matslindh @corpix I have not been able to reproduce even with a `-` upgrading from 7.1.3 to 8.0.6.

However, I have been able to reproduce this issue when upgrading from 6.1.2 directly to 8.0.6. Unfortunately, this is an unsupported upgrade path. https://goteleport.com/docs/setup/operations/upgrading/

When I upgraded from 6.1.2 to 7.1.3 and then 8.0.6 the upgrade was successful.

Any chance any of you were doing a direct 6.x to 8.x upgrade?

**Comment by corpix** [comment]
Yes, I went from 6.2.7 to 8.0.6.
Just tried same path as you mentioned (6.1.2 to 7.1.3 and then 8.0.6) and could confirm this is working.
Thank you, @russjones !

**Comment by PierrickBrun** [comment]
I can confirm that was my problem too, sorry about the wrong lead.

FYI, I had to restart teleport between each upgrades, `apt install` only did not suffice

**Comment by deurk** [comment]
I'd be grateful if you could provide the howto for downgrading to 7.1.3 before going back to 8.1.0 (I'm using `apt`). Thanks!
