### ISSUE TITLE
public_address not set for proxy, returning proxyHost

### ISSUE THREAD

**Issue by tjlaxs** [gravitational/teleport#947]
I'm trying to connect with ssh to a node in a trusted cluster. Running the tsh command from the main cluster results the cluster 2 teleport to crash with:
```
DEBU[0002] public_address not set for proxy, returning proxyHost: "c2-node1:3080"  file=srv/exec.go:222 func=srv.prepareCommand
panic: runtime error: slice bounds out of range

goroutine 355 [running]:
github.com/gravitational/teleport/lib/srv.prepareCommand(0x11437000, 0x4, 0x0, 0x0)
        /opt/gocode/src/github.com/gravitational/teleport/lib/srv/exec.go:207 +0x15f0
github.com/gravitational/teleport/lib/srv.prepInteractiveCommand(0x11437000, 0x0, 0x11436f80, 0x11437000)
        /opt/gocode/src/github.com/gravitational/teleport/lib/srv/exec.go:136 +0x34
github.com/gravitational/teleport/lib/srv.(*session).start(0x11400550, 0xd89b38, 0x11436f80, 0x11437000, 0x1, 0x1)
        /opt/gocode/src/github.com/gravitational/teleport/lib/srv/sess.go:491 +0xa8
github.com/gravitational/teleport/lib/srv.(*sessionRegistry).openSession(0x115faee0, 0xd89b38, 0x11436f80, 0x113f66a0, 0x11437000, 0x2, 0x11547e84)
        /opt/gocode/src/github.com/gravitational/teleport/lib/srv/sess.go:105 +0x758
github.com/gravitational/teleport/lib/srv.(*Server).dispatch(0x1117a000, 0xd89b38, 0x11436f80, 0x113f66a0, 0x11437000, 0x0, 0x0)
        /opt/gocode/src/github.com/gravitational/teleport/lib/srv/sshserver.go:831 +0x430
github.com/gravitational/teleport/lib/srv.(*Server).handleSessionRequests(0x1117a000, 0x1154f050, 0xd89b38, 0x11436f80, 0x113a7600)
        /opt/gocode/src/github.com/gravitational/teleport/lib/srv/sshserver.go:778 +0x1b0
created by github.com/gravitational/teleport/lib/srv.(*Server).HandleNewChan
        /opt/gocode/src/github.com/gravitational/teleport/lib/srv/sshserver.go:655 +0x630
```

Documentation doesn't seem to talk much about what a public_address is and I'm not even sure is it relevant to the panic? c2-node1 is the machine with cluster 2 and node1. Is this a bug or do I have something configured wrong?

Version: Teleport v2.1.0-alpha.3 git:v2.1.0-alpha.3-5-g4aff18a
Running on Linux 3.10.105-135 armv71 (incase they are relevant)

**Comment by tjlaxs** [comment]
I investigated this a bit further. Clicking the login as user button from the webui also crashes the teleport.

The reason seems to be that the length of args **lib/srv/exec.go**  for the if on line 204 is **0**. So... I wonder where my ```ssh user@node``` command has disappeared.

**Comment by tjlaxs** [comment]
My bad, the user didn't have home set.

**Comment by kontsevoy** [comment]
:) thanks.
